	.align 2
DirectSoundWaveData_sc88pro_glockenspiel::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sc88pro_organ2::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sc88pro_fretless_bass::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sc88pro_slap_bass::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sc88pro_synth_bass::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sc88pro_timpani::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_classical_choir_voice_ahhs::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sd90_classical_oboe::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_unused_sd90_oboe::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_unused_guitar_separates_power_chord::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_unused_sc88pro_unison_slap::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_unknown_snare::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_ohtsuzumi::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_hyoushigi::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sc88pro_rnd_kick::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sc88pro_rnd_snare::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sc88pro_tr909_hand_clap::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sc88pro_orchestra_snare::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_unused_sc55_tom::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_unknown_close_hihat::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_unknown_open_hihat::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_unknown_bell::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sc88pro_tambourine::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_trinity_cymbal_crash::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sc88pro_orchestra_cymbal_crash::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sc88pro_mute_high_conga::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sc88pro_open_low_conga::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_drum_and_percussion_kick::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sd90_solo_snare::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sd90_ambient_tom::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_dance_drums_ride_bell::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sd90_cowbell::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_unused_heart_of_asia_indian_drum::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sd90_open_triangle::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sc88pro_jingle_bell::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_atarigane::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sc88pro_taiko::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_kotsuzumi::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_48::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_60::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_72::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_84::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_60::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_72::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_84::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_60::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_72::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_84::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sc88pro_tuba_39:: @N.B.: These tuba samples are actually sampled at 36 and 48, then pitched up
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sc88pro_tuba_51::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sc88pro_french_horn_60::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sc88pro_french_horn_72::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sc88pro_flute::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sc88pro_fingered_bass::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_unknown_koto_high::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sd90_classical_shakuhachi::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_unknown_koto_low::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sd90_classical_overdrive_guitar::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_high::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_low::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_heart_of_asia_gamelan::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sc88pro_church_organ3_low::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sc88pro_church_organ3_high::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_unknown_female_voice::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_unused_unknown_male_voice::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_low::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_high::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sc88pro_timpani_with_snare::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_unknown_synth_snare::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sc88pro_square_wave::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_bicycle_bell::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_8725A2C::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sc88pro_pizzicato_strings::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_872762C::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_872921C::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_872A5D0::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sc88pro_wind::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sc88pro_bubbles::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_872EEA8::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_87301B0::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_trinity_30303_mega_bass::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_8734298::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_87364A8::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sc88pro_tubular_bell::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_87385E4::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_trinity_big_boned::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sc88pro_harp::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sc88pro_xylophone::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_873ECD8::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_8740818::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sc88pro_accordion::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_87424B0::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_87430C0::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_8743C50::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_87446EC::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_8745034::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_8745A7C::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Bulbasaur::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Ivysaur::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Venusaur::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Charmander::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Charmeleon::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Charizard::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Squirtle::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Wartortle::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Blastoise::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Caterpie::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Metapod::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Butterfree::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Weedle::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Kakuna::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Beedrill::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Pidgey::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Pidgeotto::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Pidgeot::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Rattata::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Raticate::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Spearow::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Fearow::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Ekans::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Arbok::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Pikachu::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Raichu::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Sandshrew::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Sandslash::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_NidoranF::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Nidorina::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Nidoqueen::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_NidoranM::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Nidorino::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Nidoking::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Clefairy::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Clefable::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Vulpix::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Ninetales::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Jigglypuff::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Wigglytuff::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Zubat::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Golbat::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Oddish::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Gloom::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Vileplume::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Paras::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Parasect::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Venonat::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Venomoth::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Diglett::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Dugtrio::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Meowth::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Persian::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Psyduck::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Golduck::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Mankey::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Primeape::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Growlithe::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Arcanine::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Poliwag::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Poliwhirl::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Poliwrath::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Abra::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Kadabra::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Alakazam::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Machop::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Machoke::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Machamp::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Bellsprout::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Weepinbell::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Victreebel::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Tentacool::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Tentacruel::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Geodude::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Graveler::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Golem::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Ponyta::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Rapidash::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Slowpoke::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Slowbro::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Magnemite::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Magneton::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Farfetchd::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Doduo::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Dodrio::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Seel::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Dewgong::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Grimer::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Muk::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Shellder::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Cloyster::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Gastly::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Haunter::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Gengar::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Onix::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Drowzee::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Hypno::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Krabby::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Kingler::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Voltorb::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Electrode::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Exeggcute::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Exeggutor::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Cubone::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Marowak::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Hitmonlee::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Hitmonchan::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Lickitung::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Koffing::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Weezing::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Rhyhorn::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Rhydon::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Chansey::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Tangela::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Kangaskhan::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Horsea::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Seadra::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Goldeen::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Seaking::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Staryu::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Starmie::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_MrMime::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Scyther::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Jynx::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Electabuzz::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Magmar::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Pinsir::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Tauros::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Magikarp::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Gyarados::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Lapras::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Ditto::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Eevee::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Vaporeon::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Jolteon::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Flareon::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Porygon::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Omanyte::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Omastar::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Kabuto::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Kabutops::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Aerodactyl::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Snorlax::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Articuno::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Zapdos::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Moltres::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Dratini::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Dragonair::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Dragonite::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Mewtwo::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Mew::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Chikorita::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Bayleef::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Meganium::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Cyndaquil::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Quilava::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Typhlosion::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Totodile::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Croconaw::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Feraligatr::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Sentret::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Furret::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Hoothoot::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Noctowl::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Ledyba::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Ledian::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Spinarak::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Ariados::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Crobat::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Chinchou::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Lanturn::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Pichu::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Cleffa::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Igglybuff::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Togepi::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Togetic::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Natu::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Xatu::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Mareep::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Flaaffy::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Ampharos::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Bellossom::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Marill::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Azumarill::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Sudowoodo::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Politoed::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Hoppip::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Skiploom::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Jumpluff::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Aipom::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Sunkern::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Sunflora::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Yanma::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Wooper::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Quagsire::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Espeon::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Umbreon::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Murkrow::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Slowking::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Misdreavus::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Unown::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Wobbuffet::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Girafarig::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Pineco::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Forretress::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Dunsparce::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Gligar::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Steelix::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Snubbull::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Granbull::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Qwilfish::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Scizor::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Shuckle::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Heracross::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Sneasel::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Teddiursa::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Ursaring::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Slugma::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Magcargo::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Swinub::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Piloswine::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Corsola::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Remoraid::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Octillery::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Delibird::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Mantine::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Skarmory::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Houndour::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Houndoom::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Kingdra::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Phanpy::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Donphan::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Porygon2::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Stantler::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Smeargle::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Tyrogue::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Hitmontop::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Smoochum::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Elekid::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Magby::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Miltank::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Blissey::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Raikou::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Entei::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Suicune::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Larvitar::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Pupitar::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Tyranitar::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Lugia::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_HoOh::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Celebi::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Kecleon::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Roselia::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Torkoal::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Electrike::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Manectric::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Duskull::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Latias::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Wynaut::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Seviper::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Sharpedo::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Zangoose::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Azurill::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Swablu::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Altaria::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Unused265::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Taillow::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Swellow::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Unused268::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Spinda::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Torchic::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Combusken::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Blaziken::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Treecko::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Grovyle::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Sceptile::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Mudkip::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Marshtomp::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Swampert::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Pelipper::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Wingull::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Banette::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Shuppet::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Lotad::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Lombre::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Ludicolo::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Seedot::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Nuzleaf::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Shiftry::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Carvanha::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Wurmple::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Silcoon::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Beautifly::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Cascoon::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Dustox::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Ralts::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Kirlia::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Gardevoir::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Slakoth::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Vigoroth::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Slaking::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Nincada::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Ninjask::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Shedinja::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Makuhita::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Hariyama::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Nosepass::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Glalie::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Plusle::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Minun::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Surskit::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Masquerain::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Skitty::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Delcatty::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Gulpin::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Swalot::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Numel::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Camerupt::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Barboach::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Whiscash::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Corphish::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Crawdaunt::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Spoink::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Grumpig::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Trapinch::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Vibrava::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Flygon::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Cacnea::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Cacturne::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Baltoy::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Claydol::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Lunatone::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Solrock::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Feebas::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Milotic::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Absol::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Meditite::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Medicham::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Spheal::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Sealeo::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Walrein::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Clamperl::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Huntail::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Gorebyss::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Lileep::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Cradily::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Anorith::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Armaldo::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Beldum::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Metang::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Metagross::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Bagon::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Shelgon::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Regirock::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Regice::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Registeel::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Castform::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Volbeat::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Illumise::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Poochyena::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Mightyena::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Dusclops::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Sableye::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Mawile::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Aron::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Lairon::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Aggron::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Relicanth::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Luvdisc::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Groudon::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Kyogre::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Rayquaza::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Salamence::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Breloom::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Shroomish::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Linoone::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Tropius::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Wailmer::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Zigzagoon::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Exploud::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Loudred::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Wailord::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Whismur::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Snorunt::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Latios::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Jirachi::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Deoxys::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
Cry_Chimecho::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_register_noise::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88D6978::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sc88pro_nylon_str_guitar::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sd90_special_scream_drive::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88DBBC0::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88DC220::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88DC704::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88DD054::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88DDAC4::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88DDDE4::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88DEA6C::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88DF08C::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88DF414::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88E01F8::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88E0B68::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88E0F04::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88E16B8::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88E2414::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88E2658::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88E3498::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88E3DEC::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88E4140::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88E4774::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88E53E0::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88E5978::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88E647C::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88E6A80::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88E6C78::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88E75DC::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88E8568::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88E8BA0::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88E9674::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88EA5B8::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88EAB30::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88EB97C::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88EC884::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88ED358::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88EDEEC::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88EE8C4::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88EEF04::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88EF9E4::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88F0020::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88F0738::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88F1074::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88F1830::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88F1D94::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88F2B08::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88F2F84::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88F3470::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88F3C38::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88F4834::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88F4BAC::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88F5368::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88F5FCC::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_88F6498::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sc88pro_accordion_duplicate::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_steinway_b_piano::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sd90_classical_whistle::
	.incbin "sound/direct_sound_samples/cries/castform.bin"

	.align 2
DirectSoundWaveData_sd90_enhanced_delay_shaku::
	.incbin "sound/direct_sound_samples/cries/castform.bin"
