gText_ApprenticeChallenge0:: @ 82B6EA5
	.string "Mm, soy el aprendiz n.º {STR_VAR_2} de {STR_VAR_1}.\n"
	.string "Snif… Esta tensión puede conmigo…$"

gText_ApprenticeChallenge1:: @ 82B6EEC
	.string "¡Soy el aprendiz n.º {STR_VAR_2} de {STR_VAR_1}!\n"
	.string "¡Allá voy!$"

gText_ApprenticeChallenge2:: @ 82B6F16
	.string "¡Soy el aprendiz n.º {STR_VAR_2} de {STR_VAR_1}!\n"
	.string "¡Acepta mi reto!$"

gText_ApprenticeChallenge3:: @ 82B6F4C
	.string "Mm, soy la aprendiz n.º {STR_VAR_2} de {STR_VAR_1}…\n"
	.string "¿Crees que tengo alguna posibilidad?$"

gText_ApprenticeChallenge4:: @ 82B6F92
	.string "¡Soy la aprendiz n.º {STR_VAR_2} de {STR_VAR_1}!\n"
	.string "¡A ver quién es mejor!$"

gText_ApprenticeChallenge5:: @ 82B6FC9
	.string "Estoy muy ocupado, pero, en fin,\n"
	.string "¡soy el aprendiz n.º {STR_VAR_2} de {STR_VAR_1}!$"

gText_ApprenticeChallenge6:: @ 82B700C
	.string "¡Soy la aprendiz n.º {STR_VAR_2} de {STR_VAR_1}!\n"
	.string "¡Encantada de conocerte!$"

gText_ApprenticeChallenge7:: @ 82B703A
	.string "¡Soy la aprendiz n.º {STR_VAR_2} de {STR_VAR_1}!\n"
	.string "¿Qué? ¿Empezamos ya?$"

gText_ApprenticeChallenge8:: @ 82B706A
	.string "¡Eh! ¡Soy la aprendiz n.º {STR_VAR_2} de {STR_VAR_1}!\n"
	.string "¡Haré lo que pueda!$"

gText_ApprenticeChallenge9:: @ 82B709C
	.string "¡Eh! ¡Soy el aprendiz n.º {STR_VAR_2} de {STR_VAR_1}!\n"
	.string "¡Saca músculo!$"

gText_ApprenticeChallenge10:: @ 82B70CC
	.string "¡Soy el aprendiz n.º 1.000 de {STR_VAR_1}!\n"
	.string "¡Bueno, el n.º {STR_VAR_2}! ¿Qué importa eso?$"

gText_ApprenticeChallenge11:: @ 82B710A
	.string "¡Sí, soy el aprendiz n.º {STR_VAR_2} de {STR_VAR_1}!\n"
	.string "¡Al abordaje!$"

gText_ApprenticeChallenge12:: @ 82B714D
	.string "¡Soy el aprendiz n.º {STR_VAR_2} de {STR_VAR_1}!\n"
	.string "¡Que suene la música!$"

gText_ApprenticeChallenge13:: @ 82B7185
	.string "¡Soy el aprendiz n.º {STR_VAR_2} de {STR_VAR_1}!\n"
	.string "¡Es un placer conocerte! ¡Kiaaa!$"

gText_ApprenticeChallenge14:: @ 82B71C1
	.string "¡Soy el aprendiz n.º {STR_VAR_2} de {STR_VAR_1}!\n"
	.string "¡Quiero convertirme en leyenda!$"

gText_ApprenticeChallenge15:: @ 82B71F9
	.string "Soy el aprendiz n.º {STR_VAR_2} de {STR_VAR_1}\n"
	.string "y yo no miento.$"

gText_ApprenticePleaseTeach0:: @ 82B7229
	.string "¿Eres… {PLAYER}?\n"
	.string "¡Oh! Snif… Snif…\p"
	.string "¡Ay! Lo-lo siento…\n"
	.string "Los nervios… No puedo dejar\l"
	.string "de llorar…\p"
	.string "So-soy {STR_VAR_1}, y tú, {PLAYER},\n"
	.string "siempre has sido mi ídolo.\p"
	.string "Yo-yo… soñaba con que algún día me\n"
	.string "pudieses enseñar cosas de los Pokémon.\p"
	.string "¡Anda, por favor, {PLAYER}!\n"
	.string "¡Enséñame algo sobre los Pokémon!$"

gText_ApprenticeRejectTeaching0:: @ 82B731C
	.string "Oh… Pe-pero…\n"
	.string "Snif… ¡Buaaaaaaaa!\p"
	.string "¡Po-po-por fa-fa-vor!\n"
	.string "¡Te lo pido po-po-por fa-fa-vor!$"

gText_ApprenticeWhichLevelMode0:: @ 82B735B
	.string "¿En serio? ¿Lo harás?\n"
	.string "¡Genial! ¡Alucinante! ¡Superguay!\p"
	.string "Oh… Perdona otra vez…\n"
	.string "Ahora lloro de alegría…\p"
	.string "Mm… Entonces, dime algo…\n"
	.string "sobre la torre batalla…\p"
	.string "¿Qué nivel crees que me iría mejor?\n"
	.string "¿El nivel 50 o el nivel libre?$"

gText_ApprenticeLevelModeThanks0:: @ 82B7423
	.string "¿{STR_VAR_1}?\n"
	.string "¡Buaaaaaa!\p"
	.string "¡Oh! ¡Lo siento otra vez!\n"
	.string "Eso de que elijas por mí me hace\l"
	.string "tan feliz que no puedo contenerme…\p"
	.string "Snif…\n"
	.string "¡Muchas gracias!\l"
	.string "¡No te olvides de mí!$"

gText_ApprenticePleaseTeach1:: @ 82B74C1
	.string "¡Guau! Tú eres {PLAYER}, ¿a que sí?\n"
	.string "Guau, todo el mundo te conoce.\p"
	.string "¡Me llamo {STR_VAR_1}!\n"
	.string "¡Acabo de convertirme en entrenador!\p"
	.string "¡Porfa, {PLAYER}!\n"
	.string "¿Querrías tomarme como aprendiz para\l"
	.string "enseñarme a ser un buen Entrenador?$"

gText_ApprenticeRejectTeaching1:: @ 82B756F
	.string "Ooohh, pero ¿por qué?\n"
	.string "¡Anda, porfa! ¡No seas así!\l"
	.string "¡Déjame ser tu aprendiz!$"

gText_ApprenticeWhichLevelMode1:: @ 82B75B2
	.string "¡Yupi! ¡Genial!\p"
	.string "¡Lo primero que quiero preguntarte\n"
	.string "es sobre la torre batalla!\p"
	.string "Entre el nivel 50 y el nivel libre…\n"
	.string "¿En cuál crees que debería inscribirme?$"

gText_ApprenticeLevelModeThanks1:: @ 82B763F
	.string "¿{STR_VAR_1}? ¡Claro, es verdad!\n"
	.string "¡Haré lo que pueda para no defraudarte!\p"
	.string "¡Ojalá nos volvamos a ver\n"
	.string "para que me enseñes algo más!$"

gText_ApprenticePleaseTeach2:: @ 82B76AC
	.string "Mm… ¿Eres {PLAYER}?\n"
	.string "Yo me llamo {STR_VAR_1}.\p"
	.string "Quiero ser un gran entrenador Pokémon,\n"
	.string "aunque no sé por dónde empezar…\p"
	.string "Ya que estás aquí, a lo mejor podrías\n"
	.string "ayudarme, con toda esa fama que tienes.\p"
	.string "¿Qué me dices, {PLAYER}? ¿Me ayudarías?$"

gText_ApprenticeRejectTeaching2:: @ 82B7772
	.string "Oh, pero…\p"
	.string "¡Pero es que de verdad que quiero\n"
	.string "ser un buen entrenador Pokémon!\p"
	.string "¡Por favor, dime que sí!$"

gText_ApprenticeWhichLevelMode2:: @ 82B77CE
	.string "¡Gracias!\n"
	.string "¡Ahí va entonces mi primera pregunta!\p"
	.string "La torre batalla tiene dos niveles:\n"
	.string "el nivel 50 y el nivel libre, ¿sí?\p"
	.string "¿En cuál de los dos niveles crees\n"
	.string "que me vendría mejor participar?$"

gText_ApprenticeLevelModeThanks2:: @ 82B7871
	.string "Oh, ¿en el {STR_VAR_1}?\n"
	.string "¡Entendido!\p"
	.string "Si tengo más dudas, ¡vendré\n"
	.string "otra vez a preguntarte!$"

gText_ApprenticePleaseTeach3:: @ 82B78D4
	.string "¡Oh! ¡Pero si tú eres…!\n"
	.string "No, no puede ser verdad.\p"
	.string "Yo no tengo tanta suerte como para\n"
	.string "encontrarme de repente con {PLAYER}.\p"
	.string "Pero ¿eres de verdad {PLAYER}?\n"
	.string "¡No me creo que esté hablando contigo!\p"
	.string "¡Huy, qué miedo! Siempre que me pasa\n"
	.string "algo bueno, luego viene una desgracia,\l"
	.string "y las desgracias nunca vienen solas…\p"
	.string "Perdona…\n"
	.string "Me llamo… {STR_VAR_1}…\p"
	.string "Verás, es que yo no me siento\n"
	.string "especialmente orgullosa de nada…\p"
	.string "Ni siquiera debería decir nada de mí,\n"
	.string "porque de todas maneras me olvidarás…\p"
	.string "Siempre tenía un sueño en el que\n"
	.string "te conocía, {PLAYER}, y me dabas\l"
	.string "muchos consejos sobre cómo entrenar.\p"
	.string "Pero era un sueño, ya sé que no quieres\n"
	.string "perder el tiempo con alguien como yo…\p"
	.string "¿O sí querrías darme consejos?$"

gText_ApprenticeRejectTeaching3:: @ 82B7B1A
	.string "Lo sabía…\p"
	.string "Era lo normal porque yo soy\n"
	.string "una don nadie…\p"
	.string "Pero, por un momento pensé…\n"
	.string "No cambiarías de opinión, ¿verdad?\p"
	.string "¡Perdona que insista, pero una ocasión\n"
	.string "así no se presenta todos los días!\p"
	.string "Por favor, ¿serías tan amable de darme\n"
	.string "unos consejillos sobre los Pokémon?$"

gText_ApprenticeWhichLevelMode3:: @ 82B7C13
	.string "¿De verdad? ¡No me lo puedo creer!\n"
	.string "¡No me creo que quieras darme consejos!\l"
	.string "¡Estoy…! ¡Estoy tan contenta!…\p"
	.string "Lo primero que querría preguntarte es\n"
	.string "una tontería, pero yo no me decido…\p"
	.string "En la torre batalla, te dejan elegir\n"
	.string "entre el nivel 50 y el nivel libre.\p"
	.string "¿En cuál crees que tendría más\n"
	.string "posibilidades de ganar algo?$"

gText_ApprenticeLevelModeThanks3:: @ 82B7D18
	.string "¿{STR_VAR_1}? ¡Vale!\n"
	.string "Pero ¿de verdad crees que alguien\l"
	.string "como yo tiene la menor posibilidad?\p"
	.string "Bueno, haré lo que pueda,\n"
	.string "aunque sé que no puedo mucho.\p"
	.string "¡Y perdona que te haya robado\n"
	.string "tanto tiempo!$"

gText_ApprenticePleaseTeach4:: @ 82B7DD4
	.string "¡Oh! Tú eres {PLAYER}{KUN}, ¿verdad?\p"
	.string "¡Dicen que hay pocos entrenadores\n"
	.string "que entrenen Pokémon como tú!\p"
	.string "¡Me llamo {STR_VAR_1}!\n"
	.string "¡Voy a ser tu amiga!\p"
	.string "¿Sabes?\p"
	.string "No se puede ganar nada en el frente de\n"
	.string "Batalla sabiendo únicamente lo que te\l"
	.string "enseñan en la escuela de entrenadores.\p"
	.string "Por eso me gustaría oír tus consejos.\n"
	.string "Si quieres dármelos, claro…$"

gText_ApprenticeRejectTeaching4:: @ 82B7EE5
	.string "¿Eh? ¿Por qué te niegas?\n"
	.string "¡Soy yo quien te lo está pidiendo!\l"
	.string "¡Anda, piénsatelo otra vez!$"

gText_ApprenticeWhichLevelMode4:: @ 82B7F35
	.string "¡Vale, entonces, cuando tenga alguna\n"
	.string "duda, te dejo decidir por mí!\p"
	.string "Sabes que en la torre batalla está\n"
	.string "el nivel 50 y el nivel libre, ¿verdad?\p"
	.string "¿Cuál crees que es el más adecuado\n"
	.string "para mí, {PLAYER}{KUN}?$"

gText_ApprenticeLevelModeThanks4:: @ 82B7FE8
	.string "¿Piensas que el {STR_VAR_1}?\n"
	.string "¡Gracias!\p"
	.string "Sabiendo que lo decidiste tú, {PLAYER}{KUN},\n"
	.string "no podré enfadarme si pierdo.\p"
	.string "Bueno, ya te pediré otro consejo\n"
	.string "otro día. ¡Chao!$"

gText_ApprenticePleaseTeach5:: @ 82B8087
	.string "¡Oh, hola, {PLAYER}{KUN}!\n"
	.string "¡Todo el mundo sabe tu nombre!\l"
	.string "¡A mí llámame {STR_VAR_1}! ¡Encantado!\p"
	.string "Soy un triatleta, así que me entreno\n"
	.string "a mí mismo a la vez que entreno Pokémon.\p"
	.string "También me gusta hacer otras cosas,\n"
	.string "como trabajar, hacer parapente, bailar…\p"
	.string "Comprenderás que, estando tan ocupado,\n"
	.string "no es fácil ser un buen Entrenador.\p"
	.string "Pero estoy pensando…\n"
	.string "Tiene que haber un motivo para que tú\l"
	.string "y yo nos hayamos encontrado aquí.\p"
	.string "Oye, {PLAYER}{KUN}, ¿qué tal si me ayudas\n"
	.string "dándome un consejo de vez en cuando?$"

gText_ApprenticeRejectTeaching5:: @ 82B822B
	.string "Oh, pero, ¡por favor!\n"
	.string "¡Un tipo como yo necesita alguien como\l"
	.string "tú a su lado, {PLAYER}{KUN}!\p"
	.string "¡En serio, necesito tus consejos!$"

gText_ApprenticeWhichLevelMode5:: @ 82B8286
	.string "¡Gracias! ¡Eso es genial!\n"
	.string "¡Vamos a empezar por uno fácil!\p"
	.string "Ya sabes que en la torre batalla\n"
	.string "hay dos niveles de combates, ¿verdad?\l"
	.string "Ya sabes, el nivel 50 y el nivel libre.\p"
	.string "¿Cuál es el que más le conviene\n"
	.string "a un tipo tan ocupado como yo?$"

gText_ApprenticeLevelModeThanks5:: @ 82B8356
	.string "¿{STR_VAR_1}? Vale, comprendido.\n"
	.string "¡A ver cuándo tengo tiempo y pruebo!\p"
	.string "¡Huy, me tengo que largar!\n"
	.string "¡Gracias! ¡Nos vemos!$"

gText_ApprenticePleaseTeach6:: @ 82B83CE
	.string "¡No puedo creerlo! ¡Eh!\n"
	.string "¿Eres tú de verdad, {PLAYER}?\p"
	.string "¡Guau! ¡Alucinante! ¡Soy {STR_VAR_1},\n"
	.string "encantada de conocerte!\p"
	.string "{PLAYER}, eres muy fuerte,\n"
	.string "¿a que sí?\p"
	.string "¡Todo el mundo habla de ti!\p"
	.string "¡Oh! ¡Tengo una idea!\n"
	.string "¡Te pediré que me aconsejes, {PLAYER}!\l"
	.string "¡Así yo también me haré más fuerte!\p"
	.string "¿A que es buena idea?\n"
	.string "¡Por favor, necesito que me aconsejes!$"

gText_ApprenticeRejectTeaching6:: @ 82B84FC
	.string "Ja, ja, ja, ja. ¡A mí no me engañas!\n"
	.string "¡No puedes ser tan egoísta!\l"
	.string "En realidad, me vas a ayudar, ¿verdad?$"

gText_ApprenticeWhichLevelMode6:: @ 82B8559
	.string "¡Yupi! ¡Sabía que tenías buen corazón,\n"
	.string "{PLAYER}!\p"
	.string "¿Qué puedo preguntarte primero?…\n"
	.string "¡Ah, sí, ya sé!\p"
	.string "Y la pregunta es…\n"
	.string "Tachán, tachán…\p"
	.string "Para participar en un desafío de la\n"
	.string "torre batalla, ¿qué nivel elijo?\p"
	.string "¿El nivel 50 o el nivel libre?\n"
	.string "¿Qué sería mejor para mí?$"

gText_ApprenticeLevelModeThanks6:: @ 82B8656
	.string "¡Oh-oh-oh!\n"
	.string "¡Has dicho {STR_VAR_1}!\l"
	.string "¡Muchas gracias por tu respuesta!\p"
	.string "Creo que eso es todo lo\n"
	.string "que quería preguntarte.\p"
	.string "Nos vemos aquí otra vez, ¿vale?\n"
	.string "¡Gracias!$"

gText_ApprenticePleaseTeach7:: @ 82B86EA
	.string "Ay, discúlpame, pero…\n"
	.string "¿tú no eres {PLAYER}?\p"
	.string "Me llamo {STR_VAR_1}, y para mí es\n"
	.string "todo un placer conocerte.\p"
	.string "He sido una admiradora tuya desde\n"
	.string "siempre…\p"
	.string "…\p"
	.string "Mm… Espero que me permitas\n"
	.string "el atrevimiento…\p"
	.string "¿Podría ser tu aprendiz, {PLAYER}?$"

gText_ApprenticeRejectTeaching7:: @ 82B87DA
	.string "¡Oh!…\p"
	.string "¡Vaya!… \p"
	.string "Esto…\p"
	.string "Me he quedado un poco traspuesta.\n"
	.string "Perdona, he debido de oírte mal.\p"
	.string "Me vas a tomar de aprendiz, ¿verdad?$"

gText_ApprenticeWhichLevelMode7:: @ 82B887C
	.string "¡Oh!… ¡Estoy feliz!\p"
	.string "No quiero hacerte perder más tiempo,\n"
	.string "así que contéstame a esto, porfa.\p"
	.string "Tengo la intención de participar pronto\n"
	.string "en la torre batalla.\p"
	.string "Pero hay dos niveles…\p"
	.string "¿Cuál crees que se adapta mejor a mí?\n"
	.string "¿El nivel 50 o el nivel libre?$"

gText_ApprenticeLevelModeThanks7:: @ 82B8957
	.string "¿Me has dicho el {STR_VAR_1}?\n"
	.string "¡Vale! ¡A ver qué tal se me da!\p"
	.string "Oye, que muchísimas gracias, {PLAYER}.\n"
	.string "Espero que me sigas ayudando.\l"
	.string "Te me cuidas muchísimo, ¿vale?$"

gText_ApprenticePleaseTeach8:: @ 82B89C6
	.string "¡No! ¡No puede ser! ¿{PLAYER}?\n"
	.string "¿De verdad eres tú?\l"
	.string "¡Qu-qué alegría!\p"
	.string "¡Yo! ¡Me llamo {STR_VAR_1}!\n"
	.string "¡Acabo de conseguir el título!\l"
	.string "¡Ya puedo entrenar Pokémon!\p"
	.string "¡Es un placer conocerte, {PLAYER}!\n"
	.string "¡Tu nombre ya es una leyenda!\p"
	.string "¡Oh-oh-oh, ya sé!\n"
	.string "¿Me dejas pedirte un enorme favor?\p"
	.string "¡Me dejarías ser tu aprendiz!\n"
	.string "¡Quiero aprender de ti!$"

gText_ApprenticeRejectTeaching8:: @ 82B8ACF
	.string "¡Oh, {PLAYER}!\n"
	.string "¿Me vas a rechazar?…\l"
	.string "¡Es… una oportunidad única!\p"
	.string "Perdona, pero tengo que insistir.\n"
	.string "¡{PLAYER}, por favor! ¡Dime que sí!\p"
	.string "¡Te suplico que me dejes\n"
	.string "ser tu aprendiz!$"

gText_ApprenticeWhichLevelMode8:: @ 82B8B66
	.string "¡Yupi! ¡{PLAYER} ha dicho que sí!\n"
	.string "¡{PLAYER} ha dicho que sí!\p"
	.string "Ya no voy a dormir esta noche…\n"
	.string "¡Muchisísimas gracias!\p"
	.string "¡Oye, tengo una primera pregunta!\p"
	.string "En la torre batalla, qué crees que me\n"
	.string "conviene, ¿el nivel 50 o el nivel libre?$"

gText_ApprenticeLevelModeThanks8:: @ 82B8C20
	.string "¡{STR_VAR_1}! ¡Vale, entiendo!\n"
	.string "¡Lo entiendo perfectamente!\l"
	.string "¡Qué genial! ¡Qué suerte!\p"
	.string "Espero que no te olvides de\n"
	.string "seguir enseñándome cosas, ¿eh?$"

gText_ApprenticePleaseTeach9:: @ 82B8CAA
	.string "¡Guau! ¿No serás tú…?\n"
	.string "¡¿Es posible que seas… {PLAYER}{KUN}?!\l"
	.string "¡Ésta sí que es buena!\p"
	.string "¡Hola, me llamo {STR_VAR_1}!\p"
	.string "Llevo tiempo buscando un buen\n"
	.string "profesor que sepa de Pokémon.\p"
	.string "¡Y ahora llegas tú {PLAYER}{KUN},\n"
	.string "como agua de mayo!\p"
	.string "Bueno, ya lo sabes, {PLAYER}{KUN}.\n"
	.string "¿Me aceptas como tu aprendiz?$"

gText_ApprenticeRejectTeaching9:: @ 82B8DD3
	.string "¡Buaaaa!\n"
	.string "¡No hay nadie como tú!…\p"
	.string "No seas así, te lo pido por favor.\n"
	.string "¡Déjame ser tu aprendiz!$"

gText_ApprenticeWhichLevelMode9:: @ 82B8E24
	.string "¡Genial! ¡Eso es una respuesta!\n"
	.string "¡Una excelente, si puedo decirlo!\p"
	.string "¿Por qué no me das tu primer consejo\n"
	.string "sobre la torre batalla?\p"
	.string "Si fuese a participar en un desafío,\n"
	.string "¿qué elijo, el nivel 50 o el libre?$"

gText_ApprenticeLevelModeThanks9:: @ 82B8ED5
	.string "¡{STR_VAR_1}!\n"
	.string "¡G-e-n-i-a-l!\l"
	.string "¡Haré exactamente lo que dices!\p"
	.string "¡Ahora que soy tu aprendiz, nos veremos\n"
	.string "más a menudo! ¡Adiós!$"

gText_ApprenticePleaseTeach10:: @ 82B8F45
	.string "Eh, tú eres {PLAYER}{KUN}, ¿verdad?\n"
	.string "¡Te está buscando la policía!\p"
	.string "…\n"
	.string "¡Es broma!\p"
	.string "Yo me llamo {STR_VAR_1}. Aunque no lo\n"
	.string "parezca, soy un campeón Pokémon…\l"
	.string "¡Eso también es broma!\p"
	.string "Bueno, ahora fuera de bromas:\n"
	.string "no soy demasiado bueno combatiendo.\p"
	.string "¿Por qué no me dejas ser tu aprendiz\n"
	.string "y me enseñas algo sobre los Pokémon?$"

gText_ApprenticeRejectTeaching10:: @ 82B905F
	.string "Si vas a ir por ahí pasando de todo,\n"
	.string "¡vas a ver lo que hago yo!\p"
	.string "¡Buaaaa! ¡Buaaaa! ¡Buaaaa!\n"
	.string "¡Snif! ¡Buaaaa! ¡Buaaaa!\p"
	.string "¡Ja, ja, ja, ja! ¡Ése es mi llanto falso!\p"
	.string "Vamos, venga, que no se diga.\n"
	.string "¿Me dejas ser tu aprendiz?$"

gText_ApprenticeWhichLevelMode10:: @ 82B910E
	.string "¡Yupi!\n"
	.string "¡Te voy a regalar un yate!\p"
	.string "¡Bueno, otro día, claro!\n"
	.string "Pero… ¡gracias, mi capitán!\p"
	.string "Ya sabes que hay un nivel 50 y un nivel\n"
	.string "libre en la torre batalla, ¿verdad?\p"
	.string "Es que tengo problemas para decidirme\n"
	.string "en cuál de los dos debería participar…\p"
	.string "¿Cuál elegirías en mi lugar?$"

gText_ApprenticeLevelModeThanks10:: @ 82B9204
	.string "Vale, conque el {STR_VAR_1}.\n"
	.string "Entonces me apunto al otro, ¿no?\p"
	.string "¡Es broma!\n"
	.string "¡Te haré caso!\p"
	.string "¡Gracias!\n"
	.string "¡Espero que sigas instruyéndome!$"

gText_ApprenticePleaseTeach11:: @ 82B929C
	.string "¡Hola, hola, hola,\n"
	.string "dijo el mar a la caracola!\p"
	.string "¡Me llamo {STR_VAR_1}, soy soltero,\n"
	.string "mal poeta y buen Marinero!\p"
	.string "¡Dime algo de ti, hombre,\n"
	.string "aunque solo sea tu nombre!\p"
	.string "¡Mmm! ¡{PLAYER}{KUN} dices llamarte,\n"
	.string "y que te gusta de Pokémon rodearte!\p"
	.string "¡Ah, qué edad la tuya más tierna,\n"
	.string "en la que la vida parece eterna!\p"
	.string "Bueno, de suerte creo que estoy,\n"
	.string "pues contigo ya son 10\l"
	.string "los Entrenadores que he visto hoy.\p"
	.string "Y, ya puestos, vamos a rematarlo.\n"
	.string "¡Hazme tu aprendiz para celebrarlo!$"

gText_ApprenticeRejectTeaching11:: @ 82B9438
	.string "Será broma, espero…\n"
	.string "¿O acaso rehúsas a un caballero?\p"
	.string "¡No me dejes con mal sabor!\n"
	.string "¡Hazme tu aprendiz, por favor!$"

gText_ApprenticeWhichLevelMode11:: @ 82B9488
	.string "¡Eso es! ¡Qué alegría! ¡Qué alegría!\n"
	.string "¡{PLAYER}, me has animado el día!\p"
	.string "¡Aconséjame sobre la torre batalla,\n"
	.string "porque mi buen juicio a veces me falla!\p"
	.string "Nivel 50 o nivel libre: debo elegir.\n"
	.string "¿En cuál me debería inscribir?$"

gText_ApprenticeLevelModeThanks11:: @ 82B9564
	.string "Vale, el {STR_VAR_1} me aconsejas.\n"
	.string "¡Una duda que me despejas!\p"
	.string "¡Aquí vendré si necesito otro consejo!\n"
	.string "¡Hasta entonces, {PLAYER}, te dejo!$"

gText_ApprenticePleaseTeach12:: @ 82B95D8
	.string "¡Ey! ¿{PLAYER}? ¿Eres tú?\n"
	.string "¡Pues claro! “¡Only you!”\p"
	.string "Tranqui, {PLAYER}, no estoy loco.\n"
	.string "¡Es la música, que me absorbe el coco!\p"
	.string "Llámame {STR_VAR_1} si quieres,\n"
	.string "o rey de la guitarra, si lo prefieres.\p"
	.string "Sí, no, sí, no, probando, probando.\n"
	.string "¡Te diré lo que quiero cantando!\p"
	.string "{PLAYER}, voy a echarle valor,\n"
	.string "y te voy a pedir un favor.\p"
	.string "¡“Please”, déjame ser tu aprendiz!\n"
	.string "¡No habría nadie en el mundo tan feliz!$"

gText_ApprenticeRejectTeaching12:: @ 82B9763
	.string "No me digas que no, te lo pido.\n"
	.string "¡Las baladas tristes no son mi estilo!\p"
	.string "¡“Please”, déjame ser tu aprendiz!\n"
	.string "¡No habría nadie en el mundo tan feliz!$"

gText_ApprenticeWhichLevelMode12:: @ 82B97E5
	.string "“¡Ou, yea!” ¡Y ya que soy tu aprendiz!\n"
	.string "¿Por qué no me ayudas a decidir?\p"
	.string "En la torre batalla, siempre tengo\n"
	.string "una duda que nunca falla.\p"
	.string "De los niveles que vas a ver,\n"
	.string "¿cuál crees que debo escoger?$"

gText_ApprenticeLevelModeThanks12:: @ 82B989A
	.string "En el {STR_VAR_1} que me sugieres,\n"
	.string "prometo hacer bien los deberes.\p"
	.string "¡{PLAYER}, fue un placer encontrarte!\n"
	.string "¡Me largo con la música a otra parte!$"

gText_ApprenticePleaseTeach13:: @ 82B992D
	.string "¡Oh, hola! ¡Qué tal!\n"
	.string "¿Me das un masaje en el hombro?…\p"
	.string "¡Sí, ahí! ¡Justo ahí!\n"
	.string "¡Ay! ¡Ah! ¡Oh! ¡Oooh! ¡Mucho mejor!\p"
	.string "Me llamo {STR_VAR_1}.\n"
	.string "Voy a clases de karate, pero creo que\l"
	.string "mi cuerpo no está hecho para sufrir…\p"
	.string "He decidido combatir con Pokémon,\n"
	.string "así al menos yo no me haré daño.\p"
	.string "Tú eres {PLAYER}{KUN}, ¿a que sí?\n"
	.string "¿Verdad que has conseguido un\l"
	.string "campeonato de la liga Pokémon?\p"
	.string "Oye, ¿por qué no te animas a darme\n"
	.string "consejos en plan maestro y aprendiz?$"

gText_ApprenticeRejectTeaching13:: @ 82B9A84
	.string "Oh, ¿y por qué no?\p"
	.string "¡No te daré la lata, de verdad!\n"
	.string "¿Anda, por favor?$"

gText_ApprenticeWhichLevelMode13:: @ 82B9AB9
	.string "Muchas gracias. ¡Es un detallazo!…\n"
	.string "¡Achís! ¡Achís!\p"
	.string "Ay, tengo que curarme esto…\p"
	.string "Voy a participar ahora mismo en la\n"
	.string "torre batalla, pero ¿qué crees que me\l"
	.string "convendría más? ¿El nivel 50 o el libre?$"

gText_ApprenticeLevelModeThanks13:: @ 82B9B76
	.string "Ah, vale, el {STR_VAR_1}.\n"
	.string "Me largo ahora mismo.\p"
	.string "¡Espero poder seguir contando\n"
	.string "con tu ayuda!$"

gText_ApprenticePleaseTeach14:: @ 82B9BF2
	.string "Esto… Mm…\n"
	.string "¿{PLAYER}{KUN}?…\p"
	.string "Anda, por favor, no me mires así.\n"
	.string "Me vas a sacar los colores.\p"
	.string "Yo… soy {STR_VAR_1}.\p"
	.string "Suena un poco pretencioso y así, pero\n"
	.string "yo me dedico a explorar ruinas, ¿sabes?\p"
	.string "Aunque puede que hasta suene\n"
	.string "más pretencioso querer participar\l"
	.string "en el frente de batalla…\p"
	.string "{PLAYER}{KUN}, tú tienes fama de saber\n"
	.string "entrenar duro…\p"
	.string "No quería soltártelo así de repente,\n"
	.string "pero no me queda otro remedio.\p"
	.string "¿Querrías tomarme como aprendiz\n"
	.string "tuyo y darme consejos?$"

gText_ApprenticeRejectTeaching14:: @ 82B9D83
	.string "¡Por favor, no me rechaces!\n"
	.string "Llevo fatal lo de las humillaciones.\p"
	.string "¡Anda, déjame ser tu aprendiz!\n"
	.string "¡Necesito tus consejos!$"

gText_ApprenticeWhichLevelMode14:: @ 82B9DF9
	.string "Gra-gracias…\p"
	.string "Pero no me mires más con esa cara\n"
	.string "o solo tendrás un aprendiz frustrado.\p"
	.string "Anda, respóndeme a esta pregunta,\n"
	.string "pero sin mirarme a los ojos.\p"
	.string "En la torre batalla…\n"
	.string "¿en qué nivel debería inscribirme?$"

gText_ApprenticeLevelModeThanks14:: @ 82B9EAA
	.string "Oh… ¡Vale!\n"
	.string "Probaré en ése, a ver qué tal.\p"
	.string "Espero combatir de manera digna para\n"
	.string "que no tengas que avergonzarte de mí…\p"
	.string "Bueno, gracias, {PLAYER}{KUN}.\n"
	.string "Ojalá nos veamos pronto otra vez.\l"
	.string "¡Estos consejos tuyos son geniales!$"

gText_ApprenticePleaseTeach15:: @ 82B9F55
	.string "¿Mm? Vaya, pareces ser {PLAYER}{KUN}…\n"
	.string "Pero me pregunto si serás real…\p"
	.string "Mi nombre es {STR_VAR_1}.\p"
	.string "Estoy sopesando la idea de continuar\n"
	.string "mi aprendizaje bajo los auspicios\l"
	.string "de un Entrenador de fama reconocida.\p"
	.string "¡Me congratula pues verte ahora aquí!…\n"
	.string "Porque de verdad eres {PLAYER}{KUN}, ¿no?\p"
	.string "No, no, si eres {PLAYER}{KUN}, está bien.\n"
	.string "Tan solo quisiera que considerases\l"
	.string "tomarme como tu aprendiz.$"

gText_ApprenticeRejectTeaching15:: @ 82BA084
	.string "¡Oh!\n"
	.string "¿Qué te habrá empujado a rechazarme?\p"
	.string "Siento haberme mostrado tan escéptico\n"
	.string "sobre tu verdadera identidad.\p"
	.string "Te ruego aceptes mis disculpas\n"
	.string "y me tomes como tu aprendiz.$"

gText_ApprenticeWhichLevelMode15:: @ 82BA11D
	.string "¿Realmente me aceptas de aprendiz?\n"
	.string "No querría lanzar las campanas al vuelo.\p"
	.string "Si es verdad, perdona las dudas que\n"
	.string "expresé antes sobre tu identidad.\l"
	.string "Pero ahora, necesito de tu consejo.\p"
	.string "Si fuese a entrar en la torre batalla,\n"
	.string "¿qué nivel sería digno de mí?,\l"
	.string "¿el nivel 50 o el nivel libre?$"

gText_ApprenticeLevelModeThanks15:: @ 82BA1F3
	.string "¿{STR_VAR_1}?\n"
	.string "¿Es ésa tu conclusión?\p"
	.string "Bien. Confiaré en tu buen juicio.\n"
	.string "Tienes todo mi agradecimiento.\p"
	.string "Soy consciente de lo pesado que puedo\n"
	.string "resultar, por eso lo agradezco aún más.\p"
	.string "¡Sería todo un placer volver a verte!\n"
	.string "Ahora, si me disculpas…$"

gText_ApprenticeWhatHeldItem0:: @ 82BA2A3
	.string "Ay… Ay…\n"
	.string "¡Oh, {PLAYER}!\p"
	.string "Tengo un dilema y no sé qué hacer.\p"
	.string "No me decido sobre qué objeto debe\n"
	.string "sostener mi {STR_VAR_1}.\p"
	.string "¿Tú qué opinas, {PLAYER}?\n"
	.string "¿Qué objeto debería sostener?$"

gText_ApprenticeHoldNothing0:: @ 82BA34E
	.string "¿Ah, sí? ¿Crees que es mejor que mi\n"
	.string "{STR_VAR_1} no sostenga ningún objeto?$"

gText_ApprenticeThanksNoHeldItem0:: @ 82BA380
	.string "¡Ah, vale! ¡Pues entonces ya está!\n"
	.string "¡Genial! ¡Alucinante! ¡Superguay!\p"
	.string "¡Muchísimas gracias!$"

gText_ApprenticeThanksHeldItem0:: @ 82BA3D2
	.string "Ah, muy bien…\n"
	.string "Sí, tengo eso que llamas {STR_VAR_1}.\p"
	.string "¡Una preocupación menos!\n"
	.string "¡Genial! ¡Alucinante! ¡Superguay!\p"
	.string "¡Muchísimas gracias!$"

gText_ApprenticeItemAlreadyRecommended0:: @ 82BA448
	.string "¡Buaaaa! ¡Anda, no seas así!\p"
	.string "Eso que llamas {STR_VAR_1} ya me\n"
	.string "suena de haberlo oído antes…\p"
	.string "¿O me quieres decir que {STR_VAR_2}\n"
	.string "no debería sostener nada?$"

gText_ApprenticeWhatHeldItem1:: @ 82BA4D3
	.string "¡Yupi! ¡Pero si eres {PLAYER}!\n"
	.string "¡Genial! ¡Quería preguntarte algo!\p"
	.string "¿Tus Pokémon sostienen objetos?\n"
	.string "Quiero que el mío sostenga uno, pero…\p"
	.string "¿Cuál crees que le convendría más\n"
	.string "sostener a {STR_VAR_1}?\p"
	.string "¿Tú qué piensas?$"

gText_ApprenticeHoldNothing1:: @ 82BA58C
	.string "¿Cómo? ¿Quieres decir que es mejor\n"
	.string "que mi {STR_VAR_1} no sostenga nada?$"

gText_ApprenticeThanksNoHeldItem1:: @ 82BA5BF
	.string "¡Vale, lo he pillado!\n"
	.string "¡Gracias por enseñarme!$"

gText_ApprenticeThanksHeldItem1:: @ 82BA5F3
	.string "Conque {STR_VAR_1}, ¿eh?\n"
	.string "¡Vale, lo he pillado!\p"
	.string "¡Gracias por enseñarme!$"

gText_ApprenticeItemAlreadyRecommended1:: @ 82BA635
	.string "Ah, no, eso no es lo que quería.\n"
	.string "Quería que me dijeses un objeto\l"
	.string "distinto de los que ya conozco.\p"
	.string "¿O me estás queriendo decir que no\n"
	.string "debería sujetar nada mi Pokémon?$"

gText_ApprenticeWhatHeldItem2:: @ 82BA6E6
	.string "¡{PLAYER}, hola!\n"
	.string "Es sobre mi {STR_VAR_1}…\p"
	.string "Quiero que sostenga algún objeto.\n"
	.string "¿Cuál le vendría mejor?$"

gText_ApprenticeHoldNothing2:: @ 82BA742
	.string "Ah, ¿entonces crees que no tiene\n"
	.string "que sostener nada mi {STR_VAR_1}?$"

gText_ApprenticeThanksNoHeldItem2:: @ 82BA770
	.string "¡Vale, lo he entendido!\n"
	.string "¡Nos vemos!$"

gText_ApprenticeThanksHeldItem2:: @ 82BA78F
	.string "Oh, ¿{STR_VAR_1}?\n"
	.string "¡Entendido!\p"
	.string "¡Haré lo que pueda por encontrar eso!\n"
	.string "¡Hasta otra!$"

gText_ApprenticeItemAlreadyRecommended2:: @ 82BA7D8
	.string "Lo de {STR_VAR_1} ya me suena\n"
	.string "que me lo han dicho antes.\p"
	.string "Pero yo quiero que mi Pokémon\n"
	.string "sostenga algo distinto.\p"
	.string "¿O piensas que mi {STR_VAR_2}\n"
	.string "no debería sostener nada?$"

gText_ApprenticeWhatHeldItem3:: @ 82BA867
	.string "Hola, {PLAYER}…\n"
	.string "Perdona que te moleste, pero hay\l"
	.string "algo más que quería preguntarte.\p"
	.string "No creo que sea muy buena ganando\n"
	.string "solita los combates, y estaba pensando\l"
	.string "en que {STR_VAR_1} podía sostener algo.\p"
	.string "Pero no sé qué objeto le vendría mejor.\p"
	.string "{PLAYER}, porfa, ¿me ayudas?$"

gText_ApprenticeHoldNothing3:: @ 82BA96B
	.string "¿Crees que, teniendo en cuenta a quién\n"
	.string "pertenece, sería mejor que mi Pokémon\l"
	.string "no sostuviese ningún objeto?$"

gText_ApprenticeThanksNoHeldItem3:: @ 82BA9B7
	.string "Ya veo… Quieres decir que no debo\n"
	.string "confiar demasiado en los objetos, ¿eh?\p"
	.string "¡Haré lo posible por no confiar en ellos!\n"
	.string "¡Gracias mil!$"

gText_ApprenticeThanksHeldItem3:: @ 82BAA1B
	.string "Uf, {STR_VAR_1}, vale.\n"
	.string "No va a ser fácil conseguir algo así…\l"
	.string "Pero haré lo que pueda.\p"
	.string "¡Gracias mil!$"

gText_ApprenticeItemAlreadyRecommended3:: @ 82BAA81
	.string "Oh, pero…\n"
	.string "Eso ya me lo han recomendado…\p"
	.string "¿A lo mejor es que no sé manejar\n"
	.string "bien ninguna clase de {STR_VAR_1}?\p"
	.string "¿O me quieres decir realmente que\n"
	.string "{STR_VAR_2} no debería sostener nada?$"

gText_ApprenticeWhatHeldItem4:: @ 82BAB22
	.string "Oh, {PLAYER}{KUN}.\n"
	.string "Tenía ganas de preguntarte una cosa.\p"
	.string "¿Te acuerdas de que una vez me dijiste\n"
	.string "qué clase de Pokémon debería entrenar?\p"
	.string "Pues es que se te olvidó decirme\n"
	.string "qué clase de objeto debería sostener.\p"
	.string "Ya que te decidiste a darme un consejo,\n"
	.string "no quiero que lo dejes a medias, claro.\p"
	.string "Anda, dime, ¿qué objeto debería\n"
	.string "sostener mi {STR_VAR_1}?$"

gText_ApprenticeHoldNothing4:: @ 82BAC43
	.string "¡Ah! ¿Conque a mi {STR_VAR_1}\n"
	.string "le irá mejor si no lleva nada?$"

gText_ApprenticeThanksNoHeldItem4:: @ 82BAC78
	.string "Si de verdad piensas que es lo mejor,\n"
	.string "haré lo que dices.\p"
	.string "Sabiendo que me lo has dicho tú,\n"
	.string "{PLAYER}{KUN}, no me enfadaré si pierdo.\p"
	.string "Bueno, ya te pediré otro consejo\n"
	.string "otro día. ¡Chao!$"

gText_ApprenticeThanksHeldItem4:: @ 82BAD17
	.string "Así que {STR_VAR_1}, ¿eh?\n"
	.string "¡No está mal! ¡Tomo nota!\p"
	.string "Sabiendo que me lo has dicho tú,\n"
	.string "{PLAYER}{KUN}, no me enfadaré si pierdo.\p"
	.string "Bueno, ya te pediré otro consejo\n"
	.string "otro día. ¡Chao!$"

gText_ApprenticeItemAlreadyRecommended4:: @ 82BADB6
	.string "¿Cómo? Pero ¿de qué hablas?\n"
	.string "No me vengas otra vez con lo de\l"
	.string "{STR_VAR_1}.\p"
	.string "¿O quieres decir que a {STR_VAR_2}\n"
	.string "le iría mejor si no llevase nada?$"

gText_ApprenticeWhatHeldItem5:: @ 82BAE36
	.string "¡Mira quién está aquí!\n"
	.string "¡{PLAYER}{KUN}!\p"
	.string "Puede que tengamos mucho que hacer, \n"
	.string "¡pero siempre nos encontramos!\p"
	.string "Hoy he estado todo el día de aquí\n"
	.string "para allá.\p"
	.string "Ni siquiera he tenido tiempo de comprar\n"
	.string "nada a mi precioso {STR_VAR_1}.\p"
	.string "Oye, ¿por qué no me aconsejas\n"
	.string "algún objeto que le pueda venir bien?$"

gText_ApprenticeHoldNothing5:: @ 82BAF4E
	.string "Oh, así que, como tengo tanto lío, ¿no\n"
	.string "tengo que buscarle nada a {STR_VAR_1}?$"

gText_ApprenticeThanksNoHeldItem5:: @ 82BAF8F
	.string "Vale, ya sé por dónde vas.\n"
	.string "¡Así no perderé el tiempo de compras!\p"
	.string "¡Gracias!\n"
	.string "¡Ya nos veremos!$"

gText_ApprenticeThanksHeldItem5:: @ 82BAFDB
	.string "{STR_VAR_1}, vale, entiendo.\n"
	.string "A ver si puedo sacar un rato libre\l"
	.string "y me voy a comprar eso que dices.\p"
	.string "Me alegro de ser tu aprendiz.\n"
	.string "¡Gracias! ¡Ya nos veremos!$"

gText_ApprenticeItemAlreadyRecommended5:: @ 82BB05F
	.string "¿Eh? Lo de {STR_VAR_1} ya me suena\n"
	.string "de haberlo oído antes.\p"
	.string "¡Ah, ya! ¡Ahora pillo la indirecta!\n"
	.string "Que no pierda el tiempo en comprarle\l"
	.string "nada a {STR_VAR_2}, ¿no?$"

gText_ApprenticeWhatHeldItem6:: @ 82BB0D4
	.string "¡{PLAYER}! ¡Soy yo!\n"
	.string "Necesito tu coco otra vez.\l"
	.string "¡Tienes que darme un consejo!\p"
	.string "¡Iré al grano!\n"
	.string "Mi pregunta es…\p"
	.string "Si quiero que mi {STR_VAR_1} sostenga\n"
	.string "un objeto, ¿cuál me recomendarías?$"

gText_ApprenticeHoldNothing6:: @ 82BB18C
	.string "¿Seguro? Que mejor que mi {STR_VAR_1}\n"
	.string "no sostenga nada, dices, ¿eh?$"

gText_ApprenticeThanksNoHeldItem6:: @ 82BB1CE
	.string "¡Muy bien, con eso es suficiente!\p"
	.string "Es todo lo que quería preguntarte.\p"
	.string "Nos vemos aquí otra vez, ¿vale?\n"
	.string "¡Gracias!$"

gText_ApprenticeThanksHeldItem6:: @ 82BB242
	.string "¡Anda! ¡{STR_VAR_1}!\n"
	.string "¿Cómo no se me había ocurrido antes?\l"
	.string "¡Voy a probar ahora mismo con eso!\p"
	.string "Es todo lo que quería preguntarte.\p"
	.string "Nos vemos aquí otra vez, ¿vale?\n"
	.string "¡Gracias!$"

gText_ApprenticeItemAlreadyRecommended6:: @ 82BB2D9
	.string "¡Ja, ja, ja! ¡Qué tontería!\n"
	.string "¡Eso de {STR_VAR_1} ya me lo habías\l"
	.string "dicho antes!\p"
	.string "¿Seguro que estás bien, {PLAYER}?\p"
	.string "¡Espera! ¡Era una indirecta para decirme\n"
	.string "que {STR_VAR_2} no debería llevar nada!$"

gText_ApprenticeWhatHeldItem7:: @ 82BB370
	.string "Hola, {PLAYER}. \n"
	.string "¿Te va todo bien?\p"
	.string "¿Podría solicitar otra vez uno\n"
	.string "de tus maravillosos consejos?\p"
	.string "En mi último combate, creo que mi rival\n"
	.string "le dio un objeto a su Pokémon\l"
	.string "para que lo sostuviera.\p"
	.string "Creo que perdí por ese dichoso objeto…\p"
	.string "No quiero quedarme atrás.\n"
	.string "Yo también quiero que mi {STR_VAR_1}\l"
	.string "sostenga un objeto.\p"
	.string "Te agradecería mucho si me dijeses\n"
	.string "cuál le convendría más…$"

gText_ApprenticeHoldNothing7:: @ 82BB4C3
	.string "En otras palabras…, que mi Pokémon\n"
	.string "no necesita llevar ningún objeto…$"

gText_ApprenticeThanksNoHeldItem7:: @ 82BB4FB
	.string "¡Pues claro! ¡Ahora lo entiendo!\n"
	.string "Seguiré combatiendo como hasta ahora.\p"
	.string "Gracias, {PLAYER}.\n"
	.string "Espero poder contar contigo otra vez.\l"
	.string "Te me cuidas mucho, ¿vale?$"

gText_ApprenticeThanksHeldItem7:: @ 82BB575
	.string "¡{STR_VAR_1}! ¡Entendido!\n"
	.string "¡Ahora mismo voy a pedir lo que me dices!\p"
	.string "Gracias, {PLAYER}.\n"
	.string "Espero poder contar contigo otra vez.\l"
	.string "Te me cuidas mucho, ¿vale?$"

gText_ApprenticeItemAlreadyRecommended7:: @ 82BB5E1
	.string "¡Eso ya me lo dijiste\n"
	.string "y además ya lo tengo!\p"
	.string "¿O me estás diciendo que mi Pokémon\n"
	.string "no necesita llevar ningún objeto?$"

gText_ApprenticeWhatHeldItem8:: @ 82BB656
	.string "¡Hooola, {PLAYER}!\n"
	.string "¡Qu-qué alegría verte!\p"
	.string "¡Oh-oh-oh! ¡Ya sé! ¡Voy a preguntarte\n"
	.string "algo ahorita mismo, {PLAYER}!\p"
	.string "¡Dime qué objeto crees que\n"
	.string "debería sostener mi {STR_VAR_1}!$"

gText_ApprenticeHoldNothing8:: @ 82BB6E5
	.string "¡Oh, vaya! ¡Eso no me lo esperaba!\n"
	.string "¿Así que no tiene que llevar nada?$"

gText_ApprenticeThanksNoHeldItem8:: @ 82BB72C
	.string "¡Lo he entendido a la primera!\n"
	.string "¡Seguiré luchando sin objetos!\p"
	.string "Espero que no te olvides\n"
	.string "de seguir enseñándome cosas, ¿eh?$"

gText_ApprenticeThanksHeldItem8:: @ 82BB7A2
	.string "¡{STR_VAR_1}! ¡Por supuestísimo!\p"
	.string "Mmm… ¿No será, {PLAYER}, que tu Pokémon\n"
	.string "también sostiene ese objeto?\p"
	.string "¡Da igual! ¡Te haré caso!\n"
	.string "Espero que no te olvides\l"
	.string "de seguir enseñándome cosas, ¿eh?$"

gText_ApprenticeItemAlreadyRecommended8:: @ 82BB84A
	.string "¿Cómo? ¿{STR_VAR_1}? ¿Otra vez?\n"
	.string "¡Pero eso ya me lo recomendaste antes!\p"
	.string "Una de dos, o te gusta mucho,\n"
	.string "o me estás diciendo que mi {STR_VAR_2}\l"
	.string "no necesita llevar ningún objeto…$"

gText_ApprenticeWhatHeldItem9:: @ 82BB8CD
	.string "¡Hola! ¡{PLAYER}{KUN}!\n"
	.string "¡Qué ganas tenía de verte!\p"
	.string "Necesito que me aconsejes\n"
	.string "sobre los objetos Pokémon.\p"
	.string "¿Cuál crees que sería mejor\n"
	.string "que sostuviese mi {STR_VAR_1}?\p"
	.string "No te cortes.\n"
	.string "¡Venga, suéltalo!$"

gText_ApprenticeHoldNothing9:: @ 82BB970
	.string "¿Eh? ¿Así que mi {STR_VAR_1}\n"
	.string "no debería llevar nada?$"

gText_ApprenticeThanksNoHeldItem9:: @ 82BB9AE
	.string "¡Vale, vale!\n"
	.string "¡Lo intentaré como dices, a ver qué tal!\p"
	.string "¡Muy bien, gracias, como siempre!\n"
	.string "¡Adiós!$"

gText_ApprenticeThanksHeldItem9:: @ 82BBA05
	.string "¿{STR_VAR_1}? ¡Vale, vale!\n"
	.string "¡A ver si pillo algo de eso!\p"
	.string "¡Muy bien, gracias, como siempre!\n"
	.string "¡Adiós!$"

gText_ApprenticeItemAlreadyRecommended9:: @ 82BBA6C
	.string "¡No, no! ¡Eso ya lo has dicho antes!\n"
	.string "¡Sí, me acuerdo! ¡{STR_VAR_1}!\p"
	.string "Alto ahí… ¿No me estarás diciendo que\n"
	.string "{STR_VAR_2} puede ganar sin objetos?$"

gText_ApprenticeWhatHeldItem10:: @ 82BBB01
	.string "¡{PLAYER}{KUN}, ha pasado algo increíble!\p"
	.string "¡Cuando me levanté esta mañana,\n"
	.string "mi Pokémon tenía 10 Pepitas!\p"
	.string "¡Que no, que es broma!\n"
	.string "¡Ja, ja, ja, ja!\p"
	.string "Ahora en serio: no sé qué objeto\n"
	.string "debería sostener mi Pokémon.\p"
	.string "¿Por qué no decides tú por mí?\n"
	.string "¿Qué le doy a mi {STR_VAR_1}?$"

gText_ApprenticeHoldNothing10:: @ 82BBC1C
	.string "¿Qué significa eso?\n"
	.string "¿Que no sostenga nada?$"

gText_ApprenticeThanksNoHeldItem10:: @ 82BBC4B
	.string "Vale, entonces no sostendrá nada.\n"
	.string "Pero yo sí puedo, ¿no?\p"
	.string "¡Es broma!\n"
	.string "¡Te voy a hacer caso!\p"
	.string "¡Gracias!\n"
	.string "¡Espero que sigas instruyéndome!$"

gText_ApprenticeThanksHeldItem10:: @ 82BBCF6
	.string "¡{STR_VAR_1}! ¡Entendido!\n"
	.string "¡Le compraré todo menos eso!\p"
	.string "¡Es broma!\n"
	.string "¡Te haré caso!\p"
	.string "¡Gracias!\n"
	.string "¡Espero que sigas instruyéndome!$"

gText_ApprenticeItemAlreadyRecommended10:: @ 82BBD90
	.string "¡Pero si eso ya me lo has dicho otra vez!\p"
	.string "¿No se te ocurre otra cosa?\p"
	.string "¿O quieres decir que es mejor\n"
	.string "que mi {STR_VAR_2} no sostenga nada?$"

gText_ApprenticeWhatHeldItem11:: @ 82BBE0B
	.string "¡Hola, hola, hola,\n"
	.string "dijo el mar a la caracola!\p"
	.string "Soy un poeta marinero,\n"
	.string "y necesito otro de tus consejos\l"
	.string "para llegar a donde quiero.\p"
	.string "¡Aconséjame bien sobre un objeto\n"
	.string "y te ganarás todo mi respeto!\p"
	.string "Dime, ¿de entre todos los objetos,\n"
	.string "cuál debe mi {STR_VAR_1} llevar sujeto?$"

gText_ApprenticeHoldNothing11:: @ 82BBEE5
	.string "La cosa no parece muy clara. Acaso…,\n"
	.string "¿no debe mi {STR_VAR_1} sujetar nada?$"

gText_ApprenticeThanksNoHeldItem11:: @ 82BBF25
	.string "¡Ah, claro! ¡Ya entiendo tu teoría!\n"
	.string "¡Mi Pokémon irá con las manos vacías!\p"
	.string "¡Aquí vendré si necesito otro consejo!\n"
	.string "¡Hasta entonces, {PLAYER}, te dejo!$"

gText_ApprenticeThanksHeldItem11:: @ 82BBFA4
	.string "¿{STR_VAR_1}? ¿Has dicho eso?\n"
	.string "¡Si no picara mi barba, te daría un beso!\p"
	.string "¡Aquí vendré si necesito otro consejo!\n"
	.string "¡Hasta entonces, {PLAYER}, te dejo!$"

gText_ApprenticeItemAlreadyRecommended11:: @ 82BC024
	.string "{STR_VAR_1} me dijiste ya el otro día…\n"
	.string "¿Te repites o es solo antipatía?\p"
	.string "Espera, ahora veo la cosa más clara…,\n"
	.string "¿no debe mi Pokémon sujetar nada?$"

gText_ApprenticeWhatHeldItem12:: @ 82BC0C8
	.string "Oh, “yea”, {PLAYER}, ¿qué tal?\n"
	.string "¡A mí me va la cosa fatal!\p"
	.string "¿Qué hago? ¿Te pido consejo?\n"
	.string "¿Por qué no? ¡Si tú eres mi espejo!\p"
	.string "{PLAYER}, ¿te estoy dando la lata?\n"
	.string "Naa, qué va, ¡yo nunca meto la pata!\p"
	.string "¿Me escucharías un segundo?\n"
	.string "Estoy buscando un consejo\l"
	.string "para ganar combates por todo el mundo.\p"
	.string "Anda, dime, ¿qué objeto crees\n"
	.string "que mi {STR_VAR_1} debería sujetar?\l"
	.string "Es una decisión que no puedo demorar.$"

gText_ApprenticeHoldNothing12:: @ 82BC213
	.string "¿Que mi {STR_VAR_1} no necesita nada?\n"
	.string "¡Eso sí que no me lo esperaba!$"

gText_ApprenticeThanksNoHeldItem12:: @ 82BC247
	.string "Si llevar nada es lo mejor,\n"
	.string "¡voy a tener que echarle valor!\p"
	.string "¡{PLAYER}, fue un placer encontrarte!\n"
	.string "¡Me largo con la música a otra parte!$"

gText_ApprenticeThanksHeldItem12:: @ 82BC2DD
	.string "¿{STR_VAR_1}? ¡Si eso es lo mejor,\n"
	.string "adelante, le echaré valor!\p"
	.string "¡{PLAYER}, fue un placer encontrarte!\n"
	.string "¡Me largo con la música a otra parte!$"

gText_ApprenticeItemAlreadyRecommended12:: @ 82BC373
	.string "¿{STR_VAR_1}? Esa cosa ya me suena.\n"
	.string "¿No tienes una idea más nueva?\p"
	.string "Pero, espera, quieres decir acaso…,\n"
	.string "¿que mi {STR_VAR_2} no necesita nada?\l"
	.string "¡Eso sí que no me lo esperaba!$"

gText_ApprenticeWhatHeldItem13:: @ 82BC40E
	.string "¡Uaa! ¡Ay! ¡{PLAYER}{KUN}, me he roto el brazo!\n"
	.string "¡No me lo toques, por favor!\p"
	.string "He debido de rompérmelo antes cuando\n"
	.string "estaba intentando sujetar distintos\l"
	.string "objetos con mi pose de Pokémon.\p"
	.string "Bueno, visto lo visto, ahora voy\n"
	.string "a necesitar tu ayuda para decidirme.\p"
	.string "{PLAYER}{KUN}, ¿qué objeto crees\n"
	.string "que debería sujetar mi {STR_VAR_1}?$"

gText_ApprenticeHoldNothing13:: @ 82BC514
	.string "¡Ay!…\p"
	.string "¿Tanto probar y ahora me dices que\n"
	.string "mi {STR_VAR_1} no debería llevar nada?$"

gText_ApprenticeThanksNoHeldItem13:: @ 82BC555
	.string "Mmm, de acuerdo. Tal y como están\n"
	.string "las cosas ahora, me vendrá bien.\p"
	.string "¡Espero poder seguir contando\n"
	.string "con tu ayuda!$"

gText_ApprenticeThanksHeldItem13:: @ 82BC5CE
	.string "¿{STR_VAR_1}? Mmm, de acuerdo.\n"
	.string "El brazo de mi Pokémon está bien,\l"
	.string "así que le haré sujetar eso ahora mismo.\p"
	.string "¡Espero poder seguir contando\n"
	.string "con tu ayuda!$"

gText_ApprenticeItemAlreadyRecommended13:: @ 82BC666
	.string "¿{STR_VAR_1}? ¿Otra vez?\n"
	.string "¡Pero eso ya me lo dijiste antes!\p"
	.string "¿Por qué no me dices algo mejor?\p"
	.string "Pero, un momento. Ya veo, ya veo…\n"
	.string "Me estás diciendo que mi {STR_VAR_2}\l"
	.string "no debería llevar nada, ¿verdad?$"

gText_ApprenticeWhatHeldItem14:: @ 82BC714
	.string "Eh… Mmm…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "Anda, por favor, no me mires así.\n"
	.string "Mi Pokémon no tiene nada.\p"
	.string "Me… avergüenza un poco decirlo,\n"
	.string "pero necesito otro consejo tuyo.\p"
	.string "No me decido sobre qué objeto haría más\n"
	.string "fuerte a mi {STR_VAR_1} si lo sujetara.\p"
	.string "{PLAYER}{KUN}, ¿tú cuál crees\n"
	.string "que lo haría más fuerte?$"

gText_ApprenticeHoldNothing14:: @ 82BC808
	.string "Oh… Conque piensas que a mí {STR_VAR_1}\n"
	.string "le iría mejor si no sujetase nada…$"

gText_ApprenticeThanksNoHeldItem14:: @ 82BC84D
	.string "Eh… ¡Como tú digas!\n"
	.string "Sin ningún objeto, entonces.\p"
	.string "Aunque me agobia un poco la idea.\n"
	.string "¿No crees que es ir de muy guay?\p"
	.string "Bueno, gracias, {PLAYER}{KUN}.\n"
	.string "Ojalá nos veamos pronto otra vez.\l"
	.string "¡Estos consejos tuyos son geniales!$"

gText_ApprenticeThanksHeldItem14:: @ 82BC8EA
	.string "Oh… ¡Como tú digas!\n"
	.string "¿{STR_VAR_1}? Vale, vale.\p"
	.string "Aunque me agobia un poco la idea.\n"
	.string "¿No crees que es ir de muy guay?\p"
	.string "Bueno, gracias, {PLAYER}{KUN}.\n"
	.string "Ojalá nos veamos pronto otra vez.\l"
	.string "¡Estos consejos tuyos son geniales!$"

gText_ApprenticeItemAlreadyRecommended14:: @ 82BC984
	.string "Pe-pero eso ya me suena de otra vez.\p"
	.string "¡Anda, no te burles así de mí!\n"
	.string "¡Bastante agobio tengo ya!\p"
	.string "Oh, espera… ¿Era una indirecta?…\n"
	.string "¿En realidad estás diciéndome que\l"
	.string "mi {STR_VAR_2} no debería sujetar nada?$"

gText_ApprenticeWhatHeldItem15:: @ 82BCA4D
	.string "¿Mmm? Vaya, pareces ser {PLAYER}{KUN}…\n"
	.string "Pero ¿lo eres en realidad?\l"
	.string "¿O es que te pareces mucho?\p"
	.string "¡Oh, no, no, no, no te preocupes!\n"
	.string "Si de verdad eres {PLAYER}, por favor,\l"
	.string "perdona el despiste.\p"
	.string "La verdad es que me gustaría\n"
	.string "solicitar uno de tus sabios consejos.\p"
	.string "Desearía conocer el objeto que más le\n"
	.string "convendría sostener a mi {STR_VAR_1}.\p"
	.string "¿Cuál crees que sería más digno de él?$"

gText_ApprenticeHoldNothing15:: @ 82BCB75
	.string "¿Nada, dices que sostenga?\n"
	.string "¿Es ésa tu conclusión?$"

gText_ApprenticeThanksNoHeldItem15:: @ 82BCBA6
	.string "Ya veo. Así lo haré si ése es tu consejo.\n"
	.string "Déjame expresarte mi agradecimiento.\p"
	.string "¡Sería todo un placer volver a verte!\n"
	.string "Ahora, si me disculpas…$"

gText_ApprenticeThanksHeldItem15:: @ 82BCBFC
	.string "¿{STR_VAR_1}?\n"
	.string "¿Es ésa tu conclusión?\p"
	.string "Ya veo. Así lo haré si ése es tu consejo.\n"
	.string "Déjame expresarte mi agradecimiento.\p"
	.string "Confío en que mi Pokémon sabrá hacer\n"
	.string "buen uso del objeto que recomiendas.\p"
	.string "¡Sería todo un placer volver a verte!\n"
	.string "Ahora, si me disculpas…$"

gText_ApprenticeItemAlreadyRecommended15:: @ 82BCCA4
	.string "Vaya, qué contradicción.\n"
	.string "Creo haber oído eso ya otra vez de ti.\p"
	.string "Me hubiese gustado oír\n"
	.string "algo diferente esta vez.\p"
	.string "Salvo que… estés sugiriéndome que mi\n"
	.string "{STR_VAR_2} no sujete nada…\l"
	.string "¿Estoy en lo cierto? ¿Es lo que dices?$"

gText_ApprenticeWhichMonFirst0:: @ 82BCD68
	.string "¡Ay, {PLAYER}!\n"
	.string "Qué dilema tengo, snif…\p"
	.string "Quiero empezar a combatir,\n"
	.string "pero no sé muy bien qué hacer.\p"
	.string "¿Cómo debo alinear mis Pokémon\n"
	.string "para que sean más fuertes?\p"
	.string "Porfa, dímelo, {PLAYER}.\n"
	.string "Si fueses yo, ¿a cuál de estos Pokémon\l"
	.string "sacarías a combatir en primer lugar?$"

gText_ApprenticeMonFirstThanks0:: @ 82BCE64
	.string "¿Primero mi {STR_VAR_1}?\n"
	.string "¡Buaaaaaa!\p"
	.string "¡Oh! ¡Lo siento mucho!\n"
	.string "De tanta alegría por elegir a mi primer\l"
	.string "Pokémon me he puesto a llorar…\p"
	.string "¡Muchas gracias!$"

gText_ApprenticeWhichMonFirst1:: @ 82BCEF2
	.string "¡Yupi, {PLAYER}! ¡Qué suerte!\n"
	.string "¡Así podré hacerte una pregunta!\p"
	.string "Eh, de todos mis Pokémon, ¿a cuál crees\n"
	.string "que debería sacar primero a combatir?$"

gText_ApprenticeMonFirstThanks1:: @ 82BCF61
	.string "¿Mi {STR_VAR_1}? ¡Claro, es verdad!\n"
	.string "¡Perfecto, será lo que haga!\p"
	.string "¡Gracias por enseñarme!$"

gText_ApprenticeWhichMonFirst2:: @ 82BCFA1
	.string "¡{PLAYER}, hola!\p"
	.string "Creo que es muy importante elegir qué\n"
	.string "Pokémon saldrá primero a combatir.\p"
	.string "De todos los Pokémon que tengo,\n"
	.string "¿a cuál debería sacar primero?$"

gText_ApprenticeMonFirstThanks2:: @ 82BD03C
	.string "¿{STR_VAR_1}, el primero?\n"
	.string "¡Vale, entendido!\p"
	.string "¡Nos vemos!$"

gText_ApprenticeWhichMonFirst3:: @ 82BD06D
	.string "Hola, {PLAYER}…\n"
	.string "Siento molestarte otra vez\l"
	.string "con una de mis preguntas.\p"
	.string "Confío tan poco en mí…\n"
	.string "No sé lo que haría sin ti, {PLAYER}.\p"
	.string "A lo mejor es solo una tontería,\n"
	.string "pero te lo pregunto de todos modos\l"
	.string "porque no me decido…\p"
	.string "¿A qué Pokémon debería sacar\n"
	.string "primero en los combates?$"

gText_ApprenticeMonFirstThanks3:: @ 82BD18A
	.string "¿Mi {STR_VAR_1}?\n"
	.string "¡Entendido!\p"
	.string "¡Qué suerte! ¡Creí que no ibas a querer\n"
	.string "responder a todas mis preguntillas!\p"
	.string "Te daría las gracias aunque solo fuera\n"
	.string "por hablar conmigo… ¡Gracias!$"

gText_ApprenticeWhichMonFirst4:: @ 82BD222
	.string "¡Eh, hola, {PLAYER}{KUN}! ¡Soy yo!\n"
	.string "Qué suerte que estés aquí,\l"
	.string "porque tengo una duda.\p"
	.string "No me decido sobre cuál sería la mejor\n"
	.string "alineación de mis Pokémon. ¿Me ayudas?\p"
	.string "No hace falta que decidas toda\n"
	.string "la alineación ahora.\p"
	.string "Basta que me digas a qué Pokémon\n"
	.string "sacarías primero. ¿Cuál sería mejor?$"

gText_ApprenticeMonFirstThanks4:: @ 82BD325
	.string "¿Mi querido {STR_VAR_1}? ¡Fenomenal!\p"
	.string "Sabiendo que lo has decidido tú,\n"
	.string "{PLAYER}{KUN}, ya no me enfadaré si pierdo.\p"
	.string "Bueno, ya te pediré otro consejo\n"
	.string "otro día. ¡Chao!$"

gText_ApprenticeWhichMonFirst5:: @ 82BD3B1
	.string "¡Hola, {PLAYER}{KUN}!\n"
	.string "¡Sigo sin parar de hacer cosas!\p"
	.string "Que si correr en bici, que si comprar,\n"
	.string "que si hacer esto y aquello…\p"
	.string "La verdad es que no he tenido tiempo de\n"
	.string "pensar en la alineación de mis Pokémon.\p"
	.string "Anda, ¿por qué no me ayudas tú un poco?\n"
	.string "¿A cuál debería sacar siempre primero?$"

gText_ApprenticeMonFirstThanks5:: @ 82BD493
	.string "Hecho.\n"
	.string "¡Espero al menos tener tiempo para\l"
	.string "poner a mi {STR_VAR_1} el primero!\p"
	.string "¡Huy, me está esperando mi novia!\n"
	.string "¡Gracias! ¡Nos vemos!$"

gText_ApprenticeWhichMonFirst6:: @ 82BD51C
	.string "¡Eh, mírate, {PLAYER}!\n"
	.string "¡Siempre vas por ahí de perdonavidas!\p"
	.string "Escucha, necesito otro favorcillo.\n"
	.string "Una cosilla de nada, ya sabes.\p"
	.string "Y la pregunta es…\n"
	.string "¡Tachán, tachán!…\p"
	.string "¿A cuál de mis Pokémon\n"
	.string "debo sacar primero en los combates?$"

gText_ApprenticeMonFirstThanks6:: @ 82BD609
	.string "¡Mmm!\n"
	.string "Mi {STR_VAR_1}, ¿dices?\l"
	.string "¡Gracias por enrollarte!\p"
	.string "Creo que eso es todo\n"
	.string "lo que quería preguntarte.\p"
	.string "Nos vemos aquí otra vez, ¿vale?\n"
	.string "¡Gracias!$"

gText_ApprenticeWhichMonFirst7:: @ 82BD697
	.string "Huy, qué fenomenal que vengas\n"
	.string "a hablar conmigo, {PLAYER}.\p"
	.string "No quiero parecer una desvergonzada,\n"
	.string "pero ¿podría pedirte otro favor?\p"
	.string "Querría que eligieses por mí el orden\n"
	.string "de los Pokémon de mi equipo.\p"
	.string "Te estaría agradecidísima si me dijeras\n"
	.string "a cuál de mis Pokémon sacarías primero.$"

gText_ApprenticeMonFirstThanks7:: @ 82BD797
	.string "¿{STR_VAR_1}? ¡Justo lo que pensaba!\n"
	.string "¡Voy a ponerlo primero ahora mismo!\p"
	.string "Oye, que muchísimas gracias, {PLAYER}.\n"
	.string "Espero que me sigas ayudando.\l"
	.string "Te me cuidas muchísimo, ¿vale?$"

gText_ApprenticeWhichMonFirst8:: @ 82BD806
	.string "¡Hooola, {PLAYER}!\n"
	.string "¡Qu-qué alegría verte otra vez!\p"
	.string "¡Gracias a ti, mis Pokémon son ahora\n"
	.string "pero que muchísimo más fuertes!\p"
	.string "Aunque no siempre gano. Creo que\n"
	.string "depende de qué Pokémon salga primero.\p"
	.string "¡{PLAYER}, por favor, ayúdame con esto!\p"
	.string "¡Elige al Pokémon que crees que\n"
	.string "tengo que sacar primero a combatir!$"

gText_ApprenticeMonFirstThanks8:: @ 82BD8F5
	.string "Ay…\n"
	.string "¡Si es que tengo más suerte que…!\p"
	.string "Es un sueño hecho realidad\n"
	.string "que decidas por mí, {PLAYER}.\p"
	.string "¡Perfecto, perfecto!\n"
	.string "¡Sacaré primero a mi {STR_VAR_1}!\p"
	.string "Espero que no te olvides\n"
	.string "de seguir enseñándome cosas, ¿eh?$"

gText_ApprenticeWhichMonFirst9:: @ 82BD9BE
	.string "¡Pero si eres tú, {PLAYER}{KUN}!\n"
	.string "¡Sorpréndeme con otro sabio\l"
	.string "consejo de los tuyos!\p"
	.string "He conseguido formar un equipo de tres\n"
	.string "Pokémon. Así dicho, la cosa suena bien.\p"
	.string "Pero no tengo muy claro el orden\n"
	.string "en que deben combatir.\p"
	.string "¡Y para eso estás tú aquí, {PLAYER}{KUN}! ¡Tú\n"
	.string "decidirás a qué Pokémon saco primero!\p"
	.string "No te cortes.\n"
	.string "¡Venga, suéltalo!$"

gText_ApprenticeMonFirstThanks9:: @ 82BDAE1
	.string "¡Eso es, mi {STR_VAR_1} será el primero!\n"
	.string "¡G-e-n-i-a-l!\l"
	.string "¡Voy a cambiar ya mismo la alineación!\p"
	.string "¡Muy bien, gracias, como siempre!\n"
	.string "¡Adiós!$"

gText_ApprenticeWhichMonFirst10:: @ 82BDB4E
	.string "¡{PLAYER}{KUN}, escucha!\n"
	.string "¡Estoy en medio de una crisis!\p"
	.string "¡Los tres Pokémon de mi equipo\n"
	.string "salen a la vez a combatir!\p"
	.string "¡Bueno, bueno, “casi” a la vez!\n"
	.string "Je, je, je, je.\p"
	.string "Pero hay algo que es verdad.\n"
	.string "Mis tres Pokémon son tan buenos que\l"
	.string "no me decido a elegir cuál sale primero.\p"
	.string "¿Por qué no me ayudas? ¿Tú qué crees,\n"
	.string "a qué Pokémon sacarías primero?$"

gText_ApprenticeMonFirstThanks10:: @ 82BDC6B
	.string "Entendido, mi {STR_VAR_1}, vale.\n"
	.string "¡Lo pondré el último!\p"
	.string "¡Es broma!\n"
	.string "¡Te haré caso!\p"
	.string "¡Gracias!\n"
	.string "¡Espero que sigas instruyéndome!$"

gText_ApprenticeWhichMonFirst11:: @ 82BDD0D
	.string "¡Hola, hola, hola,\n"
	.string "dijo el mar a la caracola!\p"
	.string "Soy un poeta marinero,\n"
	.string "y necesito otro de tus consejos\l"
	.string "para llegar a donde quiero.\p"
	.string "¡Aconséjame sobre la alineación\n"
	.string "y te lo agradeceré con devoción!\p"
	.string "De todos los Pokémon de este marinero\n"
	.string "¿con cuál combatirías primero?$"

gText_ApprenticeMonFirstThanks11:: @ 82BDDEC
	.string "¡Hacerte caso es lo que quiero!\n"
	.string "¡Pondré al que dices primero!\p"
	.string "¡Aquí vendré si necesito otro consejo!\n"
	.string "¡Hasta entonces, {PLAYER}, te dejo!$"

gText_ApprenticeWhichMonFirst12:: @ 82BDE68
	.string "¡Ey, {PLAYER}, “yea”!\n"
	.string "¡Qué bueno que viniste!\p"
	.string "¿Qué hago? ¿Te pregunto?\n"
	.string "Teniendo algo que preguntar,\l"
	.string "hasta a veces yo me pregunto:\l"
	.string "¿a qué viene tanto dudar?\p"
	.string "Sí, no, sí, no, probando, probando.\n"
	.string "¡Te diré lo que quiero cantando!\p"
	.string "Dime, pues, de mis Pokémon\n"
	.string "¿a cuál pondrías primero?$"

gText_ApprenticeMonFirstThanks12:: @ 82BDF4D
	.string "¿Mi {STR_VAR_1}? ¡Pues claro!\n"
	.string "¡Menos mal que te he preguntado!\p"
	.string "¡{PLAYER}, fue un placer encontrarte!\n"
	.string "¡Me largo con la música a otra parte!$"

gText_ApprenticeWhichMonFirst13:: @ 82BDFD8
	.string "Uuf… Auu… {PLAYER}{KUN}…\n"
	.string "Me duele mucho la tripa…\p"
	.string "Pero se me está pasando…\p"
	.string "Deben de ser los nervios por no saber\n"
	.string "a qué Pokémon debería sacar primero.\p"
	.string "Bueno, estando yo tan mal, \n"
	.string "vas a tener que decidir tú.\p"
	.string "{PLAYER}{KUN}, ¿a qué Pokémon debería\n"
	.string "sacar primero? Para ganar, se entiende.$"

gText_ApprenticeMonFirstThanks13:: @ 82BE0FD
	.string "Mm, muy bien.\n"
	.string "Pondré primero a mi {STR_VAR_1}.\p"
	.string "Voy a comer algo y luego arreglo\n"
	.string "lo de la alineación.\p"
	.string "¡Espero poder seguir contando\n"
	.string "con tu ayuda!$"

gText_ApprenticeWhichMonFirst14:: @ 82BE189
	.string "Esto… Mm…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "Anda, por favor, no me mires así.\n"
	.string "Me vas a sacar los colores.\p"
	.string "Mm…\n"
	.string "Necesito tu consejo, de verdad.\p"
	.string "Ahora que por fin había elegido los\n"
	.string "tres Pokémon de mi equipo, no me\l"
	.string "decido por cuál debería salir primero.\p"
	.string "¿Cuál crees que debería salir primero\n"
	.string "para por lo menos no hacer el ridículo?$"

gText_ApprenticeMonFirstThanks14:: @ 82BE2A5
	.string "Ah… ¡Vale!\n"
	.string "Pondré a mi {STR_VAR_1} primero.\p"
	.string "Espero hacerlo bien y no aturullarme\n"
	.string "en el momento del combate.\p"
	.string "Bueno, gracias, {PLAYER}{KUN}.\n"
	.string "Ojalá nos veamos pronto otra vez.\l"
	.string "¡Estos consejos tuyos son geniales!$"

gText_ApprenticeWhichMonFirst15:: @ 82BE33E
	.string "¿Mmm? Vaya, pareces ser {PLAYER}{KUN}…\n"
	.string "Pero ¿lo eres en realidad?\l"
	.string "¿O es que os parecéis un horror?\p"
	.string "¡Oh, no, no, no, no te preocupes!\n"
	.string "Si de verdad eres {PLAYER}, por favor,\l"
	.string "perdona el despiste.\p"
	.string "Lo cierto es que requiero una vez más\n"
	.string "uno de tus sabios consejos.\p"
	.string "Tengo aquí a mi equipo de Pokémon.\n"
	.string "Te rogaría me dijeses a cuál sacarías\l"
	.string "primero a combatir.$"

gText_ApprenticeMonFirstThanks15:: @ 82BE46C
	.string "Mi {STR_VAR_1}…\n"
	.string "¿Te burlas de mí?\p"
	.string "En fin, confiaré en tu buen juicio.\n"
	.string "Tienes todo mi agradecimiento.\p"
	.string "Confío en hacerlo lo mejor que pueda.\p"
	.string "¡Sería todo un placer volver a verte!\n"
	.string "Ahora, si me disculpas…$"

gText_ApprenticeWhichMon0:: @ 82BE50D
	.string "Snif…\n"
	.string "¡Oh, {PLAYER}!\p"
	.string "¡Justo a tiempo!\n"
	.string "Hay una duda que me tiene en vilo…\p"
	.string "No sé qué Pokémon debería usar.\p"
	.string "Estoy dudando entre\n"
	.string "{STR_VAR_1} y {STR_VAR_2}…\p"
	.string "{PLAYER}, ¿con cuál crees que tendría\n"
	.string "más posibilidades de ganar?$"

gText_ApprenticeMonThanks0:: @ 82BE5F5
	.string "Snif… Ya… Comprendo.\n"
	.string "¡Oh! ¡Cuánto lo siento!\l"
	.string "Son lágrimas de felicidad otra vez…\p"
	.string "¡Haré lo que pueda por atrapar uno\n"
	.string "de esos {STR_VAR_1}!\p"
	.string "¡Muchas gracias!$"

gText_ApprenticeWhichMon1:: @ 82BE679
	.string "¡Yupi! ¡Eres {PLAYER}!\n"
	.string "¡Y llegas en el momento adecuado!\l"
	.string "¡Necesito otra vez tu ayuda!\p"
	.string "Estoy hecho un lío. Que si el\n"
	.string "{STR_VAR_1} o que si el {STR_VAR_2}…\p"
	.string "¿Cuál crees que debería entrenar,\n"
	.string "{PLAYER}?$"

gText_ApprenticeMonThanks1:: @ 82BE71E
	.string "Oh, mejor mi {STR_VAR_1}, ¿eh?\n"
	.string "¡Genial, haré justo eso!\p"
	.string "¡Gracias por enseñarme!$"

gText_ApprenticeWhichMon2:: @ 82BE762
	.string "¡{PLAYER}, hola!\n"
	.string "Quería preguntarte algo.\p"
	.string "Tengo el dilema de si debería entrenar\n"
	.string "un {STR_VAR_1} o un {STR_VAR_2}.\p"
	.string "¿Con qué Pokémon crees que llegaré\n"
	.string "a hacerme más fuerte?$"

gText_ApprenticeMonThanks2:: @ 82BE7F8
	.string "Un {STR_VAR_1}. Perfecto.\n"
	.string "¡Vale, lo he entendido!\p"
	.string "¡Voy a atrapar ahora mismo\n"
	.string "un {STR_VAR_1} fuerte de verdad!\p"
	.string "¡Nos vemos!$"

gText_ApprenticeWhichMon3:: @ 82BE850
	.string "Hola, {PLAYER}…\p"
	.string "Mm, probablemente ya ni te acuerdes\n"
	.string "de mí…\p"
	.string "Pero no importa, con tal de que quieras\n"
	.string "volver a darme un consejo…\p"
	.string "No me decido por qué clase de\n"
	.string "Pokémon debería entrenar…\p"
	.string "Ahora la duda está entre un {STR_VAR_1}\n"
	.string "o un {STR_VAR_2}, pero no salgo de ahí…\p"
	.string "{PLAYER}, ¿sería mucho pedirte\n"
	.string "que decidieses por mí?$"

gText_ApprenticeMonThanks3:: @ 82BE99C
	.string "Espero que los {STR_VAR_1} salvajes\n"
	.string "no pasen también de mí.\p"
	.string "¡Intentaré encontrar uno!\p"
	.string "No sé si seré capaz de encontrar uno…\n"
	.string "¡No! ¡Basta ya! ¡Tengo que ser positiva!\p"
	.string "¡Gracias!$"

gText_ApprenticeWhichMon4:: @ 82BEA1B
	.string "¡Oh, {PLAYER}{KUN}! ¡Qué alegría verte!\n"
	.string "¡Justo iba a ir a buscarte!\p"
	.string "¿Me ayudarías a decidir qué Pokémon\n"
	.string "debería entrenar?\p"
	.string "Por ejemplo…\n"
	.string "¿Un {STR_VAR_1} o un {STR_VAR_2}?\p"
	.string "¿Cuál de los dos elegirías para mí?$"

gText_ApprenticeMonThanks4:: @ 82BEAE9
	.string "¿{STR_VAR_1}? ¡Maravilloso!\p"
	.string "Sabiendo que lo decidiste tú, {PLAYER}{KUN},\n"
	.string "no podré enfadarme si pierdo.\p"
	.string "Bueno, ya te pediré otro consejo\n"
	.string "otro día. ¡Chao!$"

gText_ApprenticeWhichMon5:: @ 82BEB72
	.string "¡Pero si es {PLAYER}{KUN}! ¿Cómo te va?\n"
	.string "¡Yo, ocupado, como siempre!\p"
	.string "Ya sabes que yo también quiero llegar a\n"
	.string "ser alguien muy bueno con mis Pokémon,\l"
	.string "pero no sé en cuál debo centrarme.\p"
	.string "Sí, los {STR_VAR_1} son fuertes,\n"
	.string "pero los {STR_VAR_2} no lo son menos.\p"
	.string "¡{PLAYER}{KUN}, dame un consejillo!\n"
	.string "¿Cuál me vendría mejor a mí?$"

gText_ApprenticeMonThanks5:: @ 82BEC8E
	.string "Perfecto, entendido.\n"
	.string "A ver si pillo un rato libre y atrapo uno\l"
	.string "de esos {STR_VAR_1} que recomiendas.\p"
	.string "Me alegro de ser tu aprendiz.\n"
	.string "¡Gracias! ¡Ya nos veremos!$"

gText_ApprenticeWhichMon6:: @ 82BED16
	.string "¡Oh!\n"
	.string "¡Eh, hola, es {PLAYER}!\p"
	.string "¡No he perdido el tiempo presumiendo de\n"
	.string "haberte conocido delante de mis amigos!\p"
	.string "Necesito tu coco otra vez.\n"
	.string "¡Ahí va una fácil para ti!\p"
	.string "Y la pregunta es…\n"
	.string "Tachán, tachán…\p"
	.string "Si tuviera que entrenar un Pokémon,\n"
	.string "y las opciones fueran un {STR_VAR_1}\l"
	.string "o un {STR_VAR_2}, ¿cuál debería elegir?$"

gText_ApprenticeMonThanks6:: @ 82BEE29
	.string "¡Aaah!\n"
	.string "¡{STR_VAR_1}, claro!\l"
	.string "¡Gracias por enrollarte!\p"
	.string "Creo que eso es todo lo\n"
	.string "que quería preguntarte.\p"
	.string "Nos vemos aquí otra vez, ¿vale?\n"
	.string "¡Gracias!$"

gText_ApprenticeWhichMon7:: @ 82BEEB4
	.string "¡Oh, oh, oh! ¡{PLAYER}!\n"
	.string "¡Encantadísima de volver a verte!\p"
	.string "Desde que soy tu aprendiz,\n"
	.string "tengo mucha más confianza en mí misma.\p"
	.string "¡Creo que ya estoy preparada para\n"
	.string "entrenar un Pokémon yo solita!\p"
	.string "¡Sólo necesito que ahora tú\n"
	.string "me aconsejes cuál, {PLAYER}!\p"
	.string "Las opciones son un Pokémon\n"
	.string "{STR_VAR_1} o un {STR_VAR_2}…\l"
	.string "¿Cuál es mejor para mí?$"

gText_ApprenticeMonThanks7:: @ 82BEFE2
	.string "¡Un {STR_VAR_1}! ¡Perfecto!\n"
	.string "¡Voy a buscar uno ahora mismo!\p"
	.string "Oye, que muchísimas gracias, {PLAYER}.\n"
	.string "Espero que me sigas ayudando.\l"
	.string "Te me cuidas muchísimo, ¿vale?$"

gText_ApprenticeWhichMon8:: @ 82BF04E
	.string "¡Hooola, {PLAYER}! ¡Qué suerte!\n"
	.string "¡Qu-qué alegría verte!\p"
	.string "¡Oh-oh-oh, ya sé!\n"
	.string "¡No quiero que te me vayas así!\p"
	.string "¿Puedo pedirte un gran favor, {PLAYER}?\n"
	.string "¡Elige un Pokémon por mí!\p"
	.string "Decide por mí a cuál debería entrenar,\n"
	.string "¿a {STR_VAR_1} o a {STR_VAR_2}?$"

gText_ApprenticeMonThanks8:: @ 82BF11D
	.string "¡Guay! ¡Gracias por decidir!\n"
	.string "¡Voy a entrenar a ese {STR_VAR_1}\l"
	.string "lo mejor que pueda, ya verás!\p"
	.string "Espero que no te olvides de\n"
	.string "seguir enseñándome cosas, ¿eh?$"

gText_ApprenticeWhichMon9:: @ 82BF1A8
	.string "¡Eh, eh! ¡{PLAYER}{KUN}!\n"
	.string "¡Soy tu aprendiz favorito! Espero…\p"
	.string "¡He andado por ahí buscándote porque\n"
	.string "necesito otro de tus sabios consejos!\p"
	.string "¿Cuál de estos dos Pokémon piensas\n"
	.string "tú que me convendría entrenar más,\l"
	.string "un {STR_VAR_1} o un {STR_VAR_2}?\p"
	.string "No te cortes.\n"
	.string "¡Venga, suéltalo!$"

gText_ApprenticeMonThanks9:: @ 82BF268
	.string "¡Ah, ajá, un {STR_VAR_1}!\n"
	.string "¡Genial!\l"
	.string "¡Voy a meterlo en mi bola pero que ya!\p"
	.string "¡Muy bien, gracias, como siempre!\n"
	.string "¡Adiós!$"

gText_ApprenticeWhichMon10:: @ 82BF2D1
	.string "¡{PLAYER}{KUN}, escucha! ¡Buenas noticias!\n"
	.string "¡He pillado un Pokémon espejismo!\p"
	.string "¡Es broma!\n"
	.string "¡Ja, ja, ja, ja!\p"
	.string "Pero lo que voy a decirte ahora no lo es.\n"
	.string "Soy un poco malillo pillando Pokémon.\p"
	.string "He pensado que lo mejor es que me\n"
	.string "centre en atrapar solo uno, y por eso\l"
	.string "quería que eligieses por mí cuál.\p"
	.string "¿Cuál me convendría más?\n"
	.string "¿Un {STR_VAR_1} o un {STR_VAR_2}?$"

gText_ApprenticeMonThanks10:: @ 82BF3CF
	.string "Vale, dices que un {STR_VAR_1}, ¿no?\n"
	.string "¡Entonces trataré de pillar el otro!\p"
	.string "¡Es broma!\n"
	.string "¡Te haré caso!\p"
	.string "¡Gracias!\n"
	.string "¡Espero que sigas instruyéndome!$"

gText_ApprenticeWhichMon11:: @ 82BF46A
	.string "¡Hola, hola, hola,\n"
	.string "dijo el mar a la caracola!\p"
	.string "¡Soy el poeta marinero!\n"
	.string "¡De tus aprendices, el primero!\p"
	.string "Sobre un Pokémon te quiero preguntar,\n"
	.string "¡espero que tú me sepas contestar!\p"
	.string "Quiero uno de estos Pokémon entrenar:\n"
	.string "un {STR_VAR_1} o un {STR_VAR_2}.\l"
	.string "Dime, ¿cuál de los dos Pokémon será?$"

gText_ApprenticeMonThanks11:: @ 82BF551
	.string "¡{STR_VAR_1}! ¡Bien visto!\n"
	.string "¡Voy a por él ahora mismo!\p"
	.string "¡Aquí vendré si necesito otro consejo!\n"
	.string "¡Hasta entonces, {PLAYER}, te dejo!$"

gText_ApprenticeWhichMon12:: @ 82BF5C3
	.string "¡Ey, {PLAYER}, “yea”!\n"
	.string "¡Qué suerte que vinieras!\p"
	.string "¿Qué hago? ¿Te pido consejo?\n"
	.string "¿Por qué no? ¡Si tú eres mi espejo!\p"
	.string "Ya hace mucho que no nos vemos,\n"
	.string "y necesito un consejo, de los buenos.\p"
	.string "Sí, no, sí, no, probando, probando.\n"
	.string "¡Te diré lo que quiero cantando!\p"
	.string "¿Qué Pokémon debo elegir?\n"
	.string "¿Un {STR_VAR_1} o un {STR_VAR_2}?\l"
	.string "¡Ayúdame a decidir!$"

gText_ApprenticeMonThanks12:: @ 82BF6E5
	.string "¡Oh, sí, sí! ¡Un {STR_VAR_1} es lo mejor!\n"
	.string "Y ahora, ¡a echarle valor!\p"
	.string "¡{PLAYER}, fue un placer encontrarte!\n"
	.string "¡Me largo con la música a otra parte!$"

gText_ApprenticeWhichMon13:: @ 82BF773
	.string "Ay, hola, {PLAYER}{KUN}…\n"
	.string "Qué dolor de cabeza llevo…\p"
	.string "Seguro que es por pensar tanto en qué\n"
	.string "Pokémon debería elegir para entrenar.\p"
	.string "Bueno, estando yo tan mal, \n"
	.string "vas a tener que decidir tú.\p"
	.string "{PLAYER}{KUN}, si tuvieras que elegir entre\n"
	.string "el Pokémon {STR_VAR_1} y el {STR_VAR_2}\l"
	.string "para mí, ¿cuál elegirías?$"

gText_ApprenticeMonThanks13:: @ 82BF869
	.string "Mm, un {STR_VAR_1}, de acuerdo.\n"
	.string "Buscaré uno cuando se me pase esto.\p"
	.string "¡Espero poder seguir contando\n"
	.string "con tu ayuda!$"

gText_ApprenticeWhichMon14:: @ 82BF8DD
	.string "Eh… Mm…\n"
	.string "¿{PLAYER}{KUN}…?\p"
	.string "Anda, por favor, no me mires así.\n"
	.string "Me frustra mucho eso…\l"
	.string "Es que… necesito otro consejo.\p"
	.string "Es que… me avergüenza reconocerlo,\n"
	.string "pero no sé qué Pokémon entrenar.\p"
	.string "Entre un {STR_VAR_1} o un {STR_VAR_2},\n"
	.string "¿cuál es mejor para mí?$"

gText_ApprenticeMonThanks14:: @ 82BF9BA
	.string "Oh… ¡Vale!\n"
	.string "A ver dónde llego con ese {STR_VAR_1}…\p"
	.string "Espero hacerlo bien y no aturullarme\n"
	.string "en el momento del combate.\p"
	.string "Bueno, gracias, {PLAYER}{KUN}.\n"
	.string "Ojalá nos veamos pronto otra vez.\l"
	.string "¡Estos consejos tuyos son geniales!$"

gText_ApprenticeWhichMon15:: @ 82BFA5A
	.string "¿Mm? Vaya, pareces ser {PLAYER}{KUN}…\n"
	.string "Pero ¿lo eres en realidad?\p"
	.string "No, no, si lo eres, está bien.\n"
	.string "A propósito, necesitaría un consejo.\p"
	.string "Es sobre el Pokémon que debo entrenar.\p"
	.string "Si las posibilidades fueran un Pokémon\n"
	.string "{STR_VAR_1} y un {STR_VAR_2}, ¿cuál\l"
	.string "crees tú que sería más digno de mí?$"

gText_ApprenticeMonThanks15:: @ 82BFB4E
	.string "¿{STR_VAR_1}?\n"
	.string "¿Es ésa tu conclusión?\p"
	.string "Bien. Confiaré en tu buen juicio.\n"
	.string "Tienes todo mi agradecimiento.\p"
	.string "Deseo poder sobrellevarlo con todo\n"
	.string "el aplomo que requiere la situación.\p"
	.string "¡Sería todo un placer volver a verte!\n"
	.string "Ahora, si me disculpas…$"

gText_ApprenticeWhichMove0:: @ 82BFBF2
	.string "¡Buaaa! ¡Oh, {PLAYER}!\n"
	.string "Snif… Snif…\p"
	.string "¡Tengo un terrible dilema!\n"
	.string "No sé qué movimiento usar\l"
	.string "con mi {STR_VAR_1}…\p"
	.string "Porfa, porfa, {PLAYER}.\n"
	.string "¡Decide tú por mí!\p"
	.string "Para mi {STR_VAR_1}, qué movimiento\n"
	.string "sería mejor: ¿{STR_VAR_2}\l"
	.string "o quizás {STR_VAR_3}?$"

gText_ApprenticeMoveThanks0:: @ 82BFCAE
	.string "¿{STR_VAR_1}?\n"
	.string "¡Buaaaaaa!\p"
	.string "¡Oh! ¡Lo siento, {PLAYER}!\n"
	.string "Me alegra tanto que hayas elegido tú el\l"
	.string "movimiento, que me he puesto a llorar…\p"
	.string "Snif…\n"
	.string "¡Muchas gracias!$"

gText_ApprenticeWhichMove1:: @ 82BFD26
	.string "¡Yupi! ¡Hola, {PLAYER}!\n"
	.string "¡Necesito otro consejo!\p"
	.string "Quiero enseñar a mi {STR_VAR_1}\n"
	.string "un movimiento alucinante.\p"
	.string "Me gustan {STR_VAR_2} y\n"
	.string "{STR_VAR_3}. ¿Cuál me recomiendas?$"

gText_ApprenticeMoveThanks1:: @ 82BFDB1
	.string "¿Mejor {STR_VAR_1}? ¡Supongo que sí!\n"
	.string "¡Vale, haré lo que dices!\p"
	.string "¡Ojalá nos volvamos a ver para que me\n"
	.string "enseñes algo más!$"

gText_ApprenticeWhichMove2:: @ 82BFE24
	.string "¡{PLAYER}, hola!\n"
	.string "Es sobre mi {STR_VAR_1}, me preocupa\l"
	.string "qué movimiento debo enseñarle.\p"
	.string "Estoy dudando entre {STR_VAR_2}\n"
	.string "y {STR_VAR_3}.\p"
	.string "¿Cuál de ellos crees que haría más\n"
	.string "fuerte a mi {STR_VAR_1}?$"

gText_ApprenticeMoveThanks2:: @ 82BFEAD
	.string "¿De verdad crees que {STR_VAR_1}?\n"
	.string "¡Muy bien, te haré caso!\p"
	.string "Voy a tratar de enseñarle {STR_VAR_1}\n"
	.string "a mi Pokémon ahora mismo.\p"
	.string "¡Nos vemos!$"

gText_ApprenticeWhichMove3:: @ 82BFF0A
	.string "Ooooh, {PLAYER}…\n"
	.string "¡Soy un caso, en serio!\p"
	.string "Ahora que me decido a entrenar un\n"
	.string "Pokémon, no puedo decidirme sobre\l"
	.string "qué movimiento debo enseñarle…\p"
	.string "Ya sé que esto no tiene ninguna\n"
	.string "importancia para ti, {PLAYER}.\p"
	.string "Pero sí la tiene para mí…\p"
	.string "{PLAYER}, ayúdame a elegir un movimiento\n"
	.string "para mi {STR_VAR_1}, ¿vale?\p"
	.string "Te doy a elegir entre {STR_VAR_2} y\n"
	.string "{STR_VAR_3}…$"

gText_ApprenticeMoveThanks3:: @ 82C0032
	.string "¡Comprendido!\p"
	.string "¿Pero tú crees que {STR_VAR_1}\n"
	.string "querrá aprenderlo…?\l"
	.string "¡Esperemos que sí!\p"
	.string "¡Gracias!$"

gText_ApprenticeWhichMove4:: @ 82C0090
	.string "¡Oh, {PLAYER}{KUN}!\n"
	.string "¡Estaba deseando que aparecieses!\p"
	.string "No tengo nada claro qué movimiento le\n"
	.string "convendría aprender a mi {STR_VAR_1}.\p"
	.string "¿Me ayudas a decidir?\p"
	.string "Por ejemplo… Estaba pensando en\n"
	.string "{STR_VAR_2} y {STR_VAR_3}…\l"
	.string "¿Cuál le vendría mejor aprender?$"

gText_ApprenticeMoveThanks4:: @ 82C016E
	.string "¿{STR_VAR_1}? ¡Genial!\p"
	.string "Sabiendo que lo decidiste tú, {PLAYER}{KUN},\n"
	.string "no podré enfadarme si pierdo.\p"
	.string "Bueno, ya te pediré otro consejo\n"
	.string "otro día. ¡Chao!$"

gText_ApprenticeWhichMove5:: @ 82C01F7
	.string "¿Cómo puedo estar tan agobiado?\n"
	.string "¡Eh, pero si es {PLAYER}{KUN}!\l"
	.string "¿Cómo va eso?\p"
	.string "Desde que me he levantado, no he\n"
	.string "parado. Correr, nadar, cocinar…\p"
	.string "¡No te puedes llegar a hacer una idea\n"
	.string "de lo ocupado que estoy!\p"
	.string "¡Ni tiempo tengo de estudiar qué\n"
	.string "movimiento debería aprender mi\l"
	.string "{STR_VAR_1}!\p"
	.string "{STR_VAR_2} suena bien, ¿eh?\n"
	.string "Pero {STR_VAR_3} también es decente.\p"
	.string "{PLAYER}{KUN}, ¡dame otro de tus sabios\n"
	.string "consejos! ¿Qué movimiento me conviene?$"

gText_ApprenticeMoveThanks5:: @ 82C034C
	.string "¡Vale, comprendido!\n"
	.string "Tendré que hacer un hueco en mi\l"
	.string "agenda para enseñárselo.\p"
	.string "Me alegro de ser tu aprendiz.\n"
	.string "¡Gracias! ¡Ya nos veremos!$"

gText_ApprenticeWhichMove6:: @ 82C03CA
	.string "¡Oh! ¡Qué suerte!\n"
	.string "¡Nos volvemos a ver, {PLAYER}!\l"
	.string "Necesito tu coco otra vez.\p"
	.string "Y la pregunta es…\n"
	.string "Tachán, tachán…\p"
	.string "Para mi {STR_VAR_1}, ¿qué movimiento\n"
	.string "le vendría mejor aprender, \l"
	.string "{STR_VAR_2} o quizás {STR_VAR_3}?$"

gText_ApprenticeMoveThanks6:: @ 82C046E
	.string "¡Aaah!\n"
	.string "¡{STR_VAR_1}, claro!\l"
	.string "¡Gracias por enrollarte!\p"
	.string "Creo que eso es todo lo\n"
	.string "que quería preguntarte.\p"
	.string "Nos vemos aquí otra vez, ¿vale?\n"
	.string "¡Gracias!$"

gText_ApprenticeWhichMove7:: @ 82C04F9
	.string "Oh, hola, {PLAYER}.\n"
	.string "¿Te va todo superfantástico?\p"
	.string "Siento tener que pedirte ayuda\n"
	.string "una vez más, pero es sobre mi\l"
	.string "queridísimo {STR_VAR_1}.\p"
	.string "¿Qué movimiento haría a mi adorado\n"
	.string "{STR_VAR_1} más superalucinante?\l"
	.string "¿{STR_VAR_2} o quizás {STR_VAR_3}?$"

gText_ApprenticeMoveThanks7:: @ 82C0598
	.string "¡{STR_VAR_1}!\n"
	.string "¡Voy a enseñárselo ahora mismo!\p"
	.string "Oye, que muchísimas gracias, {PLAYER}.\n"
	.string "Espero que me sigas ayudando.\l"
	.string "Te me cuidas muchísimo, ¿vale?$"

gText_ApprenticeWhichMove8:: @ 82C0602
	.string "¡Hooola, {PLAYER}! ¡Otra vez!\n"
	.string "¡Qu-qué alegría verte!\p"
	.string "¡Siempre que estoy desesperada,\n"
	.string "aquí llega mi {PLAYER}!\p"
	.string "¡Hoy necesito que me recomiendes\n"
	.string "un movimiento!\p"
	.string "¡Anda, elige el que crees que le iría\n"
	.string "mejor a mi {STR_VAR_1}!\p"
	.string "¿Con cuál te quedas de estos dos?\n"
	.string "¿{STR_VAR_2} o quizás {STR_VAR_3}?$"

gText_ApprenticeMoveThanks8:: @ 82C06D8
	.string "¡Oh-oh-oh! ¡Gracias mil!\n"
	.string "¡{STR_VAR_1}!\l"
	.string "¡Recibido! ¡Cambio y corto!\p"
	.string "Espero que no te olvides de\n"
	.string "seguir enseñándome cosas, ¿eh?$"

gText_ApprenticeWhichMove9:: @ 82C074A
	.string "¡Hola, {PLAYER}{KUN}!\n"
	.string "¡Espero poder contar hoy con otro\l"
	.string "de esos impagables consejos tuyos!\p"
	.string "¿Cuál sería el mejor movimiento\n"
	.string "para mi {STR_VAR_1}?\p"
	.string "¡Tendría que ser algo que me\n"
	.string "ayudase a ganar así, sin más!\p"
	.string "¿Qué tal {STR_VAR_2}?\n"
	.string "¿O {STR_VAR_3}?$"

gText_ApprenticeMoveThanks9:: @ 82C0809
	.string "¡Ajá, {STR_VAR_1}!\n"
	.string "¡Vale!\l"
	.string "¡Me voy corriendo a enseñárselo!\p"
	.string "¡Muy bien, gracias, como siempre!\n"
	.string "¡Adiós!$"

gText_ApprenticeWhichMove10:: @ 82C086E
	.string "¡{PLAYER}{KUN}, esto es una locura!\p"
	.string "¡Mi Pokémon!\n"
	.string "¡Ya ha aprendido seis movimientos!\p"
	.string "¡Na! ¡Es broma!\n"
	.string "¡Ja, ja, ja, ja!\p"
	.string "Pero te diré algo en serio.\n"
	.string "Soy pésimo eligiendo movimientos para\l"
	.string "mis Pokémon.\p"
	.string "Estaba pensando que por qué no\n"
	.string "eliges tú por mí, ¿de acuerdo?\p"
	.string "{STR_VAR_2} o quizá {STR_VAR_3}.\n"
	.string "¿Cuál le iría mejor a mi {STR_VAR_1}?$"

gText_ApprenticeMoveThanks10:: @ 82C0982
	.string "Muy bien, has dicho {STR_VAR_1}.\n"
	.string "¡Entonces le enseñaré otro!\p"
	.string "¡Es broma!\n"
	.string "¡Te haré caso!\p"
	.string "¡Gracias!\n"
	.string "¡Espero que sigas instruyéndome!$"

gText_ApprenticeWhichMove11:: @ 82C0A1D
	.string "¡Hola, hola, hola,\n"
	.string "dijo el mar a la caracola!\p"
	.string "Soy poeta y además marinero,\n"
	.string "pero Entrenar es lo que quiero.\p"
	.string "¡Aconséjame sobre un movimiento\n"
	.string "y te expresaré mi agradecimiento!\p"
	.string "{STR_VAR_2}, {STR_VAR_3}… Dime,\n"
	.string "¿cuál hará a mi {STR_VAR_1} más sublime?$"

gText_ApprenticeMoveThanks11:: @ 82C0AFD
	.string "{STR_VAR_1}, ¿ése me aconsejas?\n"
	.string "¡Gracias! ¡Otra duda que me despejas!\p"
	.string "¡Aquí vendré si necesito otro consejo!\n"
	.string "¡Hasta entonces, {PLAYER}, te dejo!$"

gText_ApprenticeWhichMove12:: @ 82C0B6F
	.string "¡Ey, {PLAYER}, “yea”!\n"
	.string "¡Qué suerte que vinieras!\p"
	.string "¿Qué hago? ¿Te pido consejo?\n"
	.string "¿Por qué no? ¡Si tú eres mi espejo!\p"
	.string "{PLAYER}, necesito que me ayudes,\n"
	.string "pero te lo agradeceré, no lo dudes.\p"
	.string "Sí, no, sí, no, probando, probando.\n"
	.string "¡Te diré lo que quiero cantando!\p"
	.string "A mi {STR_VAR_1}, ¿qué le enseño?\n"
	.string "¿{STR_VAR_2} o quizás {STR_VAR_3}?\l"
	.string "¿En qué movimiento pongo mi empeño?$"

gText_ApprenticeMoveThanks12:: @ 82C0C7D
	.string "Si {STR_VAR_1} es el mejor movimiento,\n"
	.string "¡no quiero perder más el tiempo!\p"
	.string "¡{PLAYER}, fue un placer encontrarte!\n"
	.string "¡Me largo con la música a otra parte!$"

gText_ApprenticeWhichMove13:: @ 82C0D0B
	.string "¡Achís! ¡Aaaaaachís! Oh, {PLAYER}{KUN}…\n"
	.string "He pillado este espantoso resfriado…\p"
	.string "Querría elegir un movimiento para mi\n"
	.string "Pokémon, pero ya ves cómo estoy…\p"
	.string "En fin, estando yo tan mal, \n"
	.string "vas a tener que decidir tú.\p"
	.string "{PLAYER}{KUN}, si yo tuviera que elegir entre\n"
	.string "{STR_VAR_2} y {STR_VAR_3} para mi\l"
	.string "{STR_VAR_1}, ¿cuál debería escoger?$"

gText_ApprenticeMoveThanks13:: @ 82C0DFE
	.string "Mm, {STR_VAR_1}, vale. ¡Aaaachís!\n"
	.string "¡Se lo enseñaré en cuanto me recupere!\p"
	.string "¡Espero poder seguir contando\n"
	.string "con tu ayuda!$"

gText_ApprenticeWhichMove14:: @ 82C0E71
	.string "Esto… Mm…\n"
	.string "¿{PLAYER}{KUN}…?\p"
	.string "Anda, por favor, no me mires así.\n"
	.string "Me frustra mucho eso…\l"
	.string "Es que… necesito otro consejo.\p"
	.string "Es que… me avergüenza reconocerlo,\n"
	.string "pero no sé qué movimiento debo enseñar\l"
	.string "a mi Pokémon.\p"
	.string "Es para mi {STR_VAR_1}.\n"
	.string "Entre {STR_VAR_2} y {STR_VAR_3},\l"
	.string "¿cuál piensas que debería elegir?$"

gText_ApprenticeMoveThanks14:: @ 82C0F6D
	.string "Oh… ¡Vale!\n"
	.string "Lo intentaré con {STR_VAR_1}.\p"
	.string "Espero poder enseñárselo…\n"
	.string "No sé si podré con los nervios…\p"
	.string "Bueno, gracias, {PLAYER}{KUN}.\n"
	.string "Ojalá nos veamos pronto otra vez.\l"
	.string "¡Estos consejos tuyos son geniales!$"

gText_ApprenticeWhichMove15:: @ 82C1003
	.string "¿Mm? Vaya, pareces ser {PLAYER}{KUN}…\n"
	.string "Pero ¿lo eres en realidad?\p"
	.string "¿Quizás te cuentes entre sus\n"
	.string "mejores imitadores?\p"
	.string "No, no, si lo eres de verdad, está bien.\n"
	.string "No hay necesidad de mal encararse.\p"
	.string "A propósito, necesitaría un consejo.\p"
	.string "Es sobre mi {STR_VAR_1}.\p"
	.string "¿Qué movimiento le vendría mejor usar?\n"
	.string "¿{STR_VAR_2} o quizás {STR_VAR_3}?$"

gText_ApprenticeMoveThanks15:: @ 82C1122
	.string "¿{STR_VAR_1}?\n"
	.string "¿Sin lugar a dudas?…\p"
	.string "Bien. Confiaré en tu buen juicio.\n"
	.string "Tienes todo mi agradecimiento.\p"
	.string "Esperemos que sea algo que hasta uno\n"
	.string "de mis Pokémon pueda aprender.\p"
	.string "¡Sería todo un placer volver a verte!\n"
	.string "Ahora, si me disculpas…$"

gText_ApprenticePickWinSpeech0:: @ 82C11D1
	.string "Ah… ¿{PLAYER}?\n"
	.string "¿Eres tú, {PLAYER}?\l"
	.string "¡Oh! Snif… Snif… Escúchame, por favor…\p"
	.string "Me… pongo tan nervioso en los combates\n"
	.string "que no puedo evitar llorar, aunque gane.\p"
	.string "En lugar de eso, me gustaría poder decir\n"
	.string "algo que quedara guay…\p"
	.string "¡Anda, por favor, {PLAYER}!\n"
	.string "¡Enséñame a decir algo guay\l"
	.string "para no llorar cuando gane!$"

gText_ApprenticeWinSpeechThanks0:: @ 82C12D5
	.string "{STR_VAR_1}\p"
	.string "¡Genial! ¡Alucinante! ¡Superguay!\n"
	.string "¡Suena totalmente guay!\p"
	.string "Oh… lo siento otra vez…\n"
	.string "Lloro de alegría…\p"
	.string "Snif… ¡{PLAYER}!\n"
	.string "¡Muchas gracias por todo!\p"
	.string "¡Combatiré lo mejor que pueda\n"
	.string "en tu honor, {PLAYER}!\p"
	.string "{PLAYER}…, la próxima vez…,\n"
	.string "¡debemos combatir tú y yo!$"

gText_ApprenticePickWinSpeech1:: @ 82C13AB
	.string "¡Yupi! ¡Hola, {PLAYER}!\n"
	.string "¡Quería preguntarte algo!\p"
	.string "Quiero decir algo que quede guay\n"
	.string "justo después de ganar un combate.\p"
	.string "¿Se te ocurre algo que quede guay?$"

gText_ApprenticeWinSpeechThanks1:: @ 82C1444
	.string "{STR_VAR_1}\p"
	.string "¡Eh! ¡Eso suena guay!\n"
	.string "¡Genial! ¡Voy a decir eso!\p"
	.string "¡Gracias por todas tus enseñanzas!\n"
	.string "A partir de ahora voy a combatir\l"
	.string "lo mejor que pueda, ¡ya verás!\p"
	.string "¡La próxima vez que nos veamos,\n"
	.string "será para enfrentarnos el uno al otro!$"

gText_ApprenticePickWinSpeech2:: @ 82C1501
	.string "¡{PLAYER}, hola!\p"
	.string "Mis Pokémon y yo estamos listos\n"
	.string "para cualquier cosa, excepto una.\p"
	.string "Necesitamos un buen grito de victoria,\n"
	.string "algo guay que podamos decir al ganar.\p"
	.string "¿Se te ocurre algo que quede bien?$"

gText_ApprenticeWinSpeechThanks2:: @ 82C15B6
	.string "{STR_VAR_1}\p"
	.string "¡Estupendo!\n"
	.string "¡Voy a gritar eso cada vez que ganemos!\p"
	.string "Ahora voy a ponerme a combatir por\n"
	.string "todos los sitios.\p"
	.string "Quién sabe, quizás llegue a enfrentarme\n"
	.string "a ti algún día, {PLAYER}.\p"
	.string "¡Ojalá la próxima vez nos veamos\n"
	.string "en un escenario de combate!$"

gText_ApprenticePickWinSpeech3:: @ 82C165E
	.string "Hola, {PLAYER}…\n"
	.string "Siento molestarte otra vez, de verdad,\l"
	.string "pero es que no debo de valer para nada…\p"
	.string "Ni siquiera cuando gano se me ocurre\n"
	.string "nada especial que decir…\p"
	.string "Sí, ya sé que eso te tiene sin cuidado,\n"
	.string "{PLAYER}.\p"
	.string "Pero para mí es muy importante…\p"
	.string "Porfa, {PLAYER}, dime algo especial que\n"
	.string "pueda decir yo cuando gane un combate.$"

gText_ApprenticeWinSpeechThanks3:: @ 82C174F
	.string "{STR_VAR_1}\p"
	.string "¡Qué inspiración tienes!…\p"
	.string "Eh… ¿No crees que suena demasiado\n"
	.string "para alguien como yo?\p"
	.string "¡No! ¡Es verdad! ¡Basta de lamentos!\n"
	.string "¡Sólo gritos de guerra!\p"
	.string "{PLAYER}, gracias por todos esos\n"
	.string "consejos que me has ido dando…\p"
	.string "A partir de ahora, prometo ser fuerte.\p"
	.string "Supongo que no te acordarás de mí\n"
	.string "la próxima vez que nos veamos,\l"
	.string "pero, quién sabe, ¡quizás te sorprenda!$"

gText_ApprenticePickWinSpeech4:: @ 82C1862
	.string "Oh, {PLAYER}{KUN}.\n"
	.string "Hay algo que me gustaría decirte.\p"
	.string "Ya sé que no siempre sueno muy\n"
	.string "agradable y educada…\p"
	.string "Pero cuando gano un combate, creo\n"
	.string "que todos piensan que soy arrogante.\p"
	.string "No quiero que la gente me odie,\n"
	.string "así que querría decirles algo bonito\l"
	.string "a los que pierden contra mí.\p"
	.string "¡Lo peor es que no se me ocurre nada!\n"
	.string "Anda, ayúdame, ¿qué les digo?$"

gText_ApprenticeWinSpeechThanks4:: @ 82C19A0
	.string "{STR_VAR_1}\p"
	.string "¡No está mal!\n"
	.string "¡Perfecto, con eso bastará!\p"
	.string "Voy a echarme a la aventura a ver\n"
	.string "qué tal se me da con todo lo que\l"
	.string "me has enseñado.\p"
	.string "¡Y siento mucho todas las veces\n"
	.string "que he sido tan borde!\p"
	.string "La próxima vez, luchamos, ¿vale?\n"
	.string "¡Nos vemos!$"

gText_ApprenticePickWinSpeech5:: @ 82C1A76
	.string "Oh, justo estaba buscándote, {PLAYER}{KUN}.\n"
	.string "¡No te imaginas lo liado que estoy!\p"
	.string "Tú supongo que como siempre, ¿no?\n"
	.string "Es que yo no paro, oye.\p"
	.string "Que si correr, combatir, dibujar planos,\n"
	.string "hacer planes. ¿Por qué seré siempre yo?\p"
	.string "Pero ni siquiera lo ocupado que estoy\n"
	.string "es excusa para largarme sin decir nada\l"
	.string "después de ganar un combate.\p"
	.string "Dime, {PLAYER}{KUN}, ¿qué crees que debería\n"
	.string "decir nada más ganar para que quedase\l"
	.string "guay y resaltase el carisma que tengo?$"

gText_ApprenticeWinSpeechThanks5:: @ 82C1C16
	.string "{STR_VAR_1}\p"
	.string "Vale, lo he entendido.\n"
	.string "¡Creo que tendré tiempo de decir eso!\p"
	.string "Eh, he tenido mucha suerte contigo.\n"
	.string "Ningún aprendiz tuvo mejor ejemplo.\p"
	.string "Debo sacar tiempo de debajo de las\n"
	.string "piedras y ponerme a combatir en serio.\p"
	.string "¡Gracias por todo, {PLAYER}{KUN}!\n"
	.string "¡Tenemos que luchar, tú y yo, un día!$"

gText_ApprenticePickWinSpeech6:: @ 82C1CF5
	.string "¡Qué suertuda que soy!\n"
	.string "¡{PLAYER}! ¡Cómo me alegro de verte!\l"
	.string "¡Como siempre, necesito tu ayuda!\p"
	.string "Y la pregunta es…\n"
	.string "Tachán, tachán…\p"
	.string "Si gano un combate y quiero ponerle\n"
	.string "la guinda diciendo algo que quede guay,\l"
	.string "¿qué debo decir?$"

gText_ApprenticeWinSpeechThanks6:: @ 82C1DC1
	.string "{STR_VAR_1}\p"
	.string "¡Eso mola un montón!\n"
	.string "¡Es justo lo que quería! \p"
	.string "Por cierto, estaba pensando que ya soy\n"
	.string "medianamente buena en esto, ¿no crees?\p"
	.string "Así que estaba pensando en retar a\n"
	.string "otros Entrenadores a partir de ahora.\p"
	.string "{PLAYER}, no habría llegado hasta aquí\n"
	.string "si no hubiese sido por tus consejos.\p"
	.string "Quién sabe, ¡quizás algún día nos\n"
	.string "enfrentemos tú y yo!\p"
	.string "¡Gracias otra vez por todo!$"

gText_ApprenticePickWinSpeech7:: @ 82C1EDC
	.string "Oh, {PLAYER}. ¡Encantadísima que estoy\n"
	.string "de volver a verte!\p"
	.string "¿Sabes? Ya no me preocupan\n"
	.string "en absoluto mis Pokémon.\p"
	.string "Ahora lo que me preocupa soy yo…\p"
	.string "Sabes que los entrenadores dicen\n"
	.string "unas palabras cuando ganan, ¿verdad?\p"
	.string "Pues eso es lo que yo quiero: saber\n"
	.string "qué podría decir para quedar chuli.\p"
	.string "¿Qué piensas tú? ¿Qué debería\n"
	.string "decir cuando gane un combate?$"

gText_ApprenticeWinSpeechThanks7:: @ 82C1FEC
	.string "{STR_VAR_1}\p"
	.string "¡Oh! ¡Eso que dices suena\n"
	.string "pero que estupendísimo!\p"
	.string "¡A ver si gano pronto para poder\n"
	.string "decirlo ya!\p"
	.string "Bueno, ha llegado la hora de despedirme,\n"
	.string "{PLAYER}…\p"
	.string "He decidido ir a luchar contra otros\n"
	.string "Entrenadores, pero nunca olvidaré\l"
	.string "todo lo que me has enseñado.\p"
	.string "Quizás algún día…\n"
	.string "¡Adiós!$"

gText_ApprenticePickWinSpeech8:: @ 82C20D1
	.string "¡Eh, hooola, {PLAYER}!\n"
	.string "¡Qu-qué alegría verte!\p"
	.string "¡Oh-oh-oh! ¡Ya sé! ¡Ya sé!\n"
	.string "¡Déjame preguntarte algo!\p"
	.string "Hace poco, gané un combate.\n"
	.string "¡No te puedes ni imaginar la alegría…!\p"
	.string "¡Pero estaba tan alucinada\n"
	.string "que no pude decir ni pío!\p"
	.string "No quiero que me vuelva a pasar.\n"
	.string "¡Anda, {PLAYER}, dime qué crees que\l"
	.string "debería decir la próxima vez que gane!$"

gText_ApprenticeWinSpeechThanks8:: @ 82C21FF
	.string "{STR_VAR_1}\p"
	.string "¡Buaaaaa!\n"
	.string "¡¿Quieres que diga eso?!\l"
	.string "Qué… ¡Qué alucinante!\p"
	.string "¡Gra-gra-gracias!\n"
	.string "¡Qué suerte he tenido contigo!\p"
	.string "Ahora voy a viajar por ahí para\n"
	.string "combatir con todo tipo de gente.\p"
	.string "Todo te lo debo a ti, {PLAYER}.\n"
	.string "¡En serio, de verdad, gracias!\p"
	.string "Ahora tengo que irme, pero ojalá\n"
	.string "nos veamos otra vez, ¡combatiendo!$"

gText_ApprenticePickWinSpeech9:: @ 82C231C
	.string "¡Hola, {PLAYER}{KUN}!\p"
	.string "Últimamente, siento ganas de combatir\n"
	.string "con todo el mundo, donde sea.\p"
	.string "Pero antes, necesito un último consejo.\p"
	.string "Al ganar un combate, me gustaría poder\n"
	.string "decir algo para animar al que ha perdido.\l"
	.string "¿Qué crees que podría decir?$"

gText_ApprenticeWinSpeechThanks9:: @ 82C2407
	.string "{STR_VAR_1}\p"
	.string "¡Ah, vale, perfecto!\n"
	.string "¡Entonces será eso lo que diga!\p"
	.string "¡Y llegó el momento de despedirse!\n"
	.string "¡Gracias por toda tu ayuda!\p"
	.string "Enfrentémonos algún día, ¿vale?\n"
	.string "¡Adiós!$"

gText_ApprenticePickWinSpeech10:: @ 82C24B5
	.string "¡{PLAYER}{KUN}, tengo un problema!\p"
	.string "¡Cada vez que gano un combate, me paso\n"
	.string "la hora siguiente presumiendo de ello!\p"
	.string "¡Es broma!\n"
	.string "¡Ja, ja, ja, ja!\p"
	.string "Y ahora, en serio.\n"
	.string "Lo mío no es el idioma.\p"
	.string "Así que, ¿por qué no decides tú por mí\n"
	.string "lo que debo decir al ganar un combate?\l"
	.string "Venga, ¿qué crees que quedaría bien?$"

gText_ApprenticeWinSpeechThanks10:: @ 82C25B1
	.string "{STR_VAR_1}\p"
	.string "Eso no me gusta. \n"
	.string "¡Voy a decir justo lo contrario!\p"
	.string "¡Es broma!\n"
	.string "¡Te haré caso!\p"
	.string "Gracias por todas tus enseñanzas,\n"
	.string "¡me han servido de mucho!\p"
	.string "Por fin he comprendido qué significa\n"
	.string "esto de ser Entrenador.\p"
	.string "He decidido liarme la manta a la cabeza\n"
	.string "y luchar contra otros Entrenadores.\p"
	.string "¡Vete preparándote para el día\n"
	.string "que nos encontremos!\p"
	.string "¡Gracias otra vez por todo!\n"
	.string "¡Adiós!$"

gText_ApprenticePickWinSpeech11:: @ 82C2707
	.string "¡Hola, hola, hola,\n"
	.string "dijo el mar a la caracola!\p"
	.string "Soy el poeta marinero.\n"
	.string "¡Una última pregunta,\l"
	.string "antes de decirte “hasta luego”!\p"
	.string "Aconséjame sobre qué decir,\n"
	.string "que no me acabo de decidir.\p"
	.string "Cuando gane un combate a un rival,\n"
	.string "¿qué puedo decir que suene cabal?$"

gText_ApprenticeWinSpeechThanks11:: @ 82C27D4
	.string "{STR_VAR_1}\p"
	.string "¡Perfecto! ¡Suena bien! ¡Te haré caso!\n"
	.string "¡Será lo que diga cuando llegue el caso!\p"
	.string "Y ahora, como siempre ocurre en la vida,\n"
	.string "¡llegó la hora de la amarga despedida!\p"
	.string "Gracias otra vez por tus consejos,\n"
	.string "¡siento que con ellos llegaré muy lejos!\p"
	.string "¡Adiós! “¡Goodbye!” “¡Au revoir!”\n"
	.string "¡Ojalá nos volvamos a encontrar!$"

gText_ApprenticePickWinSpeech12:: @ 82C28D6
	.string "¡Ey, {PLAYER}, estamos en sintonía!\n"
	.string "¡Nos vemos otra vez en este día!\p"
	.string "¿Qué hago? ¿Te pido consejo?\n"
	.string "¿Por qué no? ¡Si tú eres mi espejo!\p"
	.string "“Yea”, {PLAYER}…\n"
	.string "Sí, no, sí, no, probando, probando.\l"
	.string "¡Te diré lo que quiero cantando!\p"
	.string "Dime algo que anime a mi rival\n"
	.string "cuando lo haya derrotado,\l"
	.string "y que a la vez quede genial.\p"
	.string "¡Oh, “yea”!…\n"
	.string "¡Oh, “yea”!…$"

gText_ApprenticeWinSpeechThanks12:: @ 82C2A0B
	.string "{STR_VAR_1}\p"
	.string "¡Eso suena bien! ¡Suena potente!\n"
	.string "¡Le va a molar a la gente!\p"
	.string "Ahora que sin preguntas me he quedado,\n"
	.string "“yea”, el momento del adiós ha llegado.\p"
	.string "Pero quizás combatamos algún día,\n"
	.string "si permites a este aprendiz la osadía.\p"
	.string "¡{PLAYER}, fue un placer encontrarte!\n"
	.string "¡Me largo con la música a otra parte!\p"
	.string "¡{PLAYER}, hasta siempre!\n"
	.string "¡Jamás te olvidaré, aunque lo intente!$"

gText_ApprenticePickWinSpeech13:: @ 82C2B50
	.string "{PLAYER}{KUN}, estoy hecho polvo…\n"
	.string "No dejo de moquear…\p"
	.string "Resulta que estaba pensando en algo\n"
	.string "guay que decir tras ganar un combate.\p"
	.string "Me gustaban tanto las ideas, que me\n"
	.string "puse a llorar de la emoción y mira,\l"
	.string "empecé a moquear y ahora no paro…\p"
	.string "Bueno, estando yo tan mal, \n"
	.string "vas a tener que decidir tú, {PLAYER}{KUN}.\p"
	.string "Cuando gane un combate,\n"
	.string "¿qué debería decir?$"

gText_ApprenticeWinSpeechThanks13:: @ 82C2C77
	.string "{STR_VAR_1}\p"
	.string "Está bien.\n"
	.string "¿Cómo que bien?… ¡Se sale!\l"
	.string "¡Se me han vuelto a saltar las lágrimas!\p"
	.string "¡No te preocupes, ya se me pasará!\p"
	.string "Bueno, creo que no tengo nada más\n"
	.string "que preguntarte, {PLAYER}{KUN}.\p"
	.string "¡A partir de ahora, somos rivales!\n"
	.string "¡Gracias por todo!$"

gText_ApprenticePickWinSpeech14:: @ 82C2D67
	.string "Esto… Mm…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "Anda, por favor, no me mires así.\n"
	.string "Me estás poniendo nervioso.\p"
	.string "Esto… quería pedirte un consejo.\n"
	.string "Pero te prometo que será el último…\p"
	.string "Me da no sé qué preguntarlo, pero,\n"
	.string "si alguna vez ganase un combate,\l"
	.string "¿qué crees que debería decir al final?$"

gText_ApprenticeWinSpeechThanks14:: @ 82C2E41
	.string "{STR_VAR_1}\p"
	.string "Oh… ¡Perfecto!\n"
	.string "¡Trataré de decirlo!\l"
	.string "Aunque, con los nervios, no sé si podré…\p"
	.string "Gracias, {PLAYER}{KUN}.\n"
	.string "Ahora tengo que decirte adiós.\p"
	.string "Tendré presentes todos tus consejos,\n"
	.string "{PLAYER}{KUN}, y lo haré lo mejor que pueda.$"

gText_ApprenticePickWinSpeech15:: @ 82C2EF5
	.string "¿Mmm? Vaya, pareces ser {PLAYER}{KUN}…\n"
	.string "Pero ¿lo eres en realidad?\l"
	.string "¿O eres un muñeco de {PLAYER} muy listo?\p"
	.string "¡Oh, no, no, no, no te preocupes!\n"
	.string "Si de verdad eres {PLAYER}, por favor,\l"
	.string "perdona el despiste.\p"
	.string "No hace falta malhumorarse. Al fin y al\n"
	.string "cabo, solo quiero un consejo más de ti.\p"
	.string "Es una cuestión de palabras…\p"
	.string "Más concretamente, ¿qué debería\n"
	.string "decir tras vencer un combate?$"

gText_ApprenticeWinSpeechThanks15:: @ 82C3023
	.string "{STR_VAR_1}\p"
	.string "… \n"
	.string "Así que cuando gane debo decir…\p"
	.string "{STR_VAR_1}\p"
	.string "¿Estás hablando en serio?\p"
	.string "Bien. Confiaré en tu buen juicio.\n"
	.string "Tienes todo mi agradecimiento.\p"
	.string "Espero saber decirlo con la misma\n"
	.string "sabiduría que tú.\p"
	.string "Bueno, parece ser que no me queda\n"
	.string "nada más que inquirirte.\p"
	.string "Creo que ha llegado la hora de decirnos\n"
	.string "adiós y desearnos suerte. \p"
	.string "¡Gracias, pues, y suerte!\n"
	.string "¡Y disculpa una vez más mi escepticismo!$"
