FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent: @ 82C47EB
	.string "¡Te damos la bienvenida a la tienda\n"
	.string "de batalla de pueblo Pardal!\p"
	.string "¡Yo soy el guía del torneo con juez!$"

FallarborTown_BattleTentLobby_Text_TakeChallenge: @ 82C4843
	.string "¿Te atreves a participar\n"
	.string "en un torneo con juez?$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge: @ 82C487F
	.string "Bueno, vuelve cuando quieras.$"

FallarborTown_BattleTentLobby_Text_ExplainFallarborTent: @ 82C48AC
	.string "En la tienda de batalla de Pardal,\n"
	.string "se disputan torneos con juez.\p"
	.string "Cada entrenador participa\n"
	.string "con un equipo de tres Pokémon.\p"
	.string "Primero, debes elegir los tres Pokémon\n"
	.string "en el orden en que deseas que combatan.\p"
	.string "Durante el combate, los Pokémon\n"
	.string "aparecerán uno a uno en ese orden.\p"
	.string "Una vez entre un Pokémon en combate,\n"
	.string "deberá seguir hasta que concluya.\p"
	.string "Pero si no hay ganador al cabo\n"
	.string "de tres rondas, el juez decidirá.\p"
	.string "Si quieres interrumpir el desafío,\n"
	.string "no olvides guardar antes la partida.\p"
	.string "Si no la guardas, se te descalificará.\p"
	.string "Si logras vencer a tres entrenadores\n"
	.string "seguidos, ganarás un bonito premio.$"

FallarborTown_BattleTentLobby_Text_SaveBeforeChallenge: @ 82C4B35
	.string "Te mostraré la tienda de batalla,\n"
	.string "pero antes guardaré la partida, ¿eh?…$"

@ Unused 
FallarborTown_BattleTentLobby_Text_WhichLevelMode: @ 82C4B77
	.string "Ofrecemos dos niveles de desafio,\n"
	.string "nivel 50 y nivel abierto.\l"
	.string "¿Cuál eliges?$"

FallarborTown_BattleTentLobby_Text_SelectThreeMons: @ 82C4BC8
	.string "Selecciona los tres Pokémon\n"
	.string "con los que quieres combatir.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLv50: @ 82C4BFA
	.string "Qué lástima…\p"
	.string "No tienes tres Pokémon que puedan\n"
	.string "participar en este desafío.\p"
	.string "Cuando los consigas, deben sostener\n"
	.string "distintos tipos de objeto.\p"
	.string "Los huevos{STR_VAR_1} participar.\p"
	.string "Vuelve cuando cumplas las condiciones\n"
	.string "para aceptar el desafío.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen: @ 82C4CC0
	.string "Qué lástima…\p"
	.string "No tienes tres Pokémon que puedan\n"
	.string "participar en este desafío.\p"
	.string "Necesitas tres Pokémon diferentes\n"
	.string "para poder participar.\p"
	.string "Además, deben sostener distintos\n"
	.string "tipos de objeto.\p"
	.string "Los huevos{STR_VAR_1} participar.\p"
	.string "Vuelve cuando cumplas las condiciones\n"
	.string "para aceptar el desafío.$"

FallarborTown_BattleTentLobby_Text_GuideYouToBattleTent: @ 82C4DC3
	.string "Ahora te guiaré hasta\n"
	.string "la tienda de batalla.$"

FallarborTown_BattleTentLobby_Text_DidntSaveBeforeQuitting: @ 82C4DED
	.string "Lástima…\p"
	.string "No guardaste la partida antes\n"
	.string "de abandonar el desafío, ¿verdad?…\p"
	.string "Eso implica la descalificación…\p"
	.string "No obstante, puedes volver\n"
	.string "a participar cuando quieras.$"

FallarborTown_BattleTentLobby_Text_BeatThreeTrainers: @ 82C4EC3
	.string "¡Espléndido! ¡Has vencido a tres\n"
	.string "Entrenadores consecutivos!$"

FallarborTown_BattleTentLobby_Text_WaitWhileSaveGame: @ 82C4EFF
	.string "Espera un segundo mientras\n"
	.string "guardo la partida.$"

FallarborTown_BattleTentLobby_Text_PresentYouWithPrize: @ 82C4F22
	.string "Toma este premio para conmemorar\n"
	.string "tu racha de 3 victorias consecutivas.$"

FallarborTown_BattleTentLobby_Text_ReceivedPrize: @ 82C4F69
	.string "{PLAYER} recibió el premio\n"
	.string "{STR_VAR_1}.$"

FallarborTown_BattleTentLobby_Text_BagFullReturnForPrize: @ 82C4F83
	.string "¡Pero bueno!\n"
	.string "Tienes la Mochila repleta.\p"
	.string "Será mejor que la vacíes un poco\n"
	.string "si quieres llevarte el premio.$"

FallarborTown_BattleTentLobby_Text_ThankYouWaitWhileSaving: @ 82C4FD7
	.string "¡Muchas gracias por participar!\p"
	.string "Espera un segundo mientras\n"
	.string "guardo la partida.$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge2: @ 82C501F
	.string "Esperamos que vuelvas\n"
	.string "pronto por aquí.$"

FallarborTown_BattleTentLobby_Text_LookingForwardToArrival: @ 82C504C
	.string "Ya tenía ganas de volver a verte.\p"
	.string "Antes de conducirte a la tienda\n"
	.string "de batalla, debo guardar la partida.\l"
	.string "Espera un momento…$"

VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent: @ 82C50C3
	.string "¡Ésta es la tienda de batalla\n"
	.string "de Verdegal!\p"
	.string "Aquí ponemos a prueba la confianza\n"
	.string "de los Entrenadores en sus Pokémon.$"

VerdanturfTown_BattleTentLobby_Text_TakeChallenge: @ 82C5129
	.string "¿Deseas afrontar el desafío de la\n"
	.string "tienda de batalla de Verdegal?$"

VerdanturfTown_BattleTentLobby_Text_ExplainVerdanturfTent: @ 82C5163
	.string "En la tienda de batalla\n"
	.string "de Verdegal, hay una regla\l"
	.string "básica que debe ser respetada.\p"
	.string "Los entrenadores solo pueden\n"
	.string "cambiar de Pokémon.\p"
	.string "Es decir, los entrenadores no pueden\n"
	.string "dar órdenes a sus Pokémon.\p"
	.string "De este modo, se deja que los Pokémon\n"
	.string "combatan solos, según su naturaleza.\p"
	.string "Debes confiar en tus Pokémon\n"
	.string "y vigilar para que nada les pase.\p"
	.string "Si logras derrotar consecutivamente\n"
	.string "a tres Entrenadores, obtendrás\l"
	.string "un premio como reconocimiento.\p"
	.string "Si quieres interrumpir el desafío,\n"
	.string "no olvides guardar antes la partida.\p"
	.string "Si no la guardas, se te descalificará.$"

VerdanturfTown_BattleTentLobby_Text_ReturnFortified: @ 82C539A
	.string "Vuelve cuando tu corazón y el de tus\n"
	.string "Pokémon latan como uno solo.$"

@ Unused 
VerdanturfTown_BattleTentLobby_Text_WhichLevelMode: @ 82C53DB
	.string "Ofrecemos dos niveles de dificultad,\n"
	.string "nivel 50 y nivel abierto.\l"
	.string "¿Cuál eliges?$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLv50: @ 82C543D
	.string "Qué desgracia…\p"
	.string "No tienes tres Pokémon que puedan\n"
	.string "participar en este desafío.\p"
	.string "Necesitas tres Pokémon diferentes\n"
	.string "para poder participar.\p"
	.string "Además, deben sostener distintos\n"
	.string "tipos de objeto.\p"
	.string "Los huevos{STR_VAR_1} participar.\p"
	.string "Vuelve cuando cumplas las condiciones\n"
	.string "para aceptar el desafío.$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen: @ 82C5538
	.string "Qué desgracia…\p"
	.string "No tienes tres Pokémon que puedan\n"
	.string "participar en este desafío.\p"
	.string "Necesitas tres Pokémon diferentes\n"
	.string "para poder participar.\p"
	.string "Además, deben sostener distintos\n"
	.string "tipos de objeto.\p"
	.string "Los huevos{STR_VAR_1} participar.\p"
	.string "Vuelve cuando cumplas las condiciones\n"
	.string "para aceptar el desafío.$"

VerdanturfTown_BattleTentLobby_Text_SelectThreeMons: @ 82C5633
	.string "Selecciona los tres Pokémon\n"
	.string "con los que quieres combatir.$"

VerdanturfTown_BattleTentLobby_Text_SaveBeforeChallenge: @ 82C5662
	.string "Antes de conducirte a la tienda\n"
	.string "de batalla, debes guardar la partida.\l"
	.string "¿Estás de acuerdo?$"

VerdanturfTown_BattleTentLobby_Text_NowFollowMe: @ 82C56A2
	.string "Bien.\n"
	.string "Ahora, sígueme.$"

VerdanturfTown_BattleTentLobby_Text_ResultsWillBeRecorded: @ 82C56B8
	.string "Me siento privilegiado por poder haber\n"
	.string "visto combatir a tus Pokémon.\p"
	.string "Voy a guardar tu resultado.\n"
	.string "Sólo será un segundo, por favor.$"

VerdanturfTown_BattleTentLobby_Text_AchievedThreeWinStreak: @ 82C5731
	.string "A juzgar por tus tres victorias\n"
	.string "consecutivas…\p"
	.string "El vínculo que une tu corazón al de tus \n"
	.string "Pokémon debe de ser firme y fuerte.$"

VerdanturfTown_BattleTentLobby_Text_FeatWillBeRecorded: @ 82C5791
	.string "Voy a guardar tu récord.\n"
	.string "Espera unos instantes.$"

VerdanturfTown_BattleTentLobby_Text_PresentYouWithPrize: @ 82C57CD
	.string "Tus tres victorias consecutivas se\n"
	.string "merecen qué menos que este premio.$"

SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent: @ 82C5810
	.string "¡Ésta es la tienda de batalla\n"
	.string "de Ciudad Portual!\p"
	.string "Aquí se celebran los famosos \n"
	.string "Torneos de combates con trueque.$"

SlateportCity_BattleTentLobby_Text_TakeChallenge: @ 82C586A
	.string "¿Deseas afrontar el desafío de un\n"
	.string "torneo de combates con trueque?$"

SlateportCity_BattleTentLobby_Text_ExplainSlateportTent: @ 82C589C
	.string "En la tienda de batalla de ciudad\n"
	.string "Portual se disputan Combates\l"
	.string "con Trueque con Pokémon prestados.\p"
	.string "Primero, debes elegir los tres Pokémon\n"
	.string "con los que vas a comenzar el torneo.\p"
	.string "Con esos Pokémon prestados, debes\n"
	.string "luchar en el primer combate individual.\p"
	.string "Si ganas a tu rival, tendrás derecho a\n"
	.string "un trueque: podrás elegir uno de sus\l"
	.string "Pokémon y cambiárselo por uno tuyo.\p"
	.string "Repite este ciclo de combate y trueque\n"
	.string "y, si logras ganar tres veces seguidas,\l"
	.string "conseguirás un fabuloso premio.\p"
	.string "Si quieres interrumpir el desafío,\n"
	.string "no olvides guardar antes la partida.\p"
	.string "Si no la guardas, se te descalificará.$"

SlateportCity_BattleTentLobby_Text_LookForwardToNextVisit: @ 82C5AA5
	.string "Espero que vuelvas\n"
	.string "pronto por aquí.$"

@ Unused 
SlateportCity_BattleTentLobby_Text_WhichLevelMode: @ 82C5AC9
	.string "¿Qúe nivel de desafio quieres?\n"
	.string "¿Nivel 50 o nivel 100?$"

SlateportCity_BattleTentLobby_Text_SaveBeforeChallenge: @ 82C5B06
	.string "Antes de afrontar tu desafío,\n"
	.string "debo guardar la partida, ¿de acuerdo?$"

@ Unused 
SlateportCity_BattleTentLobby_Text_HoldMonsForSafekeeping: @ 82C5B4A
	.string "Ok, cuidate a tus Pokémon\n"
	.string "mientras compites.$"

SlateportCity_BattleTentLobby_Text_StepThisWay: @ 82C5B8C
	.string "Pasa por aquí.$"

SlateportCity_BattleTentLobby_Text_ReturnRentalMonsSaveResults: @ 82C5BA2
	.string "¡Gracias por participar!\p"
	.string "Voy a devolverte tus Pokémon\n"
	.string "a cambio de los que te prestamos.\p"
	.string "Y voy a guardar también tus resultados.\n"
	.string "Un momento, por favor.$"

@ Unused 
SlateportCity_BattleTentLobby_Text_ReturnMonsExchangeRentals: @ 82C5C30
	.string "Aquí tienes de vuelta tus Pokémon\n"
	.string "a cambio de los alquilados.$"

SlateportCity_BattleTentLobby_Text_WonThreeMatchesReturnMons: @ 82C5C6F
	.string "¡Enhorabuena!\n"
	.string "¡Tres victorias seguidas!\p"
	.string "Voy a devolverte tus Pokémon\n"
	.string "a cambio de los que te prestamos.\p"
	.string "Y voy a guardar también tus resultados.\n"
	.string "Un momento, por favor.$"

SlateportCity_BattleTentLobby_Text_AwardYouThisPrize: @ 82C5D14
	.string "Como premio por las tres victorias\n"
	.string "seguidas, toma esto. Para ti.$"

SlateportCity_BattleTentLobby_Text_NoRoomInBagMakeRoom: @ 82C5D52
	.string "¿Eh?\n"
	.string "Se diría que no tienes sitio para esto.\p"
	.string "Haz un hueco en la Mochila\n"
	.string "y vuelve por aquí.$"

SlateportCity_BattleTentLobby_Text_BeenWaitingForYou: @ 82C5DA7
	.string "¡Te estábamos esperando!\p"
	.string "Antes de volver a competir,\n"
	.string "déjame guardarte la partida.$"

SlateportCity_BattleTentLobby_Text_DidntSaveBeforeQuitting: @ 82C5DFA
	.string "Siento decírtelo, pero no guardaste\n"
	.string "la partida la última vez que jugaste.\p"
	.string "Así que se te ha descalificado.\n"
	.string "Lo siento.$"

@ Unused 
SlateportCity_BattleTentLobby_Text_ReturnPersonalMons: @ 82C5E85
	.string "Aquí tienes de vuelta tus Pokémon.$"

@ Unused 
SlateportCity_BattleTentLobby_Text_ReceivedPrize: @ 82C5EA9
	.string "{PLAYER} recibió el premio\n"
	.string "{STR_VAR_1}.$"

@ Unused 
SlateportCity_BattleTentLobby_Text_RulesAreListed: @ 82C5EC3
	.string "Se enumeran las reglas de battle swap.$"

@ Unused 
SlateportCity_BattleTentLobby_Text_ReadWhichHeading: @ 82C5EE5
	.string "¿Qué título quieres leer?$"

SlateportCity_BattleTentLobby_Text_ExplainBasicRules: @ 82C5F08
	.string "En los enfrentamientos de Combate\n"
	.string "con Trueque, solo se usan tres Pokémon.\p"
	.string "Al tomar prestados o trocar Pokémon,\n"
	.string "hay que tener en cuenta que el equipo\l"
	.string "no debe tener dos Pokémon iguales.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapPartnerRules: @ 82C5F9D
	.string "Sólo puedes cambiarle un Pokémon\n"
	.string "al Entrenador al que acabas de vencer.\p"
	.string "Y solo puedes elegir entre los Pokémon\n"
	.string "que haya usado ese Entrenador.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNumberRules: @ 82C6020
	.string "Después de cada victoria, podrás\n"
	.string "cambiar uno de tus Pokémon por\l"
	.string "uno de los del Entrenador derrotado.\p"
	.string "Con el tercer entrenador\n"
	.string "no podrás hacer trueque de Pokémon.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNotes: @ 82C60C0
	.string "A la hora de trocar Pokémon, debes\n"
	.string "tener en cuenta dos cosas.\p"
	.string "Primera: en el momento del trueque,\n"
	.string "no podrás ver las características\l"
	.string "del Pokémon que vas a recibir.\p"
	.string "Segunda: los Pokémon de tu equipo\n"
	.string "se mostrarán siguiendo el orden\l"
	.string "en el que los elegiste.\p"
	.string "Ese orden no se altera aunque\n"
	.string "luego realices trueques.$"

SlateportCity_BattleTentLobby_Text_ExplainMonRules: @ 82C61FE
	.string "Todos los Pokémon de la tienda de\n"
	.string "batalla de Ciudad Portual se alquilan.\p"
	.string "Todos los Pokémon que se alquilan\n"
	.string "se encuentran en el nivel 30.$"

@ Unused 
VerdanturfTown_BattleTentLobby_Text_RulesAreListed2: @ 82C6261
	.string "Son las reglas de la tienda de batalla\n"
	.string "de Verdegal.$"

@ Unused 
VerdanturfTown_BattleTentLobby_Text_ReadWhichHeading: @ 82C628E
	.string "¿Qué título quieres leer?$"

@ Unused 
VerdanturfTown_BattleTentLobby_Text_ExplainBasicRules: @ 82C62B1
	.string "Aquí en la tienda de batalla de Verdegal,\n"
	.string "los Pokémon deben pensar y\l"
	.string "luchar por ellos mismos.\p"
	.string "A diferencia de lo que ocurre en la naturaleza,\n"
	.string "los Pokémon que viven con gente\l"
	.string "se comportan de manera diferente\l"
	.string "dependiendo de su naturaleza.$"

@ Unused 
VerdanturfTown_BattleTentLobby_Text_ExplainNatureRules: @ 82C636D
	.string "Dependiendo de su naturaleza, un Pokémon\n"
	.string "puede que prefiera atacar pase lo que pase..\p"
	.string "Otro Pokémon puede preferir protegerse\n"
	.string "de cualquier daño.\p"
	.string "Sin embargo, otro puede disfrutar irritando\n"
	.string "o confundiendo a sus rivales.\p"
	.string "Dependiendo de su naturaleza, un Pokémon\n"
	.string "tendrá movimientos favoritos que los\l"
	.string "usa mejor.\p"
	.string "ISin embargo, tendrá movimientos que no\n"
	.string "le gusten y tendra problemas al usarlos.$"

@ Unused 
VerdanturfTown_BattleTentLobby_Text_ExplainMoveRules: @ 82C64BA
	.string "Hay movimientos ofensivos que\n"
	.string "infligen daño directo al enemigo.\p"
	.string "Hay movimientos defensivos que se utilizan\n"
	.string "para prepararse para los ataques\l"
	.string "enemigos o para curar HP, etc.\p"
	.string "También hay otros movimientos algo extraños\n"
	.string "que pueden debilitar a los enemigos con\l"
	.string "problemas de estadísticas, como veneno\l"
	.string "y parálisis.\p"
	.string "Los Pokémon pueden usar movimientos\n"
	.string "de esas tres categorias.$"

@ Unused 
VerdanturfTown_BattleTentLobby_Text_ExplainUnderpoweredRules: @ 82C6612
	.string "Cuando no está bajo el mando de su Entrenador,\n"
	.string "es posible que un Pokémon no pueda\l"
	.string "usar ciertos movimientos.\p"
	.string "Un Pokémon no es bueno para usar\n"
	.string "ningún movimiento que no le guste.\p"
	.string "Si un Pokémon solo conoce movimientos que \n"
	.string "no coinciden con su naturaleza, a menudo \l"
	.string "no podrá estar a la altura de su potencial.$"

@ Unused 
VerdanturfTown_BattleTentLobby_Text_ExplainWhenInDangerRules: @ 82C671E
	.string "Dependiendo de su naturaleza, un Pokémon puede\n"
	.string "comenzar a usar movimientos que\l"
	.string "no coinciden con su naturaleza\p"
	.string "cuando está en problemas.\n"
	.string "Si un Pokémon comienza a comportarse\l"
	.string "de manera extraña en un apuro, obsérvelo con atención.$"

BattleTentLobby_Text_ExplainLevelRules: @ 82C67CD
	.string "En esta tienda de batalla, los niveles\n"
	.string "de tus rivales se ajustarán para\l"
	.string "igualarse a los de tus Pokémon.\p"
	.string "Con todo, ningún Entrenador\n"
	.string "al que te enfrentes tendrá Pokémon\l"
	.string "por debajo del nivel 30.$"

VerdanturfTown_BattleTentLobby_Text_RulesAreListed: @ 82C6878
	.string "Son las reglas de la tienda de batalla\n"
	.string "de Verdegal.$"
