PetalburgCity_Gym_Text_GiveEnigmaBerry: @ 82A6D3D
	.string "Papá: ¡Hola, {PLAYER}!\p"
	.string "Acabo de recibir esta baya rara.\n"
	.string "Venga, es para ti.$"

Route104_Text_PlantBerriesInSoilTakeThis: @ 82A6D86
	.string "Si ves bayas que crecen en un\n"
	.string "terreno fértil, cógelas.\p"
	.string "Pero asegúrate de plantar otra baya\n"
	.string "en ese lugar. Quien siembra, recoge.\p"
	.string "Mira, voy a compartir esto contigo.$"

Route104_Text_TrainersOftenMakeMonHoldBerries: @ 82A6E32
	.string "Por tu forma de mirar, sé que tú\n"
	.string "entrenas Pokémon, ¿a que sí?\p"
	.string "Los entrenadores suelen dar\n"
	.string "Bayas a sus Pokémon.\p"
	.string "Es asunto tuyo si quieres plantar\n"
	.string "Bayas o simplemente usarlas.$"

Route111_Text_WateredPlantsEveryDayTakeBerry: @ 82A6EBD
	.string "Regué las plantas cada día y ahora\n"
	.string "tienen un montón de flores.\p"
	.string "También han dado muchas bayas.\p"
	.string "¡Mira, esto es para ti!$"

Route111_Text_GoingToTryToMakeDifferentColorBerries: @ 82A6F3D
	.string "Voy a intentar hacer bayas\n"
	.string "de diferentes colores.\p"
	.string "¡Prueba tú también!$"

Route111_Text_WhatColorBerriesToLookForToday: @ 82A6F9A
	.string "Me pregunto qué color tendrán\n"
	.string "las Bayas hoy…$"

Route114_Text_LoveUsingBerryCrushShareBerry: @ 82A6FCB
	.string "Me encanta usar el Machacabayas,\n"
	.string "por eso estoy recogiendo Bayas.\p"
	.string "¡Si quieres, te puedo dar una!$"

Route114_Text_TryBerryCrushWithFriends: @ 82A7034
	.string "Deberías usar el Machacabayas\n"
	.string "con tus amigos.$"

Route114_Text_FunToThinkAboutBerries: @ 82A706E
	.string "¿Qué baya debería plantar?\n"
	.string "¿Tendría que usarla o guardarla?\p"
	.string "Con tantas dudas, nunca te aburres.$"

Route120_Text_BerriesExpressionOfLoveIsntIt: @ 82A70C7
	.string "Las bayas absorben la luz\n"
	.string "del sol para crecer fuertes.\p"
	.string "También hay que regarlas de forma\n"
	.string "regular para potenciar el crecimiento.\p"
	.string "Hay que tratarlas con cariño, ¿sabes?$"

Route120_Text_YesYouUnderstand: @ 82A7147
	.string "Sí, sí.\n"
	.string "Tú sabes a lo que me refiero.\p"
	.string "Toma esto.$"

Route120_Text_MakeYourOwnImpressions: @ 82A7183
	.string "Oh… Bueno, supongo que es mejor\n"
	.string "que saques tus propias conclusiones.\p"
	.string "Toma esto.$"

Route120_Text_BerryIsRareRaiseItWithCare: @ 82A71D5
	.string "Creo que esta baya es rara.\n"
	.string "Espero que la cuides con amor.$"

Route120_Text_IllGetMoreBerriesFromBerryMaster: @ 82A7217
	.string "Iré a pedir más bayas al\n"
	.string "Bayólogo.$"

LilycoveCity_Text_BerrySuitsYou: @ 82A7244
	.string "Cuando lo piensas…\p"
	.string "Igual que un traje te sienta bien o\n"
	.string "que el aire fresco sienta bien para\l"
	.string "el dolor de cabeza…\p"
	.string "¡Una baya también puede\n"
	.string "sentar como un guante!\p"
	.string "¿Y eso por qué?$"

LilycoveCity_Text_BecauseYoureTrainer: @ 82A72E3
	.string "Cuando lo piensas…\p"
	.string "¡Debe de ser porque entrenas Pokémon!$"

LilycoveCity_Text_PokeblocksSuitPokemon: @ 82A7321
	.string "Cuando lo piensas…\p"
	.string "¡Igual que me sienta bien un aire de\n"
	.string "humildad, los Pokécubos sientan de\l"
	.string "muerte a los Pokémon!$"

Route123_BerryMastersHouse_Text_YoureDeservingOfBerry: @ 82A7386
	.string "¡Puedes llamarme el BAYÓLOGO!\p"
	.string "Mi sueño es cubrir el mundo de bellas\n"
	.string "flores que den Bayas para compartirlas\l"
	.string "con todo el mundo.\p"
	.string "¡Tú ya te mereces una!$"

Route123_BerryMastersHouse_Text_WhyBeStingyTakeAnother: @ 82A7428
	.string "¿Por qué ser rata?\n"
	.string "¡Toma otra más!$"

Route123_BerryMastersHouse_Text_VisitPrettyPetalFlowerShop: @ 82A7445
	.string "No olvides visitar la floristería\n"
	.string "Pitiminí, cerca de ciudad Férrica.\p"
	.string "¡Cubre el mundo de flores!$"

Route123_BerryMastersHouse_Text_DoneForToday: @ 82A749E
	.string "Ya he acabado por hoy.\n"
	.string "Vuelve otro día.\p"
	.string "¡Cubre de flores el mundo!$"

Route123_BerryMastersHouse_Text_HeardAGoodSayingLately: @ 82A74E6
	.string "La manera en que mi marido cultiva\n"
	.string "Bayas no tiene igual.\p"
	.string "Estoy orgullosísima de él, en serio.\p"
	.string "Por cierto, no habrás oído una\n"
	.string "buena expresión últimamente, ¿no?$"

Route123_BerryMastersHouse_Text_InspirationalTakeThis: @ 82A7583
	.string "¡Oh! ¡Qué expresión tan excepcional!\n"
	.string "¡Realmente inspirada!\p"
	.string "Toma esto en agradecimiento.$"

Route123_BerryMastersHouse_Text_GoodSayingTakeThis: @ 82A75D0
	.string "¡Oh! ¡Qué expresión tan buena!\n"
	.string "Se te da bastante bien.\p"
	.string "Toma esto en agradecimiento.$"

Route123_BerryMastersHouse_Text_JoyNeverGoesOutOfMyLife: @ 82A761B
	.string "Nuestros cuatro nietos un día serán\n"
	.string "tan buenos como mi marido.\p"
	.string "¡Tengo una vida maravillosa!$"

Route123_BerryMastersHouse_Text_Ah: @ 82A7682
	.string "Ah…$"

Route104_PrettyPetalFlowerShop_Text_ThisIsPrettyPetalFlowerShop: @ 82A7686
	.string "¡Hola!\p"
	.string "Ésta es la floristería Pitiminí, la que\n"
	.string "reparte flores a diestro y siniestro.$"

Route104_PrettyPetalFlowerShop_Text_LearnAboutBerries: @ 82A76D9
	.string "{PLAYER}{KUN}, ¿quieres saber algo sobre\n"
	.string "las Bayas?$"

Route104_PrettyPetalFlowerShop_Text_IntroLearnAboutBerries: @ 82A7706
	.string "¿Cómo te llamas?\p"
	.string "Ah, {PLAYER}{KUN}…\n"
	.string "¡Qué nombre tan bonito!\p"
	.string "{PLAYER}{KUN}, ¿quieres saber algo sobre\n"
	.string "las Bayas?$"

Route104_PrettyPetalFlowerShop_Text_BerriesExplanation: @ 82A775B
	.string "Las bayas crecen en los arbustos que\n"
	.string "hay en las zonas con tierra oscura\l"
	.string "y fértil.\p"
	.string "Si coges alguna baya, asegúrate de\n"
	.string "plantar otra en ese lugar.\p"
	.string "Las bayas que plantas no tardan en\n"
	.string "brotar, crecer, florecer y dar Bayas.\p"
	.string "Quiero llenar Hoenn de hermosas\n"
	.string "flores. Es mi sueño.\p"
	.string "Ayúdame, {PLAYER}{KUN}. Planta bayas\n"
	.string "y cubre de flores el mundo.$"

Route104_PrettyPetalFlowerShop_Text_FlowersBringHappiness: @ 82A78DF
	.string "Las flores te alegran el día,\n"
	.string "¿a que sí?$"

Route104_PrettyPetalFlowerShop_Text_YouCanHaveThis: @ 82A7916
	.string "¡Hola!\p"
	.string "Cuanta más atención prestas a las\n"
	.string "flores, más bonitas se ponen.\p"
	.string "Te gustará cuidar de las flores.\n"
	.string "Seguro. Mira, toma esto.$"

Route104_PrettyPetalFlowerShop_Text_WailmerPailExplanation: @ 82A79A6
	.string "Mientras las bayas estén creciendo,\n"
	.string "riégalas con el cubo Wailmer.\p"
	.string "Otra cosa:\p"
	.string "Si no recoges las bayas en mucho\n"
	.string "tiempo, se volverán a caer al suelo,\l"
	.string "pero vuelven a crecer al rato.\p"
	.string "¿No es interesantísimo?\n"
	.string "Es el instinto de supervivencia.$"

Route104_PrettyPetalFlowerShop_Text_ImGrowingFlowers: @ 82A7A98
	.string "Quiero ser como mis hermanas\n"
	.string "mayores y cultivar flores.\p"
	.string "¡Toma! ¡Es para ti!$"

Route104_PrettyPetalFlowerShop_Text_MachineMixesBerries: @ 82A7AF3
	.string "Puedes plantar una baya y cultivarla\n"
	.string "o puedes dársela a un Pokémon.\p"
	.string "Pero también hay una máquina que\n"
	.string "mezcla distintos tipos de bayas y\l"
	.string "hace caramelos para los Pokémon.\p"
	.string "¡Los llaman Pokécubos!\n"
	.string "Yo también quiero uno…$"

SootopolisCity_Text_NameIsKiriHaveOneOfThese: @ 82A7BB0
	.string "Hola, ¿cómo te llamas?\p"
	.string "Ajá…\n"
	.string "Sí, muy bonito.\p"
	.string "Yo me llamo Dulcinea.\p"
	.string "Mis padres me llamaron así porque\n"
	.string "deseaban que fuera dulce y amable.\l"
	.string "Así querían que fuera y así soy.\p"
	.string "Toma esto.$"

SootopolisCity_Text_GiveYouThisBerryToo: @ 82A7C7C
	.string "Te voy a dar esta baya también.\n"
	.string "Me gusta un montón.$"

SootopolisCity_Text_WhatKindOfWishInYourName: @ 82A7CB7
	.string "Me pregunto qué deseo estará\n"
	.string "encerrado en tu nombre.$"

SootopolisCity_Text_LikeSeasonBornIn: @ 82A7CEC
	.string "Primavera, verano, otoño, invierno.\p"
	.string "¿Crees que si naces en primavera te\n"
	.string "gusta más esa estación y si naces\l"
	.string "en verano prefieres el verano?$"

SootopolisCity_Text_ThenILoveAutumn: @ 82A7D80
	.string "Pues yo nací en otoño,\n"
	.string "¡por eso me gusta el otoño!\p"
	.string "¿Qué estación te gusta a ti?$"

SootopolisCity_Text_OhDoesntMatter: @ 82A7DD2
	.string "Oh…\n"
	.string "Bueno, no importa…\p"
	.string "Hay tanto que me gustaría saber…$"
