gText_Birch_Welcome:: @ 82C897B
	.string "¡Hola! Perdona que te haya\n"
	.string "hecho esperar.\p"
	.string "¡Te doy la bienvenida al fabuloso\n"
	.string "mundo de los Pokémon!\p"
	.string "Me llamo Abedul.\p"
	.string "Pero todo el mundo me llama\n"
	.string "profesor Abedul.\p"
	.string "$"

gText_Birch_Pokemon:: @ 82C89FB
	.string "Esto es lo que llamamos un “Pokémon.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech:: @ 82C8A1F
	.string "El mundo está habitado por\n"
	.string "criaturas llamadas Pokémon.\p"
	.string "Los humanos y los Pokémon vivimos\n"
	.string "juntos. A veces nos lo pasamos bien\l"
	.string "y nos ayudamos unos a otros.\p"
	.string "A veces nos unimos y combatimos\n"
	.string "contra equipos como el nuestro.\p"
	.string "Pero, a pesar de estos vínculos,\n"
	.string "ignoramos mucho sobre los Pokémon.\p"
	.string "De hecho, hay multitud de secretos\n"
	.string "que rodean a los Pokémon.\p"
	.string "En mi afán por descubrirlos, he\n"
	.string "dedicado mi vida a la investigación.\l"
	.string "Eso es lo que hago.\p"
	.string "$"

gText_Birch_AndYouAre:: @ 82C8BD0
	.string "¿Tú quién eres?$"

gText_Birch_BoyOrGirl:: @ 82C8BDD
	.string "¿Eres un chico o una chica?$"

gText_Birch_WhatsYourName:: @ 82C8BFF
	.string "Muy bien.\n"
	.string "¿Y cómo te llamas?$"

gText_Birch_SoItsPlayer:: @ 82C8C1C
	.string "Así que eres {PLAYER}{KUN}…$"

gText_Birch_YourePlayer:: @ 82C8C2A
	.string "¡Ah, sí, ya me acuerdo!\p"
	.string "Tú te acabas de mudar a mi\n"
	.string "pueblo natal, Villa Raíz.\l"
	.string "¿A que sí?\p"
	.string "$"

gText_Birch_AreYouReady:: @ 82C8C7A
	.string "Vale, escucha bien lo que te\n"
	.string "voy a decir…\p"
	.string "Tu propia aventura está a punto\n"
	.string "de comenzar.\p"
	.string "Adelante, entra en el mundo de los\n"
	.string "Pokémon: un mundo de ensueño, lleno\l"
	.string "de aventuras y grandes amigos.\p"
	.string "Bueno, ven a verme luego. Te espero\n"
	.string "en mi Laboratorio Pokémon.\p"
	.string "$"
