BerryBlender_Text_BlendWithTheBlendMaster: @ 82C427C
	.string "Licuólogo: ¡Que sí, que sí!\n"
	.string "¡Que yo soy el Licuólogo! ¿Quién si no?\p"
	.string "¡Quédate conmigo y aprenderás\n"
	.string "a sacarle el jugo a las cosas!$"

BerryBlender_Text_SeeMyMasteryInAction: @ 82C42F4
	.string "Licuólogo: ¡Mmmm! ¿Cómo?\n"
	.string "¿Quieres ver al Licuólogo en acción?$"

BerryBlender_Text_TooBusyNowIsee: @ 82C4332
	.string "¡Mmmm!\p"
	.string "Conque no tienes tiempo, ¿eh?\p"
	.string "¡No te preocupes!\n"
	.string "¡Estaré aquí todo el día!\l"
	.string "¡Acaba pronto lo que tengas que hacer!$"

BerryBlender_Text_BlendMasterNoBerries: @ 82C439D
	.string "¡Mmmm!\p"
	.string "Conque no tienes bayas, ¿eh?\p"
	.string "¡Estaré aquí todo el día!\n"
	.string "¡Ve a buscar algunas bayas!$"

BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks: @ 82C43FA
	.string "¡Por supuesto!\n"
	.string "¡Por supuesto!\p"
	.string "Por cierto…\n"
	.string "¿Sabes cómo crear Pokécubos\l"
	.string "con Bayas?$"

BerryBlender_Text_BlendMasterExplainBerryBlending: @ 82C444C
	.string "Vale, pues entonces te explico.\p"
	.string "No te asustes, es facilísimo.\p"
	.string "Cuando la flecha de la Licuabayas\n"
	.string "llegue a tu marcador, pulsa el botón A.\p"
	.string "Es lo único que hay que hacer.\p"
	.string "Cuando veas lo bien que pulso\n"
	.string "el botón A, ya verás cómo aprendes…$"

BerryBlender_Text_BlendMasterLetsBerryBlender: @ 82C451B
	.string "¡Bien!\p"
	.string "¡Comencemos, pues!\p"
	.string "¡Que eche humo esa Licuabayas!\n"
	.string "¡A licuar con el Licuólogo!$"

BerryBlender_Text_BlendMasterNoPokeblockCase: @ 82C4573
	.string "¡Mmm!\p"
	.string "¡Pero si no tienes ningún\n"
	.string "Tubo de Pokécubos!\p"
	.string "¡Estaré aquí todo el día!\n"
	.string "¡Consigue un tubo de Pokécubos y vuelve!$"

BerryBlender_Text_BlendMasterPokeblockCaseFull: @ 82C45E8
	.string "¡Mmm!\p"
	.string "¡Pero si tu tubo de Pokécubos está lleno!\p"
	.string "¡Estaré aquí todo el día!\n"
	.string "¡Gasta unos Pokécubos y vuelve luego!$"

BerryBlender_Text_WhoaAwesome: @ 82C464B
	.string "¡Eh!\n"
	.string "¡Fenomenal!$"

BerryBlender_Text_WickedlyFast: @ 82C465A
	.string "¡Espectacular!$"

BerryBlender_Text_WhatAnExpert: @ 82C4669
	.string "¡Estoy francamente impresionado!$"

BerryBlender_Text_MadeAmazingPokeblocksWithMaster: @ 82C4679
	.string "Me encanta licuar con el Licuólogo,\n"
	.string "¡hacemos Pokécubos alucinantes!$"

BerryBlender_Text_QualitiesOfBlendMaster: @ 82C46B1
	.string "Esa concentración…\n"
	.string "Esos ojos fijos en la flecha…\p"
	.string "Esa rapidez para pulsar el botón A…\n"
	.string "Esa increíble precisión…\p"
	.string "Ese Licuólogo es realmente único.$"

BerryBlender_Text_MasterWorksOnSkillsInMountains: @ 82C4763
	.string "Dicen que el Licuólogo se pasa la vida\n"
	.string "practicando su técnica en la montaña.\p"
	.string "Pero a veces se acerca a Calagua y\n"
	.string "se queda el día entero licuando Bayas.$"
