Underwater_SealedChamber_Braille_GoUpHere:
	.byte 4
	.byte 6
	.byte 26
	.byte 13
	.byte 7
	.byte 9
	.braille "SUBE AHORA.$"

SealedChamber_OuterRoom_Braille_ABC:
	.byte 7
	.byte 6
	.byte 21
	.byte 13
	.byte 10
	.byte 9
	.braille "ABC$"

SealedChamber_OuterRoom_Braille_GHI:
	.byte 7
	.byte 6
	.byte 21
	.byte 13
	.byte 10
	.byte 9
	.braille "GHI$"

SealedChamber_OuterRoom_Braille_MNO:
	.byte 7
	.byte 6
	.byte 21
	.byte 13
	.byte 10
	.byte 9
	.braille "MNO$"

SealedChamber_OuterRoom_Braille_TUV:
	.byte 7
	.byte 6
	.byte 21
	.byte 13
	.byte 10
	.byte 9
	.braille "TUV$"

SealedChamber_OuterRoom_Braille_DEF:
	.byte 7
	.byte 6
	.byte 21
	.byte 13
	.byte 10
	.byte 9
	.braille "DEF$"

SealedChamber_OuterRoom_Braille_JKL:
	.byte 7
	.byte 6
	.byte 21
	.byte 13
	.byte 10
	.byte 9
	.braille "JKL$"

SealedChamber_OuterRoom_Braille_PQRS:
	.byte 7
	.byte 6
	.byte 21
	.byte 13
	.byte 10
	.byte 9
	.braille "PQRS$"

SealedChamber_OuterRoom_Braille_Period:
	.byte 9
	.byte 6
	.byte 19
	.byte 13
	.byte 12
	.byte 9
	.braille ".$"

SealedChamber_OuterRoom_Braille_WXYZ:
	.byte 7
	.byte 6
	.byte 21
	.byte 13
	.byte 10
	.byte 9
	.braille "WXYZ$"

SealedChamber_OuterRoom_Braille_Comma:
	.byte 9
	.byte 6
	.byte 19
	.byte 13
	.byte 12
	.byte 9
	.braille ",$"

SealedChamber_OuterRoom_Braille_DigHere:
	.byte 7
	.byte 4
	.byte 23
	.byte 15
	.byte 10
	.byte 7
	.braille "CAVA AHORA.$"

SealedChamber_InnerRoom_Braille_FirstWailordLastRelicanth:
	.byte 0
	.byte 0
	.byte 29
	.byte 19
	.byte 3
	.byte 3
	.braille "PRIMERO\n"
	.braille "WAILORD.\n"
	.braille "AL FINAL,\n"
	.braille "RELICANTH.$"

SealedChamber_InnerRoom_Braille_InThisCaveWeHaveLived:
	.byte 2
	.byte 0
	.byte 26
	.byte 19
	.byte 5
	.byte 3
	.braille "ESTA CUEVA\n"
	.braille "HA SIDO\n"
	.braille "NUESTRO\n"
	.braille "HOGAR.$"

SealedChamber_InnerRoom_Braille_WeOweAllToThePokemon:
	.byte 7
	.byte 2
	.byte 23
	.byte 17
	.byte 10
	.byte 5
	.braille "LO QUE SOMOS\n"
	.braille "SE LO DEBEMOS\n"
	.braille "A LOS POKEMON.$"

SealedChamber_InnerRoom_Braille_ButWeSealedThePokemonAway:
	.byte 3
	.byte 0
	.byte 25
	.byte 19
	.byte 6
	.byte 3
	.braille "PERO LOS\n"
	.braille "ENCERRAMOS\n"
	.braille "PARA\n"
	.braille "SIEMPRE.$"

SealedChamber_InnerRoom_Braille_WeFearedIt:
	.byte 5
	.byte 6
	.byte 25
	.byte 13
	.byte 8
	.byte 9
	.braille "TUVIMOS MIEDO.$"

SealedChamber_InnerRoom_Braille_ThoseWithCourageHope:
	.byte 6
	.byte 0
	.byte 24
	.byte 19
	.byte 9
	.byte 3
	.braille "QUIENES\n"
	.braille "POSEEN\n"
	.braille "VALOR Y\n"
	.braille "ESPERANZA.$"

SealedChamber_InnerRoom_Braille_OpenDoorEternalPokemonWaits:
	.byte 3
	.byte 2
	.byte 27
	.byte 17
	.byte 6
	.byte 5
	.braille "ABREN LA\n"
	.braille "PUERTA HACIA\n"
	.braille "UN POKEMON\n"
	.braille "ETERNO.$"

DesertRuins_Braille_UseRockSmash:
	.byte 1
	.byte 0
	.byte 27
	.byte 19
	.byte 4
	.byte 3
	.braille "IZQ, IZQ,\n"
	.braille "ABAJO, ABAJO.\n"
	.braille "LUEGO USA\n"
	.braille "GOLPE ROCA.$"

IslandCave_Braille_RunLapAroundWall:
	.byte 5
	.byte 0
	.byte 25
	.byte 19
	.byte 8
	.byte 3
	.braille "PONTE JUNTO\n"
	.braille "AL MURO.\n"
	.braille "DA UNA VUELTA\n"
	.braille "COMPLETA.$"

AncientTomb_Braille_ShineInTheMiddle:
	.byte 3
	.byte 0
	.byte 25
	.byte 19
	.byte 6
	.byte 3
	.braille "QUIEN DESEE LO\n"
	.braille "QUE NOSOTROS,\n"
	.braille "QUE BRILLE\n"
	.braille "EN EL CENTRO.$"
