CableClub_Text_WelcomeWhichCableClubService: @ 8277EA4
	.string "Hola.\n"
	.string "Éste es el club del cable Pokémon.\p"
	.string "¿Qué te apetece hacer?$"

CableClub_Text_WhichService: @ 8277EF1
	.string "¿Qué podemos hacer por ti?$"

CableClub_Text_TradeUsingLinkCable:: @ 8277F1B
	.string "Intercambiar PKMN con otro jugador\n"
	.string "usando el cable Game Link de GBA.$"

CableClub_Text_BattleUsingLinkCable:: @ 8277F5A
	.string "Usando el cable Game Link de GBA,\n"
	.string "podrás luchar contra alguien.$"

CableClub_Text_RecordCornerUsingLinkCable:: @ 8277F96
	.string "Usa un cable Game Link de GBA para\n"
	.string "jugar en el centro de récords.$"

@ Unused
CableClub_Text_CloseThisMenu: @ 8277FDD
	.string "Cierra este menú.$"

CableClub_Text_NeedTwoMonsForDoubleBattle: @ 8277FEE
	.string "Para un Combate Doble, necesitas\n"
	.string "tener al menos dos Pokémon.$"

CableClub_Text_NeedTwoMonsToTrade: @ 8278027
	.string "Para intercambiar Pokémon,\n"
	.string "necesitas tener al menos dos.$"

CableClub_Text_CantTradeEnigmaBerry: @ 8278061
	.string "No puedes intercambiar el Pokémon\n"
	.string "que tiene la Baya {STR_VAR_1}.$"

gText_PleaseWaitForLink:: @ 8278091
	.string "Espera unos instantes.\n"
	.string "Pulsa el botón B para cancelar.$"

gText_ConfirmLinkWhenPlayersReady:: @ 82780B3
	.string "Cuando todos estén listos…\n"
	.string "botón A: confirmar   botón B: cancelar$"

gText_ConfirmStartLinkWithXPlayers:: @ 82780F2
	.string "Comenzar conexión con {STR_VAR_1} jugadores…\n"
	.string "botón A: confirmar   botón B: cancelar$"

gText_AwaitingLinkup:: @ 8278131
	.string "Esperando conexión…\n"
	.string "(…) botón B: cancelar$"

@ Unused
CableClub_Text_OkayToSaveProgress:: @ 8278157
	.string "Tu progreso se guardará\n"
	.string "¿estas de acuerdo en guardar?$"

CableClub_Text_PleaseEnter: @ 8278197
	.string "Adelante.$"

CableClub_Text_DirectYouToYourRoom: @ 82781A5
	.string "Te voy a llevar a tu sala.$"

Text_SomeoneIsNotReadyToLink: @ 82781C7
	.string "Uno de los jugadores no está listo\n"
	.string "para realizar la conexión.\p"
	.string "Vuelve cuando todos estéis listos.$"

Text_LinkErrorPleaseReset: @ 827821C
	.string "Error de conexión…\n"
	.string "Comprueba el cable Game Link, reinicia\l"
	.string "la consola e inténtalo de nuevo.$"

Text_PlayersMadeDifferentSelections: @ 8278255
	.string "Los demás jugadores parecen haber\n"
	.string "seleccionado opciones diferentes.$"

CableClub_Text_PleaseVisitAgain: @ 8278291
	.string "Vuelve cuando quieras.$"

CableClub_Text_IncorrectNumberOfParticipants: @ 82782A8
	.string "El número de jugadores no es correcto.$"

CableClub_Text_CantSingleBattleWithXPlayers: @ 82782D1
	.string "No se puede jugar al modo de combate\n"
	.string "IndividuaL con {STR_VAR_1} jugadores.$"

CableClub_Text_CantDoubleBattleWithXPlayers: @ 8278307
	.string "No se puede jugar al modo de combate\n"
	.string "Doble con {STR_VAR_1} jugadores.$"

CableClub_Text_NeedFourPlayers: @ 827833D
	.string "Se necesitan cuatro jugadores\n"
	.string "para jugar a este modo de combate.$"

CableClub_Text_PleaseConfirmNumberAndRestart: @ 8278372
	.string "Confirma el número de jugadores\n"
	.string "y vuelve a empezar.$"

Text_TerminateLinkConfirmation: @ 82783A8
	.string "Si sales de la sala, se pondrá fin\n"
	.string "a la conexión. ¿Estás de acuerdo?$"

Text_TerminateLinkPleaseWait: @ 82783E9
	.string "Finalizando conexión… Te acompañamos\n"
	.string "fuera de la sala. Espera un momento.$"

CableClub_Text_TooBusyToNotice: @ 827842E
	.string "Este entrenador no te hace ni caso…$"

CableClub_Text_GotToLookAtTrainerCard: @ 8278452
	.string "¡Bingo! ¡Puedes mirar la ficha\n"
	.string "de Entrenador de {STR_VAR_1}!$"

CableClub_Text_GotToLookAtColoredTrainerCard: @ 827847B
	.string "¡Bingo! ¡Puedes mirar la ficha\n"
	.string "de Entrenador de {STR_VAR_1}!\l"
	.string "¡Es de color {STR_VAR_2}!$"

BattleColosseum_2P_Text_TakePlaceStartBattle: @ 82784B4
	.string "Puedes comenzar el combate.$"

TradeCenter_Text_TakeSeatStartTrade: @ 82784E2
	.string "Puedes comenzar el intercambio.$"

RecordCorner_Text_ThanksForComing: @ 827850E
	.string "Gracias por venir.$"

CableClub_Text_TrainerCardDataOverwritten: @ 8278521
	.string "Se van a sobrescribir los datos\n"
	.string "de la ficha de entrenador.$"

CableClub_Text_HopeToSeeYouAgain: @ 827854C
	.string "¡Vuelve cuando quieras!$"

CableClub_Text_NotSetUpForFarAwayRegion: @ 8278565
	.string "Lo siento mucho.\p"
	.string "Aún no podemos realizar intercambios\n"
	.string "con EntrenadorES de otra región…$"

CableClub_Text_OtherTrainerNotReady: @ 82785C9
	.string "El otro entrenador no está listo.$"

CableClub_Text_YouHaveAMonThatCantBeTaken: @ 82785E9
	.string "Tienes al menos un Pokémon\n"
	.string "que no se puede enviar.$"

RecordCorner_Text_TakeSeatAndWait: @ 827861C
	.string "Toma asiento y espera un instante…$"

RecordCorner_Text_PlayerSentOverOneX: @ 827863C
	.string "¡{STR_VAR_1} envió {STR_VAR_2}!$"

CableClub_Text_CantMixWithJapaneseGame: @ 8278651
	.string "Hay un error de conexión.\p"
	.string "No puedes mezclar récords con las\n"
	.string "versiones japonesas de Pokémon\l"
	.string "Rubí y Zafiro.\p"
	.string "Tampoco puedes mezclar a la vez\n"
	.string "récords con la versión japonesa\l"
	.string "de Pokémon Esmeralda y cualquier\l"
	.string "versión de Rubí y Zafiro.$"

CableClub_Text_AdapterNotConnected: @ 827871F
	.string "El Conector inalámbrico de GBA\n"
	.string "no está bien conectado.$"

CableClub_Text_ParticipantsStepUpToCounter: @ 827874F
	.string "Los participantes deben pasar\n"
	.string "por el mostrador de recepción.$"

@ Unused
CableClub_Text_Hello: @ 827878B
	.string "¡Hola!$"

@ Unused
CableClub_Text_PleaseWait: @ 8278792
	.string "Por favor espera.$"

CableClub_Text_YouMayTradeHere:: @ 827879F
	.string "Aquí puedes intercambiar Pokémon\n"
	.string "con un amigo.$"

CableClub_Text_YouMayBattleHere:: @ 82787D5
	.string "Aquí puedes luchar contra tus amigos.$"

CableClub_Text_CanMakeBerryPowder:: @ 82787FC
	.string "Para hacer polvo de baya, hacen\n"
	.string "falta de dos a cinco EntrenadorES.$"

CableClub_Text_CanMixRecords:: @ 8278831
	.string "Se pueden mezclar los récords\n"
	.string "de dos a cuatro jugadores.$"

@ Unused
CableClub_Text_GuideToVariousServices: @ 827886B
	.string "Una guia para varios servicios\n"
	.string "del club Inalámbrico.$"

CableClub_Text_CancelSelectedItem:: @ 827889C
	.string "Cancelar la selección.$"

@ Unused
CableClub_Text_WhichBattleMode: @ 82788BC
	.string "¿Qué modo de juego quieres elegir?$"

@ Unused
CableClub_Text_ReturnsToPreviousStep: @ 82788DE
	.string "Vuelve a los pasos previos.$"

CableClub_Text_NeedBerryForBerryCrush: @ 82788FC
	.string "Para usar el Machacabayas,\n"
	.string "necesitas al menos una Baya.$"

CableClub_Text_NeedTwoMonsForUnionRoom: @ 827893E
	.string "Para entrar en la sala Unión,\n"
	.string "debes tener al menos dos Pokémon.$"

CableClub_Text_NoEnigmaBerryInUnionRoom: @ 827897B
	.string "Los Pokémon que tienen bayas\n"
	.string "{STR_VAR_1} no pueden entrar en la\l"
	.string "sala Unión.$"

CableClub_Text_UnionRoomAdapterNotConnected: @ 82789B5
	.string "Ésta es la sala Unión del club\n"
	.string "Inalámbrico Pokémon.\p"
	.string "Vaya, tu Conector inalámbrico\n"
	.string "de GBA no está bien conectado…\p"
	.string "Vuelve más tarde.$"

@ Unused
CableClub_Text_OhExcuseMe: @ 8278A39
	.string "Oh…\n"
	.string "¡Perdoname!$"

CableClub_Text_PlayerIsWaiting: @ 8278A48
	.string "¡Parece que {STR_VAR_1} está jugando\n"
	.string "ahora mismo! ¡Conéctate!$"

MossdeepCity_GameCorner_1F_Text_DescribeWhichGame: @ 8278A7D
	.string "Si quieres, te explico las reglas.\p"
	.string "¿De qué juego te hablo?$"

MossdeepCity_GameCorner_1F_Text_PokemonJumpInfo: @ 8278ACB
	.string "“Salto Pokémon”\p"
	.string "Consigue que a tus Pokémon no los\n"
	.string "atrape la liana usando el botón A.\p"
	.string "Sólo pueden participar los Pokémon\n"
	.string "que midan unos 70 cm o menos.\p"
	.string "A los Pokémon que naden despacio,\n"
	.string "caven o vuelen no se les dará muy\l"
	.string "bien lo de saltar.\p"
	.string "Por ello, estos Pokémon no deben\n"
	.string "participar.\p"
	.string "Si todos saltan a la vez,\n"
	.string "pueden ocurrir cosas estupendas.$"

MossdeepCity_GameCorner_1F_Text_DodrioBerryPickingInfo: @ 8278BF1
	.string "“Dodrio a por bayas”\p"
	.string "Dile a Dodrio que pille las bayas\n"
	.string "que pueda con los tres picos que\l"
	.string "tiene.\p"
	.string "Pulsa derecha, izquierda o arriba\n"
	.string "en el {PLUS} panel de control para\l"
	.string "que se mueva.\p"
	.string "Para poder jugar a este juego,\n"
	.string "hay que tener un Dodrio.$"

MossdeepCity_GameCorner_1F_Text_TalkToOldManToPlay: @ 8278CAC
	.string "Si quieres jugar a un juego, díselo\n"
	.string "al señor mayor que está a mi lado.$"

MossdeepCity_GameCorner_1F_Text_WelcomeCanYouWait: @ 8278CEB
	.string "¡Hola! ¿Vienes para jugar a juegos con\n"
	.string "el sistema de comunicación inalámbrica?\p"
	.string "¿Puedes esperar un segundo?$"

MossdeepCity_GameCorner_1F_Text_ComeAgain: @ 8278D51
	.string "¡Bueno, hasta otra!$"

MossdeepCity_GameCorner_1F_Text_AdapterNotConnected: @ 8278D68
	.string "El Conector inalámbrico de GBA\n"
	.string "no está conectado.\p"
	.string "¡Vuelve cuando lo tengas!$"

MossdeepCity_GameCorner_1F_Text_PlayWhichGame: @ 8278DAD
	.string "¿A qué juego quieres jugar?$"

MossdeepCity_GameCorner_1F_Text_EnterWhichPokemon: @ 8278DD9
	.string "¿Con qué Pokémon quieres\n"
	.string "participar?$"

MossdeepCity_GameCorner_1F_Text_AllGoodToGo: @ 8278E00
	.string "¡Muy bien! ¡Pues adelante!\n"
	.string "¡No te dejes ganar!$"

@ Unused
MossdeepCity_GameCorner_1F_Text_LeavingDoComeAgain: @ 8278E3C
	.string "¿Te vas ya?\n"
	.string "¡Vuelve de nuevo!$"

MossdeepCity_GameCorner_1F_Text_ExplainRequiredMon: @ 8278E60
	.string "Creo que no tienes Pokémon\n"
	.string "aptos para participar…\p"
	.string "¿Quieres que te diga cuáles son\n"
	.string "los que pueden participar?$"

MossdeepCity_GameCorner_1F_Text_ShortJumpingPokemonAllowed: @ 8278EDC
	.string "En “Salto Pokémon” pueden\n"
	.string "participar los Pokémon que midan\l"
	.string "unos 70 cm o menos.\p"
	.string "Los Pokémon que no pueden saltar\n"
	.string "no pueden participar.\p"
	.string "Es decir, los Pokémon que solo\n"
	.string "nadan, cavan o vuelan.\p"
	.string "Bueno, pues ya lo sabes.$"

MossdeepCity_GameCorner_1F_Text_OnlyDodrioAllowed: @ 8278FA4
	.string "Para jugar a “DodrioaA por bayas”\n"
	.string "necesitas a Dodrio.$"

@ Unused
MossdeepCity_GameCorner_1F_Text_RetryPlease: @ 8278FE0
	.string "¿Puedes reintentarlo desde el principio\n"
	.string "otra vez, por favor?$"

CableClub_Text_WelcomeWhichDirectCornerRoom: @ 8279013
	.string "Ésta es la zona directa del club\n"
	.string "Inalámbrico Pokémon.\p"
	.string "Aquí puedes comunicarte\n"
	.string "directamente con tus amigos.\p"
	.string "¿En qué sala quieres entrar?$"

CableClub_Text_TradePokemon: @ 827909D
	.string "¿Quieres cambiar Pokémon?$"

CableClub_Text_PlayWhichBattleMode: @ 82790BE
	.string "¿Qué modo de combate quieres?$"

CableClub_Text_AccessRecordCorner: @ 82790E8
	.string "¿Quieres entrar en el\n"
	.string "cntro de récords?$"

CableClub_Text_UseBerryCrush: @ 8279114
	.string "¿Quieres usar el Machacabayas?$"

CableClub_Text_ExplainBattleModes: @ 8279142
	.string "Hay tres modos de combate.\p"
	.string "El cmbate individual es para dos\n"
	.string "EntrenadorES con uno o más\l"
	.string "Pokémon cada uno.\p"
	.string "Cada entrenador puede usar\n"
	.string "un Pokémon cada vez.\p"
	.string "El combate doble es para dos\n"
	.string "EntrenadorES con dos o más\l"
	.string "Pokémon cada uno.\p"
	.string "Cada entrenador usará dos\n"
	.string "Pokémon cada vez.\p"
	.string "El combate multijugador es para\n"
	.string "cuatro EntrenadorES con uno o más\l"
	.string "Pokémon cada uno.\p"
	.string "Cada entrenador puede usar\n"
	.string "un Pokémon cada vez.$"

CableClub_Text_ChooseGroupLeaderOfTwo: @ 82792CD
	.string "Un jugador debe ser líder.\p"
	.string "Y el otro, “Unirse\n"
	.string "al Grupo”.$"

CableClub_Text_ChooseGroupLeaderOfFour: @ 8279334
	.string "Un jugador debe ser líder\n"
	.string "del Grupo.\p"
	.string "Y los otros, “Unirse\n"
	.string "al Grupo”.$"

CableClub_Text_ChooseGroupLeader: @ 82793A3
	.string "Un jugador debe ser líder\n"
	.string "del Grupo.\p"
	.string "Y los otros, “Unirse\n"
	.string "al Grupo”.$"

CableClub_Text_WelcomeUnionRoomEnter: @ 827940D
	.string "Ésta es la sala Unión del club\n"
	.string "Inalámbrico Pokémon.\p"
	.string "Aquí puedes comunicarte\n"
	.string "directamente con EntrenadorES\l"
	.string "a los que puede que no conozcas.\p"
	.string "¿Quieres entrar en la sala?$"

CableClub_Text_UnionRoomInfo: @ 82794B8
	.string "Los entrenadores de la sala Unión\n"
	.string "serán los jugadores que tengas\l"
	.string "cerca y hayan entrado en la Sala.\p"
	.string "¡Aquí se pueden hacer muchas\n"
	.string "cosas, empezando por saludarse\l"
	.string "y celebrar el encuentro!\p"
	.string "Puedes registrar dos Pokémon\n"
	.string "de nivel no superior a 30 para\l"
	.string "entablar combates de 1 contra 1.\p"
	.string "También puedes participar en chats$"

CableClub_Text_EnjoyUnionRoom: @ 827961C
	.string "Espero que disfrutes en la sala\n"
	.string "Unión.$"

CableClub_Text_FirstTimeRightThisWay: @ 827964A
	.string "¡Hola!\n"
	.string "Me llamo Teala.\p"
	.string "Es la primera vez que vienes, ¿no?\p"
	.string "Te voy a explicar cómo funciona\n"
	.string "el sistema de comunicación\l"
	.string "inalámbrica.\p"
	.string "Primero, te enseñaré esta planta\n"
	.string "de nuestro Centro Pokémon.\p"
	.string "Por aquí, por favor.$"

CableClub_Text_ExplainWirelessClubFirstTime: @ 8279718
	.string "En el primer piso de los centros\n"
	.string "Pokémon hay dos salas.\p"
	.string "Primero te hablaré de la sala\n"
	.string "de la izquierda: la sala Unión.\p"
	.string "En ella puedes conectarte con los\n"
	.string "EntrenadorES que también\p"
	.string "hayan entrado en la sala Unión\n"
	.string "y estén cerca de ti.\p"
	.string "Con ellos, podrás chatear,\n"
	.string "luchar y realizar intercambios.\p"
	.string "Ahora, la sala de la derecha:\n"
	.string "la <ona directa.\p"
	.string "En ella puedes realizar\n"
	.string "intercambios o enfrentarte a tus\l"
	.string "amigos en combates Pokémon.\p"
	.string "Si el Conector inalámbrico de GBA\n"
	.string "no estuviera conectado, puedes\p"
	.string "conectarte a tus amigos con un\n"
	.string "cable Game Link de Game Boy\l"
	.string "Advance.\p"
	.string "Para ello hay que ir a la Zona\n"
	.string "Directa.\p"
	.string "Espero que disfrutes del sistema\n"
	.string "de comunicación inalámbrica.$"

CableClub_Text_AskAboutLinking: @ 8279937
	.string "¡Hola, {PLAYER}!\p"
	.string "Soy yo, Teala, la recepcionista\n"
	.string "del 1.?? piso del Centro Pokémon.\p"
	.string "¿Necesitas información sobre\n"
	.string "cómo realizar la conexión?$"

CableClub_Text_ExplainWirelessClub: @ 82799AA
	.string "Te voy a explicar cómo funciona\n"
	.string "el club inalámbrico Pokémon.\p"
	.string "Éste es el piso de arriba y tiene\n"
	.string "dos salas.\p"
	.string "Primero te hablaré de la sala\n"
	.string "de la izquierda: la sala Unión.\p"
	.string "En ella puedes conectarte con los\n"
	.string "EntrenadorES que también\p"
	.string "hayan entrado en la sala Unión\n"
	.string "y estén cerca de ti.\p"
	.string "Con ellos, podrás chatear,\n"
	.string "luchar y realizar intercambios.\p"
	.string "Ahora, la sala de la derecha:\n"
	.string "la <ona directa.\p"
	.string "En ella puedes realizar\n"
	.string "intercambios o enfrentarte a tus\l"
	.string "amigos en combates Pokémon.\p"
	.string "Si no encontraras a tus amigos\n"
	.string "en la sala Unión ni en la Zona\l"
	.string "Directa, acercad las consolas.\p"
	.string "Si el Conector inalámbrico de GBA\n"
	.string "no estuviera conectado, puedes\p"
	.string "conectarte a tus amigos con un\n"
	.string "cable Game Link de Game Boy\l"
	.string "Advance.\p"
	.string "Para ello hay que ir a la Zona\n"
	.string "Directa.\p"
	.string "Espero que disfrutes del sistema\n"
	.string "de comunicación inalámbrica.$"

CableClub_Text_HopeYouEnjoyWirelessSystem: @ 8279C91
	.string "Espero que disfrutes del sistema\n"
	.string "de comunicación inalámbrica.$"
