Text_PictureBookShelf: @ 82A81E5
	.string "Hay una colección de libros\n"
	.string "ilustrados de Pokémon.$"

Text_BookShelf: @ 82A820D
	.string "Hay un montón de libros de todo tipo.$"

Text_PokemonCenterBookShelf: @ 82A8232
	.string "¡Son revistas sobre Pokémon!\n"
	.string "“Nuestros amigos Pokémon”…\p"
	.string "“Todo Sobre Los Pokémon”…\n"
	.string "“Esos queridos Pokémon”…$"

Text_Vase: @ 82A8276
	.string "Este jarrón parece caro…\n"
	.string "Voy a echar un ojo dentro…\p"
	.string "Vaya, está vacío…$"

Text_EmptyTrashCan: @ 82A82B3
	.string "No hay nada…$"

Text_ShopShelf: @ 82A82BF
	.string "Los estantes están repletos\n"
	.string "de todo tipo de artículos Pokémon.$"

Text_Blueprint: @ 82A82F7
	.string "¿Y este plano qué puede ser?\n"
	.string "¡Qué cosa tan rara!$"
