@ Contest move effect descriptions

gText_HighlyAppealingMove:: @ 827CB82
	.string "Resulta muy llamativo.$"

gText_UserMoreEasilyStartled:: @ 827CB9B
	.string "Tras usarlo, será fácil\n"
	.string "que te asusten.$"

gText_GreatAppealButNoMoreToEnd:: @ 827CBCE
	.string "Gusta mucho, pero impide\n"
	.string "seguir participando.$"

gText_UsedRepeatedlyWithoutBoringJudge:: @ 827CC03
	.string "Por más que se use, el juez\n"
	.string "no se aburrirá nunca.$"

gText_AvoidStartledByOthersOnce:: @ 827CC34
	.string "Puede evitar que\n"
	.string "te asusten una vez.$"

gText_AvoidStartledByOthers:: @ 827CC5D
	.string "Puede evitar\n"
	.string "que te asusten.$"

gText_AvoidStartledByOthersLittle:: @ 827CC81
	.string "Reduce la probabilidad\n"
	.string "de que te asusten.$"

gText_UserLessLikelyStartled:: @ 827CCAE
	.string "Tras usarlo, será difícil\n"
	.string "que te asusten.$"

gText_SlightlyStartleFrontMon:: @ 827CCE7
	.string "Asusta un poco al Pokémon\n"
	.string "que tengas enfrente.$"

gText_SlightlyStartleAppealed:: @ 827CD0F
	.string "Asusta un poco a los que\n"
	.string "ya se han exhibido.$"

gText_StartleAppealedBeforeUser:: @ 827CD3F
	.string "Asusta al Pokémon que se\n"
	.string "ha exhibido antes que tú.$"

gText_StartleAllAppealed:: @ 827CD73
	.string "Asusta a los Pokémon que\n"
	.string "ya se han exhibido.$"

gText_BadlyStartleFrontMon:: @ 827CDA6
	.string "Aterra al último Pokémon\n"
	.string "que se exhibió.$"

gText_BadlyStartleAppealed:: @ 827CDCB
	.string "Aterra a los que\n"
	.string "ya se han exhibido.$"

gText_StartleAppealedBeforeUser2:: @ 827CDF8
	.string "Asusta al Pokémon que se\n"
	.string "ha exhibido antes que tú.$"

gText_StartleAllAppealed2:: @ 827CE2C
	.string "Asusta a los Pokémon que\n"
	.string "se exhibieron antes que tú.$"

gText_ShiftJudgesAttentionFromOthers:: @ 827CE5F
	.string "Hace que el juez deje de\n"
	.string "prestar atención al resto.$"

gText_StartleMonHasJudgesAttention:: @ 827CE89
	.string "Asusta más al Pokémon que\n"
	.string "capta la atención del Juez.$"

gText_JamOthersMissesTurn:: @ 827CEBE
	.string "Inhibe a los otros,\n"
	.string "pero pierdes un turno.$"

gText_StartleMonsMadeSameTypeAppeal:: @ 827CEEF
	.string "Asusta más a los que usaron\n"
	.string "recursos del mismo tipo.$"

gText_BadlyStartleCoolAppeals:: @ 827CF1E
	.string "Aterra a los que han hecho\n"
	.string "alarde de Carisma.$"

gText_BadlyStartleBeautyAppeals:: @ 827CF4D
	.string "Aterra a los que han hecho\n"
	.string "alarde de Belleza.$"

gText_BadlyStartleCuteAppeals:: @ 827CF7E
	.string "Aterra a los que han hecho\n"
	.string "alarde de Dulzura.$"

gText_BadlyStartleSmartAppeals:: @ 827CFAD
	.string "Aterra a los que han hecho\n"
	.string "alarde de Ingenio.$"

gText_BadlyStartleToughAppeals:: @ 827CFDD
	.string "Aterra a los que han hecho\n"
	.string "alarde de Dureza.$"

gText_MakeMonAfterUserNervous:: @ 827D00D
	.string "Pone nervioso al Pokémon\n"
	.string "que va detrás de ti.$"

gText_MakeAllMonsAfterUserNervous:: @ 827D037
	.string "Inquieta a los Pokémon\n"
	.string "que van detrás de ti.$"

gText_WorsenConditionOfThoseMadeAppeals:: @ 827D061
	.string "Baja la forma de los que\n"
	.string "se han exhibido.$"

gText_BadlyStartleMonsGoodCondition:: @ 827D093
	.string "Aterra a los Pokémon que\n"
	.string "están en buena forma.$"

gText_AppealGreatIfPerformedFirst:: @ 827D0BD
	.string "La exhibición es un éxito\n"
	.string "si se es el primero.$"

gText_AppealGreatIfPerformedLast:: @ 827D0E8
	.string "La exhibición es un éxito\n"
	.string "si se es el último.$"

gText_AppealAsGoodAsThoseBeforeIt:: @ 827D112
	.string "La exhibición es tan buena\n"
	.string "como las anteriores.$"

gText_AppealAsGoodAsOneBeforeIt:: @ 827D13F
	.string "La exhibición es tan buena\n"
	.string "como la anterior.$"

gText_AppealBetterLaterItsPerformed:: @ 827D16E
	.string "Causa mayor impacto cuanto\n"
	.string "más tarde se usa.$"

gText_AppealVariesDependingOnTiming:: @ 827D1A1
	.string "El impacto que tenga varía\n"
	.string "según cuándo se use.$"

gText_WorksWellIfSameTypeAsBefore:: @ 827D1D6
	.string "Funciona bien si es del\n"
	.string "mismo tipo que el anterior.$"

gText_WorksWellIfDifferentTypeAsBefore:: @ 827D20A
	.string "Funciona bien si es de tipo\n"
	.string "distinto que el anterior.$"

gText_AffectedByAppealInFront:: @ 827D23F
	.string "El éxito dependerá de la\n"
	.string "actuación precedente.$"

gText_UpsConditionHelpsPreventNervousness:: @ 827D26E
	.string "Mejora tu forma y te ayuda\n"
	.string "a mantener la calma.$"

gText_AppealWorksWellIfConditionGood:: @ 827D2A3
	.string "Resulta muy lucido\n"
	.string "si estás en buena forma.$"

gText_NextAppealMadeEarlier:: @ 827D2DA
	.string "En la siguiente ronda, deja\n"
	.string "que te exhibas antes.$"

gText_NextAppealMadeLater:: @ 827D309
	.string "En la siguiente ronda, deja\n"
	.string "que te exhibas más tarde.$"

gText_TurnOrderMoreEasilyScrambled:: @ 827D336
	.string "Puede alterar los turnos\n"
	.string "en la siguiente ronda.$"

gText_ScrambleOrderOfNextAppeals:: @ 827D369
	.string "Altera los turnos en la\n"
	.string "siguiente ronda.$"

gText_AppealExcitesAudienceInAnyContest:: @ 827D39A
	.string "Entusiasma al público\n"
	.string "en cualquier Concurso.$"

gText_BadlyStartlesMonsGoodAppeals:: @ 827D3CE
	.string "Aterra a todos los Pokémon\n"
	.string "que se han exhibido bien.$"

gText_AppealBestMoreCrowdExcited:: @ 827D401
	.string "El lucimiento es mayor si\n"
	.string "el público está entregado.$"

gText_TemporarilyStopCrowdExcited:: @ 827D436
	.string "Templa momentáneamente\n"
	.string "el fervor del público.$"

@ Unused move names

gText_RainDance:: @ 827D468
	.string "Danza Lluvia$"

gText_Rage:: @ 827D473
	.string "Furia$"

gText_FocusEnergy:: @ 827D478
	.string "Foco Energía$"

gText_Hypnosis:: @ 827D485
	.string "Hipnosis$"

gText_Softboiled:: @ 827D48E
	.string "Amortiguador$"

gText_HornAttack:: @ 827D499
	.string "Cornada$"

gText_SwordsDance:: @ 827D4A5
	.string "Danza Espada$"

gText_Conversion:: @ 827D4B2
	.string "Conversión$"

gText_SunnyDay:: @ 827D4BD
	.string "Día Soleado$"

gText_Rest2:: @ 827D4C7
	.string "Descanso$"

gText_Vicegrip:: @ 827D4CC
	.string "Agarre$"

gText_DefenseCurl:: @ 827D4D5
	.string "Rizo Defensa$"

gText_LockOn:: @ 827D4E2
	.string "Fijar Blanco$"

@ Contest type names

gContestMoveTypeCoolText:: @ 827D4EA
	.string "Caris.$"

gContestMoveTypeBeautyText:: @ 827D4EF
	.string "Bell.$"

gContestMoveTypeCuteText:: @ 827D4F6
	.string "Dulz.$"

gContestMoveTypeSmartText:: @ 827D4FB
	.string "Ingen.$"

gContestMoveTypeToughText:: @ 827D501
	.string "Dureza$"

gText_AppealNumWhichMoveWillBePlayed:: @ 827D507
	.string "¡Exhibición n.º {STR_VAR_1}!\n"
	.string "¿Qué ataque vas a usar?$"

gText_AppealNumButItCantParticipate:: @ 827D531
	.string "¡Exhibición n.º {STR_VAR_1}!\n"
	.string "¡Pero no puede participar!$"

gText_MonAppealedWithMove:: @ 827D55A
	.string "¡{STR_VAR_1} se exhibe\n"
	.string "con {STR_VAR_2}!$"

gText_MonWasWatchingOthers:: @ 827D56F
	.string "{STR_VAR_1} estaba\n"
	.string "mirando a los otros.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AllOutOfAppealTime:: @ 827D597
	.string "¡Se ha acabado el tiempo\n"
	.string "de exhibición!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

@ Unused appeal result texts

gText_ButAppealWasJammed:: @ 827D5C1
	.string "Pero han inhibido\n"
	.string "la exhibición.$"

gText_FollowedAnotherMonsLead:: @ 827D5DC
	.string "Sigue el ejemplo\n"
	.string "de otro Pokémon.$"

gText_ButItMessedUp:: @ 827D600
	.string "Pero se hizo un lío.$"

gText_WentBetterThanUsual:: @ 827D612
	.string "Ha funcionado mejor\n"
	.string "que otras veces.$"

gText_JudgeLookedAwayForSomeReason:: @ 827D62D
	.string "El Juez se ha distraído\n"
	.string "con algo.$"

gText_WorkedHardToBuildOnPastMistakes:: @ 827D654
	.string "Se ha esforzado mucho\n"
	.string "para no repetir errores.$"

gText_CantMakeAnyMoreMoves:: @ 827D67E
	.string "No puede hacer\n"
	.string "más movimientos.$"

gText_WorkedFrighteninglyWell:: @ 827D69C
	.string "Funcionó de maravilla.$"

gText_WorkedHardAsStandoutMon:: @ 827D6BA
	.string "Lo hizo tan bien como\n"
	.string "el Pokémon en cabeza.$"

gText_JudgedLookedOnExpectantly:: @ 827D6E5
	.string "El Juez observa\n"
	.string "muy interesado.$"

gText_WorkedRatherWell:: @ 827D706
	.string "Funcionó bastante bien.$"

gText_WorkedLittleBetterThanUsual:: @ 827D71D
	.string "Funcionó un poco mejor\n"
	.string "que de costumbre.$"

@ Round result texts

gText_MonFailedToStandOutAtAll:: @ 827D743
	.string "{STR_VAR_1} no ha\n"
	.string "destacado en absoluto…{PAUSE_UNTIL_PRESS}$"

gText_MonDidntStandOutVeryMuch:: @ 827D764
	.string "{STR_VAR_1} no ha\n"
	.string "destacado mucho…{PAUSE_UNTIL_PRESS}$"

gText_MonCaughtALittleAttention:: @ 827D785
	.string "{STR_VAR_1} ha llamado\n"
	.string "algo la atención.{PAUSE_UNTIL_PRESS}$"

gText_MonAttractedALotOfAttention:: @ 827D7A5
	.string "{STR_VAR_1} logró atraer\n"
	.string "mucho la atención.{PAUSE_UNTIL_PRESS}$"

gText_MonCommandedTotalAttention:: @ 827D7C8
	.string "{STR_VAR_1} ha logrado\n"
	.string "atraer toda la atención.{PAUSE_UNTIL_PRESS}$"

gText_MonHasntMadeItsAppeal:: @ 827D7E8
	.string "{STR_VAR_1} no se ha\n"
	.string "exhibido.{PAUSE_UNTIL_PRESS}$"

@ Unused
gText_AnticipationSwelledForMonsAppealNext2:: @ 827D805
	.string "La anticipación aumentó \n"
	.string "por el atractivo de{STR_VAR_1}\n"
	.string "a continuación..$"

gText_EmptyContestString:: @ 827D830
	.string "$"

gText_JudgesViewsOnMonHeldFirm:: @ 827D831
	.string "La opinión del juez sobre\n"
	.string "{STR_VAR_1} es firme.$"

gText_MonsXChangedPerceptions:: @ 827D855
	.string "La {STR_VAR_3} de {STR_VAR_1}\n"
	.string "cambió las percepciones.$"

gText_MonsAppealEffectWoreOff:: @ 827D872
	.string "El efecto de la exhibición\n"
	.string "de {STR_VAR_1} ha pasado.$"

gText_SpecialAppealsEffectWoreOff:: @ 827D88F
	.string "El efecto de la exhibición\n"
	.string "especial ha pasado.$"

gText_EveryonesAppealsMadeToLookSame:: @ 827D8B5
	.string "Las exhibiciones de todos\n"
	.string "parecieron la misma.$"

gText_CheapenedMonsAppeal:: @ 827D8E4
	.string "El movimiento de\n"
	.string "{STR_VAR_2} lució menos.$"

gText_CheapenedAppealOfThoseAhead:: @ 827D8FE
	.string "Deslució las exhibiciones\n"
	.string "de los otros.$"

gText_StoleAttentionAwayFromMon:: @ 827D926
	.string "Acaparó la atención\n"
	.string "de {STR_VAR_2}.$"

gText_CheapenedMonsAppeal2:: @ 827D947
	.string "El movimiento de\n"
	.string "{STR_VAR_2} lució menos.$"

gText_SeverelyCheapenedOtherAppeals:: @ 827D961
	.string "Deslució mucho\n"
	.string "las otras exhibiciones.$"

gText_AnticipationSwelledForMonsAppealNext:: @ 827D986
	.string "El público espera ansioso\n"
	.string "el ataque de {STR_VAR_1}.$"

gText_CheapenedAppealOfThoseAhead2:: @ 827D9B1
	.string "Deslució las exhibiciones\n"
	.string "de los más aventajados.$"

gText_CheapenedJudgesFavoriteAppeal:: @ 827D9D9
	.string "Deslució el movimiento\n"
	.string "favorito del Juez.$"

gText_AppealsOfOthersCheapenedByHalf:: @ 827DA03
	.string "Los movimientos de\n"
	.string "los otros lucen la mitad.$"

gText_StoodOutToMakeUpForBeingJammed:: @ 827DA31
	.string "Se lució para compensar\n"
	.string "la inhibición anterior.$"

gText_CantParticipateInAppealsAnyMore:: @ 827DA5B
	.string "No puede seguir\n"
	.string "exhibiéndose.$"

gText_TouchedJudgeForFantasticAppeal:: @ 827DA85
	.string "Su fantástica exhibición\n"
	.string "conmovió al Juez.$"

gText_AnticipationRoseForUpcomingAppeals:: @ 827DAB2
	.string "El público espera ansioso\n"
	.string "las próximas exhibiciones.$"

gText_StoodOutAsMuchAsSpecialAppeals:: @ 827DADA
	.string "Ha gustado tanto como\n"
	.string "una exhibición especial.$"

gText_StoodOutAsMuchAsMon:: @ 827DB03
	.string "Ha gustado tanto como\n"
	.string "{STR_VAR_1}.$"

gText_JammedAppealsMadeEvenLessNoticeable:: @ 827DB1F
	.string "Deslució aún más las\n"
	.string "exhibiciones inhibidas.$"

gText_EveryonesAppealsMadeSame:: @ 827DB4E
	.string "Los movimientos de todos\n"
	.string "resultaron iguales.$"

@ Appeal result texts

gText_BecameMoreConsciousOfOtherMons:: @ 827DB75
	.string "Está más atento\n"
	.string "a los otros Pokémon.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCantMakeAnAppealAfterThis:: @ 827DBB0
	.string "{STR_VAR_1} no puede\n"
	.string "volver a exhibirse.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_SettledDownJustLittleBit:: @ 827DBE0
	.string "Se ha relajado\n"
	.string "un poco.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_BecameObliviousToOtherMons:: @ 827DC0F
	.string "Ignora la presencia\n"
	.string "de los otros Pokémon.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_BecameLessAwareOfOtherMons:: @ 827DC45
	.string "Se fija menos\n"
	.string "en los otros Pokémon.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_StoppedCaringAboutOtherMons:: @ 827DC7C
	.string "Ha dejado de preocuparse\n"
	.string "por los otros Pokémon.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_TriedToStartleOtherMons:: @ 827DCB4
	.string "Intentó asustar\n"
	.string "a los otros Pokémon.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_TriedToDazzleOthers:: @ 827DCE7
	.string "Intentó deslumbrar\n"
	.string "a los otros Pokémon.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_JudgeLookedAwayFromMon:: @ 827DD12
	.string "El Juez desvió la mirada\n"
	.string "de {STR_VAR_1}.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_TriedToUnnerveNextMon:: @ 827DD3D
	.string "Intentó poner nervioso\n"
	.string "al siguiente Pokémon.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonBecameNervous:: @ 827DD6F
	.string "{STR_VAR_1} se ha puesto\n"
	.string "nervioso.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealTriedToUnnerveWaitingMons:: @ 827DD8E
	.string "Intentó intranquilizar\n"
	.string "a los Pokémon siguientes.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_TauntedMonsDoingWell:: @ 827DDC7
	.string "Se burló de los que\n"
	.string "están haciéndolo bien.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonRegainedItsForm:: @ 827DDF2
	.string "{STR_VAR_1} recuperó\n"
	.string "su forma.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_TriedToJamMonDoingWell:: @ 827DE14
	.string "Intentó inhibir a los que\n"
	.string "están haciéndolo bien.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_StandoutMonHustledEvenMore:: @ 827DE44
	.string "{STR_VAR_1}, ya en cabeza,\n"
	.string "destacó aún más.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_LargelyUnnoticedMonWorkedHard:: @ 827DE73
	.string "El ignorado {STR_VAR_1}\n"
	.string "se ha esforzado mucho.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_WorkedAsMuchAsMonBefore:: @ 827DEA5
	.string "Se esforzó igual que\n"
	.string "los Pokémon anteriores.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsAppealDidNotGoWell:: @ 827DED9
	.string "El ataque de {STR_VAR_1}\n"
	.string "no funcionó bien.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_WorkedAsMuchAsPrecedingMon:: @ 827DF02
	.string "Se esforzó tanto como\n"
	.string "los Pokémon anteriores.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsAppealDidNotGoWell2:: @ 827DF3A
	.string "El ataque de {STR_VAR_1}\n"
	.string "no funcionó bien.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsAppealDidNotGoWell3:: @ 827DF63
	.string "El ataque de {STR_VAR_1}\n"
	.string "no funcionó bien.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsAppealWentSlightlyWell:: @ 827DF8C
	.string "El ataque de {STR_VAR_1}\n"
	.string "funcionó algo.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsAppealWentPrettyWell:: @ 827DFB8
	.string "El ataque de {STR_VAR_1}\n"
	.string "funcionó bastante bien.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsAppealWentExcellently:: @ 827DFE2
	.string "El ataque de {STR_VAR_1}\n"
	.string "funcionó de maravilla.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsAppealWasDud:: @ 827E00C
	.string "El ataque de {STR_VAR_1}\n"
	.string "fue un fracaso.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsAppealDidNotWorkVeryWell:: @ 827E02F
	.string "El ataque de {STR_VAR_1}\n"
	.string "no funcionó muy bien.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsAppealWentSlightlyWell2:: @ 827E05F
	.string "El ataque de {STR_VAR_1}\n"
	.string "funcionó algo.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsAppealWentPrettyWell2:: @ 827E08B
	.string "El ataque de {STR_VAR_1}\n"
	.string "funcionó bastante bien.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsAppealWentVeryWell:: @ 827E0B5
	.string "El ataque de {STR_VAR_1}\n"
	.string "funcionó muy bien.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsAppealWentExcellently2:: @ 827E0DD
	.string "El ataque de {STR_VAR_1}\n"
	.string "funcionó de maravilla.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_SameTypeAsOneBeforeGood:: @ 827E107
	.string "El tipo es igual que el del\n"
	.string "Pokémon anterior. ¡Bien!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_NotSameTypeAsOneBeforeGood:: @ 827E143
	.string "Es de distinto tipo al del\n"
	.string "Pokémon anterior. ¡Bien!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_StoodOutMuchMoreThanMonBefore:: @ 827E17F
	.string "Ha gustado mucho más que\n"
	.string "el del Pokémon anterior.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_DidntDoAsWellAsMonBefore:: @ 827E1BB
	.string "No ha gustado tanto como\n"
	.string "el del Pokémon anterior.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsConditionRoseAboveUsual:: @ 827E1F3
	.string "La forma de {STR_VAR_1}\n"
	.string "aumenta de forma inusual.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsHotStatusMadeGreatAppeal:: @ 827E220
	.string "¡Gran exhibición gracias\n"
	.string "al estado de {STR_VAR_1}!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MovedUpInLineForNextAppeal:: @ 827E254
	.string "Se exhibirá antes\n"
	.string "en el turno siguiente.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MovedBackInLineForNextAppeal:: @ 827E289
	.string "Se exhibirá más tarde\n"
	.string "en el turno siguiente.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ScrambledUpOrderForNextTurn:: @ 827E2C5
	.string "Ha alterado el orden\n"
	.string "del turno siguiente.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_JudgeLookedAtMonExpectantly:: @ 827E2FE
	.string "El Juez miró a {STR_VAR_1}\n"
	.string "interesado.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverWell:: @ 827E32E
	.string "El combo de exhibición\n"
	.string "funcionó bien.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverVeryWell:: @ 827E35B
	.string "El combo de exhibición\n"
	.string "funcionó muy bien.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverExcellently:: @ 827E38D
	.string "El combo de exhibición\n"
	.string "funcionó de maravilla.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonManagedToAvertGaze:: @ 827E3C1
	.string "{STR_VAR_1} consiguió\n"
	.string "desviar la mirada.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonManagedToAvoidSeeingIt:: @ 827E3EB
	.string "{STR_VAR_1} consiguió\n"
	.string "evitar verlo.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonIsntFazedByThatSortOfThing:: @ 827E416
	.string "Esto no ha afectado\n"
	.string "a {STR_VAR_1}.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonBecameALittleDistracted:: @ 827E448
	.string "{STR_VAR_1} se distrajo\n"
	.string "un poco.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_TriedToStartleOtherPokemon:: @ 827E473
	.string "Intentó asustar\n"
	.string "a los otros Pokémon.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonLookedDownOutOfDistraction:: @ 827E4A6
	.string "{STR_VAR_1} miró hacia\n"
	.string "abajo distraído.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonTurnedBackOutOfDistraction:: @ 827E4D5
	.string "{STR_VAR_1} se giró\n"
	.string "distraído.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCouldntHelpUtteringCry:: @ 827E504
	.string "{STR_VAR_1} no pudo\n"
	.string "evitar dar un grito.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCouldntHelpLeapingUp:: @ 827E531
	.string "{STR_VAR_1} no pudo\n"
	.string "evitar dar un salto.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonTrippedOutOfDistraction:: @ 827E55A
	.string "{STR_VAR_1}, distraído,\n"
	.string "tropezó y se cayó.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonWasTooNervousToMove:: @ 827E58A
	.string "{STR_VAR_1} no se pudo\n"
	.string "mover de puro nervio.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItMessedUp2:: @ 827E5B2
	.string "Pero se hizo un lío.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItFailedToMakeTargetNervous:: @ 827E5D0
	.string "Pero no consiguió poner\n"
	.string "nervioso a su adversario.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItFailedToMakeAnyoneNervous:: @ 827E606
	.string "Pero no consiguió poner\n"
	.string "a nadie nervioso.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItWasIgnored:: @ 827E638
	.string "Pero fue ignorado.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_CouldntImproveItsCondition:: @ 827E658
	.string "Pero no pudo mejorar\n"
	.string "su forma.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_BadConditionResultedInWeakAppeal:: @ 827E68B
	.string "Su exhibición fue mala\n"
	.string "debido a su baja forma.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonWasUnaffected:: @ 827E6C4
	.string "{STR_VAR_1} no se vio\n"
	.string "afectado.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_RepeatedAppeal:: @ 827E6E3
	.string "{STR_VAR_1} decepcionó\n"
	.string "al repetir su exhibición.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXWentOverGreat:: @ 827E717
	.string "{STR_VAR_3} de\n"
	.string "{STR_VAR_1} fue increíble.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXDidntGoOverWell:: @ 827E73C
	.string "{STR_VAR_3} de\n"
	.string "{STR_VAR_1} no funcionó.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXGotTheCrowdGoing:: @ 827E76A
	.string "¡{STR_VAR_3} de\n"
	.string "{STR_VAR_1} hizo furor!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCantAppealNextTurn:: @ 827E793
	.string "{STR_VAR_1} no puede usar\n"
	.string "el próximo turno.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AttractedCrowdsAttention:: @ 827E7BA
	.string "Atrajo la atención\n"
	.string "del público.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_CrowdContinuesToWatchMon:: @ 827E7EA
	.string "El público sigue\n"
	.string "observando a {STR_VAR_3}.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsMoveIsIgnored:: @ 827E817
	.string "{STR_VAR_2} de\n"
	.string "{STR_VAR_1} fue ignorado.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_Contest_Shyness:: @ 827E837
	.string "timidez$"

gText_Contest_Anxiety:: @ 827E83F
	.string "ansiedad$"

gText_Contest_Laziness:: @ 827E847
	.string "pereza$"

gText_Contest_Hesitancy:: @ 827E850
	.string "indecisión$"

gText_Contest_Fear:: @ 827E85A
	.string "miedo$"

gText_Contest_Coolness:: @ 827E85F
	.string "El carisma$"

gText_Contest_Beauty:: @ 827E868
	.string "La belleza$"

gText_Contest_Cuteness:: @ 827E86F
	.string "La dulzura$"

gText_Contest_Smartness:: @ 827E878
	.string "El ingenio$"

gText_Contest_Toughness:: @ 827E882
	.string "La dureza$"

@ Unused
gText_Tension:: @ 827E88C
	.string "Tensión$"

gText_CoolMove:: @ 827E894
	.string "M. Carisma$"

gText_BeautyMove:: @ 827E89E
	.string "M. Belleza$"

gText_CuteMove:: @ 827E8AA
	.string "M. Dulzura$"

gText_SmartMove:: @ 827E8B4
	.string "M. Ingenio$"

gText_ToughMove:: @ 827E8BF
	.string "M. Dureza$"

gText_3QuestionMarks:: @ 827E8CA
	.string "???$"
