EventTicket_Text_ShowOldSeaMap: @ 82A6848
	.string "El ferry para CIUDAD PORTUAL va a…\p"
	.string "¿Disculpa? ¿Que si podemos\n"
	.string "viajar a este punto del mapa?\p"
	.string "Conozco a alguien que puede ayudarte.\n"
	.string "Espera un momento.$"

EventTicket_Text_ThatPass: @ 82A68D2
	.string "El ferry para ciudad Portual va a…\p"
	.string "¿Eh?\n"
	.string "Ese ticket…$"

EventTicket_Text_ShowEonTicket: @ 82A68FC
	.string "Eh, oye, ¿tú eres quien trajo ese\n"
	.string "Ticket más raro que un perro verde?\p"
	.string "Te voy a decir una cosa: intentas llegar\n"
	.string "a una islita perdida en un mar del sur.\p"
	.string "Ni idea de lo que puede haber allí,\n"
	.string "oye… ¡Me da escalofríos pensarlo!\p"
	.string "¡Todos a bordo!$"

EventTicket_Text_SouthernIslandSailBack: @ 82A69F1
	.string "Eh, oye, no hay absolutamente nada que\n"
	.string "hacer en esta isla perdida en el mar.\p"
	.string "¿Y si volvemos a Calagua?$"

EventTicket_Text_SailHome: @ 82A6A5D
	.string "¡Estupendo!\n"
	.string "¡Rumbo a casa!$"

EventTicket_Text_AsYouLike: @ 82A6A82
	.string "Bah, bueno, tú sabrás lo que quieres…$"

SouthernIsland_Interior_Text_Sign: @ 82A6AA1
	.string "“Los sueños son un mundo aparte.\n"
	.string "Recuérdalo…”$"

SouthernIsland_Exterior_Text_Sign: @ 82A6AD5
	.string "“Si quieres evitar olvidar tus\n"
	.string "recuerdos, guárdalos en el corazón…”$"
