EventTicket_Text_OldSeaMapTooFar: @ 82C68A5
	.string "Eh, tú, ¿cómo va eso?\p"
	.string "¿Qué, eres tú quien se supone que tiene\n"
	.string "ese viejo mapa gusarapiento?\p"
	.string "Echémosle un vistazo, pues.\n"
	.string "Mmmm… \p"
	.string "¡Oye, eso está a muchas leguas de aquí!\n"
	.string "Creo que no podré ayudarte…$"

EventTicket_Text_BrineyHoldOnASecond: @ 82C6951
	.string "Cap. Arenque: ¡Alto ahí!\p"
	.string "¿Cómo me atrevo a defraudar\n"
	.string "a alguien a quien le debo tanto?…$"

EventTicket_Text_BrineyLetsSail: @ 82C69AA
	.string "{PLAYER}{KUN}, perdóname.\p"
	.string "Has venido aquí pidiéndome ayuda,\n"
	.string "y a punto he estado de no dártela.\p"
	.string "Hagamos lo que es justo.\p"
	.string "¡Zarparemos ahora mismo, por supuesto!\p"
	.string "¡Vamos a buscar esa isla\n"
	.string "en el Mapa Viejo!$"

EventTicket_Text_OddTicketGetOnBoard: @ 82C6A71
	.string "¿Eres tú quien trajo ese extraño\n"
	.string "ticket?\p"
	.string "El lugar al que tratas de llegar\n"
	.string "es una isla muy, muy lejana.\p"
	.string "Nadie sabe lo que puede haber allí…\p"
	.string "¡Pero, solo de pensarlo, has despertado\n"
	.string "al besugo curioso que llevo dentro!\p"
	.string "¡Sube a bordo, anda!$"

FarawayIsland_Entrance_Text_SailorReturn: @ 82C6B42
	.string "Los cambios de opinión del Cap. Arenque\n"
	.string "pueden llegar a ser tan exasperantes…\p"
	.string "¿Quieres regresar a Calagua?$"

BirthIsland_Harbor_Text_SailorReturn: @ 82C6B90
	.string "Qué forma más rara tiene esta isla,\n"
	.string "¿no te parece?\p"
	.string "¿Quieres regresar a Calagua?$"

EventTicket_Text_OddTicketsWhereTo: @ 82C6BD4
	.string "¿Eres tú quien trajo esos extraños\n"
	.string "tickets?\p"
	.string "Mmm…\p"
	.string "Esos tickets te llevarán a islas muy,\n"
	.string "muy lejanas.\p"
	.string "Nadie sabe lo que puede haber en ellas…\p"
	.string "¡Pero, solo de pensarlo, has despertado\n"
	.string "al besugo curioso que llevo dentro!\p"
	.string "¡Sube a bordo!\n"
	.string "¿Qué rumbo tomamos primero?$"

NavelRock_Harbor_Text_SailorReturn: @ 82C6CE6
	.string "Lo… ¡¿Lo has oído?!\n"
	.string "Ese gran gruñido que ha salido de ahí…\p"
	.string "¿Seguro que no nos pasará nada?\n"
	.string "¿No crees que deberíamos volver?$"

FarawayIsland_Entrance_Text_Sign: @ 82C6D5A
	.string "Las letras están borrosas… como\n"
	.string "si las hubiesen escrito hace mucho…\p"
	.string "“Día 6 de …mbre\n"
	.string "Si un huma… vuelve aqu… alguna\l"
	.string "vez …guro que tend… gran coraz…\l"
	.string "…on esa esper…, me march…”$"

FarawayIsland_Interior_Text_Mew: @ 82C6DFF
	.string "Miuu…$"
