@ Battle Tower
gText_AnabelWonSilver:: @ 82C843F
	.string "Qué lástima…$"

gText_AnabelDefeatSilver:: @ 82C8458
	.string "Vale, lo he entendido…$"

gText_AnabelWonGold:: @ 82C846C
	.string "Lo siento mucho…$"

gText_AnabelDefeatGold:: @ 82C8480
	.string "Gracias…$"

@ Battle Dome
gText_TuckerWonSilver:: @ 82C848B
	.string "¡Ja, ja, ja! ¿No te da vergüenza?\n"
	.string "¡Están todos mirando!$"

gText_TuckerDefeatSilver:: @ 82C84C1
	.string "Grr…\n"
	.string "Pero cómo…$"

gText_TuckerWonGold:: @ 82C84D0
	.string "¡Por algo soy el Astro de la Cúpula!$"

gText_TuckerDefeatGold:: @ 82C84F7
	.string "¡Ja, ja, ja!\n"
	.string "¡Eres una fuente de inspiración!$"

@ Battle Factory
gText_NolandWonSilver:: @ 82C8512
	.string "¡Vas a tener que esforzarte más!\n"
	.string "Te he dado una buena lección, ¿eh?$"

gText_NolandDefeatSilver:: @ 82C853B
	.string "¡Buen trabajo!\n"
	.string "¡Parece que sabes lo que haces!$"

gText_NolandWonGold:: @ 82C8561
	.string "¡Je, je, je!\n"
	.string "¿Ya has terminado?$"

gText_NolandDefeatGold:: @ 82C8589
	.string "¿Qué ha pasado aquí?$"

@ Battle Pike
gText_LucyWonSilver:: @ 82C859D
	.string "Bah…$"

gText_LucyDefeatSilver:: @ 82C85A4
	.string "Mmm…$"

gText_LucyWonGold:: @ 82C85A9
	.string "¡Ja!$"

gText_LucyDefeatGold:: @ 82C85AE
	.string "¡Grr!$"

@ Battle Arena
gText_GretaWonSilver:: @ 82C85B4
	.string "¡Anda, vamos!\n"
	.string "¡Tendrás que esforzarte más!$"

gText_GretaDefeatSilver:: @ 82C85E3
	.string "¡Increíble!\n"
	.string "¡Buen trabajo!$"

gText_GretaWonGold:: @ 82C85F5
	.string "¡Je, je, je!\n"
	.string "¿Qué esperabas?$"

gText_GretaDefeatGold:: @ 82C8611
	.string "¿Eh?\n"
	.string "¡¿En serio que he perdido?!$"

@ Battle Palace
gText_SpenserWonSilver:: @ 82C8628
	.string "¡Los Pokémon son endebles\n"
	.string "si su Entrenador es endeble!$"

gText_SpenserDefeatSilver:: @ 82C8662
	.string "Ah…\n"
	.string "Así son las cosas…$"

gText_SpenserWonGold:: @ 82C8682
	.string "¡Ja, ja, ja!\n"
	.string "¡No tenemos nada que temer!$"

gText_SpenserDefeatGold:: @ 82C86B3
	.string "¡Bah!\n"
	.string "¡Pues sí que!$"

@ Battle Pyramid
gText_BrandonWonSilver:: @ 82C86C3
	.string "¡Eh! ¿Qué te pasa?\n"
	.string "¡No te esfuerzas nada! ¡Venga!$"

gText_BrandonDefeatSilver:: @ 82C86FE
	.string "¡Ya está! ¡Lo has hecho genial!\n"
	.string "¡Te lo has currado, sí, señor!$"

gText_BrandonWonGold:: @ 82C8739
	.string "¡Eh! ¡No te rindas ahora!\n"
	.string "¡Venga! ¡No pierdas la fe en ti!$"

gText_BrandonDefeatGold:: @ 82C877B
	.string "¡Ya está! ¡Lo lograste!\n"
	.string "¡Esto es por lo que has luchado!$"
