LilycoveCity_DepartmentStore_1F_Text_LotteryCornerDrawTicket: @ 82A6390
	.string "Éste es el despacho de lotería\n"
	.string "Pokémon.\p"
	.string "Todos los clientes de nuestro centro\n"
	.string "comercial pueden sacar un billete\l"
	.string "de lotería Pokémon.\p"
	.string "Si el número del billete de lotería\n"
	.string "coincide con el del ID de uno de tus\l"
	.string "Pokémon, ganas un gran premio.\p"
	.string "¿Quieres sacar un billete\n"
	.string "de lotería Pokémon?$"

LilycoveCity_DepartmentStore_1F_Text_ComeBackTomorrow: @ 82A6496
	.string "Vuelve mañana, por favor.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain: @ 82A64B1
	.string "Vuelve cuando quieras.$"

LilycoveCity_DepartmentStore_1F_Text_PleasePickTicket: @ 82A64C8
	.string "Elige un billete de lotería.\n"
	.string "A ver… {PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}… {PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

LilycoveCity_DepartmentStore_1F_Text_TicketNumberIsXPleaseWait: @ 82A650B
	.string "El número del billete de lotería\n"
	.string "es {STR_VAR_1}.\p"
	.string "Debo comprobar si este número coincide\n"
	.string "con el del ID de alguno de tus Pokémon.\l"
	.string "Espera un momento.$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPartyMon: @ 82A6592
	.string "¡Felicidades!\p"
	.string "El número ID del {STR_VAR_1} de tu\n"
	.string "equipo coincide con el número del\l"
	.string "billete de lotería.$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPCMon: @ 82A65E6
	.string "¡Felicidades!\p"
	.string "El número ID del {STR_VAR_1} de una\n"
	.string "caja de tu PC coincide con el número\l"
	.string "del billete de lotería.$"

LilycoveCity_DepartmentStore_1F_Text_NoNumbersMatched: @ 82A663C
	.string "Lo siento.\n"
	.string "No coincide ningún número.$"

LilycoveCity_DepartmentStore_1F_Text_TwoDigitsMatched: @ 82A6664
	.string "Coincidían dos dígitos, así que has\n"
	.string "ganado el tercer premio.\l"
	.string "¡Un magnífico {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_ThreeDigitsMatched: @ 82A66A7
	.string "Coincidían tres dígitos, así que has\n"
	.string "ganado el segundo premio.\l"
	.string "¡Un magnífico {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_FourDigitsMatched: @ 82A66ED
	.string "Coincidían cuatro dígitos, así que\n"
	.string "has ganado el primer premio.\l"
	.string "¡Un magnífico {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_AllFiveDigitsMatched: @ 82A6731
	.string "¡Guau! ¡Coinciden los cinco dígitos!\p"
	.string "¡Has ganado el premio gordo!\n"
	.string "¡Un magnífico {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_NoRoomForThis: @ 82A678C
	.string "¿Eh?\n"
	.string "Se diría que no tienes sitio para esto.\p"
	.string "Haz un hueco en la mochila\n"
	.string "y vuelve por aquí.$"

LilycoveCity_DepartmentStore_1F_Text_PrizeWeveBeenHolding: @ 82A67E1
	.string "¿{PLAYER}?\n"
	.string "Sí, te estaba esperando.\p"
	.string "Tenía este premio guardado para ti.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain2: @ 82A6831
	.string "Vuelve cuando quieras.$"
