MatchCall_WildBattleText1:: @ 82A971C
	.string "¡Eh! ¡Hola, {PLAYER}{KUN}!\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Hace un rato, vi un {STR_VAR_2},\n"
	.string "pero no pude hacerme con él.\p"
	.string "¡Me faltó tan poco!\n"
	.string "¡En fin, hasta luego!$"

MatchCall_WildBattleText2:: @ 82A9798
	.string "¡Eh! ¡Hola, {PLAYER}{KUN}!\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Intenté atrapar un {STR_VAR_2}\n"
	.string "ideal hace un rato.\p"
	.string "¡Pero se me escapó!\n"
	.string "¡Me llevé un chasco!\p"
	.string "¡Bueno, nos vemos!$"

MatchCall_WildBattleText3:: @ 82A9813
	.string "¡Eh, oye, {PLAYER}!\n"
	.string "Soy yo, {STR_VAR_1}.\p"
	.string "He estado a puntito de atrapar\n"
	.string "un {STR_VAR_2}, pero nada.\p"
	.string "¡Casi me hago con él!\p"
	.string "Me ha fastidiado el día…\n"
	.string "Bueno, nos vemos.$"

MatchCall_WildBattleText4:: @ 82A98A8
	.string "Eh, {PLAYER}{KUN}.\n"
	.string "Oye, soy {STR_VAR_1}.\p"
	.string "¿Conoces al Pokémon {STR_VAR_2}?\n"
	.string "Casi me hago con uno.\p"
	.string "Ha sido hace un momento.\n"
	.string "Pensé que lo tenía, pero no.\p"
	.string "Si lo vuelvo a ver, te aseguro\n"
	.string "que no se me escapa.\p"
	.string "Bueno, ya hablaremos.$"

MatchCall_WildBattleText5:: @ 82A9977
	.string "¡{PLAYER}{KUN}! ¿Qué tal?\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Te has hecho con algún Pokémon\n"
	.string "últimamente?\p"
	.string "Hace poco, estuve a nada\n"
	.string "y menos de hacerme con uno.\p"
	.string "¡Bueno, hasta otra!$"

MatchCall_WildBattleText6:: @ 82A99FD
	.string "¡{PLAYER}{KUN}! ¿Qué tal?\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Te has hecho con algún Pokémon\n"
	.string "últimamente?\p"
	.string "El otro día, casi me hago con uno,\n"
	.string "pero se me escapó no sé cómo.\p"
	.string "Bueno, cuídate.$"

MatchCall_WildBattleText7:: @ 82A9A78
	.string "Eh…, ¿{PLAYER}{KUN}?\n"
	.string "Hola, soy {STR_VAR_1}.\p"
	.string "¡Ay, espera, espera! ¡Estoy a\n"
	.string "punto de atrapar un {STR_VAR_2}!…\p"
	.string "¡Aaarrrg! ¡Ha salido por patas!\n"
	.string "¡Por qué poco!$"

MatchCall_WildBattleText8:: @ 82A9AE8
	.string "Eh, {PLAYER}{KUN}, ¿qué tal vas?\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Te ha ido bien atrapando\n"
	.string "Pokémon últimamente?\p"
	.string "Yo casi me hago con uno,\n"
	.string "pero logró escapar.\p"
	.string "¡Tendré que intentarlo otra vez!\n"
	.string "¡Nos vemos!$"

MatchCall_WildBattleText9:: @ 82A9BA7
	.string "¡Anda, {PLAYER}{KUN}, hola!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "¿Qué?\n"
	.string "¿Tienes ya muchos Pokémon?\p"
	.string "¡Yo me estoy cansando un poco ya!\n"
	.string "¡Se me escapan todos!\p"
	.string "¡Nos vemos!$"

MatchCall_WildBattleText10:: @ 82A9C36
	.string "Eh, {PLAYER}{KUN}, hola…\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Mira, he estado a nada de pillar\n"
	.string "un {STR_VAR_2}…\p"
	.string "Pero me he quedado sin él…\p"
	.string "Tendré que intentarlo de nuevo.\n"
	.string "Nos vemos.$"

MatchCall_WildBattleText11:: @ 82A9CC8
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Qué tal te van las cosas?\p"
	.string "He querido atrapar un {STR_VAR_2}\n"
	.string "salvaje antes, pero se me ha ido.\p"
	.string "Me siento fatal…$"

MatchCall_WildBattleText12:: @ 82A9D44
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy yo, {STR_VAR_1}.\p"
	.string "¿Sigues atrapando Pokémon?\p"
	.string "Yo he estado intentando atrapar\n"
	.string "algunos, pero no es nada fácil.\p"
	.string "¡Esto de los Pokémon tiene\n"
	.string "su miga!$"

MatchCall_WildBattleText13:: @ 82A9DD7
	.string "¡Ah, hola, {PLAYER}{KUN}!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "¿Has estado atrapando Pokémon?\p"
	.string "Yo lo he estado intentando,\n"
	.string "pero no he tenido éxito.\p"
	.string "¡Esto de los Pokémon tiene\n"
	.string "su miga!$"

MatchCall_WildBattleText14:: @ 82A9E70
	.string "¡Eh, {PLAYER}{KUN}! ¿Qué tal?\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Ahora mismo, he intentado\n"
	.string "atrapar un {STR_VAR_2}.\p"
	.string "¡Pero se me ha escapado!\n"
	.string "¡Se me ha quedado una cara!…\p"
	.string "¡Nos vemos!$"

MatchCall_WildBattleText15:: @ 82A9EFD
	.string "¡Eh, {PLAYER}!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "He estado pensando en ir\n"
	.string "a atrapar algunos Pokémon.\p"
	.string "¡Es que normalmente me cuesta!\n"
	.string "¡Siempre se me ha dado fatal!\p"
	.string "¡A ver si recupero las ganas!\n"
	.string "¡Hala, adiós!$"

MatchCall_NegativeBattleText1:: @ 82A9FAB
	.string "¡Hola, {PLAYER}{KUN}!\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "He intentado ganar a otro\n"
	.string "ENTRENADOR, pero nada.\p"
	.string "Me he desanimado bastante.\n"
	.string "En fin, nos vemos.$"

MatchCall_NegativeBattleText2:: @ 82AA028
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Me enfrenté a alguien después\n"
	.string "de nuestro combate.\p"
	.string "Estuve a punto de ganar,\n"
	.string "pero al final perdí. ¡Ay!$"

MatchCall_NegativeBattleText3:: @ 82AA099
	.string "¡Eh, hola, {PLAYER}!\n"
	.string "Soy yo, {STR_VAR_1}.\p"
	.string "Me acaban de dar una paliza\n"
	.string "en combate…\p"
	.string "¡Creo que tengo que entrenar más\n"
	.string "a mi equipo!$"

MatchCall_NegativeBattleText4:: @ 82AA100
	.string "Eh, {PLAYER}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Ayer lo intenté en otro combate,\n"
	.string "pero no conseguí ganar.\p"
	.string "Mi equipo necesita más\n"
	.string "entrenamiento. Bueno, nos vemos.$"

MatchCall_NegativeBattleText5:: @ 82AA188
	.string "¡Hola, hola, hola, {PLAYER}!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "¿Qué tal te va todo, eh?\p"
	.string "He estado todo este tiempo\n"
	.string "luchando, pero no he ganado\l"
	.string "demasiadas veces.\p"
	.string "¡No acabo de pillarle el tranquillo!\n"
	.string "Bueno, que te vaya bien.$"

MatchCall_NegativeBattleText6:: @ 82AA214
	.string "¡Eh, {PLAYER}!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "¿Te va todo bien?\p"
	.string "Yo he estado luchando un montón,\n"
	.string "pero no he tenido demasiado éxito.\p"
	.string "Me cuesta mantener el ritmo.\n"
	.string "En fin, cuídate.$"

MatchCall_NegativeBattleText7:: @ 82AA2A1
	.string "Soy {STR_VAR_1}.\n"
	.string "¿Cómo lo llevas?\p"
	.string "Ayer perdí un combate\n"
	.string "y no se me quita de la cabeza.\p"
	.string "Necesito una estrategia.\n"
	.string "Nos vemos.$"

MatchCall_NegativeBattleText8:: @ 82AA31B
	.string "Eh, {PLAYER}{KUN}, ¿qué tal?\n"
	.string "Sí, soy {STR_VAR_1}.\p"
	.string "¿Qué tal tus Pokémon?\n"
	.string "Yo el otro día perdí un combate.\p"
	.string "¡Necesito esforzarme más!\n"
	.string "¡Nos vemos!$"

MatchCall_NegativeBattleText9:: @ 82AA3A8
	.string "¡Eh, {PLAYER}{KUN}!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "Oye, oye, ¡no te lo vas a creer!\p"
	.string "Acabo de luchar en un combate\n"
	.string "Pokémon, ¡y he perdido\l"
	.string "en el último segundo!\p"
	.string "¡No sabes cómo me fastidia!$"

MatchCall_NegativeBattleText10:: @ 82AA442
	.string "Eh, {PLAYER}{KUN}, hola…\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Acabo de participar en un combate,\n"
	.string "pero he perdido.\p"
	.string "Tengo que dedicarle más tiempo\n"
	.string "a mis Pokémon. ¡Adiós!$"

MatchCall_NegativeBattleText11:: @ 82AA4C5
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Qué tal van tus Pokémon?\p"
	.string "Yo acabo de perder otra vez…\p"
	.string "En fin, nos vemos.$"

MatchCall_NegativeBattleText12:: @ 82AA520
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy yo, {STR_VAR_1}.\p"
	.string "¿Sigues siendo tan fuerte?\p"
	.string "Yo perdí hace muy poco,\n"
	.string "así que he empezado a entrenar\l"
	.string "a mi equipo otra vez.\p"
	.string "A ver si nos vemos.$"

MatchCall_NegativeBattleText13:: @ 82AA5AD
	.string "¡Ah, hola, {PLAYER}{KUN}!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "¡Espero que te haya ido bien!\p"
	.string "Hace nada estaba en pleno\n"
	.string "combate.\p"
	.string "¡{PLAYER}{KUN}, no te duermas\n"
	.string "en los laureles!\l"
	.string "¡Nos vemos!$"

MatchCall_NegativeBattleText14:: @ 82AA64D
	.string "Eh, hola, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Estás bien?\p"
	.string "Yo creo que deberías pasarte\n"
	.string "por tu casa de vez en cuando.\p"
	.string "Hala, te dejo.$"

MatchCall_PositiveBattleText1:: @ 82AA6AF
	.string "¡Eh! ¡Hola, {PLAYER}{KUN}!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "He luchado con otro entrenador\n"
	.string "¡y he ganado! ¡He ganado!\p"
	.string "Mi {STR_VAR_2} se ha portado como\n"
	.string "un fiera. ¡Ha sido una pasada!$"

MatchCall_PositiveBattleText2:: @ 82AA730
	.string "¡Hola, {PLAYER}{KUN}!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "¡Ayer luché de nuevo! ¡Y gané!\n"
	.string "¡Qué guay!$"

MatchCall_PositiveBattleText3:: @ 82AA77A
	.string "¡Eh, {PLAYER}!\n"
	.string "¡Soy yo, {STR_VAR_1}!\p"
	.string "¿Qué tal en combate?\p"
	.string "¡Yo participé en un combate el otro\n"
	.string "día y mi {STR_VAR_2} rompió moldes!\p"
	.string "La próxima vez que luche contigo,\n"
	.string "{PLAYER}, ¡no vas a poder conmigo!$"

MatchCall_PositiveBattleText4:: @ 82AA81C
	.string "Hola, {PLAYER}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "He estado luchando\n"
	.string "y he ganado, pero por muy poco.\p"
	.string "Mi {STR_VAR_2} estuvo bastante\n"
	.string "bien.$"

MatchCall_PositiveBattleText5:: @ 82AA88C
	.string "¡Hola, hola, hola, {PLAYER}{KUN}!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "¿Qué tal te van las cosas?\n"
	.string "¿Llevas muchos combates?\p"
	.string "¡Yo he ganado uno hace poco!\n"
	.string "¡Mi {STR_VAR_2} es una máquina!\p"
	.string "Tú, ya verás, la próxima vez\n"
	.string "que nos veamos seguro que\l"
	.string "te machaco. ¡Nos vemos!$"

MatchCall_PositiveBattleText6:: @ 82AA934
	.string "¿Qué pasa, {PLAYER}{KUN}?\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Qué tal vas, eh?\p"
	.string "A mí no me ha ido del todo mal.\n"
	.string "Bueno, he ganado un combate.\p"
	.string "Cuando nos veamos otra vez,\n"
	.string "¡ya verás, ya!$"

MatchCall_PositiveBattleText7:: @ 82AA9D3
	.string "¿{PLAYER}{KUN}?\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¡Mi {STR_VAR_2} es total!\n"
	.string "¡Acaba de ganarme otro combate!\p"
	.string "¡Estoy deseando enfrentarme\n"
	.string "a ti de nuevo!$"

MatchCall_PositiveBattleText8:: @ 82AAA40
	.string "¡{PLAYER}{KUN}, qué sorpresa!\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Espero que estés estupendamente.\n"
	.string "¡Quería decirte que acabo de ganar\l"
	.string "un combate!\p"
	.string "Mi {STR_VAR_2} se ha esforzado\n"
	.string "un montón para que ganáramos.\p"
	.string "¡Nos vemos!$"

MatchCall_PositiveBattleText9:: @ 82AAAE4
	.string "¡Eh, {PLAYER}{KUN}, hola!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "¿Qué tal lo llevan tus Pokémon?\n"
	.string "¡Los míos acaban de ganar\l"
	.string "un combate!\p"
	.string "Mi {STR_VAR_2} ha estado\n"
	.string "espectacular, las cosas como son.\p"
	.string "¡Me hubiera encantado que\n"
	.string "lo vieras! ¡Nos vemos!$"

MatchCall_PositiveBattleText10:: @ 82AAB8C
	.string "Eh, {PLAYER}{KUN}, hola…\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Qué tal te va la vida?\p"
	.string "Mis Pokémon están llenos\n"
	.string "de energía.\p"
	.string "Acabo de ganar un combate\n"
	.string "con ellos. A ver si nos vemos.$"

MatchCall_PositiveBattleText11:: @ 82AAC25
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Has luchado recientemente?\n"
	.string "¡Yo acabo de ganar de nuevo!\p"
	.string "¡Estoy en racha! ¡Ja, ja, ja, ja!\n"
	.string "Bueno, te dejo.$"

MatchCall_PositiveBattleText12:: @ 82AAC9D
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Espero que estés bien.\n"
	.string "¡Yo estoy hecho un chaval!\p"
	.string "Es que acabo de ganar de nuevo.\n"
	.string "¡Todavía no pienso dejar paso\l"
	.string "a los jóvenes como tú!$"

MatchCall_PositiveBattleText13:: @ 82AAD41
	.string "¡Eh, hola, {PLAYER}{KUN}!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "Espero que estés bien.\n"
	.string "¡Yo estoy más joven que nunca!\p"
	.string "Acabo de ganar otro combate.\n"
	.string "¡Aún me queda mucho por hacer,\l"
	.string "joven!\p"
	.string "¡Hala!$"

MatchCall_PositiveBattleText14:: @ 82AAE00
	.string "Eh, hola, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "He estado luchando hace poco.\n"
	.string "¡Mi {STR_VAR_2} lo ha hecho\l"
	.string "de escándalo!\p"
	.string "Tendrías que haberlo visto,\n"
	.string "{PLAYER}{KUN}. ¡Hasta luego!$"

MatchCall_SameRouteBattleRequestText1:: @ 82AAE7F
	.string "¡Eh! ¡{PLAYER}, hola!\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Cómo? ¿Que estás\n"
	.string "cerca de {STR_VAR_2}?\p"
	.string "¡Anda, pues entonces tenemos\n"
	.string "que luchar!\l"
	.string "¡Te espero! ¡Hasta luego!$"

MatchCall_SameRouteBattleRequestText2:: @ 82AAEF1
	.string "¡Hola, {PLAYER}!\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Sí? ¿Estás cerca\n"
	.string "de {STR_VAR_2}?\p"
	.string "¿Te apetece luchar?\n"
	.string "¡Venga, te espero! ¡Hasta luego!$"

MatchCall_SameRouteBattleRequestText3:: @ 82AAF69
	.string "¡Eh, {PLAYER}! ¿Qué tal?\n"
	.string "Soy yo, {STR_VAR_1}.\p"
	.string "¿Estás ahora mismo cerca de\n"
	.string "{STR_VAR_2}?\p"
	.string "¿Echamos un combate?\n"
	.string "¡Esta vez no pienso perder!\l"
	.string "¡Aquí te espero! ¡Hasta luego!$"

MatchCall_SameRouteBattleRequestText4:: @ 82AB010
	.string "¿Qué pasa, {PLAYER}{KUN}?\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Por dónde andas?\n"
	.string "¿Eh? ¿Por {STR_VAR_2}?\p"
	.string "¿Luchamos?\n"
	.string "Te espero, ¡hasta ahora!$"

MatchCall_SameRouteBattleRequestText5:: @ 82AB076
	.string "¡{PLAYER}{KUN}! ¿Cómo vas?\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Cómo te va? ¿Eh? ¿Que andas\n"
	.string "por {STR_VAR_2}?\p"
	.string "¿Y si nos echamos un combate\n"
	.string "de nuevo?\p"
	.string "Espero que vengas.\n"
	.string "¡No tardes!$"

MatchCall_SameRouteBattleRequestText6:: @ 82AB11A
	.string "Eh, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Qué tal tus Pokémon?\p"
	.string "¿En serio? ¿Estás por\n"
	.string "{STR_VAR_2}?\p"
	.string "Pues entonces tenemos\n"
	.string "que luchar de nuevo.\p"
	.string "Sí, sí, yo te espero.\n"
	.string "¡Hasta luego!$"

MatchCall_SameRouteBattleRequestText7:: @ 82AB1B4
	.string "Eh…, ¿{PLAYER}{KUN}?\n"
	.string "Soy {STR_VAR_1}…\p"
	.string "¿Que estás por\n"
	.string "{STR_VAR_2}?\p"
	.string "Pues lucha conmigo, anda.\n"
	.string "Ahora mismo, claro.\p"
	.string "Quiero enseñarte mis Pokémon.\n"
	.string "Te espero aquí.$"

MatchCall_SameRouteBattleRequestText8:: @ 82AB23D
	.string "{PLAYER}{KUN}, ¿cómo estás?\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Espero que estés bien. ¿Estás\n"
	.string "cerca de {STR_VAR_2}?\p"
	.string "¿Querrías aprovechar para\n"
	.string "luchar conmigo?\p"
	.string "Te espero.\n"
	.string "¡Nos vemos!$"

MatchCall_SameRouteBattleRequestText9:: @ 82AB2E9
	.string "¡{PLAYER}{KUN}, hola!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "¿Todo bien? ¿Que estás cerca de\n"
	.string "{STR_VAR_2}?\p"
	.string "¿No crees que deberíamos\n"
	.string "aprovechar y enfrentarnos?\p"
	.string "¡No tardes mucho, anda!$"

MatchCall_SameRouteBattleRequestText10:: @ 82AB382
	.string "Eh, {PLAYER}{KUN}, hola…\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Cómo te va? ¿Estás cerca de\n"
	.string "{STR_VAR_2}?\p"
	.string "Pues deberíamos luchar.\p"
	.string "Cuando quieras, aquí estoy.\n"
	.string "¡Date prisa!$"

MatchCall_SameRouteBattleRequestText11:: @ 82AB410
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Así que estás en\n"
	.string "{STR_VAR_2}…\p"
	.string "Pues tendríamos que luchar,\n"
	.string "¿no crees?\p"
	.string "¡No me falles!\n"
	.string "¡Y date prisa!$"

MatchCall_SameRouteBattleRequestText12:: @ 82AB4B0
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy yo, {STR_VAR_1}.\p"
	.string "¿Por dónde andas? ¿Por\n"
	.string "{STR_VAR_2}? ¡Qué cerca!\p"
	.string "¿Qué me dices a un combate\n"
	.string "aquí y ahora?\p"
	.string "¡Estoy deseándolo!\n"
	.string "¡Nos vemos!$"

MatchCall_SameRouteBattleRequestText13:: @ 82AB538
	.string "¡Ah, hola, {PLAYER}{KUN}!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "Espero que todo vaya bien. ¿Estás\n"
	.string "cerca de {STR_VAR_2}?\p"
	.string "Pues no estás lejos,\n"
	.string "¿por qué no luchamos?\p"
	.string "Te espero, ¿eh?\n"
	.string "Hasta luego.$"

MatchCall_SameRouteBattleRequestText14:: @ 82AB5E4
	.string "Eh, hola, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Que estás dónde? ¿Por\n"
	.string "{STR_VAR_2}? ¡Qué cerca!\p"
	.string "¿No crees que deberíamos\n"
	.string "luchar?\p"
	.string "¡No me dejes con las ganas!\n"
	.string "¡Adiós!$"

MatchCall_DifferentRouteBattleRequestText1:: @ 82AB670
	.string "¡Eh! ¡Hola, {PLAYER}!\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Quieres luchar conmigo?\p"
	.string "¡Te espero por {STR_VAR_2}!$"

MatchCall_DifferentRouteBattleRequestText2:: @ 82AB6CD
	.string "¡Hola, {PLAYER}!\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Quieres que luchemos de nuevo?\p"
	.string "Estaré por {STR_VAR_2}.\n"
	.string "¡Te espero!$"

MatchCall_DifferentRouteBattleRequestText3:: @ 82AB73C
	.string "¡{PLAYER}! ¿Cómo lo llevas?\n"
	.string "Soy yo, {STR_VAR_1}.\p"
	.string "Mis Pokémon están mucho\n"
	.string "más fuertes ahora.\p"
	.string "Me gustaría medir sus fuerzas\n"
	.string "con las de tus Pokémon, {PLAYER}.\p"
	.string "¡Vamos a luchar, anda!\p"
	.string "Te espero por\n"
	.string "{STR_VAR_2}.$"

MatchCall_DifferentRouteBattleRequestText4:: @ 82AB808
	.string "Eh, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Cómo te va todo?\n"
	.string "Mis Pokémon están imparables.\p"
	.string "¿Y si lucháramos otra vez?\p"
	.string "¿Nos vemos por\n"
	.string "{STR_VAR_2}, eh?$"

MatchCall_DifferentRouteBattleRequestText5:: @ 82AB8B7
	.string "¡Ey, {PLAYER}{KUN}!\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Mis Pokémon han crecido\n"
	.string "de forma considerable.\p"
	.string "Realmente me encantaría\n"
	.string "luchar de nuevo contigo.\p"
	.string "Te esperaré por\n"
	.string "{STR_VAR_2}. ¡No tardes!$"

MatchCall_DifferentRouteBattleRequestText6:: @ 82AB95D
	.string "Ey, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Espero que te vaya todo\n"
	.string "de miedo.\p"
	.string "Quería decirte que me gustaría\n"
	.string "que lucháramos otra vez.\l"
	.string "¿Qué dices?\p"
	.string "Si te apetece, búscame por\n"
	.string "{STR_VAR_2}.\p"
	.string "¡Adiós!$"

MatchCall_DifferentRouteBattleRequestText7:: @ 82ABA03
	.string "Eh…, ¿{PLAYER}{KUN}?\n"
	.string "Soy {STR_VAR_1}…\p"
	.string "¿Qué, han mejorado tus Pokémon?\p"
	.string "Los míos, una barbaridad.\n"
	.string "Me gustaría demostrártelo.\p"
	.string "Estaré por {STR_VAR_2}.\n"
	.string "Ven y luchamos, ¿vale?\p"
	.string "¡Nos vemos!$"

MatchCall_DifferentRouteBattleRequestText8:: @ 82ABA9F
	.string "Eh, {PLAYER}{KUN}, ¿qué tal?\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Espero que estés bien.\n"
	.string "Mis Pokémon no paran.\p"
	.string "Si vienes por aquí, me gustaría\n"
	.string "que lucháramos de nuevo.\p"
	.string "Estaré por {STR_VAR_2}.\n"
	.string "Hasta entonces, ¡adiós!$"

MatchCall_DifferentRouteBattleRequestText9:: @ 82ABB62
	.string "¡Oh, {PLAYER}{KUN}, hola!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "¿Qué tal están tus Pokémon?\p"
	.string "Mis Pokémon siguen mejorando.\n"
	.string "Querría demostrártelo, {PLAYER}{KUN}.\p"
	.string "Ahora mismo estoy por\n"
	.string "{STR_VAR_2}.\l"
	.string "Si estás cerca, ¿luchamos?\p"
	.string "¡Espero verte!$"

MatchCall_DifferentRouteBattleRequestText10:: @ 82ABC26
	.string "Eh, {PLAYER}{KUN}, hola…\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Cómo va todo?\p"
	.string "Mis Pokémon están mucho\n"
	.string "más fuertes.\p"
	.string "Me encantaría luchar contigo\n"
	.string "otra vez, {PLAYER}{KUN}.\p"
	.string "Estaré por {STR_VAR_2}.\n"
	.string "Ven a verme si pasas por aquí.$"

MatchCall_DifferentRouteBattleRequestText11:: @ 82ABCE9
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Por dónde andas ahora?\p"
	.string "Mis Pokémon están llenos de vida.\n"
	.string "Creo que están deseando ver\l"
	.string "a los tuyos, {PLAYER}{KUN}.\p"
	.string "Estoy por {STR_VAR_2}.\n"
	.string "Espero que des con nosotros.$"

MatchCall_DifferentRouteBattleRequestText12:: @ 82ABDA2
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy yo, {STR_VAR_1}.\p"
	.string "Debo decirte que mis Pokémon\n"
	.string "se han puesto tremendos.\p"
	.string "Me gustaría verlos en combate\n"
	.string "contra ti, {PLAYER}{KUN}.\p"
	.string "Estaremos por {STR_VAR_2}.\n"
	.string "¡Ven a vernos cuando quieras!$"

MatchCall_DifferentRouteBattleRequestText13:: @ 82ABE5E
	.string "¡Ah, hola, {PLAYER}{KUN}!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "¿Qué tal siguen tus Pokémon,\n"
	.string "bien?\p"
	.string "Los míos tienen un aspecto muy\n"
	.string "sano, no tienen pinta de perder.\p"
	.string "Me encantaría que lucháramos\n"
	.string "de nuevo.\p"
	.string "Si estás por {STR_VAR_2},\n"
	.string "ven a vernos.$"

MatchCall_DifferentRouteBattleRequestText14:: @ 82ABF36
	.string "Eh, hola, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Espero que sigas bien.\p"
	.string "¡Sí, sí, mis Pokémon están\n"
	.string "mucho más fuertes!\p"
	.string "¿No crees que deberíamos\n"
	.string "enfrentarnos, {PLAYER}{KUN}?\p"
	.string "Estaremos esperándote por\n"
	.string "{STR_VAR_2}.\p"
	.string "Ven cuando quieras, ¿eh?$"

MatchCall_PersonalizedText1:: @ 82AC009
	.string "¡Soy yo, {STR_VAR_1},\n"
	.string "el apasionado de la montaña!\p"
	.string "Bueno, ¿te gustan ahora más\n"
	.string "las montañas?\p"
	.string "Nunca te veo por los montes…\p"
	.string "A ver si la próxima vez que nos\n"
	.string "veamos es por {STR_VAR_2}.$"

MatchCall_PersonalizedText2:: @ 82AC0BD
	.string "Soy {STR_VAR_1}.\n"
	.string "Hola.\p"
	.string "Ahora mismo estaba hablándole\n"
	.string "de ti a una Entrenadora.\p"
	.string "Le estaba hablando de alguien\n"
	.string "fuerte que cuida mucho\l"
	.string "a sus Pokémon.\p"
	.string "Espero que todo el mundo acabe\n"
	.string "admirándote.\p"
	.string "¡A ver si volvemos a vernos!$"

MatchCall_PersonalizedText3:: @ 82AC18C
	.string "¡Hola!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "Me encanta el sitio en el que\n"
	.string "estoy ahora. ¡Huele tan bien!\p"
	.string "Creo que es porque alguien ha\n"
	.string "plantado Bayas y ya hay brotes.\p"
	.string "¡A ver si nos vemos!$"

MatchCall_PersonalizedText4:: @ 82AC228
	.string "¡Hola! Soy {STR_VAR_1}, llevo\n"
	.string "30 años explorando ruinas\l"
	.string "y estoy a tu servicio.\p"
	.string "Se ve que vas todo el tiempo\n"
	.string "de aquí para allá sin parar.\p"
	.string "¿Has descubierto algunas ruinas?\n"
	.string "Si es así, dímelo, anda.\p"
	.string "Bueno, si me lo permites, te dejo,\n"
	.string "que tengo ruinas que explorar.$"

MatchCall_PersonalizedText5:: @ 82AC30C
	.string "¡Soy {STR_VAR_1}!\p"
	.string "¿Sabes qué estoy haciendo hoy?\n"
	.string "¡Mirando las olas desde la playa!\p"
	.string "Ay… Tienen un brillo…\n"
	.string "El mar es mucho más bonito\l"
	.string "desde aquí.\p"
	.string "¡Bueno, te dejo, que tengo hambre!$"

MatchCall_PersonalizedText6:: @ 82AC3B6
	.string "Ñam, ñam, ñam…\n"
	.string "Eh, hola, soy {STR_VAR_1}.\p"
	.string "Me encanta comer en la playa.\p"
	.string "Mis Pokémon y yo estamos genial.\n"
	.string "¡Estamos listos para lo que sea!\p"
	.string "Bueno, voy a darme un baño. ¡Adiós!$"

MatchCall_PersonalizedText7:: @ 82AC446
	.string "Hola, soy {STR_VAR_1}…\p"
	.string "Estoy hasta el gorro de ser\n"
	.string "entrenador guay…\p"
	.string "Todos piensan que soy un perfecto\n"
	.string "entrenador, y me agobia\l"
	.string "tener que dar siempre la talla.\p"
	.string "Aunque supongo que forma parte\n"
	.string "de ser entrenador guay.\p"
	.string "Bueno, seguiré entrenándome como\n"
	.string "siempre, lanzaré mi mejor sonrisa\l"
	.string "y lo llevaré lo mejor que pueda.\p"
	.string "Eres la única persona con la que\n"
	.string "puedo hablar de estas cosas.\p"
	.string "Pero no te preocupes, ¡que no voy\n"
	.string "a ponerme a quejarme cuando\l"
	.string "nos veamos la próxima vez!$"

MatchCall_PersonalizedText8:: @ 82AC5C7
	.string "¡Ey, soy {STR_VAR_1}!\n"
	.string "¿Qué pasa, eh?\p"
	.string "He estado entrenando mis Pokémon\n"
	.string "para ganarte.\p"
	.string "No pienso perder cuando\n"
	.string "nos enfrentemos de nuevo.\p"
	.string "¿No es guay tener amigos\n"
	.string "Entrenadores? ¡A ver si nos vemos!$"

MatchCall_PersonalizedText9:: @ 82AC682
	.string "Soy {STR_VAR_1}…\n"
	.string "Creo que justo ahora…\l"
	.string "Tienes algo detrás…\p"
	.string "El poder de los Pokémon que\n"
	.string "duermen aquí en el Monte Pírico…\p"
	.string "Me habla sobre ti…\p"
	.string "Corre, camina hacia el frente\n"
	.string "¡y no mires atrás ni una sola vez!…\p"
	.string "Adiós…\n"
	.string "Ja, ja, ja…$"

MatchCall_PersonalizedText10:: @ 82AC755
	.string "Soy {STR_VAR_1}.\n"
	.string "¿Cómo estás?\p"
	.string "¿No es una maravilla que podamos\n"
	.string "charlar estando lejos?\p"
	.string "Antes, cuando quería hablar con\n"
	.string "alguien, hacía a mi padre llevarme\l"
	.string "donde fuera…\p"
	.string "Bueno, que tengo que hacer cosas.\n"
	.string "Me alegro de haber hablado contigo.$"

MatchCall_PersonalizedText11:: @ 82AC82C
	.string "¡Soy {STR_VAR_1}!\n"
	.string "¿Te cuento una cosa?\p"
	.string "A mí me encanta la Zona Safari,\n"
	.string "¡pero me pierdo siempre que voy!\p"
	.string "¡Con tanta hierba!\n"
	.string "¡Con tantos recovecos!\p"
	.string "Bueno, ¡tenía que decírselo\n"
	.string "a alguien!\p"
	.string "En fin, allá que voy otra vez.\n"
	.string "¡A ver si nos vemos!$"

MatchCall_PersonalizedText12:: @ 82AC914
	.string "Hola, soy {STR_VAR_1}.\n"
	.string "Exacto, sí, soy bastante pudiente.\p"
	.string "Más que la última vez\n"
	.string "que nos vimos.\p"
	.string "Y lo que es más: mis Pokémon\n"
	.string "tienen más fuerza aún.\p"
	.string "¡La verdad es que la vida\n"
	.string "me sonríe!\p"
	.string "Ya, ya, es así.\n"
	.string "Eso lo ve cualquiera.\p"
	.string "Oh, perdona, si me disculpas,\n"
	.string "es que tengo que ir a una cena.$"

MatchCall_PersonalizedText13:: @ 82ACA59
	.string "Uf, uf, uf…\n"
	.string "Soy yo, {STR_VAR_1}…\p"
	.string "¿A que no sabes qué estoy viendo?\n"
	.string "Un par de {STR_VAR_2} en combate.\p"
	.string "Creo que voy a intentar hacerme\n"
	.string "con el que gane…\l"
	.string "Uf, uf, uf…\p"
	.string "Eh… estoy liado ahora mismo.\n"
	.string "Te dejo.$"

MatchCall_PersonalizedText14:: @ 82ACB02
	.string "¡Eh, soy {STR_VAR_1}!\p"
	.string "Creo que estoy aburrida ya\n"
	.string "de la Nao Abandonada.\p"
	.string "Pero, ya que estoy, me gustaría\n"
	.string "luchar contigo y ganarte.\l"
	.string "Voy a quedarme un poco más.\p"
	.string "Si te apetece, ¿por qué no\n"
	.string "te pasas a verme?\p"
	.string "De hoy no pasa sin que desafíe\n"
	.string "al del camarote de al lado.\p"
	.string "¡Nos vemos!$"

MatchCall_PersonalizedText15:: @ 82ACC3F
	.string "¡Soy {STR_VAR_1}!\n"
	.string "¡El amante del mar!\p"
	.string "¿Sabes lo que creo?\p"
	.string "Creo que los entrenadores\n"
	.string "de mar son los más curtidos.\p"
	.string "Deberías aprender de mí\n"
	.string "y entrenarte en el mar…\p"
	.string "¡Uaaaaaaaa, una ola gigante!\p"
	.string "¡Qué oportunidad para entrenar!\n"
	.string "¡Lo siento, te dejo!$"

MatchCall_PersonalizedText16:: @ 82ACD2F
	.string "¡Soy {STR_VAR_1}! Oye, he estado\n"
	.string "enseñándoles karate a mis Pokémon.\p"
	.string "¡Y ahora son mucho mejores\n"
	.string "que yo! ¡Me ganan todo el tiempo!\p"
	.string "Pero, aunque pierda ante los\n"
	.string "Pokémon, con los entrenadores\l"
	.string "seguro que no tengo problema.\p"
	.string "¡Tenemos que luchar de nuevo!\n"
	.string "¿Eeeeeeh?$"

MatchCall_PersonalizedText17:: @ 82ACE1E
	.string "Soy yo, {STR_VAR_1}.\n"
	.string "¿Qué tal va tu viaje?\p"
	.string "Bua…, ¿en serio?\n"
	.string "¡Suena que se te va la olla!\p"
	.string "Creo que podría escribir una\n"
	.string "canción con una de tus historias.\p"
	.string "Ey…, ya lo tengo…\n"
	.string "Es como si la estuviera oyendo.\p"
	.string "Voy a ponerme a hacerle\n"
	.string "los arreglos, ¡me piro!$"

MatchCall_PersonalizedText18:: @ 82ACF32
	.string "Soy {STR_VAR_1}…\n"
	.string "Mira, ésta es mi canción:\p"
	.string "Lalala, ¡{STR_VAR_2}, {STR_VAR_2}!\n"
	.string "¿Por qué eres tú {STR_VAR_2}?\l"
	.string "¿Por qué no soy yo {STR_VAR_2}?\l"
	.string "Lalala, ¡{STR_VAR_2} y {STR_VAR_1},\l"
	.string "{STR_VAR_1} y {STR_VAR_2}! Lalala…\p"
	.string "Y ahora vendría el estribillo…$"

MatchCall_PersonalizedText19:: @ 82ACFBE
	.string "¡Soy {STR_VAR_1}, ya sabes,\n"
	.string "el experto en acampadas!\p"
	.string "Cuando luchamos, no pude\n"
	.string "evitar perder contra ti.\p"
	.string "En realidad, a mí lo que se me\n"
	.string "da bien son las acampadas.\p"
	.string "Con todo, gane o pierda, me gusta\n"
	.string "luchar cuando estoy de acampada.\p"
	.string "Lucha con nosotros otra vez,\n"
	.string "¿vale? ¡Ah, y vente de acampada!$"

MatchCall_PersonalizedText20:: @ 82AD0AC
	.string "Soy yo, yo, ¡{STR_VAR_1}!\p"
	.string "La verdad es que me encantaría\n"
	.string "escalar otras montañas.\p"
	.string "Pero creo que el Monte Cenizo\n"
	.string "es donde hay más gente,\l"
	.string "sobre todo chicas.\p"
	.string "Si sabes de otro sitio, me dices,\n"
	.string "¿eh?\p"
	.string "¡Bueno, nos vemos, je, je!$"

MatchCall_PersonalizedText21:: @ 82AD194
	.string "(…)\p"
	.string "Soy {STR_VAR_1}…\p"
	.string "(…)\n"
	.string "Pues eso, adiós…$"

MatchCall_PersonalizedText22:: @ 82AD1DF
	.string "Soy {STR_VAR_1}. Hoy, sabía\n"
	.string "que iba a hablar contigo.\p"
	.string "Estoy deseando ganarte,\n"
	.string "no me lo quito de la cabeza.\p"
	.string "¿Ah, sí, que tienes rival?\n"
	.string "Cómo me gustaría ser yo…\p"
	.string "Me alegro de haber hablado\n"
	.string "contigo. Adiós.$"

MatchCall_PersonalizedText23:: @ 82AD2A8
	.string "Soy {STR_VAR_1}.\p"
	.string "A veces, siento la presencia\n"
	.string "de los Entrenadores fuertes,\l"
	.string "cuando están cerca.\p"
	.string "¿Has pasado por donde yo estaba,\n"
	.string "{PLAYER}{KUN}? A lo mejor has sido tú.\p"
	.string "Espero tu visita.\n"
	.string "¡Adiós!$"

MatchCall_PersonalizedText24:: @ 82AD34F
	.string "Hola, soy {STR_VAR_1}.\n"
	.string "Se te oye muy bien, {PLAYER}{KUN}.\p"
	.string "He viajado por todo el mundo,\n"
	.string "pero esta región tiene algo.\p"
	.string "Tengo intención de quedarme\n"
	.string "un tiempo. A lo mejor podríamos\l"
	.string "volver a vernos.\p"
	.string "No he podido olvidar lo brillante\n"
	.string "de tu técnica.\p"
	.string "Espero que luchemos de nuevo.$"

MatchCall_PersonalizedText25:: @ 82AD44E
	.string "Snif… Soy… {STR_VAR_1}…\n"
	.string "Snif…\p"
	.string "Hoy, estábamos en clase\n"
	.string "y Petra me ha echado.\p"
	.string "Pero no tengo nada en contra\n"
	.string "de ella.\p"
	.string "Petra siempre me dice lo que\n"
	.string "hago mal y aprendo un montón.\p"
	.string "¡Mañana pienso volver\n"
	.string "a la escuela de entrenadores!\p"
	.string "¡Hasta luego!$"

MatchCall_PersonalizedText26:: @ 82AD53A
	.string "¡Soy {STR_VAR_1}!\p"
	.string "Petra me dejó luchar con ella ayer.\p"
	.string "Los resultados fueron… terribles,\n"
	.string "¡no sé para qué preguntas!\p"
	.string "Pero me da igual, ¡me flipó que\n"
	.string "Petra me dejara luchar con ella!\p"
	.string "¡No sabes cuánto la admiro!\p"
	.string "¡Voy a esforzarme y a entrenarme\n"
	.string "a conciencia! ¡Adiós!$"

MatchCall_PersonalizedText27:: @ 82AD642
	.string "¡Hola, soy Ani!\n"
	.string "¡Estoy con mi pupila, Mati!\p"
	.string "Me encanta ocuparme de Mati\n"
	.string "y de los Pokémon. ¡Son adorables!\p"
	.string "¡Me gustaría cuidar de ellos\n"
	.string "como si fueran mis hermanos!\p"
	.string "¡Ah, hola, Mati!\n"
	.string "¿Has traído los bollos?\p"
	.string "¿Cómo? ¿Que te estoy tratando\n"
	.string "como si fueras una esclava?\p"
	.string "Oye, tú fuiste la que perdió,\n"
	.string "así que te toca ir a por el pan.\p"
	.string "¡No es que quiera aprovecharme,\n"
	.string "Mati! ¡Si me caes muy bien!\p"
	.string "Bueno, que tengo que irme.\n"
	.string "¡Vamos a comernos el bocata!$"

MatchCall_PersonalizedText28:: @ 82AD801
	.string "¡Me encantan los Pokémon!\n"
	.string "¡Soy {STR_VAR_1}, del club de fans!\p"
	.string "Quería decirte que mis dulces\n"
	.string "Pokémon…\p"
	.string "¡Pstch! ¡Ja, ja, ja! ¡No pienso\n"
	.string "decirte más, es un secreto!\p"
	.string "¡No hay palabras para describir\n"
	.string "la dulzura!\p"
	.string "¡Ay, a mi dulce {STR_VAR_2}\n"
	.string "le pirraría un Pokécubo!\p"
	.string "¡Es que es la definición de dulzura!\p"
	.string "Bueno, no puedo entretenerme.\n"
	.string "¡La próxima vez te contaré más!$"

MatchCall_PersonalizedText29:: @ 82AD92E
	.string "¡Eeeeeh!\p"
	.string "¡Soy {STR_VAR_1}! ¡Voy a hablarte\n"
	.string "sobre mis adorables Pokémon!\p"
	.string "Presta atención, es sobre\n"
	.string "mi adorado {STR_VAR_2}.\p"
	.string "Siempre que alguien lo toma en\n"
	.string "brazos, quiere venirse conmigo.\p"
	.string "Oh… Oh…\n"
	.string "¿Acaso hay algo más maravilloso?\p"
	.string "¡Es que es para comérselo!\p"
	.string "Estoy feliz de haber compartido\n"
	.string "mi alegría contigo.\p"
	.string "Bueno, tengo que marcharme.\n"
	.string "¡Hasta otra!$"

MatchCall_PersonalizedText30:: @ 82ADA8F
	.string "Soy… {STR_VAR_1}.\n"
	.string "Para todos soy un Pokéabu.\p"
	.string "Aunque, ser Pokéabu solo\n"
	.string "se consigue si tienes ayuda.\p"
	.string "La ayuda de tus Pokémon y\n"
	.string "la experiencia de los años, claro.\p"
	.string "En fin, igual he sonado demasiado\n"
	.string "profundo, pero así es.\p"
	.string "¡Bueno, ya sabes cómo se llega\n"
	.string "a ser Pokéabu!$"

MatchCall_PersonalizedText31:: @ 82ADB9B
	.string "Soy {STR_VAR_1}.\n"
	.string "¡Cómo me alegro de hablar contigo!\p"
	.string "Oye, los baños termales me dejan\n"
	.string "como nueva, ¡me quitan años!\p"
	.string "He luchado con entrenadores\n"
	.string "jóvenes desde que nos vimos,\l"
	.string "pero no hay nadie como tú.\p"
	.string "Seguro que con los años, acabarás\n"
	.string "siendo Pokéabu como yo.\l"
	.string "¡Je, je, je!$"

MatchCall_PersonalizedText32:: @ 82ADC92
	.string "¡Eh! ¡Soy {STR_VAR_1}!\n"
	.string "¿Cómo te va?\p"
	.string "Creo que son cosas mías, pero\n"
	.string "cuando gano, me siento mejor\l"
	.string "dentro de los pantalones cortos.\l"
	.string "En serio.\p"
	.string "¿Que qué quiero decir?\n"
	.string "¿Cómo te diría yo? Es que…\l"
	.string "es que no sé, los noto más cómodos…\l"
	.string "¡Más suaves!\p"
	.string "Pero al luchar contigo, {PLAYER}{KUN},\n"
	.string "me resultaron incómodos y tiesos.\p"
	.string "(…)\p"
	.string "Que no te lo acabas de creer, ¿no?\n"
	.string "Je, je, je, pues eso te digo. ¡Adiós!$"

MatchCall_PersonalizedText33:: @ 82ADE08
	.string "¡Ey!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "Como siempre, ¡estoy pescando\n"
	.string "a mi bola!\p"
	.string "¿Dónde se podrá pescar además\n"
	.string "de en el mar y los ríos?\p"
	.string "¡Es que me entran ganas de pescar\n"
	.string "por todos lados!\p"
	.string "¡Ah, vaya, hombre!\n"
	.string "¡Se me ha liado el sedal!\p"
	.string "¡Oye, tengo que dejarte! ¡A ver\n"
	.string "si me buscas un sitio para pescar!$"

MatchCall_PersonalizedText34:: @ 82ADF07
	.string "¡Eh, oye! Soy {STR_VAR_1}.\n"
	.string "¿Te lo estás tomando\l"
	.string "con espíritu deportivo?\p"
	.string "Yo siempre me he tomado las\n"
	.string "cosas con calma, desde pequeño.\p"
	.string "Nunca me ha gustado hacer nada\n"
	.string "corriendo y sin pensar.\p"
	.string "Pero, hay que ver lo que son\n"
	.string "las cosas, ahora soy Triatleta.\p"
	.string "Nunca sabes por dónde te va\n"
	.string "a llevar la vida, fíjate en mí.\p"
	.string "Ahora te dedicas a entrenar,\n"
	.string "pero ¿quién sabe en el futuro, eh?\p"
	.string "Igual acabas dando clase o te\n"
	.string "conviertes en artista. Mola, ¿eh?\p"
	.string "Bueno, de momento tómatelo\n"
	.string "con deportividad. ¡Ea, nos vemos!$"

MatchCall_PersonalizedText35:: @ 82AE0D9
	.string "¡Soy {STR_VAR_1}!\n"
	.string "¡Voy en bici!\p"
	.string "Nadar y correr me encanta, pero\n"
	.string "¡donde me pongan una bici…!\p"
	.string "Me hace sentir que el viento y yo\n"
	.string "somos uno.\p"
	.string "¡Me hace sentir como si volara!\p"
	.string "¡Ya está! ¡Hoy pienso batir\n"
	.string "el récord en el camino de bicis!\p"
	.string "¡Tú deberías intentarlo también!\n"
	.string "¡Adiós!$"

MatchCall_PersonalizedText36:: @ 82AE1FD
	.string "¡Eh, soy {STR_VAR_1}!\n"
	.string "¡Estoy en pleno triatlón!\p"
	.string "¡Pero, oye, para charlar siempre\n"
	.string "saco tiempo!\p"
	.string "¡Entrenarse con Pokémon\n"
	.string "es lo mejor!\p"
	.string "Nos comunicamos sin necesidad\n"
	.string "de hablar, ¡somos uno!\p"
	.string "¡Es una sensación increíble!\p"
	.string "Ufff… Esto de hablar mientras\n"
	.string "corro… Uff, qué paliza…\l"
	.string "Auuuuff… Oye… te… dejo…$"

MatchCall_PersonalizedText37:: @ 82AE327
	.string "Eh, soy {STR_VAR_1}.\n"
	.string "Si quieres tener más resistencia,\l"
	.string "entrénate a gran altura.\p"
	.string "Intenta correr en lo alto de\n"
	.string "una montaña. Verás cómo machaca.\p"
	.string "¡Oye, te dejo, que me estoy\n"
	.string "quedando sin aire! ¡Adiós!$"

MatchCall_PersonalizedText38:: @ 82AE3DA
	.string "Eh, soy {STR_VAR_1}, hola.\p"
	.string "Llevo nadando la tira y aún\n"
	.string "no he llegado a Colosalia.\p"
	.string "Igual es que estoy dando\n"
	.string "vueltas en círculo.\p"
	.string "No, no, no lo creo.\n"
	.string "Je, je, je. ¡Hala, adiós!$"

MatchCall_PersonalizedText39:: @ 82AE489
	.string "Eh, soy {STR_VAR_1}…\n"
	.string "¡Ahí va!\p"
	.string "¡Plas!\p"
	.string "Glup, glup, glup, glup…\p"
	.string "¡Plaaasssh!\p"
	.string "¡Psssssch!\p"
	.string "¡Anda! ¡Perdona! ¡Es que acababa\n"
	.string "de ponerme crema bronceadora,\l"
	.string "se me ha resbalado mi Pokénav\l"
	.string "y se me ha caído al agua!\p"
	.string "Pero, oye, el Pokénav de Devon\n"
	.string "es todoterreno. ¡No se ha ahogado!\p"
	.string "Bueno, que estoy tomando el sol.\n"
	.string "Hablamos en otro momento, ¿eh?$"

MatchCall_PersonalizedText40:: @ 82AE5CD
	.string "Hola, soy {STR_VAR_1}.\p"
	.string "De todas las pruebas del triatlón,\n"
	.string "la natación es la mejor.\p"
	.string "Pero, como me quede en remojo\n"
	.string "más tiempo, ¡me voy a poner\l"
	.string "como un garbanzo!\p"
	.string "¡Ay, el triatlón es una prueba de\n"
	.string "fuego para la resistencia física!\l"
	.string "¡Hasta luego!$"

MatchCall_PersonalizedText41:: @ 82AE698
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Cómo van tus Pokémon?\p"
	.string "Mis Pokémon dragón parece\n"
	.string "que están a tope. Hasta pronto.$"

MatchCall_PersonalizedText42:: @ 82AE704
	.string "Soy {STR_VAR_1}.\p"
	.string "Mi {STR_VAR_2} se ha hecho mucho\n"
	.string "más fuerte desde la última\l"
	.string "vez que nos enfrentamos.\p"
	.string "No voy a volver a perder contigo.\n"
	.string "¡Ya verás la próxima vez!\p"
	.string "¡Nos vemos!$"

MatchCall_PersonalizedText43:: @ 82AE78F
	.string "Hola, soy {STR_VAR_1}.\p"
	.string "He continuado mis estudios\n"
	.string "sobre la técnica de camuflaje.\p"
	.string "Pero creo que me he pasado:\n"
	.string "¡no me ha encontrado nadie!…\l"
	.string "Tanto estudiar para acabar solo…\p"
	.string "¡Me esfumo!$"

MatchCall_PersonalizedText44:: @ 82AE859
	.string "Soy {STR_VAR_1}.\n"
	.string "He seguido entrenando mucho\l"
	.string "desde que nos encontramos.\p"
	.string "Mi {STR_VAR_2} se ha hecho\n"
	.string "muy fuerte.\p"
	.string "Lo de entrenar en la playa\n"
	.string "funciona como pensaba. ¡Chao!$"

MatchCall_PersonalizedText45:: @ 82AE8E6
	.string "¿Cómo estás?\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Me gustaría saber cuándo pararán\n"
	.string "de caer estas cenizas volcánicas…\p"
	.string "Si siguen así, van a tapar\n"
	.string "el dibujo de mi parasol…\p"
	.string "¡Oye, tenemos que vernos otra vez!$"

MatchCall_PersonalizedText46:: @ 82AE998
	.string "Hola, soy {STR_VAR_1}.\p"
	.string "¿Sabías que es más fácil flotar\n"
	.string "en el mar que en una piscina?\p"
	.string "Te quedas quieta y tu cuerpo\n"
	.string "flota solo.\p"
	.string "Pero no estés flotando mucho\n"
	.string "tiempo, no vaya a ser que te\l"
	.string "arrastre la corriente mar adentro.\p"
	.string "A todo esto, ¿dónde estoy?…\n"
	.string "¡Será mejor que me largue!$"

MatchCall_PersonalizedText47:: @ 82AEA8F
	.string "Oh, {PLAYER}{KUN}, ¡hola!\n"
	.string "Soy {STR_VAR_1}.\l"
	.string "Estoy en las montañas.\p"
	.string "El suelo es demasiado irregular.\n"
	.string "No sé si podré poner la tienda…\p"
	.string "Oh, ¡qué buena idea!\p"
	.string "¡A lo mejor puedo hacer que\n"
	.string "mi Pokémon allane el terreno!\p"
	.string "¡Voy a probar!\n"
	.string "¡Chao!$"

MatchCall_PersonalizedText48:: @ 82AEB77
	.string "¡Eh! ¡Hola, hola, hola!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "¡Mar y yo entrenamos juntas!\n"
	.string "¡Nos estamos esforzando mucho!\p"
	.string "¡Si seguimos así, llegaremos lejos!\n"
	.string "¡Adiós!$"

MatchCall_PersonalizedText49:: @ 82AEBFA
	.string "¡Soy {STR_VAR_1}!\p"
	.string "Soy un marinero, aunque ahora\n"
	.string "no estoy en el mar.\p"
	.string "Eso me hace preguntarme, ¿cómo\n"
	.string "deberían llamarnos a los MarineroS\l"
	.string "cuando estamos en tierra firme?\p"
	.string "Es lo que pensaba con la mirada\n"
	.string "perdida más allá de las olas…\p"
	.string "¡Hasta otra!$"

MatchCall_PersonalizedText50:: @ 82AECC1
	.string "Al habla {STR_VAR_1}.\n"
	.string "¿Qué? ¿Ya tienes más Pokémon?\p"
	.string "Si atrapas otro Pokémon,\n"
	.string "no te olvides de enseñármelo.\p"
	.string "De verdad que no voy a pedírtelo.\n"
	.string "¡Te estaré esperando!$"

MatchCall_PersonalizedText51:: @ 82AED52
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Estás criando a tus Pokémon\n"
	.string "en condiciones?\p"
	.string "Aquí donde estoy el aire es puro.\n"
	.string "Es el lugar ideal para criar\l"
	.string "Pokémon, créeme.\p"
	.string "Si vas a dedicarte a criar\n"
	.string "Pokémon, deberías venir\l"
	.string "a {STR_VAR_2}. ¡Cuídate!$"

MatchCall_PersonalizedText52:: @ 82AEE35
	.string "Hola, soy {STR_VAR_1}.\p"
	.string "Le di un Pokécubo a mi {STR_VAR_2}\n"
	.string "y creo que le ha encantado.\p"
	.string "Parece que no a todos los Pokémon\n"
	.string "les gustan los mismos Pokécubos.\p"
	.string "Me parece algo fascinante.\n"
	.string "Porfa, cuídate.$"

MatchCall_PersonalizedText53:: @ 82AEEF4
	.string "Soy {STR_VAR_1}.\p"
	.string "Si cooperas con los Pokémon,\n"
	.string "puedes llegar a sentirte realmente\l"
	.string "a gusto en el mundo salvaje.\p"
	.string "Todos deberían comprender eso\n"
	.string "y cooperar más con los Pokémon.\p"
	.string "Eso sería lo ideal, pienso yo.\p"
	.string "¡Creo que vas por el buen camino!\n"
	.string "¡Ya nos veremos!$"

MatchCall_PersonalizedText54:: @ 82AEFDA
	.string "Hola, soy {STR_VAR_1}.\n"
	.string "Ya sabes, ¡la entrenadora\l"
	.string "que siempre está preparada!\p"
	.string "{PLAYER}{KUN}, ¿tienes suficientes\n"
	.string "objetos? ¿Están esos Pokémon\l"
	.string "tuyos preparados para la acción?\p"
	.string "Mantener siempre todo a punto\n"
	.string "es el secreto para continuar\l"
	.string "por la buena senda.\p"
	.string "¡Por cierto, voy a comprobar\n"
	.string "mi Mochila! ¡No te descuides!$"

MatchCall_PersonalizedText55:: @ 82AF0E7
	.string "¡Soy {STR_VAR_1}!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "Por {STR_VAR_2} pasa mucha\n"
	.string "gente y todos los días combato\l"
	.string "contra todo tipo de Entrenadores.\p"
	.string "Hoy, por ejemplo, he ganado cinco\n"
	.string "combates y he perdido solo tres.\p"
	.string "¿Qué tal se te ha dado a ti?\n"
	.string "Me lo cuentas la próxima vez, ¿eh?$"

MatchCall_PersonalizedText56:: @ 82AF1B8
	.string "Soy yo, {STR_VAR_1}.\p"
	.string "Eso de tener muchos Pokémon bicho\n"
	.string "me ha dado cierta fama, ya sabes.\p"
	.string "El otro día llevé a la escuela\n"
	.string "los cinco que más me gustan.\p"
	.string "¡Se los enseñé a la chica que\n"
	.string "me gusta y no veas cómo chillaba!\l"
	.string "Ríete, ríete, si quieres.\p"
	.string "¡Yo solo quería enseñarle lo guays\n"
	.string "que son los Pokémon bicho!…\p"
	.string "Snif…\n"
	.string "¡Nos vemos!$"

MatchCall_PersonalizedText57:: @ 82AF2C4
	.string "¡Uf!…\n"
	.string "¡Uf!…\p"
	.string "Ho… ¡Uf!\n"
	.string "Hola, soy {STR_VAR_1}.\p"
	.string "Esto de hablar…\n"
	.string "mientras estás escalando…\l"
	.string "es duro de verdad…\p"
	.string "¡Uf!… Mira que está empinado esto…\n"
	.string "Bueno… Ya hablamos otro rato…\l"
	.string "¡Uf!$"

MatchCall_PersonalizedText58:: @ 82AF371
	.string "¡Ah, hola!\p"
	.string "¡Todavía sigo buscando\n"
	.string "tesoros con Luci!\p"
	.string "Puede que al final no haya ningún\n"
	.string "tesoro por aquí…\p"
	.string "Pero para mí lo importante\n"
	.string "es poder buscar con Luci.\p"
	.string "Oh, ¡hola, Luci!\n"
	.string "¿Po-por qué te has enfadado?\p"
	.string "¡No paso de ti, cariño!\n"
	.string "¡Tú eres la única que me importa!\p"
	.string "{PLAYER}, ¡tengo que dejarte, adiós!$"

MatchCall_PersonalizedText59:: @ 82AF480
	.string "¡Soy {STR_VAR_1}!\p"
	.string "He ido otra vez al gimnasio\n"
	.string "de Azuliza para entrenarme.\p"
	.string "Marcial, el líder del gimnasio,\n"
	.string "parece ahora más fuerte que antes.\p"
	.string "Creo que se ha fortalecido\n"
	.string "con las embestidas de las olas…\p"
	.string "Pero sigue siendo un tipo genial.\n"
	.string "¡Las mujeres lo adoran!\l"
	.string "Si te digo la verdad, me da envidia.\p"
	.string "Yo me pregunto… ¿Tú crees que\n"
	.string "el Juaspi ese se parece a Marcial?\p"
	.string "Ya sabes, todo oloroso y sudoroso,\n"
	.string "siempre en plan chulo con la gente\l"
	.string "y esas cosas.\p"
	.string "Bueno, parece que son mis celos\n"
	.string "los que hablan por mí, ¿verdad?\p"
	.string "Olvida esta conversación,\n"
	.string "¿vale? ¡Hasta otra!$"

MatchCall_PersonalizedText60:: @ 82AF671
	.string "Es un placer hablar con alguien\n"
	.string "tan joven como tú.\p"
	.string "Seguro que, cuando te hagas mayor,\n"
	.string "seguirán gustándote los Pokémon.\p"
	.string "Por cierto, ¿no te gustaría formar\n"
	.string "una pareja como la nuestra?\p"
	.string "Aunque, claro, {PLAYER}{KUN},\n"
	.string "tú ya cuentas con una relación\l"
	.string "de confianza con tus Pokémon.\p"
	.string "¡Ya sabes perfectamente lo que\n"
	.string "es una relación larga y fructífera!\p"
	.string "¡Ja, ja, ja!\n"
	.string "¡Que no decaiga!$"

MatchCall_PersonalizedText61:: @ 82AF7D8
	.string "¡Hola, aquí {STR_VAR_1}!\n"
	.string "¡Acabamos de ganar un combate!\p"
	.string "No solemos ganar, pero ha sido\n"
	.string "contra un Nadador muy guay.\p"
	.string "¡Mi hermana echaba chispas!\p"
	.string "¡Se hizo la débil para llamar\n"
	.string "la atención!\p"
	.string "Da igual que ganemos o perdamos,\n"
	.string "¡siempre me echa el sermón!\p"
	.string "{PLAYER}{KUN}, ¿por qué no le das\n"
	.string "un toque la próxima vez?\p"
	.string "¡Venga, hasta pronto!$"

MatchCall_PersonalizedText62:: @ 82AF8F7
	.string "Soy {STR_VAR_1}, sí.\n"
	.string "Ayer me hice al mar.\p"
	.string "Esperaba descubrir algunas ruinas\n"
	.string "nuevas en un sitio que prometía.\p"
	.string "Pero las olas me devolvían a la\n"
	.string "costa. No había manera, oye.\p"
	.string "Combatiendo tampoco he mejorado…\n"
	.string "Puedes reírte si quieres…,\l"
	.string "pero no pienso rendirme.\p"
	.string "¡Llegará el día en que descubra\n"
	.string "unas ruinas inexploradas!\p"
	.string "¡Eso es todo lo que te digo!\n"
	.string "¡Adiós por ahora!$"

MatchCall_PersonalizedText63:: @ 82AFA39
	.string "¡Hooola! ¡Soy yo, {STR_VAR_1}!\n"
	.string "¡Estoy por la Ruta 108!\l"
	.string "O sea, donde siempre.\p"
	.string "¡Hoy me he topado con una\n"
	.string "Nadadora espectacular!\l"
	.string "¡Parecía una sirena!\p"
	.string "¡La dejé alucinada con mi canto!\n"
	.string "¡Bueno, más bien con mi grito!\p"
	.string "¡Parece que no le gustó, porque\n"
	.string "me lanzó una mirada de arpía!\p"
	.string "¡Eso es todo desde la Ruta 108!\n"
	.string "¡Cambio y corto!$"

MatchCall_PersonalizedText64:: @ 82AFB26
	.string "¡Soy {STR_VAR_1}!\p"
	.string "Hoy estoy un pelín ocupada, pero\n"
	.string "supuse que querrías saber que…\l"
	.string "¡He ganado a cinco entrenadores!\p"
	.string "Si sigo así, creo que te voy a ganar\n"
	.string "la próxima vez que nos veamos.\p"
	.string "¡Será un combate digno de ver!\n"
	.string "¡Cuídate hasta ese día!$"

MatchCall_BattleFrontierStreakText1:: @ 82AFC07
	.string "¡Hola! Soy {STR_VAR_1}.\n"
	.string "¡Ya me ha llegado la noticia!\p"
	.string "¡Dicen que te has salido\n"
	.string "en {STR_VAR_2}!\p"
	.string "¡Es impresionante!\n"
	.string "¡¿{STR_VAR_3} victorias seguidas?!\l"
	.string "¡Pues sigue, sigue así!$"

MatchCall_BattleFrontierStreakText2:: @ 82AFC78
	.string "¡Hola, soy {STR_VAR_1}!\n"
	.string "¡Se habla mucho de ti!\p"
	.string "¡Y de tus {STR_VAR_3} victorias\n"
	.string "seguidas en {STR_VAR_2}!\p"
	.string "¡Guau! ¡A ver si me animo algún día!\n"
	.string "¡Cuídate!$"

MatchCall_BattleFrontierStreakText3:: @ 82AFCFF
	.string "¿Qué tal, {PLAYER}?\n"
	.string "Soy yo, {STR_VAR_1}.\p"
	.string "¡Ya me han dicho que estás\n"
	.string "creando escuela en ese sitio\l"
	.string "al que llaman {STR_VAR_2}!\p"
	.string "¡{STR_VAR_3} victorias seguidas!…\n"
	.string "Menudo récord, ¿no?\p"
	.string "¡A ver cuándo me acerco por ahí!\n"
	.string "¡Nos vemos!$"

MatchCall_BattleFrontierStreakText4:: @ 82AFDA7
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}. ¿Qué tal?\p"
	.string "Corre el rumor de que lograste\n"
	.string "{STR_VAR_3} victorias seguidas\l"
	.string "en {STR_VAR_2}.\p"
	.string "¡Será mejor que me aplique!\n"
	.string "¡Nos vemos!$"

MatchCall_BattleFrontierStreakText5:: @ 82AFE3D
	.string "¡Eh, {PLAYER}{KUN}!\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Que en {STR_VAR_2} ganaste\n"
	.string "{STR_VAR_3} veces seguidas?…\p"
	.string "¡Me lo estás poniendo difícil!\n"
	.string "¡Ya nos veremos!$"

MatchCall_BattleFrontierStreakText6:: @ 82AFECA
	.string "Ey, {PLAYER}{KUN}, hola.\n"
	.string "Soy {STR_VAR_1}. ¿Qué tal?\p"
	.string "Por cierto, dicen por ahí que has\n"
	.string "ganado {STR_VAR_3} veces seguidas\l"
	.string "en {STR_VAR_2}…\p"
	.string "¡Será mejor que me ponga las pilas!\n"
	.string "¡Nos vemos!$"

MatchCall_BattleFrontierStreakText7:: @ 82AFF64
	.string "Esto…, ¿{PLAYER}{KUN}?\n"
	.string "Soy yo, {STR_VAR_1}…\p"
	.string "Dicen que has estado en ese sitio\n"
	.string "al que llaman {STR_VAR_2}…\p"
	.string "Y que ganaste {STR_VAR_3} veces seguidas…\p"
	.string "¡Anda, un Pokémon muy raro!\n"
	.string "¡Te dejo! ¡Me tengo que ir!$"

MatchCall_BattleFrontierStreakText8:: @ 82AFFF0
	.string "Eh, {PLAYER}{KUN}, ¿cómo estás?\n"
	.string "Al habla {STR_VAR_1}.\l"
	.string "Espero que te vaya bien.\p"
	.string "¡Eh, ahora que lo pienso, dicen\n"
	.string "que ganaste {STR_VAR_3} veces seguidas\l"
	.string "en {STR_VAR_2}!\p"
	.string "¡Eso no se oye todos los días!\n"
	.string "¡A ver si me esfuerzo un poco más!$"

MatchCall_BattleFrontierStreakText9:: @ 82B00B5
	.string "¡Eh, {PLAYER}{KUN}, hola!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "¡Ya me lo han dicho!\n"
	.string "¡{STR_VAR_3} victorias seguidas en ese\l"
	.string "sitio llamado {STR_VAR_2}!\p"
	.string "¡Me dejas alucinada!\n"
	.string "¡A ver si me animo yo también!$"

MatchCall_BattleFrontierStreakText10:: @ 82B0129
	.string "Eh, {PLAYER}{KUN}, hola…\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Dicen que has ganado {STR_VAR_3} veces\n"
	.string "seguidas en ese lugar espantoso\l"
	.string "al que llaman {STR_VAR_2}.\p"
	.string "¡Eso está de maravilla!\n"
	.string "¡Voy a tener que aplicarme!$"

MatchCall_BattleFrontierStreakText11:: @ 82B01A5
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Dicen que eres el terror\n"
	.string "de ese sitio al que llaman\l"
	.string "{STR_VAR_2}.\p"
	.string "Ya has ganado, ¿cuántas,\n"
	.string "{STR_VAR_3} veces seguidas?\p"
	.string "¡Menuda carrera que llevas!\n"
	.string "¿Cuántas veces podría ganar yo?…$"

MatchCall_BattleFrontierStreakText12:: @ 82B0232
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy yo, {STR_VAR_1}.\l"
	.string "¿Qué tal estás?\p"
	.string "Me han hablado de ti, y de cómo\n"
	.string "lograste {STR_VAR_3} victorias seguidas\l"
	.string "en {STR_VAR_2}.\p"
	.string "¡Menuda historia!\n"
	.string "¡A ver cuándo nos vemos!$"

MatchCall_BattleFrontierStreakText13:: @ 82B02D9
	.string "¡Ah, hola, {PLAYER}{KUN}!\n"
	.string "¡Soy {STR_VAR_1}!\l"
	.string "Espero que te estés cuidando.\p"
	.string "Me han dicho que ganaste {STR_VAR_3}\n"
	.string "combates seguidos\l"
	.string "en {STR_VAR_2}.\p"
	.string "¡Cómo envidio tu energía!\n"
	.string "Hasta pronto.$"

MatchCall_BattleFrontierStreakText14:: @ 82B0366
	.string "Oh, hola, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¡Se habla mucho de ti y del lugar\n"
	.string "al que llaman {STR_VAR_2}!\p"
	.string "¿Es verdad que lograste {STR_VAR_3}\n"
	.string "victorias consecutivas allí?\p"
	.string "¡Eres una fuente de inspiración!\n"
	.string "¡Hasta otra!$"

MatchCall_BattleFrontierRecordStreakText1:: @ 82B03E6
	.string "¡Hola! Soy {STR_VAR_1}.\n"
	.string "¡Ya me ha llegado la noticia!\p"
	.string "¡Dicen que te has salido\n"
	.string "en {STR_VAR_2}!\p"
	.string "¡Es impresionante!\n"
	.string "¡¿{STR_VAR_3} victorias seguidas?!\l"
	.string "¡Pues sigue, sigue así!$"

MatchCall_BattleFrontierRecordStreakText2:: @ 82B0457
	.string "¡Hola, soy {STR_VAR_1}!\n"
	.string "¡Se habla mucho de ti!\p"
	.string "¡Y de tus {STR_VAR_3} victorias\n"
	.string "seguidas en {STR_VAR_2}!\p"
	.string "¡Guau! ¡A ver si me animo algún día!\n"
	.string "¡Cuídate!$"

MatchCall_BattleFrontierRecordStreakText3:: @ 82B04DE
	.string "¿Qué tal, {PLAYER}?\n"
	.string "Soy yo, {STR_VAR_1}.\p"
	.string "¡Ya me han dicho que estás\n"
	.string "creando escuela en ese sitio\l"
	.string "al que llaman {STR_VAR_2}!\p"
	.string "¡{STR_VAR_3} victorias seguidas!…\n"
	.string "Menudo récord, ¿no?\p"
	.string "¡A ver cuándo me acerco por ahí!\n"
	.string "¡Nos vemos!$"

MatchCall_BattleFrontierRecordStreakText4:: @ 82B0586
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}. ¿Qué tal?\p"
	.string "Corre el rumor de que lograste\n"
	.string "{STR_VAR_3} victorias seguidas\l"
	.string "en {STR_VAR_2}.\p"
	.string "¡Será mejor que me aplique!\n"
	.string "¡Nos vemos!$"

MatchCall_BattleFrontierRecordStreakText5:: @ 82B061C
	.string "¡Eh, {PLAYER}{KUN}!\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Que en {STR_VAR_2} ganaste\n"
	.string "{STR_VAR_3} veces seguidas?…\p"
	.string "¡Me lo estás poniendo difícil!\n"
	.string "¡Ya nos veremos!$"

MatchCall_BattleFrontierRecordStreakText6:: @ 82B06A3
	.string "Ey, {PLAYER}{KUN}, hola.\n"
	.string "Soy {STR_VAR_1}. ¿Qué tal?\p"
	.string "Por cierto, dicen por ahí que has\n"
	.string "ganado {STR_VAR_3} veces seguidas\l"
	.string "en {STR_VAR_2}…\p"
	.string "¡Será mejor que me ponga las pilas!\n"
	.string "¡Nos vemos!$"

MatchCall_BattleFrontierRecordStreakText7:: @ 82B073B
	.string "Esto…, ¿{PLAYER}{KUN}?\n"
	.string "Soy yo, {STR_VAR_1}…\p"
	.string "Dicen que has estado en ese sitio\n"
	.string "al que llaman {STR_VAR_2}…\p"
	.string "Y que ganaste {STR_VAR_3} veces seguidas…\p"
	.string "¡Anda, un Pokémon muy raro!\n"
	.string "¡Te dejo! ¡Me tengo que ir!$"

MatchCall_BattleFrontierRecordStreakText8:: @ 82B07C7
	.string "Oh, {PLAYER}{KUN}, ¿cómo estás?\n"
	.string "Al habla {STR_VAR_1}.\l"
	.string "Espero que te vaya bien.\p"
	.string "¡Eh, ahora que lo pienso, dicen que\n"
	.string "ganaste {STR_VAR_3} veces seguidas\l"
	.string "en {STR_VAR_2}!\p"
	.string "¡Eso no se oye todos los días!\n"
	.string "¡A ver si me esfuerzo un poco más!$"

MatchCall_BattleFrontierRecordStreakText9:: @ 82B0894
	.string "¡Eh, {PLAYER}{KUN}, hola!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "¡Ya me lo han dicho!\n"
	.string "¡{STR_VAR_3} victorias seguidas en ese\l"
	.string "lugar llamado {STR_VAR_2}!\p"
	.string "¡Me dejas alucinada!\n"
	.string "¡A ver si me animo yo también!$"

MatchCall_BattleFrontierRecordStreakText10:: @ 82B0908
	.string "Eh, {PLAYER}{KUN}, hola…\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Dicen que has ganado {STR_VAR_3} veces\n"
	.string "seguidas en ese lugar espantoso\l"
	.string "al que llaman {STR_VAR_2}…\p"
	.string "¡Eso está de maravilla!\n"
	.string "¡Voy a tener que aplicarme!$"

MatchCall_BattleFrontierRecordStreakText11:: @ 82B0984
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Dicen que eres el terror\n"
	.string "de ese sitio al que llaman\l"
	.string "{STR_VAR_2}.\p"
	.string "Ya has ganado, ¿cuántas,\n"
	.string "{STR_VAR_3} veces seguidas?\p"
	.string "¡Menuda carrera que llevas!\n"
	.string "¿Cuántas veces podría ganar yo?…$"

MatchCall_BattleFrontierRecordStreakText12:: @ 82B0A11
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy yo, {STR_VAR_1}.\l"
	.string "¿Qué tal estás?\p"
	.string "Mi vecina me dice que ganaste\n"
	.string "{STR_VAR_3} veces seguidas en un lugar\l"
	.string "al que llaman {STR_VAR_2}…\p"
	.string "¡Menuda historia!\n"
	.string "¡A ver cuándo nos vemos!$"

MatchCall_BattleFrontierRecordStreakText13:: @ 82B0AB8
	.string "¡Ah, hola, {PLAYER}{KUN}!\n"
	.string "¡Soy {STR_VAR_1}!\l"
	.string "Espero que te estés cuidando.\p"
	.string "Dicen que has conseguido ganar\n"
	.string "{STR_VAR_3} veces seguidas en ese lugar\l"
	.string "al que llaman {STR_VAR_2}.\p"
	.string "¡Cómo envidio tu energía!\n"
	.string "Hasta pronto.$"

MatchCall_BattleFrontierRecordStreakText14:: @ 82B0B45
	.string "Oh, hola, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\l"
	.string "¡Me han hablado de ti!\p"
	.string "¿Es verdad que en ese sitio\n"
	.string "al que llaman {STR_VAR_2} has\l"
	.string "ganado {STR_VAR_3} veces seguidas?\p"
	.string "¡Eres una fuente de inspiración!\n"
	.string "¡Hasta otra!$"

MatchCall_BattleDomeText1:: @ 82B0BC5
	.string "¡Hola! ¿{PLAYER}?\n"
	.string "Hola, soy {STR_VAR_1}.\l"
	.string "¡Ya me ha llegado la noticia!\p"
	.string "¡Has logrado el campeonato\n"
	.string "de {STR_VAR_2} nada menos\l"
	.string "que {STR_VAR_3} veces!\p"
	.string "¡Alucinante! ¡Ya me sacas ventaja!\n"
	.string "¡Hasta pronto!$"

MatchCall_BattleDomeText2:: @ 82B0C4A
	.string "¡Hola, soy {STR_VAR_1}!\n"
	.string "¡Me han hablado de ti!\p"
	.string "Dicen que has ganado {STR_VAR_3} títulos\n"
	.string "en ese horror al que llaman\l"
	.string "{STR_VAR_2}.\p"
	.string "¡Impresionante! No sé si yo\n"
	.string "tendré valor para tanto…$"

MatchCall_BattleDomeText3:: @ 82B0CC7
	.string "¡Eh, hola, {PLAYER}!\n"
	.string "Te habla {STR_VAR_1}.\l"
	.string "¿Cómo te va?\p"
	.string "¡Dicen que ya has ganado\n"
	.string "{STR_VAR_3} eventos en ese sitio\l"
	.string "al que llaman {STR_VAR_2}!\p"
	.string "¡Venga, a por otro!\n"
	.string "¡Nos veremos pronto!$"

MatchCall_BattleDomeText4:: @ 82B0D4A
	.string "Eh, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "He oído que has conseguido\n"
	.string "{STR_VAR_3} campeonatos en ese sitio\l"
	.string "al que llaman {STR_VAR_2}.\p"
	.string "Parece que te lo estás currando.\n"
	.string "¡A ver si me aplico el cuento!$"

MatchCall_BattleDomeText5:: @ 82B0DC8
	.string "¡Eh, {PLAYER}{KUN}!\n"
	.string "Soy yo, {STR_VAR_1}.\p"
	.string "He oído que has ganado\n"
	.string "{STR_VAR_3} veces seguidas\l"
	.string "en {STR_VAR_2}.\p"
	.string "¡Voy a tener que ponerme en serio!\n"
	.string "¡Nos vemos!$"

MatchCall_BattleDomeText6:: @ 82B0E35
	.string "Ey, {PLAYER}{KUN}, hola.\n"
	.string "Soy {STR_VAR_1}. ¿Qué tal?\p"
	.string "Por cierto, he oído que ya tienes\n"
	.string "{STR_VAR_3} campeonatos de ese lugar\l"
	.string "al que llaman {STR_VAR_2}.\p"
	.string "¡Voy a tener que entrenar a mis\n"
	.string "Pokémon o te me vas a escapar!$"

MatchCall_BattleDomeText7:: @ 82B0ED1
	.string "¿{PLAYER}{KUN}?\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Que en {STR_VAR_2} has\n"
	.string "ganado {STR_VAR_3} campeonatos?\p"
	.string "Estupendo. Por cierto, ¿has pillado\n"
	.string "últimamente algún Pokémon raro?\p"
	.string "Ah, vale.\n"
	.string "Muy bien, adiós.$"

MatchCall_BattleDomeText8:: @ 82B0F72
	.string "Eh, {PLAYER}{KUN}, ¿cómo estás?\n"
	.string "Al habla {STR_VAR_1}.\l"
	.string "Espero que te vaya bien.\p"
	.string "He oído que ya tienes {STR_VAR_3} títulos\n"
	.string "de {STR_VAR_2} en el bolsillo.\p"
	.string "A ver si me pongo a entrenar ya.\n"
	.string "¡Nos veremos!$"

MatchCall_BattleDomeText9:: @ 82B102A
	.string "¡Eh, {PLAYER}{KUN}, hola!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "¡Ya me han contado lo de tus {STR_VAR_3}\n"
	.string "campeonatos en {STR_VAR_2}!\p"
	.string "¡Me dejas alucinada!\n"
	.string "¡A ver si me animo yo también!$"

MatchCall_BattleDomeText10:: @ 82B10A7
	.string "Oh, {PLAYER}{KUN}, hola.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Que has ganado {STR_VAR_3} veces\n"
	.string "seguidas en {STR_VAR_2}?\p"
	.string "¡Eso está de maravilla!\n"
	.string "¡Voy a tener que aplicarme!$"

MatchCall_BattleDomeText11:: @ 82B1121
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Dicen que eres el terror\n"
	.string "de ese sitio al que llaman\l"
	.string "{STR_VAR_2}.\p"
	.string "Ya has ganado, ¿cuántas,\n"
	.string "{STR_VAR_3} veces seguidas?\p"
	.string "Me pregunto si alguna vez podré\n"
	.string "llegar a ser yo el campeón…\p"
	.string "¿Lo ves bastante improbable?\n"
	.string "¡Bueno, nos vemos!$"

MatchCall_BattleDomeText12:: @ 82B11D3
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy yo, {STR_VAR_1}.\l"
	.string "¿Qué tal estás?\p"
	.string "¿Que has ganado {STR_VAR_3} eventos en un\n"
	.string "lugar llamado {STR_VAR_2}?\p"
	.string "¡Menuda historia!\n"
	.string "¡A ver cuándo nos vemos!$"

MatchCall_BattleDomeText13:: @ 82B124D
	.string "¡Ah, hola, {PLAYER}{KUN}!\n"
	.string "¡Soy {STR_VAR_1}!\l"
	.string "Espero que te estés cuidando.\p"
	.string "Dicen que has ganado {STR_VAR_3} eventos\n"
	.string "en {STR_VAR_2}, ¿es verdad?\p"
	.string "¡Cómo envidio tu energía!\n"
	.string "Hasta pronto.$"

MatchCall_BattleDomeText14:: @ 82B12D0
	.string "Ah, hola, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\l"
	.string "¡Me han hablado de ti!\p"
	.string "¿Es verdad lo de tus {STR_VAR_3}\n"
	.string "títulos en {STR_VAR_2}?\p"
	.string "¡Eres una fuente de inspiración!\n"
	.string "¡Hasta otra!$"

MatchCall_BattlePikeText1:: @ 82B1347
	.string "¡Hola! ¿{PLAYER}?\n"
	.string "Hola, soy {STR_VAR_1}.\l"
	.string "¡Ya me ha llegado la noticia!\p"
	.string "¡Has pasado {STR_VAR_3} salas\n"
	.string "en {STR_VAR_2}!\p"
	.string "¡Impresionante!\n"
	.string "¡Hasta luego!$"

MatchCall_BattlePikeText2:: @ 82B13B1
	.string "¡Hola, soy {STR_VAR_1}!\n"
	.string "¡Se habla mucho de ti!\p"
	.string "Dicen que has logrado pasar\n"
	.string "{STR_VAR_3} salas en {STR_VAR_2}.\p"
	.string "¡Voy a tener que esforzarme!\n"
	.string "¡Adiós!$"

MatchCall_BattlePikeText3:: @ 82B142B
	.string "¿Qué tal, {PLAYER}?\n"
	.string "Soy yo, {STR_VAR_1}. \l"
	.string "¿Cómo te va?\p"
	.string "¡He oído que has pasado\n"
	.string "{STR_VAR_3} salas en {STR_VAR_2}!\p"
	.string "¡Mucha suerte para la próxima vez!\n"
	.string "¡Y a ver si nos vemos!$"

MatchCall_BattlePikeText4:: @ 82B14B4
	.string "Eh, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Dicen por ahí que has pasado {STR_VAR_3}\n"
	.string "salas en {STR_VAR_2}.\p"
	.string "¡Será mejor que me ponga yo\n"
	.string "también a entrenar en serio!$"

MatchCall_BattlePikeText5:: @ 82B1525
	.string "¡Hola, {PLAYER}{KUN}!\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Me han dicho que has pasado\n"
	.string "{STR_VAR_3} salas en {STR_VAR_2}.\p"
	.string "¡Voy a tener que ponerme en serio!\n"
	.string "¡Nos vemos!$"

MatchCall_BattlePikeText6:: @ 82B158E
	.string "Ey, {PLAYER}{KUN}, hola.\n"
	.string "Soy {STR_VAR_1}. ¿Qué tal?\p"
	.string "Por cierto, corre el rumor\n"
	.string "de que has pasado {STR_VAR_3} salas\l"
	.string "en {STR_VAR_2}.\p"
	.string "¡Voy a tener que entrenar a mis\n"
	.string "Pokémon o te me vas a escapar!$"

MatchCall_BattlePikeText7:: @ 82B1622
	.string "¿{PLAYER}{KUN}?\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Cómo? ¿Que has estado\n"
	.string "en {STR_VAR_2} y has pasado\l"
	.string "{STR_VAR_3} salas?\p"
	.string "¡Eso mola un montón!\p"
	.string "¡Anda, un Pokémon muy raro!\n"
	.string "¡Te dejo!$"

MatchCall_BattlePikeText8:: @ 82B169D
	.string "Eh, {PLAYER}{KUN}, ¿cómo estás?\n"
	.string "Al habla {STR_VAR_1}.\l"
	.string "Espero que te vaya bien.\p"
	.string "He oído que has pasado {STR_VAR_3} salas\n"
	.string "en {STR_VAR_2}.\p"
	.string "¡Es impresionante!\n"
	.string "A ver si me pongo a entrenar ya.\l"
	.string "¡Nos vemos!$"

MatchCall_BattlePikeText9:: @ 82B1775
	.string "¡Eh, {PLAYER}{KUN}, hola!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "¡Ya me lo han dicho!\n"
	.string "¡Que te has pasado {STR_VAR_3}\l"
	.string "salas en {STR_VAR_2}!\p"
	.string "¡Me dejas alucinada!\n"
	.string "¡A ver si me animo yo también!$"

MatchCall_BattlePikeText10:: @ 82B17F8
	.string "Eh, {PLAYER}{KUN}, hola.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Te has pasado {STR_VAR_3} salas\n"
	.string "en {STR_VAR_2}?\p"
	.string "¡Eso está de maravilla!\n"
	.string "¡Voy a tener que aplicarme!$"

MatchCall_BattlePikeText11:: @ 82B1877
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Dicen que eres el terror\n"
	.string "de {STR_VAR_2}.\p"
	.string "¿Cuántas salas van ya? ¿{STR_VAR_3}?\n"
	.string "Guau, eso no se oye todos los días.\p"
	.string "Me pregunto si yo podría pasar\n"
	.string "todas las salas…\p"
	.string "¿Lo ves bastante improbable?\n"
	.string "¡Bueno, nos vemos!$"

MatchCall_BattlePikeText12:: @ 82B1946
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy yo, {STR_VAR_1}.\l"
	.string "¿Qué tal estás?\p"
	.string "¿Que te has pasado {STR_VAR_3} salas\n"
	.string "en {STR_VAR_2}?\p"
	.string "¡Menuda historia!\n"
	.string "¡A ver cuándo nos vemos!$"

MatchCall_BattlePikeText13:: @ 82B19C7
	.string "¡Ah, hola, {PLAYER}{KUN}!\n"
	.string "¡Soy {STR_VAR_1}!\l"
	.string "Espero que te estés cuidando.\p"
	.string "Dicen que has pasado {STR_VAR_3} salas\n"
	.string "en {STR_VAR_2}, ¿es verdad?\p"
	.string "¡Cómo envidio tu energía!\n"
	.string "Hasta pronto.$"

MatchCall_BattlePikeText14:: @ 82B1A4C
	.string "Eh, hola, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\l"
	.string "¡Me han hablado de ti!\p"
	.string "¿De verdad te has pasado\n"
	.string "{STR_VAR_3} salas en {STR_VAR_2}?\p"
	.string "¡Eres una fuente de inspiración!\n"
	.string "¡Hasta otra!$"

MatchCall_BattlePyramidText1:: @ 82B1ACA
	.string "¡Hola! ¿{PLAYER}?\n"
	.string "Hola, soy {STR_VAR_1}.\l"
	.string "¡Ya me ha llegado la noticia!\p"
	.string "Has subido {STR_VAR_3} niveles\n"
	.string "dentro de {STR_VAR_2}, ¿eh?\p"
	.string "¡A-lu-ci-nan-te!\n"
	.string "¡Debería probar yo!$"

MatchCall_BattlePyramidText2:: @ 82B1B50
	.string "¡Hola, soy {STR_VAR_1}!\n"
	.string "¡Se habla mucho de ti!\p"
	.string "Dicen que has conseguido subir\n"
	.string "{STR_VAR_3} niveles en {STR_VAR_2}.\p"
	.string "¡Genial!\n"
	.string "¡A ver si espabilo!$"

MatchCall_BattlePyramidText3:: @ 82B1BE4
	.string "¡Eh, hola, {PLAYER}!\n"
	.string "Te habla {STR_VAR_1}.\l"
	.string "¿Cómo te va?\p"
	.string "Conque ya has subido {STR_VAR_3} niveles\n"
	.string "en {STR_VAR_2}, ¿eh?\p"
	.string "¡Venga, a ver si puedes superarte!\n"
	.string "¡Y a ver si nos vemos!$"

MatchCall_BattlePyramidText4:: @ 82B1C6A
	.string "Eh, {PLAYER}{KUN}.\n"
	.string "Al habla {STR_VAR_1}.\p"
	.string "He oído que has subido\n"
	.string "{STR_VAR_3} niveles en {STR_VAR_2}.\p"
	.string "¡Espero que no sea demasiado\n"
	.string "tarde para alcanzarte!$"

MatchCall_BattlePyramidText5:: @ 82B1CCF
	.string "¡Hola, {PLAYER}{KUN}!\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Me han dicho que has subido\n"
	.string "{STR_VAR_3} niveles en {STR_VAR_2}.\p"
	.string "¡Voy a tener que ponerme en serio!\n"
	.string "¡Nos vemos!$"

MatchCall_BattlePyramidText6:: @ 82B1D38
	.string "Ey, {PLAYER}{KUN}, hola.\n"
	.string "Soy {STR_VAR_1}. ¿Qué tal?\p"
	.string "Por cierto, dicen que has subido\n"
	.string "{STR_VAR_3} niveles en {STR_VAR_2}.\p"
	.string "¡Voy a tener que entrenar a mis\n"
	.string "Pokémon o te me vas a escapar!$"

MatchCall_BattlePyramidText7:: @ 82B1DCD
	.string "¿{PLAYER}{KUN}?\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Es verdad que has subido\n"
	.string "{STR_VAR_3} niveles en {STR_VAR_2}?\p"
	.string "Estupendo. Oye, ¿no habrás pillado\n"
	.string "últimamente algún Pokémon raro?\p"
	.string "No, ¿eh?\n"
	.string "Vale, adiós.$"

MatchCall_BattlePyramidText8:: @ 82B1E4B
	.string "Eh, {PLAYER}{KUN}, ¿cómo estás?\n"
	.string "Al habla {STR_VAR_1}.\l"
	.string "Espero que te vaya bien.\p"
	.string "He oído que has subido\n"
	.string "{STR_VAR_3} niveles en {STR_VAR_2}.\p"
	.string "¡Es impresionante!\n"
	.string "A ver si me pongo a entrenar ya.\l"
	.string "¡Nos vemos!$"

MatchCall_BattlePyramidText9:: @ 82B1F24
	.string "¡Eh, {PLAYER}{KUN}, hola!\n"
	.string "¡Soy {STR_VAR_1}!\p"
	.string "¡Ya me lo han contado!\n"
	.string "¡Que has subido {STR_VAR_3} niveles\l"
	.string "en {STR_VAR_2}!\p"
	.string "¡Me dejas alucinada!\n"
	.string "¡A ver si me animo yo también!$"

MatchCall_BattlePyramidText10:: @ 82B1FA8
	.string "Eh, {PLAYER}{KUN}, hola.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "¿Que has subido {STR_VAR_3}\n"
	.string "niveles en {STR_VAR_2}?\p"
	.string "¡Eso está de maravilla!\n"
	.string "¡Voy a tener que aplicarme!$"

MatchCall_BattlePyramidText11:: @ 82B2022
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\p"
	.string "Dicen que eres el terror\n"
	.string "de {STR_VAR_2}.\p"
	.string "¿Cuántos niveles van ya? ¿{STR_VAR_3}?\n"
	.string "Guau, eso no se oye todos los días.\p"
	.string "Me preguntaba si podría llegar\n"
	.string "yo alguna vez arriba del todo…\p"
	.string "¿Lo ves bastante improbable?\n"
	.string "¡Bueno, nos vemos!$"

MatchCall_BattlePyramidText12:: @ 82B20F3
	.string "Hola, {PLAYER}{KUN}.\n"
	.string "Soy yo, {STR_VAR_1}.\l"
	.string "¿Qué tal estás?\p"
	.string "¿Es verdad que has subido\n"
	.string "{STR_VAR_3} niveles en un lugar\l"
	.string "llamado {STR_VAR_2}?\p"
	.string "¡Menuda historia!\n"
	.string "¡A ver cuándo nos vemos!$"

MatchCall_BattlePyramidText13:: @ 82B2175
	.string "¡Ah, hola, {PLAYER}{KUN}!\n"
	.string "¡Soy {STR_VAR_1}!\l"
	.string "Espero que te estés cuidando.\p"
	.string "Dicen que has subido {STR_VAR_3} niveles\n"
	.string "en {STR_VAR_2}, ¿es verdad?\p"
	.string "¡Cómo envidio tu energía!\n"
	.string "Hasta pronto.$"

MatchCall_BattlePyramidText14:: @ 82B21FC
	.string "Oh, hola, {PLAYER}{KUN}.\n"
	.string "Soy {STR_VAR_1}.\l"
	.string "¡Me han hablado de ti!\p"
	.string "¡No!… ¿De verdad has subido ya\n"
	.string "{STR_VAR_3} niveles en {STR_VAR_2}?\p"
	.string "¡Eres una fuente de inspiración!\n"
	.string "¡Hasta otra!$"

MatchCall_Text_Mom1:: @ 82B227B
	.string "Mamá: Tu padre y tú…\n"
	.string "Estáis embobados con los Pokémon.\p"
	.string "¿Qué es lo que tienen los Pokémon\n"
	.string "que gustan tantísimo?\p"
	.string "¿A mí?\n"
	.string "Sí, bueno, a mí me gustan los que\l"
	.string "me ayudan en el día a día, claro.$"

MatchCall_Text_Mom2:: @ 82B2310
	.string "Mamá: ¡Hola, {PLAYER}!\n"
	.string "Tu padre sigue encerrado\l"
	.string "en el gimnasio de Petalia.\p"
	.string "Viene a casa de vez en cuando,\n"
	.string "pero para darse una comilona e\l"
	.string "irse volando de nuevo al Gimnasio.\p"
	.string "Este hombre…, desde que le ganaste\n"
	.string "tiene el orgullo por los suelos.$"

MatchCall_Text_Mom3:: @ 82B23F3
	.string "Mamá: {PLAYER}…\n"
	.string "No te preocupes por mí\l"
	.string "ni por la casa.\p"
	.string "Y no te quites las deportivas\n"
	.string "hasta que no se te rompan, cariño.$"

MatchCall_Text_Roxanne1:: @ 82B2456
	.string "Petra: ¡Anda, hola, {PLAYER}!\p"
	.string "Desde que nos vimos,\n"
	.string "no he dejado de entrenarme.\p"
	.string "Aún voy a tardar en poner\n"
	.string "el Gimnasio a punto.\p"
	.string "Pero, cuando esté listo,\n"
	.string "¡ven a verme para luchar otra vez!$"

MatchCall_Text_Roxanne2:: @ 82B250E
	.string "Petra: ¿{PLAYER}, eres tú?\n"
	.string "¡Enhorabuena!\l"
	.string "¡Todo el mundo habla de ti!\p"
	.string "¿Yo? No, aún voy a tardar en poner\n"
	.string "el Gimnasio a punto.\p"
	.string "Pero, cuando esté listo,\n"
	.string "¡ven a verme para luchar otra vez!$"

MatchCall_Text_Roxanne3:: @ 82B25C1
	.string "Petra: ¡{PLAYER}!\n"
	.string "¡Ya está listo mi gimnasio!\p"
	.string "¡A ver cuándo puedes venirte\n"
	.string "por ciudad Férrica!$"

MatchCall_Text_Roxanne4:: @ 82B2607
	.string "Petra: {PLAYER}, en el gimnasio\n"
	.string "de ciudad Férrica, luchar\l"
	.string "es una cuestión de orgullo.$"

MatchCall_Text_Brawly1:: @ 82B2659
	.string "Marcial: ¡Eh, hola, {PLAYER}{KUN}!\p"
	.string "He aprendido mucho de nuestro\n"
	.string "combate.\p"
	.string "Quiero prepararme antes de volver\n"
	.string "a poner el Gimnasio en marcha.\p"
	.string "Voy a tardar en recuperar\n"
	.string "fuerzas para llevar el Gimnasio.\p"
	.string "Pero, si consigo organizarlo\n"
	.string "todo bien, me gustaría luchar\l"
	.string "contigo de nuevo.$"

MatchCall_Text_Brawly2:: @ 82B275D
	.string "Marcial: ¡Eh, {PLAYER}{KUN}!\n"
	.string "¡Enhorabuena!\p"
	.string "¡No dejan de llegar noticias sobre\n"
	.string "tus éxitos!\p"
	.string "Me parece a mí que me hace falta\n"
	.string "entrenarme mucho más.\p"
	.string "Voy a tardar en recuperar\n"
	.string "fuerzas para llevar el Gimnasio.\p"
	.string "Pero, si consigo organizarlo\n"
	.string "todo bien, me gustaría luchar\l"
	.string "contigo de nuevo.$"

MatchCall_Text_Brawly3:: @ 82B286F
	.string "Marcial: ¡Eh, {PLAYER}{KUN}!\n"
	.string "¡Mi Gimnasio está como nunca!\p"
	.string "¡A ver si te acercas por Azuliza\n"
	.string "y luchamos un rato!$"

MatchCall_Text_Brawly4:: @ 82B28D1
	.string "Marcial: {PLAYER}{KUN}, no creo que\n"
	.string "me aburra nunca de luchar contigo.$"

MatchCall_Text_Wattson1:: @ 82B2912
	.string "Erico: ¡Anda, eres tú!\p"
	.string "Cuando te marchaste, reciclé\n"
	.string "mi sistema de entrenamiento.\p"
	.string "Voy a tomarme mi tiempo antes\n"
	.string "de seguir con el Gimnasio.\p"
	.string "¡Así que ya te avisaré!\n"
	.string "¡Je, je, je, je!$"

MatchCall_Text_Wattson2:: @ 82B29CA
	.string "Erico: ¡Eh, je, je, je!\p"
	.string "Estás imparable, ¿eh?\n"
	.string "¡Estás en boca de todos!\p"
	.string "Yo creo que aún me falta un poco.\p"
	.string "Voy a tomarme mi tiempo antes\n"
	.string "de seguir con el Gimnasio.\p"
	.string "¡Así que ya te avisaré!\n"
	.string "¡Je, je, je, je!$"

MatchCall_Text_Wattson3:: @ 82B2AB6
	.string "Erico: ¡Eh, oye!\n"
	.string "¡El Gimnasio ya está!\p"
	.string "¡Vente a Malvalona cuando\n"
	.string "quieras! ¡Ja, ja, ja, ja!$"

MatchCall_Text_Wattson4:: @ 82B2B01
	.string "Erico: ¡Ja, ja, ja, ja!\p"
	.string "¡Luchar contigo resulta siempre\n"
	.string "electrizante!$"

MatchCall_Text_Flannery1:: @ 82B2B4D
	.string "Candela: {PLAYER}…\p"
	.string "Cuando luchamos, me di cuenta\n"
	.string "de lo mucho que me queda\l"
	.string "por aprender.\p"
	.string "Y aún me falta…\p"
	.string "Debo entrenarme de otra forma\n"
	.string "para poder estar al frente\l"
	.string "del Gimnasio.\p"
	.string "Espero, {PLAYER}, que volvamos\n"
	.string "a enfrentarnos cuando esté lista.$"

MatchCall_Text_Flannery2:: @ 82B2C0E
	.string "Candela: Hola, ¿{PLAYER}?\n"
	.string "¡Enhorabuena!\p"
	.string "¡Todo el mundo compara tu fuerza\n"
	.string "con el ímpetu de un volcán!\p"
	.string "Por aquí, todo bien, entrenando.\p"
	.string "Cuando el gimnasio esté a punto de\n"
	.string "caramelo, verás una marca junto a\l"
	.string "mi nombre en tu agenda del móvil.$"

MatchCall_Text_Flannery3:: @ 82B2CF1
	.string "Candela: Eh, ¿{PLAYER}?\n"
	.string "¡Ya está listo el gimnasio!\p"
	.string "¡Pásate por Lavacalda para darte\n"
	.string "un bañito en los baños termales\l"
	.string "y combatir conmigo!$"

MatchCall_Text_Flannery4:: @ 82B2D54
	.string "Candela: {PLAYER}…\n"
	.string "Estoy convencida de que cada vez\l"
	.string "vas a entrenar mejor.$"

MatchCall_Text_Winona1:: @ 82B2DA4
	.string "Alana: ¡Hola, {PLAYER}!\p"
	.string "Gracias a nuestro combate,\n"
	.string "he podido ver mis puntos débiles.\p"
	.string "Cuando vuelva a estar lista para\n"
	.string "el Gimnasio, ¡no darás con ellos!$"

MatchCall_Text_Winona2:: @ 82B2E2B
	.string "Alana: ¡Muy bien, {PLAYER}!\p"
	.string "¡Las noticias sobre tu victoria\n"
	.string "en la Liga Pokémon han llegado\l"
	.string "volando a ciudad Arborada!\p"
	.string "Pero… la próxima vez que luchemos,\n"
	.string "no creo que salgas tan bien…$"

MatchCall_Text_Winona3:: @ 82B2EC2
	.string "Alana: ¿Eres {PLAYER}?\n"
	.string "¡Nuestro gimnasio está en marcha!\p"
	.string "¡Te esperamos en ciudad Arborada!$"

MatchCall_Text_Winona4:: @ 82B2F16
	.string "Alana: {PLAYER}…\n"
	.string "A mí no se me caen las alas\l"
	.string "por perder…\p"
	.string "Exacto, como tú tampoco pierdes\n"
	.string "de vista tus sueños.$"

MatchCall_Text_TateLiza1:: @ 82B2F97
	.string "Vito: ¡Anda, es…!\n"
	.string "Leti: ¡{PLAYER}!\p"
	.string "Vito: Estamos entrenándonos\n"
	.string "de nuevo…\l"
	.string "Leti: ¡Para darlo todo\l"
	.string "en el Gimnasio!\p"
	.string "Vito: Cuando estemos listos…\n"
	.string "Leti: Cuando estemos listos…\p"
	.string "Vito: Aparecerá una marca junto\n"
	.string "a nuestro nombre…\l"
	.string "Leti: En tu agenda del móvil.$"

MatchCall_Text_TateLiza2:: @ 82B306E
	.string "Vito: ¡{PLAYER}, enhorabuena!\n"
	.string "Leti: ¡{PLAYER}, enhorabuena!\p"
	.string "Vito: Aún estamos…\n"
	.string "Leti: ¡Aún estamos entrenándonos!\p"
	.string "Vito: Pero todavía nos falta…\n"
	.string "Leti: Cuando estemos listos…\p"
	.string "Vito: Aparecerá una marca junto\n"
	.string "a nuestro nombre…\l"
	.string "Leti: En tu agenda del móvil.$"

MatchCall_Text_TateLiza3:: @ 82B3158
	.string "Vito: ¡{PLAYER}!\n"
	.string "Leti: ¡{PLAYER}!\p"
	.string "Vito: ¡El gimnasio ya está!\n"
	.string "Leti: ¡El gimnasio ya está!\p"
	.string "Vito: Podrías venir a vernos…\n"
	.string "Leti: ¡Te esperamos en Algaria!$"

MatchCall_Text_TateLiza4:: @ 82B31CD
	.string "Vito: {PLAYER}, nuestro combate…\n"
	.string "Leti: Es una experiencia sin igual.\p"
	.string "Vito: No estaría mal…\n"
	.string "Leti: ¡Que lucháramos de nuevo!$"

MatchCall_Text_Juan1:: @ 82B3249
	.string "Galano: Mmm…\n"
	.string "Te llamabas {PLAYER}{KUN}, ¿no?\p"
	.string "Nuestro combate…\n"
	.string "Me recordó a la primera vez\l"
	.string "que me enfrenté con Plubio.\p"
	.string "¡A ver si va a resultar que eres\n"
	.string "mejor que Plubio!$"

MatchCall_Text_Juan2:: @ 82B32EC
	.string "Galano: Je, je… {PLAYER}{KUN}…\n"
	.string "Por fin has logrado lo que querías.\p"
	.string "Yo sabía que tenía buen ojo para\n"
	.string "las promesas como tú…\p"
	.string "Luchemos de nuevo. Estás en\n"
	.string "lo más en lo que a posibilidades\l"
	.string "y prestigio se refiere.$"

MatchCall_Text_Juan3:: @ 82B33AA
	.string "Galano: Eh, je, je… {PLAYER}{KUN}…\p"
	.string "El gimnasio de Arrecípolis\n"
	.string "está a tu disposición.\p"
	.string "Si quieres que nos veamos,\n"
	.string "aquí estoy.$"

MatchCall_Text_Juan4:: @ 82B341E
	.string "Galano: {PLAYER}{KUN}…\p"
	.string "Como la buena música, nuestros\n"
	.string "combates resuenan en mí como\l"
	.string "auténtica fuente de inspiración…\p"
	.string "Cuando cierro los ojos, te veo\n"
	.string "componer tu estrategia marcando\l"
	.string "un ritmo ineludible…$"

MatchCall_Text_Sidney:: @ 82B34CC
	.string "Sixto: ¡Eh, {PLAYER}!\p"
	.string "Si quieres luchar conmigo\n"
	.string "de nuevo, vuelve cuando quieras\l"
	.string "a la Liga Pokémon.\p"
	.string "¡De aquí no me muevo!\n"
	.string "¡Aquí te espero!$"

MatchCall_Text_Phoebe:: @ 82B3561
	.string "Fátima: ¡Hola, {PLAYER}!\p"
	.string "¿Por qué no vuelves por aquí?\p"
	.string "Me encantaría ver cómo\n"
	.string "has estrechado el lazo\l"
	.string "con tus Pokémon.$"

MatchCall_Text_Glacia:: @ 82B35E4
	.string "Nívea: Hola, {PLAYER}.\p"
	.string "Imagino que aún querrás\n"
	.string "aumentar tu fuerza.\p"
	.string "Pues, si te apetece, podríamos\n"
	.string "vernos en la Liga Pokémon\l"
	.string "para templar los ánimos un poco…$"

MatchCall_Text_Drake:: @ 82B368B
	.string "Dracón: Tu voz me suena…\n"
	.string "Eres {PLAYER}, ¿no?\l"
	.string "Se te oye muy alegre…\p"
	.string "Tengo entendido que hay un sitio\n"
	.string "llamado Frente de batalla\l"
	.string "en el que se pone a prueba\l"
	.string "a algunos Entrenadores.\p"
	.string "Con todo, si quieres combates\n"
	.string "de verdad, ¡ya sabes cómo es\l"
	.string "la Liga Pokémon!\p"
	.string "¿O no, {PLAYER}?$"

MatchCall_Text_Wallace:: @ 82B3790
	.string "Plubio: Hola, {PLAYER}{KUN}.\n"
	.string "¿Has visto ya a Máximo?\p"
	.string "La verdad es que es…\n"
	.string "es un hacha.\p"
	.string "Pero va un poco a su aire,\n"
	.string "no suele combatir mucho.\p"
	.string "Prefiere buscar piedras raras\n"
	.string "por ahí.\p"
	.string "Seguro que está ahora mismo\n"
	.string "cavando en alguna cueva o en algún\l"
	.string "monte escarpado.\p"
	.string "Y a todo esto, ¿una piedra rara\n"
	.string "qué es lo que es?\l"
	.string "Como no sea un meteorito…$"

MatchCall_Text_MayRayquazaCall: @ 82B38C1
	.string "¡Bip!\p"
	.string "Aura: ¡Hola, {PLAYER}{KUN}!\p"
	.string "¡Hace poco he estado en Oromar!\p"
	.string "Allí vi un Pokémon verde y enorme\n"
	.string "surcando el cielo.\p"
	.string "Oye…\n"
	.string "¡Nunca había visto nada parecido!\p"
	.string "¿Quién sabe? ¡Podría ser\n"
	.string "un gran descubrimiento!\p"
	.string "¡Clic!$"

MatchCall_Text_BrendanRayquazaCall: @ 82B39C6
	.string "¡Bip!\p"
	.string "Bruno: ¡Hola, {PLAYER}!\p"
	.string "¡Hace poco he estado en Oromar!\p"
	.string "Allí vi un Pokémon verde y enorme\n"
	.string "surcando el cielo.\p"
	.string "¡Nunca había visto nada parecido!\p"
	.string "Ojalá lo hubieras visto tú,\n"
	.string "{PLAYER}.\p"
	.string "¡Clic!$"

MatchCall_Text_May1:: @ 2B3AB3
	.string "Aura: ¡Hola, {PLAYER}{KUN}!\p"
	.string "El Sr. Arenque se ha retirado\n"
	.string "de Marinero, pero a veces lo veo\l"
	.string "en el mar con su mascota, Peeko.\p"
	.string "¡Debe de echarlo mucho de menos!$"

MatchCall_Text_May2:: @ 2B3B3F
	.string "Aura: ¡Hola, {PLAYER}{KUN}!\p"
	.string "Sabes que Petalia y Azuliza\n"
	.string "tienen Gimnasio, ¿verdad?\p"
	.string "Pero no sé por qué, en el puerto de\n"
	.string "Ciudad Portual no hay ninguno.\p"
	.string "Creo que cuando construyan allí\n"
	.string "un Gimnasio, me voy a presentar\l"
	.string "para el puesto de Líder.$"

MatchCall_Text_May3:: @ 2B3C13
	.string "Aura: ¡Hola, {PLAYER}{KUN}!\p"
	.string "¿Te acuerdas del tipo de ciudad\n"
	.string "Férrica, al que llamaban\l"
	.string "el Cortador?\l"
	.string "El que tenía una casa allí, ¿sabes?\p"
	.string "Pues ahora he descubierto\n"
	.string "que su hermano pequeño\l"
	.string "vive en Malvalona.\p"
	.string "¿Y sabes cómo se llama?…\p"
	.string "¡Machacarrocas!$"

MatchCall_Text_May4:: @ 2B3CF3
	.string "Aura: ¿{PLAYER}{KUN}?\p"
	.string "Túnel Fervergal…\n"
	.string "Le pusieron ese nombre porque une\l"
	.string "ciudad Férrica y Verdegal.$"

MatchCall_Text_May5:: @ 2B3D4B
	.string "Aura: {PLAYER}{KUN}, ¿qué tal?\p"
	.string "Ahora ando por la Ruta 111.\p"
	.string "Voy a descansar un poco\n"
	.string "en la casa de una anciana.\p"
	.string "Vive justo al norte del desierto.$"

MatchCall_Text_May6:: @ 2B3DD1
	.string "Aura: ¡Hola, {PLAYER}{KUN}!\p"
	.string "¿Has oído hablar de la Torre\n"
	.string "Espejismo que hay en el desierto?\p"
	.string "Dicen que, como los espejismos,\n"
	.string "aparece y desaparece…\p"
	.string "Ojalá pueda verla.$"

MatchCall_Text_May7:: @ 2B3E69
	.string "Aura: ¡{PLAYER}{KUN}, hola!\n"
	.string "Ahora estoy en la Ruta 119.\p"
	.string "Hay un río enorme y, encima, \n"
	.string "a veces llueve mucho.\p"
	.string "¡Me he empapado!$"

MatchCall_Text_May8:: @ 2B3ECD
	.string "Aura: {PLAYER}{KUN}, hola.\p"
	.string "El Monte Pírico es un monumento en\n"
	.string "recuerdo de los Pokémon que ya no\l"
	.string "están físicamente entre nosotros.\p"
	.string "¡Quizás por eso está infestado\n"
	.string "de Pokémon de tipo fantasma!$"

MatchCall_Text_May9:: @ 2B3F2B
	.string "Aura: ¡Hola, {PLAYER}{KUN}!\p"
	.string "Estaba pensando en acercarme a\n"
	.string "los baños termales de Lavacalda.\p"
	.string "Pero cerca del desfiladero\n"
	.string "me he encontrado con unos\l"
	.string "tipos raros. ¡No te lo recomiendo!$"

MatchCall_Text_May10:: @ 2B3FFB
	.string "Aura: ¡Hola, {PLAYER}{KUN}!\n"
	.string "¿Has oído la última?\p"
	.string "Dicen que el capitán Babor\n"
	.string "descubrió la Caverna Abisal en una\l"
	.string "de sus expediciones submarinas.$"

MatchCall_Text_May11:: @ 2B402B
	.string "Aura: ¡Hola, {PLAYER}{KUN}!\n"
	.string "¿No te parece fantástico?…\p"
	.string "Aunque no tengas barco,\n"
	.string "puedes cruzar el mar usando\l"
	.string "el movimiento de un Pokémon.\p"
	.string "¡Pero es que aún hay más!\p"
	.string "¡Hay otro movimiento que te\n"
	.string "permite viajar por el fondo del mar!$"

MatchCall_Text_May12:: @ 2B414B
	.string "Aura: ¡Hola, {PLAYER}{KUN}!\n"
	.string "Espero que todo vaya bien.\p"
	.string "Cuando estuviste en el mar,\n"
	.string "¿pudiste pasar al lado que estaba\l"
	.string "bloqueado?\p"
	.string "Intenta sumergirte bajo el agua\n"
	.string "y sigue a lo largo de las simas.\p"
	.string "Cuando llegues al otro lado,\n"
	.string "vuelve a la superficie. ¡Es fácil!$"

MatchCall_Text_May13:: @ 2B4228
	.string "Aura: ¡Hola, {PLAYER}{KUN}!\p"
	.string "¿Cómo va eso?\n"
	.string "¿Estás llenando tu Pokédex?\p"
	.string "He oído el rumor de que hay\n"
	.string "Pokémon antiguos por ahí.\l"
	.string "¡Y que hay tres ejemplares!\p"
	.string "¡Lo que daría por ver uno!…$"

MatchCall_Text_May14:: @ 2B42E0
	.string "Aura: ¡{PLAYER}{KUN}!\n"
	.string "¡He oído los rumores que corren!\p"
	.string "¿De verdad has vencido al líder\n"
	.string "del gimnasio de Arrecípolis?\p"
	.string "Eso significa que ya\n"
	.string "te queda poco, ¿no?$"

MatchCall_Text_May15:: @ 2B4350
	.string "Aura: ¡Ya no hay ni un solo\n"
	.string "Entrenador en Hoenn que no\l"
	.string "sepa quién eres, {PLAYER}{KUN}!\p"
	.string "Cuando le digo a la gente\n"
	.string "que soy tu amiga, {PLAYER}{KUN},\l"
	.string "¡no veas qué cara ponen!$"

MatchCall_Text_Brendan1:: @ 2B43EF
	.string "Bruno: ¡Eh, {PLAYER}!\p"
	.string "El Sr. Arenque se ha retirado\n"
	.string "de Marinero, pero a veces lo veo\l"
	.string "en el mar con su mascota, Peeko.\p"
	.string "¡Debe de echarlo mucho de menos!$"

MatchCall_Text_Brendan2:: @ 2B4486
	.string "Bruno: ¡Eh, {PLAYER}!\p"
	.string "Sabes que Petalia y Azuliza\n"
	.string "tienen Gimnasio, ¿verdad?\p"
	.string "Pero no sé por qué, en el puerto de\n"
	.string "Ciudad Portual no hay ninguno.\p"
	.string "Creo que cuando construyan allí\n"
	.string "un Gimnasio, me voy a presentar\l"
	.string "para el puesto de Líder.$"

MatchCall_Text_Brendan3:: @ 2B4560
	.string "Bruno: ¡Hola, {PLAYER}!\p"
	.string "¿Te acuerdas del tipo de ciudad\n"
	.string "Férrica, al que llamaban\l"
	.string "el Cortador?\l"
	.string "El que tenía una casa allí, ¿sabes?\p"
	.string "Pues ahora he descubierto\n"
	.string "que su hermano pequeño\l"
	.string "vive en Malvalona.\p"
	.string "¿Y sabes cómo se llama?…\p"
	.string "¡Machacarrocas!$"

MatchCall_Text_Brendan4:: @ 2B463F
	.string "Bruno: Esa voz… ¿{PLAYER}?\p"
	.string "El nombre de Túnel Fervergal\n"
	.string "se lo pusieron porque une\l"
	.string "ciudad Férrica y Verdegal.\p"
	.string "¿Lo sabías?$"

MatchCall_Text_Brendan5:: @ 2B46B7
	.string "Bruno: {PLAYER}, ¿qué tal va todo?\p"
	.string "Ahora estoy por la Ruta 111.\p"
	.string "Voy a descansar un poco en\n"
	.string "la casa de una anciana que\l"
	.string "vive justo al norte del desierto.\p"
	.string "Si pasas por aquí, ven a verla.$"

MatchCall_Text_Brendan6:: @ 2B4761
	.string "Bruno: ¡Eh, {PLAYER}!\p"
	.string "¿Has oído hablar de la Torre\n"
	.string "Espejismo que hay en el desierto?\p"
	.string "Dicen que, como los espejismos,\n"
	.string "aparece y desaparece…\p"
	.string "¡Ojalá pueda verla!$"

MatchCall_Text_Brendan7:: @ 2B47F4
	.string "Bruno: ¿Quién es? Eh, ¿{PLAYER}?\n"
	.string "Ahora estoy en la Ruta 119.\p"
	.string "Hay un río enorme y, encima, \n"
	.string "a veces llueve mucho.\p"
	.string "¡Estoy calado hasta los huesos!$"

MatchCall_Text_Brendan8:: @ 2B4882
	.string "Bruno: ¡{PLAYER}!\p"
	.string "El Monte Pírico es un monumento en\n"
	.string "recuerdo de los Pokémon que ya no\l"
	.string "están físicamente entre nosotros.\p"
	.string "¡Quizás por eso está infestado\n"
	.string "de Pokémon de tipo fantasma!$"

MatchCall_Text_Brendan9:: @ 2B4909
	.string "Bruno: ¿Qué hay, {PLAYER}?\p"
	.string "Iba camino de los baños\n"
	.string "termales de Lavacalda.\p"
	.string "Pero cerca del desfiladero\n"
	.string "me he encontrado con unos\l"
	.string "tipos con cara de pocos amigos. \p"
	.string "Menudos broncas…\n"
	.string "¡Creo que era el equipo Magma!$"

MatchCall_Text_Brendan10:: @ 2B49C4
	.string "Bruno: ¡Hola, {PLAYER}!\n"
	.string "¿Has oído las últimas noticias?\p"
	.string "Dicen que el capitán Babor\n"
	.string "descubrió la Caverna Abisal en una\l"
	.string "de sus expediciones submarinas.$"

MatchCall_Text_Brendan11:: @ 2B4A44
	.string "Bruno: ¡Eh, {PLAYER}!\n"
	.string "¿No te parece alucinante?…\p"
	.string "Aunque no tengas barco,\n"
	.string "puedes cruzar el mar usando\l"
	.string "el movimiento de un Pokémon.\p"
	.string "¡Y hay otro movimiento que te\n"
	.string "permite viajar por el fondo del mar!\p"
	.string "¡Oye, estos Pokémon hacen de todo!$"

MatchCall_Text_Brendan12:: @ 2B4B28
	.string "Bruno: ¡Ey, {PLAYER}!\n"
	.string "¿Qué tal te va?\p"
	.string "¿Has dado con algún camino que\n"
	.string "conecte con la zona bloqueada?\p"
	.string "Intenta sumergirte bajo el agua\n"
	.string "y sigue a lo largo de las simas.\p"
	.string "Cuando llegues al otro lado, vuelve\n"
	.string "a la superficie. ¡Está chupado!$"

MatchCall_Text_Brendan13:: @ 2B4C15
	.string "Bruno: ¡Eh, {PLAYER}!\p"
	.string "¿Cómo va eso?\n"
	.string "¿Estás llenando tu Pokédex?\p"
	.string "He oído el rumor de que hay\n"
	.string "Pokémon antiguos por ahí.\l"
	.string "¡Y que hay tres ejemplares!\p"
	.string "¡Lo que daría por ver uno!$"

MatchCall_Text_Brendan14:: @ 2B4CD8
	.string "Bruno: ¡{PLAYER}!\n"
	.string "¡Me han llegado rumores!\p"
	.string "¿Has vencido al líder del gimnasio\n"
	.string "de Arrecípolis? ¡Genial!\p"
	.string "¡Ya te queda muy poco!$"

MatchCall_Text_Brendan15:: @ 2B4D46
	.string "Bruno: ¡Ya no hay ni un solo\n"
	.string "Entrenador en Hoenn que\l"
	.string "no sepa quién eres, {PLAYER}!\p"
	.string "Cuando le digo a la gente\n"
	.string "que soy tu amigo, {PLAYER},\l"
	.string "¡no veas qué cara de envidia ponen!$"

MatchCall_Text_Wally1:: @ 2B4DE2
	.string "Blasco: ¡Hola, {PLAYER}!\p"
	.string "Cada vez estoy más en forma\n"
	.string "tanto física como mentalmente.\p"
	.string "¡Espero convertirme pronto en un\n"
	.string "Entrenador como tú, {PLAYER}!$"

MatchCall_Text_Wally2:: @ 2B4E57
	.string "Blasco: ¡{PLAYER}, hola!\p"
	.string "Cuando acabaron el Túnel\n"
	.string "Fervergal, Clara se puso\l"
	.string "contentísima.$"

MatchCall_Text_Wally3:: @ 2B4EA5
	.string "Blasco: ¡Hola, {PLAYER}!\p"
	.string "Eh… me fui de casa de mi tío,\n"
	.string "en Verdegal, sin decírselo a nadie.\p"
	.string "Igual se ha enfadado conmigo…\p"
	.string "{PLAYER}, ¿tú me entiendes, no?$"

MatchCall_Text_Wally4:: @ 2B4F41
	.string "Blasco: ¿{PLAYER}?\n"
	.string "¡Sí, soy Blasco!\p"
	.string "¡El mundo de los entrenadores\n"
	.string "es alucinante!\p"
	.string "Cuando voy con mis Pokémon,\n"
	.string "¡me saluda todo tipo de gente!\p"
	.string "¡Es como si todo se conectara\n"
	.string "a través de los Pokémon!$"

MatchCall_Text_Wally5:: @ 2B4FF3
	.string "Blasco: ¿ {PLAYER}? ¡Escucha!\n"
	.string "¿Te acuerdas del Ralts\l"
	.string "que atrapamos?\p"
	.string "¡Pues ha evolucionado, {PLAYER}!\p"
	.string "¿Habrá sido por méritos míos?…\p"
	.string "Bueno, que no quiero ponerme\n"
	.string "en plan guay.\p"
	.string "¡Que el que lo ha hecho bien\n"
	.string "ha sido el Pokémon!$"

MatchCall_Text_Wally6:: @ 2B50B1
	.string "(…)\p"
	.string "Parece que Blasco está en una\n"
	.string "zona en la que no hay cobertura…$"

MatchCall_Text_Wally7:: @ 2B5100
	.string "Blasco: ¡Hola, {PLAYER}!\p"
	.string "Antes de conocerte, apenas\n"
	.string "había salido de casa…\p"
	.string "Y ahora, voy yo solito con mis\n"
	.string "propios Pokémon en busca\l"
	.string "de aventura…\p"
	.string "{PLAYER}…\n"
	.string "Gracias…$"

MatchCall_Text_Scott1:: @ 2B5184
	.string "Treto: ¡Eh, {PLAYER}{KUN}!\p"
	.string "¿Que sabes encontrar Pokémon\n"
	.string "en cualquier sitio?\p"
	.string "En la montaña, en el mar, entre la\n"
	.string "hierba alta, ¿en cualquier sitio?\p"
	.string "¡Yo encuentro entrenadores\n"
	.string "en cualquier sitio también!\p"
	.string "Así que te dejo, que voy a buscar\n"
	.string "más. ¡Hala, hala, adiós!$"

MatchCall_Text_Scott2:: @ 2B5275
	.string "Treto: Estoy en la Ruta 119.\n"
	.string "¡Está llena de entrenadores!\p"
	.string "Y creo que hay zonas\n"
	.string "de hierba alta por todos lados.\p"
	.string "¡Como voy con pantalón corto,\n"
	.string "me hace unas cosquillas!$"

MatchCall_Text_Scott3:: @ 2B5323
	.string "Treto: ¡Oye, {PLAYER}{KUN}!\p"
	.string "¿Has tenido ocasión de subir \n"
	.string "al Monte Pírico?\p"
	.string "Es un monumento natural a\n"
	.string "los Pokémon que nos han dejado.\p"
	.string "Un sitio al que todo entrenador\n"
	.string "debería subir al menos una vez.$"

MatchCall_Text_Scott4:: @ 2B53DB
	.string "Treto: ¡Hola, {PLAYER}{KUN}!\p"
	.string "He oído que hay un par de\n"
	.string "bandas tocando las narices.\p"
	.string "El equipo Magma y el equipo Aqua\n"
	.string "creo que eran, ¿no?\p"
	.string "Pues para mí que cuentan con más\n"
	.string "de un buen Entrenador…\p"
	.string "Pero claro, si son unos animales,\n"
	.string "tampoco es cuestión de…$"

MatchCall_Text_Scott5:: @ 2B54A5
	.string "Treto: Eh, hola, {PLAYER}{KUN}.\p"
	.string "¿Habrá buenos entrenadores\n"
	.string "en el fondo del mar?\p"
	.string "Yo no puedo ir a comprobarlo.\n"
	.string "Para empezar, porque no sé nadar.\l"
	.string "Además, yo no crío Pokémon…$"

MatchCall_Text_Scott6:: @ 2B5541
	.string "Treto: ¡Eh, hola, {PLAYER}{KUN}!\p"
	.string "¿Sabías que puedes participar en\n"
	.string "la Liga Pokémon cuando consigas\l"
	.string "todas las medallas de gimnasio?\p"
	.string "Con tu talento, ganar la liga\n"
	.string "va a resultarte pan comido.\p"
	.string "Pero ¿sabes qué es lo mejor\n"
	.string "de todo?\p"
	.string "Bueno, no hay una sola cosa, pero\n"
	.string "no voy a decirte más de momento.\p"
	.string "Lo genial es…, no te lo pierdas,\n"
	.string "lo genial es que…\p"
	.string "¡Cuando ganas la liga Pokémon,\n"
	.string "pasas a formar parte\l"
	.string "del Hall de la Fama!$"

MatchCall_Text_Scott7:: @ 2B56CA
	.string "(…)\p"
	.string "Parece que Treto está en una zona\n"
	.string "en la que no hay cobertura…$"

MatchCall_Text_Norman1:: @ 82B5719
	.string "Papá: En ciudad Férrica\n"
	.string "hay un señor al que de toda la vida\l"
	.string "han llamado Cortador.\p"
	.string "Si estás por la zona,\n"
	.string "podrías hacerle una visita.$"

MatchCall_Text_Norman2:: @ 82B5795
	.string "Papá: Mm… Te estás haciendo\n"
	.string "cada vez más fuerte, {PLAYER}.\l"
	.string "Muy bien, despacito y buena letra.\p"
	.string "Cuanto más fuerte seas, más lejos\n"
	.string "estarás de Mamá y de mí.\l"
	.string "Cada vez estarás más fuera\l"
	.string "del cascarón…\p"
	.string "Es difícil de explicar, cariño.$"

MatchCall_Text_Norman3:: @ 82B584D
	.string "Papá: Interesante…\n"
	.string "Ya has conseguido 4 medallas\l"
	.string "de Gimnasio…\p"
	.string "Ahora no me puedo negar.\n"
	.string "Lucharemos como te dije.\p"
	.string "Ven cuando quieras.\n"
	.string "¡Estoy esperándote!$"

MatchCall_Text_Norman4:: @ 82B58E3
	.string "Papá: ¡{PLAYER}, deberías ir a ver\n"
	.string "a Mamá de vez en cuando!\p"
	.string "Voy a quedarme aquí para reforzar\n"
	.string "mi entrenamiento.\p"
	.string "¡No hay más remedio que seguir\n"
	.string "aprendiendo, aunque cueste!$"

MatchCall_Text_Norman5:: @ 82B5979
	.string "Papá: ¡Eh, hola, {PLAYER}!\p"
	.string "¿Cómo? ¿El Signo Magma?\n"
	.string "No sé lo que es.\p"
	.string "Pero con ese nombre, debe de tener\n"
	.string "relación con algún volcán.$"

MatchCall_Text_Norman6:: @ 82B5A07
	.string "Papá: ¡Yiiia! ¡Uuuuaaa! ¡Aaaaj!\p"
	.string "¿Mm?… ¡¡{PLAYER}!!\p"
	.string "¡Me has pillado en plena sesión\n"
	.string "de entrenamiento Pokémon!$"

MatchCall_Text_Norman7:: @ 82B5A69
	.string "Papá: ¡{PLAYER}!\p"
	.string "Quién me iba a decir\n"
	.string "que conseguirías ganar\l"
	.string "la Liga Pokémon…\p"
	.string "¡Pues yo no me pienso\n"
	.string "quedar atrás!$"

MatchCall_Text_Norman8:: @ 82B5ACF
	.string "Papá: ¿Mm? ¿{PLAYER}?\n"
	.string "¡Qué sincronización!\p"
	.string "En esta ocasión, te reto\n"
	.string "a luchar conmigo.\p"
	.string "Te espero en el gimnasio\n"
	.string "de Petalia. ¡Ven cuando quieras!$"

MatchCall_Text_Norman9:: @ 82B5B5E
	.string "Papá: Uff… Me impresionas,\n"
	.string "{PLAYER}.\l"
	.string "¿Vas a llegar mucho más lejos?$"

MatchCall_Text_Steven1:: @ 82B5B95
	.string "Máximo: ¡Hola, {PLAYER}{KUN}!\p"
	.string "¿Has estado ya en Malvalona?\p"
	.string "Deberías ir a la tienda de bicis\n"
	.string "a por una Bici Carrera.\p"
	.string "Y, después, a la Cueva Granito\n"
	.string "para explorarla en condiciones.\p"
	.string "Es posible que te lleves alguna\n"
	.string "grata sorpresa.$"

MatchCall_Text_Steven2:: @ 82B5C53
	.string "Máximo: ¡Hola, {PLAYER}{KUN}!\p"
	.string "Ya he conocido a un montón\n"
	.string "de Entrenadores.\p"
	.string "Pero tú… Lo tuyo es increíble.\n"
	.string "Eres de lo que no hay.$"

MatchCall_Text_Steven3:: @ 82B5CC9
	.string "Máximo: ¡Hola, {PLAYER}{KUN}!\p"
	.string "Cuando vas con tus Pokémon,\n"
	.string "¿qué se te pasa por la cabeza?\p"
	.string "¿Te parecen fuertes?\p"
	.string "¿Te divierten, son buena compañía?\p"
	.string "La impresión que tengas influirá\n"
	.string "mucho en el curso de las cosas.$"

MatchCall_Text_Steven4:: @ 82B5DB4
	.string "Máximo: ¿Hola?\n"
	.string "¿{PLAYER}{KUN}?\p"
	.string "En estos momentos tenemos un lío\n"
	.string "tremendo en el Centro Espacial.\p"
	.string "Lo siento, pero no me puedo\n"
	.string "entretener. ¡Hasta luego!$"

MatchCall_Text_Steven5:: @ 82B5E26
	.string "Máximo: ¡Anda!\n"
	.string "¡{PLAYER}{KUN}!\p"
	.string "No tenemos nada de qué hablar.\n"
	.string "No necesitas que te diga nada.\p"
	.string "Tienes que confiar en ti y hacer\n"
	.string "lo que consideres correcto.$"

MatchCall_Text_Steven6:: @ 82B5EA2
	.string "Biiiip… Biiiiiiiiiip… Biiiiiiiiiiiiiip…\p"
	.string "Máximo no se entera del teléfono…$"

MatchCall_Text_Steven7:: @ 82B5ED9
	.string "Máximo: {PLAYER}{KUN}… Enhorabuena por\n"
	.string "entrar en el Hall de la Fama.\p"
	.string "(…)\p"
	.string "¡Espero que podamos volver\n"
	.string "a vernos pronto en algún sitio!$"

MatchCall_Text_BirchRegisterCall: @ 82B5F52
	.string "Prof. Abedul: ¡Hola, {PLAYER}{KUN}!\n"
	.string "¡Me han hablado mucho sobre ti!\p"
	.string "Así que le han puesto agenda\n"
	.string "de Móvil a tu Pokénav…\p"
	.string "¡Pues yo me quiero registrar\n"
	.string "también!\p"
	.string "Así, podré echar un ojo a tu\n"
	.string "Pokédex hasta cuando estés\l"
	.string "por ahí.\p"
	.string "(…)$"

MatchCall_Text_RegisteredBirch: @ 82B603A
	.string "Acabas de registrar al Prof.\n"
	.string "Abedul en el Pokénav.$"

MatchCall_Text_UnusedProfBirch:
	.string "Prof. Birch: When one has both\n"
	.string "the Pokédex and Pokénav, studying\l"
	.string "Pokémon becomes more fun, eh?$"

MatchCall_Text_MrStone1:: @ 82B60C0
	.string "Sr. Peñas: ¿Sí? ¡{PLAYER}{KUN}!\p"
	.string "¡Anda, te recibo perfectamente,\n"
	.string "el Pokénav funciona!\p"
	.string "Habrá quienes se registren,\n"
	.string "¡vas a poder llamar a mucha gente!\p"
	.string "¡Qué cara de felicidad!\n"
	.string "¡Se te ve radiante!\p"
	.string "Mm…\n"
	.string "¿Que cómo lo sé?\p"
	.string "¡Pues porque te estoy viendo desde\n"
	.string "la ventana de mi despacho!\p"
	.string "¡Ja, ja, ja, ja!\n"
	.string "¡Nos vemos!$"

MatchCall_Text_MrStone2:: @ 82B61E6
	.string "Sr. Peñas: ¿Sí? ¡{PLAYER}{KUN}!\p"
	.string "¿Qué ocurre? ¿Ya no te acuerdas\n"
	.string "del pequeño encargo que te hice?\p"
	.string "Te pedí que fueras a Azuliza\n"
	.string "a llevarle mi carta a Máximo.\p"
	.string "Y que, después, fueras a ciudad\n"
	.string "Portual a entregarle el paquete\l"
	.string "al Cap. Babor.\p"
	.string "Te acuerdas, ¿no?\p"
	.string "Bueno, pues te dejo, que como\n"
	.string "Presidente tengo mucho que\l"
	.string "hacer. ¡Adiós!$"

MatchCall_Text_MrStone3:: @ 82B6302
	.string "Sr. Peñas: ¡Hola, {PLAYER}{KUN}!\p"
	.string "Ah, así que ya has visto a Máximo.\n"
	.string "¡Pues te mereces un regalo!\p"
	.string "Cuando vengas por ciudad Férrica\n"
	.string "otra vez, ven a verme a mi oficina.\p"
	.string "¡Aquí te espero!$"

MatchCall_Text_MrStone4:: @ 82B63A0
	.string "Sr. Peñas: ¡Hola, {PLAYER}{KUN}!\p"
	.string "¿Sabías que Devon se encargaba\n"
	.string "de cavar el Túnel Fervergal?\p"
	.string "Pero tuvimos que parar las obras,\n"
	.string "para proteger a los Pokémon\l"
	.string "de la zona.\p"
	.string "Tampoco es mayor trastorno,\n"
	.string "la verdad.\p"
	.string "Es más importante dejar que los\n"
	.string "Pokémon vivan tranquilos que\l"
	.string "tener más o menos metros de túnel.$"

MatchCall_Text_MrStone5:: @ 82B64A2
	.string "Sr. Peñas: ¡Eh, hola, {PLAYER}{KUN}!\p"
	.string "¡Alguien de Petalia me ha dicho\n"
	.string "que Norman es tu padre!\p"
	.string "¡Así no me extraña que tengas\n"
	.string "la capacidad que tienes!$"

MatchCall_Text_MrStone6:: @ 82B6526
	.string "Sr. Peñas: ¿Cómo?\p"
	.string "¿Qué te has enfrentado a tu padre\n"
	.string "y le has ganado?\p"
	.string "¡Esto es ya la repanocha!\p"
	.string "¡No tenía ni idea de que contara\n"
	.string "con amigos tan fuera de lo común!\l"
	.string "¡Ja, ja, ja, ja!$"

MatchCall_Text_MrStone7:: @ 82B65BB
	.string "¡Hola!\n"
	.string "Esto es Devo…\l"
	.string "¡Oh, hola, {PLAYER}!\p"
	.string "Nuestro presidente estaba aquí\n"
	.string "hace un momento, pero se ha ido.\p"
	.string "Nuestro presidente está muy\n"
	.string "ocupado, pero tú también lo estás,\l"
	.string "¿no, {PLAYER}?$"

MatchCall_Text_MrStone8:: @ 82B6664
	.string "Mmm… ¿Cómo?…\p"
	.string "Grou… ¿Cómo? ¿…Don?\p"
	.string "Se entrecorta…\n"
	.string "Eh… no te oigo…\p"
	.string "BZZZZ…$"

MatchCall_Text_MrStone9:: @ 82B66B1
	.string "Mmm… ¿Cómo?…\p"
	.string "Cavern… ¿Cómo? ¿…Bisal?\p"
	.string "Se entrecorta…\n"
	.string "Eh… no te oigo…\p"
	.string "BZZZZ…$"

MatchCall_Text_MrStone10:: @ 82B6703
	.string "Sr. Peñas: ¡{PLAYER}{KUN}! ¡Sí, soy yo!\p"
	.string "Sé que tienes mucho lío, pero yo\n"
	.string "también estoy ocupado ¡y no sé\l"
	.string "exactamente qué tienes que hacer!\p"
	.string "En cualquier caso, elige el camino\n"
	.string "que consideres mejor.\p"
	.string "¡Yo te apoyaré siempre!\n"
	.string "¡Cuídate!$"

MatchCall_Text_MrStone11:: @ 82B67ED
	.string "Sr. Peñas: Mmm…\n"
	.string "¿{PLAYER}{KUN}? ¿Eres tú?\p"
	.string "Tu voz transmite una seguridad\n"
	.string "aplastante…\l"
	.string "¡No te reconocí al principio!\p"
	.string "¡A ver si te pasas por Devon\n"
	.string "y nos haces una visita!$"
