@ Only contains the text for the Mauville Man named Giddy. The rest is in scripts/mauville_man.inc
GiddyText_SoPretty:: @ 8294295
	.string "belleza.$"

GiddyText_SoDarling:: @ 82942A1
	.string "dulzura.$"

GiddyText_SoRelaxed:: @ 82942AE
	.string "serenidad.$"

GiddyText_SoSunny:: @ 82942BB
	.string "alegría.$"

GiddyText_SoDesirable:: @ 82942C6
	.string "atractivo.$"

GiddyText_SoExciting:: @ 82942D5
	.string "emoción.$"

GiddyText_SoAmusing:: @ 82942E3
	.string "diversión.$"

GiddyText_SoMagical:: @ 82942F0
	.string "magia.$"

GiddyText_Is:: @ 82942FD
	.string "sugiere$"

GiddyText_DontYouAgree:: @ 8294301
	.string "\n"
	.string "¿No crees?$"

GiddyText_ISoWantToGoOnAVacation:: @ 8294313
	.string "Quiero tomarme unas vacaciones.\n"
	.string "¿Conoces algún lugar bonito?$"

GiddyText_IBoughtCrayonsWith120Colors:: @ 8294359
	.string "¡Compré lápices de 120 colores!\n"
	.string "¿No te parece estupendo?$"

GiddyText_WouldntItBeNiceIfWeCouldFloat:: @ 8294398
	.string "¿A que estaría bien poder flotar\n"
	.string "en una nube de burbujas?$"

GiddyText_WhenYouWriteOnASandyBeach:: @ 82943DA
	.string "Es una pena que las olas borren\n"
	.string "lo que se escribe en la arena…$"

GiddyText_WhatsTheBottomOfTheSeaLike:: @ 829441C
	.string "¿Cómo será el fondo del mar?\n"
	.string "¿No te encantaría verlo?$"

GiddyText_WhenYouSeeTheSettingSunDoesIt:: @ 8294460
	.string "Cuando se hace de noche, \n"
	.string "¿te apetece volver a casa?$"

GiddyText_LyingBackInTheGreenGrass:: @ 82944A0
	.string "¡Tumbado en la hierba se\n"
	.string "está tan bien! ¿A que sí?$"

GiddyText_SecretBasesAreSoWonderful:: @ 82944D5
	.string "¡Las bases secretas son geniales!\n"
	.string "¿No estás de acuerdo?$"
