MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce: @ 82C6E05
	.string "Este movimiento solo se puede aprender\n"
	.string "una vez, ¿vale?$"

MoveTutor_Text_SwaggerTeach: @ 82C6E37
	.string "¡Guau! ¡Cómo mola mi Pokémon!\n"
	.string "¡Si es que no hay otro igual!\p"
	.string "Yo iba por ahí imitando ese contoneo\n"
	.string "tan gracioso cuando, de repente,\l"
	.string "me encontré con el Presidente.\p"
	.string "Se me quitó el contoneo de un plumazo.\p"
	.string "Si quieres, puedo enseñar el movimiento \n"
	.string "Contoneo a uno de tus Pokémon.$"

MoveTutor_Text_SwaggerDeclined: @ 82C6F33
	.string "Pero ¿qué pasa contigo?\n"
	.string "¿No sabes verle el fondo a las formas?$"

MoveTutor_Text_SwaggerWhichMon: @ 82C6F66
	.string "Genial, entonces dime, ¿qué Pokémon\n"
	.string "quieres que aprenda Contoneo?$"

MoveTutor_Text_SwaggerTaught: @ 82C6F9E
	.string "A partir de ahora, prometo imitar\n"
	.string "a mi Pokémon sin contonearme.$"

MoveTutor_Text_RolloutTeach: @ 82C6FDB
	.string "¡Alguna gente se enrolla y algunos\n"
	.string "Pokémon se desenrollan!\p"
	.string "¿Quieres que uno de tus Pokémon\n"
	.string "aprenda a desenrollarse?\p"
	.string "Le puedo enseñar Desenrollar\n"
	.string "a uno si tú quieres.$"

MoveTutor_Text_RolloutDeclined: @ 82C70C4
	.string "Bueno, desde luego, ¡tú no pareces\n"
	.string "estar entre la gente que se enrolla!$"

MoveTutor_Text_RolloutWhichMon: @ 82C70F3
	.string "¡Qué buen rollo! Sería genial si además\n"
	.string "eligieras uno que se parezca a mí, ¿eh?$"

MoveTutor_Text_RolloutTaught: @ 82C7133
	.string "Listo. ¡A desenrollarse se ha dicho!\n"
	.string "¡Hala!$"

MoveTutor_Text_FuryCutterTeach: @ 82C7174
	.string "Hay un movimiento que se hace más\n"
	.string "fuerte al usarlo varias veces seguidas.\p"
	.string "¡Es un movimiento de tipo bicho \n"
	.string "y mola pero que un montón!\p"
	.string "Se llama Cortefuria.\n"
	.string "¿Se lo enseño a uno de tus Pokémon?$"

MoveTutor_Text_FuryCutterDeclined: @ 82C7221
	.string "Se ve que no estamos en la misma\n"
	.string "onda.$"

MoveTutor_Text_FuryCutterWhichMon: @ 82C7243
	.string "¡Yupi!\n"
	.string "Dime a qué Pokémon se lo enseño.$"

MoveTutor_Text_FuryCutterTaught: @ 82C726E
	.string "¡Me encanta pararme a ver\n"
	.string "cómo aumenta de fuerza con el uso!$"

MoveTutor_MimicTeach: @ 82C72B6
	.string "¡Ay, qué achaques tengo!\p"
	.string "Soy muy joven, pero me encanta imitar\n"
	.string "la forma de hablar de los mayores\l"
	.string "que hay en este pueblo.\p"
	.string "¿Quieres darme una alegría dejándome\n"
	.string "enseñarle el movimiento Mimético\l"
	.string "a uno de tus Pokémon?$"

MoveTutor_MimicDeclined: @ 82C737F
	.string "¡Qué juventud tan desagradecida! ¡Sólo\n"
	.string "quería enseñar Mimético a un Pokémon!$"

MoveTutor_Text_MimicWhichMon: @ 82C73B1
	.string "¡Tjó, tjó! ¿De verdad me dejas?\n"
	.string "¡Dime entonces a qué Pokémon\l"
	.string "quieres que se lo enseñe!$"

MoveTutor_Text_MimicTaught: @ 82C73F6
	.string "El movimiento Mimético exige paciencia,\n"
	.string "algo que no soléis tener los jóvenes.\p"
	.string "¿Crees que llegarás a usarlo tan bien\n"
	.string "como yo?…$"

MoveTutor_Text_MetronomeTeach: @ 82C7449
	.string "¡Quiero comprar un montón de cosas!\n"
	.string "Pero ya me he gastado mi paga…\p"
	.string "Estaría genial que hubiese una forma\n"
	.string "de, con solo mover el dedo,\l"
	.string "hacer aparecer monedas, ¿eh?\p"
	.string "Si quieres, puedo enseñar a tu Pokémon\n"
	.string "el movimiento Metrónomo.\p"
	.string "Puede que no aparezca ninguna moneda,\n"
	.string "pero tu Pokémon sabrá mover el dedo.\l"
	.string "¿Qué me dices?$"

MoveTutor_Text_MetronomeDeclined: @ 82C7556
	.string "Estaré aquí por si cambias de idea.$"

MoveTutor_Text_MetronomeWhichMon: @ 82C7582
	.string "¡Guay! ¡Se lo enseñaré!\n"
	.string "Pero ¿a qué Pokémon?$"

MoveTutor_Text_MetronomeTaught: @ 82C75B5
	.string "Cuando tu Pokémon mueva el dedo\n"
	.string "como un Metrónomo, podrá pasar\l"
	.string "cualquier cosa.\p"
	.string "¿A que a ti también te encantaría\n"
	.string "hacerlo?$"

MoveTutor_Text_SleepTalkTeach: @ 82C7637
	.string "¡Bah! Mi mujer confía en el Poder\n"
	.string "Oculto para mantenerse despierta.\p"
	.string "Lo mejor es dar una cabezadita y luego\n"
	.string "andar Sonámbulo, como hago yo.\p"
	.string "¿Quieres que le enseñe a uno de tus\n"
	.string "Pokémon el movimiento Sonámbulo?$"

MoveTutor_Text_SleepTalkDeclined: @ 82C76E2
	.string "Vale, vale. Conque tú también prefieres\n"
	.string "Poder Oculto…$"

MoveTutor_Text_SleepTalkWhichMon: @ 82C7721
	.string "¡Joven pero inteligente!\n"
	.string "¿A qué Pokémon debo enseñárselo?$"

MoveTutor_Text_SleepTalkTaught: @ 82C775A
	.string "Nunca he acabado de entender el truco\n"
	.string "que hace mi mujer con las monedas.\p"
	.string "Me encantaría pillarlo, aunque fuese\n"
	.string "estando Sonámbulo…$"

MoveTutor_Text_SubstituteTeach: @ 82C77C6
	.string "Cuando veo lo grande que es el mundo\n"
	.string "desde lo alto de esta terraza…\p"
	.string "Pienso en lo bonito que sería tener más\n"
	.string "de un “yo” para poder vivir otras vidas.\p"
	.string "Claro que eso es imposible.\n"
	.string "Je, je. Qué tontería…\p"
	.string "¡Pero se me ocurre una cosa!\n"
	.string "¿Quieres que uno de tus Pokémon\l"
	.string "aprenda a usar Sustituto?$"

MoveTutor_Text_SubstituteDeclined: @ 82C78D1
	.string "Oh, ¿no?\p"
	.string "Tu Pokémon habría podido hacer\n"
	.string "una copia de sí mismo, ¿sabes?$"

MoveTutor_Text_SubstituteWhichMon: @ 82C7911
	.string "Je, je…\n"
	.string "¿Qué Pokémon quieres que aprenda\l"
	.string "el movimiento Sustituto?$"

MoveTutor_Text_SubstituteTaught: @ 82C794B
	.string "¡Nosotros, los humanos, deberíamos\n"
	.string "disfrutar al máximo de nuestras vidas!\p"
	.string "¡Espero que tú sí sepas hacerlo!$"

MoveTutor_Text_DynamicPunchTeach: @ 82C79A6
	.string "¡No puedo seguir haciendo esto!\p"
	.string "¡No valgo para nada!\p"
	.string "Soy un entrenador de tipo lucha,\n"
	.string "así que no hay manera de que pueda\l"
	.string "ganar en el gimnasio de Algaria.\p"
	.string "¡Grrr! ¡Toma! ¡Toma! ¡Toma!\n"
	.string "¡Toma! ¡Toma! ¡Toma!\p"
	.string "¿Qué? ¡No me mires así!\n"
	.string "¡Sólo estoy dándole al suelo!\p"
	.string "Ah, ¿que quieres que enseñe\n"
	.string "Puñodinámico a uno de tus Pokémon?$"

MoveTutor_Text_DynamicPunchDeclined: @ 82C7AD4
	.string "¡Grr! ¿Me estás tomando el pelo?\n"
	.string "¡Toma! ¡Toma! ¡Toma!$"

MoveTutor_Text_DynamicPunchWhichMon: @ 82C7B0D
	.string "¿Qué? ¿En serio? ¡Qué bien!\n"
	.string "¿A qué Pokémon se lo enseño?$"

MoveTutor_Text_DynamicPunchTaught: @ 82C7B4F
	.string "¡Ahora quiero que ganes en el gimnasio\n"
	.string "de Algaria usando Puñodinámico!$"

MoveTutor_Text_DoubleEdgeTeach: @ 82C7B8E
	.string "Ay…\p"
	.string "El líder de gimnasio de Arrecípolis\n"
	.string "es de lo más apuesto.\p"
	.string "Por desgracia, no soy yo solita\n"
	.string "quien se ha fijado en él…\p"
	.string "Además, ya se sabe que lo de ser\n"
	.string "apuesto es un arma de Doble Filo.\p"
	.string "Por cierto, déjame enseñarle Doble Filo\n"
	.string "a uno de tus Pokémon, ¿eh?$"

MoveTutor_Text_DoubleEdgeDeclined: @ 82C7C7E
	.string "Oh…\n"
	.string "Hasta tú pasas de mí…$"

MoveTutor_Text_DoubleEdgeWhichMon: @ 82C7C98
	.string "Estupendo, ¿y qué Pokémon quieres\n"
	.string "que aprenda a usar Doble Filo?$"

MoveTutor_Text_DoubleEdgeTaught: @ 82C7CC8
	.string "Dicen que el amor nos hace fuertes,\n"
	.string "pero conmigo no funciona…\p"
	.string "Voy a dejar de ser tan enamoradiza\n"
	.string "a ver qué pasa.$"

MoveTutor_Text_ExplosionTeach: @ 82C7CFA
	.string "No voy a llegar a nada si me quedo\n"
	.string "en un pueblucho como éste.\p"
	.string "Pero espera y verás. Voy a irme\n"
	.string "a la capital y me haré famoso.\p"
	.string "¡En serio, lo mío va a ser una\n"
	.string "Explosión de popularidad!\p"
	.string "Bueno, ya puestos, ¡puedo enseñarle\n"
	.string "Explosión a uno de tus Pokémon!$"

MoveTutor_Text_ExplosionDeclined: @ 82C7E04
	.string "¡Bah! Tú también pasas de mí porque\n"
	.string "crees que soy un pueblerino, ¿eh?$"

MoveTutor_Text_ExplosionWhichMon: @ 82C7E40
	.string "¡Genial! ¿Y qué Pokémon quieres\n"
	.string "que aprenda Explosión?$"

MoveTutor_Text_ExplosionTaught: @ 82C7E7A
	.string "Llevo años enseñando a los Pokémon\n"
	.string "a usar Explosión, pero todavía\l"
	.string "me falta ver la mía…\p"
	.string "Quizás sea porque, en el fondo,\n"
	.string "quiero quedarme aquí…$"
