gText_ObtainedTheItem:: @ 8272A78
	.string "¡{PLAYER} obtuvo {STR_VAR_2}!$"

gText_TheBagIsFull:: @ 8272A89
	.string "La Mochila está llena…$"

gText_PutItemInPocket:: @ 8272A9A
	.string "{PLAYER} puso {STR_VAR_2}\n"
	.string "en el Bolsillo de {STR_VAR_3}.$"

gText_PlayerFoundOneItem:: @ 8272ABF
	.string "¡{PLAYER} encontró {STR_VAR_2}!$"

gText_TooBadBagIsFull:: @ 8272AD0
	.string "¡Mala suerte!\n"
	.string "La Mochila está llena…$"

gText_PlayerPutItemInBag:: @ 8272AEA
	.string "{PLAYER} puso {STR_VAR_2}\n"
	.string "en la Mochila$"

gText_ObtainedTheDecor:: @ 8272B09
	.string "¡{PLAYER} obtuvo {STR_VAR_2}!$"

gText_NoRoomLeftForAnother:: @ 8272B1A
	.string "¡Mala suerte! No queda sitio\n"
	.string "para {STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC:: @ 8272B48
	.string "Se envió {STR_VAR_2} al PC.$"
