Text_BootUpPC: @ 827265A
	.string "{PLAYER} encendió el PC.$"

gText_WhichPCShouldBeAccessed:: @ 827266F
	.string "¿A qué PC quieres acceder?$"

gText_AccessedSomeonesPC:: @ 827268C
	.string "Accedió al PC de alguien.$"

gText_StorageSystemOpened:: @ 82726A3
	.string "Acceso al sistema de almacenamiento\n"
	.string "de Pokémon concedido.$"

gText_AccessedPlayersPC:: @ 82726C2
	.string "Accedió al PC de {PLAYER}.$"

gText_AccessedLanettesPC:: @ 82726D4
	.string "Accedió al PC de Aredia.$"
