gText_WouldYouLikeToRestYourPkmn:: @ 82726EB
	.string "Hola. Éste es el Centro Pokémon.\p"
	.string "Nosotros curamos a los Pokémon\n"
	.string "debilitados.\p"
	.string "¿Quieres que nos ocupemos\n"
	.string "de los Pokémon de tu equipo?$"

gText_IllTakeYourPkmn:: @ 8272768
	.string "Muy bien. Ten un poco de paciencia.\n"
	.string "Será solo un momento.$"

gText_RestoredPkmnToFullHealth:: @ 8272798
	.string "Gracias por esperar.\p"
	.string "Misión cumplida. Somos especialistas\n"
	.string "en devolver la forma a los Pokémon.$"

gText_WeHopeToSeeYouAgain:: @ 82727DB
	.string "¡Vuelve cuando quieras!$"

gText_WelcomeCutShort:: @ 82727F5
	.string "Hola. Éste es el Centro Pokémon.\p"
	.string "Nosotros curamos a los Pokémon\n"
	.string "debilitados.\p"
	.string "¿Quieres que…?$"

gText_NoticesGoldCard:: @ 8272860
	.string "Esa ficha…\n"
	.string "¿Es…? ¡¿Es de color oro?!\p"
	.string "¡Oh, ese color es resplandenciente!\n"
	.string "¡Las cuatro estrellas brillan tanto!\p"
	.string "Ya he visto a varios entrenadores\n"
	.string "con una Ficha de color plata, pero,\l"
	.string "{PLAYER}, ¡nunca antes había visto\l"
	.string "a nadie con una ficha de color oro!\p"
	.string "Muy bien, {PLAYER}, concédeme\n"
	.string "el honor de curar a tus Pokémon.$"

gText_YouWantTheUsual:: @ 8272982
	.string "¡Qué alegría verte, {PLAYER}!\n"
	.string "Lo de siempre, ¿no?$"

gText_IllTakeYourPkmn2:: @ 82729C0
	.string "Muy bien. Ten un poco de paciencia.\n"
	.string "Será solo un momento.$"

gText_ThankYouForWaiting:: @ 82729F0
	.string "Gracias por esperar.$"

gText_WeHopeToSeeYouAgain2:: @ 8272A07
	.string "¡Vuelve cuando quieras!$"
