gBirchDexRatingText_AreYouCurious:: @ 82A5C9C
	.string "¡Ah, {PLAYER}{KUN}!\p"
	.string "¿Quieres saber cómo llevas\n"
	.string "la Pokédex?$"

gBirchDexRatingText_Cancel: @ 82A5CEB
	.string "¿Eh? Ah, ya, no has cogido\n"
	.string "bastantes Pokémon para\l"
	.string "que valga la pena…$"

gBirchDexRatingText_SoYouveSeenAndCaught:: @ 82A5D2C
	.string "Mmmm…\p"
	.string "Así que has visto {STR_VAR_1} Pokémon\n"
	.string "y has atrapado {STR_VAR_2} Pokémon.$"

gBirchDexRatingText_LessThan10:: @ 82A5D6C
	.string "Deberías ir más a las zonas de\n"
	.string "hierba alta para buscar Pokémon.$"

gBirchDexRatingText_LessThan20:: @ 82A5DAB
	.string "Vas cogiéndole el tranquillo, pero a\n"
	.string "partir de ahora cuesta más…$"

gBirchDexRatingText_LessThan30:: @ 82A5DF1
	.string "Algunos Pokémon solo aparecen en\n"
	.string "ciertas zonas. Tienes que insistir.$"

gBirchDexRatingText_LessThan40:: @ 82A5E34
	.string "Bueno, podría estar más llena, pero\n"
	.string "ya empieza a parecer una Pokédex.$"

gBirchDexRatingText_LessThan50:: @ 82A5E83
	.string "Esto va sobre ruedas.\n"
	.string "Sigue así.$"

gBirchDexRatingText_LessThan60:: @ 82A5EB9
	.string "¿Estás usando cañas?\n"
	.string "Hay muchos Pokémon en el mar…$"

gBirchDexRatingText_LessThan70:: @ 82A5EF4
	.string "En vez de limitarte a atrapar\n"
	.string "Pokémon, ¿por qué no los haces\l"
	.string "evolucionar?$"

gBirchDexRatingText_LessThan80:: @ 82A5F39
	.string "Esta Pokédex va a ser fantástica.\n"
	.string "Lo presiento…$"

gBirchDexRatingText_LessThan90:: @ 82A5F82
	.string "Has atrapado todos éstos…\n"
	.string "¡Tienes buena mano!$"

gBirchDexRatingText_LessThan100:: @ 82A5FB9
	.string "¿Has visitado la Zona Safari?\p"
	.string "Dicen que hay algunos Pokémon\n"
	.string "que solo se pueden atrapar allí.$"

gBirchDexRatingText_LessThan110:: @ 82A6018
	.string "Por fin has llegado al número 100.\n"
	.string "¡Esta Pokédex es impresionante!$"

gBirchDexRatingText_LessThan120:: @ 82A6061
	.string "¿Sabes que se pueden encontrar\n"
	.string "ciertos Pokémon usando\l"
	.string "Golpe Roca?$"

gBirchDexRatingText_LessThan130:: @ 82A609C
	.string "Intercambiar Pokémon con tus\n"
	.string "amigos es una manera fácil de\l"
	.string "conseguir más.$"

gBirchDexRatingText_LessThan140:: @ 82A60D5
	.string "Me han dicho que algunos Pokémon\n"
	.string "evolucionan gracias al amor que\l"
	.string "sienten por sus Entrenadores.$"

gBirchDexRatingText_LessThan150:: @ 82A6124
	.string "No tenía ni idea de que había\n"
	.string "tantas especies de Pokémon en\l"
	.string "Hoenn.$"

gBirchDexRatingText_LessThan160:: @ 82A616F
	.string "A veces, algunos Pokémon aparecen\n"
	.string "en gran número.\p"
	.string "Es casi como una plaga, pero no hay\n"
	.string "mejor momento para atraparlos.$"

gBirchDexRatingText_LessThan170:: @ 82A61D6
	.string "Mirando tu Pokédex puedes hacerte\n"
	.string "una buena idea de los Pokémon que\l"
	.string "viven en la región de Hoenn.$"

gBirchDexRatingText_LessThan180:: @ 82A623A
	.string "Yo diría que ya se te puede\n"
	.string "considerar un Profesor Pokémon…\l"
	.string "¡y bueno!$"

gBirchDexRatingText_LessThan190:: @ 82A6287
	.string "With a POKéDEX this complete,\n"
	.string "¡Con una Pokédex tan completa, se\n"
	.string "puede decir que eres todo un\l"
	.string "profesional en la materia!$"

gBirchDexRatingText_LessThan200:: @ 82A62C9
	.string "Estás a punto de acabar la\n"
	.string "Pokédex.\l"
	.string "La cosa se pone emocionante.$"

gBirchDexRatingText_DexCompleted:: @ 82A6312
	.string "¡Felicidades!\n"
	.string "¡Tu Pokédex está completa!$"

gBirchDexRatingText_OnANationwideBasis:: @ 82A633D
	.string "Mmmm…\n"
	.string "A escala nacional…\p"
	.string "has visto {STR_VAR_1} Pokémon y\n"
	.string "has atrapado {STR_VAR_2} Pokémon.$"
