Questionnaire_Text_FillOut::
	.string "Hay un cuestionario.\n"
	.string "¿Quieres rellenarlo?$"

Questionnaire_Text_ThankYou::
	.string "Gracias por rellenar el\n"
	.string "cuestionario. Usaremos tus\l"
	.string "respuestas a modo de referencia.$"

Questionnaire_Text_YouKnowThoseWordsGift::
	.string "Hola, ¿conoces las palabras?\p"
	.string "Pues entonces debes de saber\n"
	.string "de qué va el regalo misterioso.\p"
	.string "¡A partir de ahora, podrás recibir\n"
	.string "regalos misteriosos!$"

Questionnaire_Text_YouCanAccessMysteryGift::
	.string "Una vez guardes la partida, podrás\n"
	.string "acceder al tegalo misterioso.$"

Questionnaire_Text_YouKnowThoseWordsEvent::
	.string "Hola, ¿conoces las palabras?\p"
	.string "Pues entonces debes de saber\n"
	.string "de qué van los eventos misteriosos.$"

Questionnaire_Text_YouCanAccessMysteryEvent::
	.string "Una vez guardes la partida, podrás\n"
	.string "acceder a los eventos misteriosos.$"

MysteryGift_Text_TheresATicketForYou::
	.string "Gracias por usar el sistema\n"
	.string "de los eventos misteriosos.\p"
	.string "Debes de ser {PLAYER}, ¿no?\p"
	.string "Pues tenemos un ticket para ti.$"

MysteryGift_Text_TryUsingItAtLilycovePort::
	.string "Parece que puedes usarlo en el\n"
	.string "Puerto de ciudad Calagua.\p"
	.string "¿Por qué no curioseas un poco\n"
	.string "para ver de qué se trata?$"
