	.align 2
gText_ConfirmSave:: @ 82C87B4
	.string "¿Quieres guardar la partida?$"

gText_AlreadySavedFile:: @ 82C87D5
	.string "Ya hay una partida guardada.\n"
	.string "¿Quieres sobrescribirla?$"

gText_SavingDontTurnOff:: @ 82C8810
	.string "Guardando…\n"
	.string "No apagues la consola.$"

gText_PlayerSavedGame:: @ 82C8832
	.string "{PLAYER} guardó la partida.$"

gText_DifferentSaveFile:: @ 82C8845
	.string "¡Atención!\p"
	.string "Ya hay una partida guardada.\p"
	.string "Si guardas, perderás los datos\n"
	.string "de la partida incluyendo los\l"
	.string "objetos y los Pokémon.\p"
	.string "y sobrescribir los otros datos?$"

gText_SaveError:: @ 82C892A
	.string "Error al guardar.\p"
	.string "Cambia la memoria\n"
	.string "de seguridad.$"

gText_SavingDontTurnOffPower:: @ 82C8959
	.string "Guardando…\n"
	.string "No apagues la consola.$"
