SecretBase_Text_Trainer0Intro: @ 82748A0
	.string "¿Ya tienes una base secreta?\p"
	.string "He dado mil vueltas antes de\n"
	.string "elegir este sitio.\p"
	.string "Y puesto que has llegado tú…,\n"
	.string "¿qué te parece si luchamos?$"

SecretBase_Text_Trainer0AcceptBattle: @ 8274939
	.string "¡Muy bien!\n"
	.string "¡Vamos allá!$"

SecretBase_Text_Trainer0DeclineBattle: @ 827494D
	.string "¿Cómo?\n"
	.string "No me dejes así…$"

SecretBase_Text_Trainer0Defeated:: @ 8274966
	.string "¡Aaaaargh! ¡Qué fuerte eres!\n"
	.string "¡No le digas a nadie que he perdido!$"

SecretBase_Text_Trainer0PostBattle: @ 82749AA
	.string "¿Qué piensas de mi base secreta?\n"
	.string "Ven a verme otra vez mañana.$"

SecretBase_Text_Trainer0PreChampion: @ 82749ED
	.string "¿Ya tienes una base secreta?\p"
	.string "He dado mil vueltas antes\n"
	.string "de elegir este sitio.\p"
	.string "¡Pásate por aquí siempre que quieras!$"

SecretBase_Text_Trainer5Intro: @ 8274A64
	.string "Puedes hacer tu base secreta\n"
	.string "en un montonazo de sitios.\p"
	.string "Pero éste es el que más me gusta.\n"
	.string "¿A que es bonito?\p"
	.string "Por cierto, ¿quieres luchar un rato?$"

SecretBase_Text_Trainer5AcceptBattle: @ 8274AFA
	.string "Muy bien, ¡allá vamos!$"

SecretBase_Text_Trainer5DeclineBattle: @ 8274B0B
	.string "¿Cómo?\n"
	.string "No me dejes así…$"

SecretBase_Text_Trainer5Defeated:: @ 8274B24
	.string "Mmmm… He perdido,\n"
	.string "¡pero no se lo digas a nadie!\l"
	.string "¡Es un secreto supersecreto!$"

SecretBase_Text_Trainer5PostBattle: @ 8274B6C
	.string "Si vuelves a pasar por aquí,\n"
	.string "espero que vengas a verme.$"

SecretBase_Text_Trainer5PreChampion: @ 8274BA2
	.string "Puedes hacer tu base secreta\n"
	.string "en un montonazo de sitios.\p"
	.string "Pero éste es el que más me gusta.\n"
	.string "¿A que es bonito?$"

SecretBase_Text_Trainer1Intro: @ 8274C13
	.string "Este sitio está muy solicitado.\n"
	.string "Siempre lo quieren pillar.\p"
	.string "Ah, ¿tú también querrías\n"
	.string "quedarte con éste?\p"
	.string "Pues, si puedes derrotarme,\n"
	.string "será todo tuyo.$"

SecretBase_Text_Trainer1AcceptBattle: @ 8274CB0
	.string "¡Vale!\n"
	.string "Voy a defender mi base secreta.$"

SecretBase_Text_Trainer1DeclineBattle: @ 8274CDA
	.string "¿Ah, sí?\n"
	.string "¿No te interesa este sitio?$"

SecretBase_Text_Trainer1Defeated:: @ 8274D13
	.string "¡Ya no puedo más!\n"
	.string "¡Me rindo!$"

SecretBase_Text_Trainer1PostBattle: @ 8274D34
	.string "Vale, si me mudo algún día,\n"
	.string "este sitio será tuyo.$"

SecretBase_Text_Trainer1PreChampion: @ 8274D69
	.string "Este sitio está muy solicitado.\n"
	.string "Siempre lo quieren pillar.\p"
	.string "Esperé un montón a que estuviera\n"
	.string "libre y ahora es mío.$"

SecretBase_Text_Trainer6Intro: @ 8274DD2
	.string "Te doy la bienvenida a mi\n"
	.string "Laboratorio Pokémon.\p"
	.string "Llevo a cabo investigaciones secretas\n"
	.string "sobre los combates Pokémon.\p"
	.string "¿Quieres ver lo fuerte que soy?$"

SecretBase_Text_Trainer6AcceptBattle: @ 8274E41
	.string "¡Te vas a enterar de lo que vale\n"
	.string "un peine!$"

SecretBase_Text_Trainer6DeclineBattle: @ 8274E5A
	.string "Vaya…\n"
	.string "Pues otro día entonces…$"

SecretBase_Text_Trainer6Defeated:: @ 8274E75
	.string "Mmmm… Tengo mucho que aprender.\n"
	.string "Me acabas de dar una lección…$"

SecretBase_Text_Trainer6PostBattle: @ 8274EB3
	.string "Gracias por luchar conmigo.\n"
	.string "Vuelve mañana, si te apetece.$"

SecretBase_Text_Trainer6PreChampion: @ 8274EF1
	.string "Te doy la bienvenida a mi\n"
	.string "Laboratorio Pokémon.\p"
	.string "Llevo a cabo investigaciones secretas\n"
	.string "sobre los combates Pokémon.$"

SecretBase_Text_Trainer2Intro: @ 8274F39
	.string "Una gran mansión está bien, pero\n"
	.string "esto es más acogedor.\p"
	.string "Siempre viene gente a verme, qué guay.\p"
	.string "¿Y tú? ¿Quieres pelear?$"

SecretBase_Text_Trainer2AcceptBattle: @ 8274FCA
	.string "¡Así se hace!$"

SecretBase_Text_Trainer2DeclineBattle: @ 8274FDA
	.string "Cuando quieras, pues. Tú avísame.$"

SecretBase_Text_Trainer2Defeated:: @ 8274FFE
	.string "¡Aaaah! ¡Me has aplastado!\n"
	.string "Pero aun así ha estado bien…$"

SecretBase_Text_Trainer2PostBattle: @ 827502A
	.string "Da igual, yo me voy ahora a comprar\n"
	.string "muebles y adornos…\p"
	.string "Quiero que mi base secreta\n"
	.string "sea la más acogedora de todas.$"

SecretBase_Text_Trainer2PreChampion: @ 82750A4
	.string "Una gran mansión está bien,\n"
	.string "pero esto es más acogedor.\p"
	.string "Siempre viene gente a verme, qué guay.$"

SecretBase_Text_Trainer7Intro: @ 8275114
	.string "Me encanta comprar muebles\n"
	.string "y adornos.\p"
	.string "También me encanta entrenar\n"
	.string "Pokémon.\p"
	.string "¿Te gustaría comparar la fuerza\n"
	.string "de nuestros Pokémon?$"

SecretBase_Text_Trainer7AcceptBattle: @ 82751AF
	.string "Gracias.\n"
	.string "¿Empezamos?$"

SecretBase_Text_Trainer7DeclineBattle: @ 82751CA
	.string "Oh…\n"
	.string "Qué decepción…$"

SecretBase_Text_Trainer7Defeated:: @ 82751E1
	.string "Has ganado…$"

SecretBase_Text_Trainer7PostBattle: @ 82751EC
	.string "¡Ha sido muy divertido!\n"
	.string "Y ahora vuelvo a irme de compras.$"

SecretBase_Text_Trainer7PreChampion: @ 8275226
	.string "Me encanta comprar muebles\n"
	.string "y adornos.\p"
	.string "También me encanta entrenar\n"
	.string "Pokémon.$"

SecretBase_Text_Trainer3Intro: @ 8275287
	.string "Algunas personas hacen sus BASES\n"
	.string "SECRETAS en sitios perdidos. ¿Les\l"
	.string "gustará estar más solos que la una?\p"
	.string "Pero tú me has encontrado, así que\n"
	.string "¿qué tal si echamos un combate?$"

SecretBase_Text_Trainer3AcceptBattle: @ 8275315
	.string "¡A mí no me ganan tan fácilmente!$"

SecretBase_Text_Trainer3DeclineBattle: @ 8275330
	.string "Oh… ¿Tanto te ha cansado\n"
	.string "encontrar este sitio?$"

SecretBase_Text_Trainer3Defeated:: @ 8275367
	.string "Me has ganado…$"

SecretBase_Text_Trainer3PostBattle: @ 8275374
	.string "¿Dónde está tu base secreta?\n"
	.string "Me gustaría ir a visitarte.$"

SecretBase_Text_Trainer3PreChampion: @ 82753AB
	.string "Algunas personas hacen sus BASES\n"
	.string "SECRETAS en sitios perdidos. ¿Les\l"
	.string "gustará estar más solos que la una?$"

SecretBase_Text_Trainer8Intro: @ 8275405
	.string "La gente me ha contado que puedes\n"
	.string "conseguir adornos de varias maneras.\p"
	.string "Deberíamos hacer una apuesta a ver\n"
	.string "quién consigue los más bonitos.\p"
	.string "Y entre tanto, ¿luchamos un rato?$"

SecretBase_Text_Trainer8AcceptBattle: @ 82754B2
	.string "¡No puedo perder estando\n"
	.string "en mi base secreta!$"

SecretBase_Text_Trainer8DeclineBattle: @ 82754D8
	.string "Cuando quieras, combatimos.$"

SecretBase_Text_Trainer8Defeated:: @ 82754F6
	.string "¿Eh?\n"
	.string "¿Me has vencido?$"

SecretBase_Text_Trainer8PostBattle: @ 827550C
	.string "¡Pero en coleccionar adornos\n"
	.string "no me gana nadie! ¡Vuelve por aquí!$"

SecretBase_Text_Trainer8PreChampion: @ 8275546
	.string "La gente me ha contado que puedes\n"
	.string "conseguir adornos de varias maneras.\p"
	.string "Deberíamos hacer una apuesta a ver\n"
	.string "quién consigue los más bonitos.$"

SecretBase_Text_Trainer4Intro: @ 82755D2
	.string "He encontrado un lugar estupendo\n"
	.string "y lo he decorado a mi gusto.\p"
	.string "Entreno a mis Pokémon favoritos\n"
	.string "y mejoro junto a ellos.\p"
	.string "Mi vida es perfecta.\n"
	.string "Y tú, ¿buscas pelea?$"

SecretBase_Text_Trainer4AcceptBattle: @ 8275679
	.string "¡Enséñame lo que vales!$"

SecretBase_Text_Trainer4DeclineBattle: @ 8275696
	.string "Supongo que hay días\n"
	.string "en los que no estás para nadie…$"

SecretBase_Text_Trainer4Defeated:: @ 82756C7
	.string "Ya veo que vales mucho…$"

SecretBase_Text_Trainer4PostBattle: @ 82756EF
	.string "Ambos podemos mejorar siempre.\n"
	.string "¡Hay que seguir así!$"

SecretBase_Text_Trainer4PreChampion: @ 827571E
	.string "He encontrado un lugar estupendo\n"
	.string "y lo he decorado a mi gusto.\p"
	.string "Entreno a mis Pokémon favoritos\n"
	.string "y mejoro junto a ellos.$"

SecretBase_Text_Trainer9Intro: @ 82757B5
	.string "Se aprende un montón sobre\n"
	.string "la gente por los adornos que eligen\l"
	.string "y por cómo los colocan.\p"
	.string "¿Qué piensas de mi fabuloso estilo\n"
	.string "decorando? ¿No tienes palabras?\p"
	.string "¿Quieres ver mi estilo luchando?$"

SecretBase_Text_Trainer9AcceptBattle: @ 8275884
	.string "¡No hay marcha atrás!$"

SecretBase_Text_Trainer9DeclineBattle: @ 827589D
	.string "Pues cuando quieras verlo,\n"
	.string "vuelve por aquí.$"

SecretBase_Text_Trainer9Defeated:: @ 82758CC
	.string "¡Tú sí que tienes un estilazo!\n"
	.string "Me has dejado boquiabierta…$"

SecretBase_Text_Trainer9PostBattle: @ 8275909
	.string "¿Qué te ha parecido mi estilo?\n"
	.string "¡Seguiré perfeccionándolo!$"

SecretBase_Text_Trainer9PreChampion: @ 8275944
	.string "Se aprende un montón sobre\n"
	.string "la gente por los adornos que eligen\l"
	.string "y por cómo los colocan.\p"
	.string "¿Qué piensas de mi fabuloso estilo\n"
	.string "decorando? ¿No tienes palabras?$"
