ShoalCave_LowTideEntranceRoom_Text_AreYouPlanningOnGoingInThere: @ 82A7E0E
	.string "¿Estás pensando en llegar\n"
	.string "hasta el fondo?\p"
	.string "¿Por qué no me traes Sal\n"
	.string "Cardumen y Conchas Cardumen?\p"
	.string "Si las consigo, podré hacerte\n"
	.string "algo muy especial.$"

ShoalCave_LowTideEntranceRoom_Text_BringMe4ShoalSaltAndShells: @ 82A7EB3
	.string "Necesito Sal Cardumen y Conchas\n"
	.string "Cardumen. Con cuatro unidades de cada\l"
	.string "una, puedo hacer una Campana Concha.\p"
	.string "Esos ingredientes se pueden conseguir\n"
	.string "un día sí y otro también.$"

ShoalCave_LowTideEntranceRoom_Text_WouldYouLikeShellBell: @ 82A7F37
	.string "¡Hala! ¡Traes Sal Cardumen\n"
	.string "y Conchas Cardumen!\l"
	.string "¡Y bastantes de cada!\p"
	.string "¿Quieres que te haga una\n"
	.string "Campana Concha con ellas?$"

ShoalCave_LowTideEntranceRoom_Text_MakeShellBellRightAway: @ 82A7FAC
	.string "Así me gusta. Te voy a hacer\n"
	.string "una Campana Concha en un plis.\p"
	.string "La, la, la…\n"
	.string "La, la, la…\p"
	.string "¡Ya está!$"

ShoalCave_LowTideEntranceRoom_Text_ExplainShellBell: @ 82A8012
	.string "Haz que algún Pokémon la sostenga.\n"
	.string "Seguro que le encanta.\p"
	.string "Y no me extraña… ¡La Campana Concha\n"
	.string "tiene un repicar sublime!\p"
	.string "Los ingredientes para hacerla se\n"
	.string "pueden conseguir diariamente, así que\l"
	.string "cuando quieras puedo hacerte más.$"

ShoalCave_LowTideEntranceRoom_Text_WantedToMakeShellBell: @ 82A80C6
	.string "Oh… Pues vaya… Yo que quería\n"
	.string "hacer una Campana Concha…$"

ShoalCave_LowTideEntranceRoom_Text_NoSpaceInYourBag: @ 82A80F5
	.string "Aunque te la hiciera, no tienes\n"
	.string "espacio en la Mochila.\p"
	.string "Deja un hueco libre y vuelve\n"
	.string "a por tu Campana Concha.$"

ShoalCave_Text_WasShoalSaltNowNothing: @ 82A8169
	.string "Aquí había algo de Sal Cardumen,\n"
	.string "pero ahora no queda nada.$"

ShoalCave_Text_WasShoallShellNowNothing: @ 82A81A8
	.string "Aquí había una Concha Cardumen,\n"
	.string "pero ahora no hay nada.$"
