Route102_Text_CalvinIntro: @ 8294513
	.string "Espero no equivocarme pero,\n"
	.string "¿eso es un Pokémon?\l"
	.string "¡Pues tienes que luchar conmigo!$"

Route102_Text_CalvinDefeated: @ 829457C
	.string "No sé para qué me meto\n"
	.string "yo solito en estos berenjenales…$"

Route102_Text_CalvinPostBattle: @ 82945AC
	.string "La próxima vez te vas a enterar.\n"
	.string "¡Voy a darte de lo lindo!$"

Route102_Text_CalvinRegister: @ 82945EB
	.string "¡Ey! ¡Tú! Me pegaste una\n"
	.string "paliza la otra vez que luchamos.\p"
	.string "¡Regístrame en tu Pokénav para que\n"
	.string "luchemos de nuevo!$"

Route102_Text_CalvinRegisterShort: @ 8294668
	.string "¡Oye, la próxima vez verás!\n"
	.string "¡Regístrame en tu Pokénav!$"

Route102_Text_CalvinRematchIntro: @ 82946AE
	.string "He estado esperando este momento.\n"
	.string "No he dejado de entrenar.\l"
	.string "¡Te vas a enterar!$"

Route102_Text_CalvinRematchDefeated: @ 829470C
	.string "¿Otra vez? No puede ser…\n"
	.string "¿Qué tengo que hacer para\l"
	.string "poder derrotarte?$"

Route102_Text_CalvinRematchPostBattle: @ 829473C
	.string "Espera y verás. Algún día\n"
	.string "te derrotaré.$"

Route102_Text_AllenIntro: @ 8294775
	.string "¡Mira qué Pokémon he capturado!\n"
	.string "¡Es único en su especie!$"

Route102_Text_AllenDefeated: @ 82947AA
	.string "Este Pokémon no me ha servido\n"
	.string "de nada…$"

Route102_Text_AllenPostBattle: @ 82947DB
	.string "No habré ganado esta vez, pero…\n"
	.string "¡Mi Pokémon es especial!$"

Route102_Text_RickIntro: @ 829480C
	.string "¡Tú! ¡Mira qué Pokémon\n"
	.string "Bicho tan espectaculares tengo!$"

Route102_Text_RickDefeated: @ 8294847
	.string "¡Nooooo! ¡Mis queridos Pokémon!$"

Route102_Text_RickPostBattle: @ 8294859
	.string "Los Pokémon Bicho tienen una ventaja\n"
	.string "respecto al resto. Crecen muy rápido.$"

Route102_Text_TianaIntro: @ 829489E
	.string "¿Crees que estás o\n"
	.string "para embarcarte en este viaje?\p"
	.string "¡Déjame comprobarlo!$"

Route102_Text_TianaDefeated: @ 82948F3
	.string "Aprobado…$"

Route102_Text_TianaPostBattle: @ 8294916
	.string "Te recomiendo capturar varios\n"
	.string "Pokémon en esta ruta.$"

Route103_Text_DaisyIntro: @ 829495A
	.string "¿Te ha atraído el dulce y relajante\n"
	.string "aroma que emanamos?$"

Route103_Text_DaisyDefeated: @ 829498F
	.string "Pues no ha debido de ser el aroma…$"

Route103_Text_DaisyPostBattle: @ 82949B4
	.string "La aromaterapia es una técnica de\n"
	.string "curación mediante el uso de fragancias.$"

Route103_Text_AmyIntro: @ 82949F9
	.string "Ali: Soy Ali.\n"
	.string "Y ésta es mi hermana pequeña, Mar.\l"
	.string "¡Combatimos juntas!$"

Route103_Text_AmyDefeated: @ 8294A3D
	.string "Ali: O-o-oh… Hemos perdido…$"

Route103_Text_AmyPostBattle: @ 8294A52
	.string "Ali: Tienes que pensar en un montón\n"
	.string "de cosas cuando luchas contra dos\l"
	.string "Entrenadores.$"

Route103_Text_AmyNotEnoughPokemon: @ 8294AAE
	.string "Ali: O-o-oh… Sólo tienes un Pokémon.\n"
	.string "Así no puedes luchar contra nosotras.$"

Route103_Text_LivIntro: @ 8294AFD
	.string "Mar: Luchamos juntas, en equipo.$"

Route103_Text_LivDefeated: @ 8294B22
	.string "Mar: O-o-oh, nos han ganado…$"

Route103_Text_LivPostBattle: @ 8294B40
	.string "Mar: Mi hermana mayor y yo trabajamos\n"
	.string "perfectamente bien en equipo.\p"
	.string "Pero esta vez no ha ido tan bien…$"

Route103_Text_AmyLivRegister: @ 8294B8A
	.string "Mar: Ahora somos mucho mejores…\n"
	.string "¡De verdad! ¡Ya verás la próxima vez!$"

Route103_Text_LivNotEnoughPokemon: @ 8294BD0
	.string "Mar: Si quieres luchar contra nosotras,\n"
	.string "necesitas dos Pokémon.\l"
	.string "¡Si no, no es justo!$"

Route103_Text_AmyRematchIntro: @ 8294C29
	.string "Ali: Soy Ali.\n"
	.string "Y ésta es mi hermana pequeña, Mar.\l"
	.string "¡Combatimos juntas!$"

Route103_Text_AmyRematchDefeated: @ 8294C6D
	.string "Ali: O-o-oh, no hemos ganado tampoco\n"
	.string "esta vez… ¡Buaaaaa!$"

Route103_Text_AmyRematchPostBattle: @ 8294C93
	.string "Ali: Tienes que pensar en un montón\n"
	.string "de cosas cuando luchas contra dos\l"
	.string "Entrenadores.$"

Route103_Text_AmyRematchNotEnoughPokemon: @ 8294CEF
	.string "Ali: O-o-oh… Sólo tienes un Pokémon.\n"
	.string "Así no puedes luchar contra nosotras.$"

Route103_Text_LivRematchIntro: @ 8294D3E
	.string "Mar: Luchamos juntas, en equipo.$"

Route103_Text_LivRematchDefeated: @ 8294D63
	.string "Mar: O-o-oh, hemos perdido otra\n"
	.string "vez… ¡Buaaaaa!$"

Route103_Text_LivRematchPostBattle: @ 8294D89
	.string "Mar: Mi hermana mayor y yo trabajamos\n"
	.string "perfectamente bien en equipo.\p"
	.string "¿Por qué hemos perdido otra vez?…$"

Route103_Text_LivRematchNotEnoughPokemon: @ 8294DDB
	.string "Mar: Si quieres luchar contra nosotras,\n"
	.string "necesitas dos Pokémon.\l"
	.string "¡Si no, no es justo!$"

Route103_Text_AndrewIntro: @ 8294E34
	.string "¡Brrrr! ¡Mi hilo de pescar está todo\n"
	.string "enredado! ¡Qué fastidio tan gordo!\l"
	.string "¡Lo voy a pagar contigo!$"

Route103_Text_AndrewDefeated: @ 8294E92
	.string "¡Brrrr! ¡He perdido!\n"
	.string "¡Ahora estoy aún más mosqueado!$"

Route103_Text_AndrewPostBattle: @ 8294EBB
	.string "¡Brrrr! ¡Qué mosqueo más\n"
	.string "tonto tengo! ¡Brrrrrrrrrr!$"

Route103_Text_MiguelIntro: @ 8294EDF
	.string "Mi Pokémon es una monada.\n"
	.string "¡Mira, te lo voy a enseñar!$"

Route103_Text_MiguelDefeated: @ 8294F21
	.string "¡Ay, ay, ay, ay!\n"
	.string "¡Mi Pokémon bonito!$"

Route103_Text_MiguelPostBattle: @ 8294F42
	.string "Mi querido Pokémon es una monada\n"
	.string "hasta cuando está debilitado.$"

Route103_Text_MiguelRegister: @ 8294F7E
	.string "¡Voy a obligarte a que admires\n"
	.string "de nuevo a mi encantador Pokémon!$"

Route103_Text_MiguelRematchIntro: @ 8294FC3
	.string "¡Eh, mira! Mi preciosísimo Pokémon\n"
	.string "es aún más encantador que antes.$"

Route103_Text_MiguelRematchDefeated: @ 8295006
	.string "¡Ay, ay, ay, ay!\n"
	.string "¡Mi Pokémon bonito!$"

Route103_Text_MiguelRematchPostBattle: @ 829501E
	.string "Cuanto más tiempo paso con él,\n"
	.string "más mono se vuelve.$"

Route103_Text_PeteIntro: @ 8295063
	.string "Aquí no hay distancia…\n"
	.string "¡Deberías echarte a nadar!$"

Route103_Text_PeteDefeated: @ 8295093
	.string "¡Tocado y hundido!$"

Route103_Text_PetePostBattle: @ 82950AA
	.string "Ah, claro, ya entiendo.\p"
	.string "Si tuviera un Pokémon como\n"
	.string "el tuyo, ¡yo también haría Surf!$"

Route103_Text_IsabelleIntro: @ 8295116
	.string "¡Mira por dónde vas!\n"
	.string "¡Colisión!$"

Route103_Text_IsabelleDefeated: @ 8295146
	.string "Glu, glu, glu…$"

Route103_Text_IsabellePostBattle: @ 829514D
	.string "Yo solo estaba haciendo unos largos…\n"
	.string "Siento haber provocado la colisión.$"

Route103_Text_RhettIntro: @ 8295199
	.string "¡Guau!\n"
	.string "¿Cómo te has metido aquí?$"

Route103_Text_RhettDefeated: @ 82951C6
	.string "¡Guau!\n"
	.string "¡Qué potencia!$"

Route103_Text_RhettPostBattle: @ 82951DE
	.string "¿A ti te gustan los espacios pequeños?$"

Route103_Text_MarcosIntro: @ 8295206
	.string "Las notas de mi guitarra atraen\n"
	.string "a la gente. ¡La prueba eres tú!$"

Route103_Text_MarcosDefeated: @ 829522B
	.string "Has arruinado mi espectáculo…$"

Route103_Text_MarcosPostBattle: @ 8295246
	.string "Siempre busco lugares solitarios\n"
	.string "para tocar, pero al final acabo rodeado\l"
	.string "de gente.\p"
	.string "Voy a tener que hacerme profesional…$"

Route104_Text_GinaIntro: @ 82952BB
	.string "Gina: Vale, ¡luchemos con nuestros\n"
	.string "Pokémon!$"

Route104_Text_GinaDefeat: @ 82952E6
	.string "Gina: ¡No me gusta perder!$"

Route104_Text_GinaPostBattle: @ 82952FE
	.string "Gina: ¡Está claro que eres fuerte!\n"
	.string "¡Tenemos que entrenar mucho más!$"

Route104_Text_GinaNotEnoughMons: @ 8295330
	.string "Gina: ¿Cómo? ¿Sólo tienes un Pokémon?\n"
	.string "Entonces no luchamos contra ti.\p"
	.string "Combatir con un solo Pokémon\n"
	.string "es de lo más aburrido. No mola.$"

Route104_Text_MiaIntro: @ 82953AF
	.string "Mini: Somos gemelas, así que\n"
	.string "entablamos combates Pokémon juntas.$"

Route104_Text_MiaDefeat: @ 82953E1
	.string "Mini: Luchamos juntas, pero eso no nos\n"
	.string "ha hecho ganar esta vez…$"

Route104_Text_MiaPostBattle: @ 829540D
	.string "Mini: Entrenaremos más a nuestros\n"
	.string "Pokémon para ser tan fuertes como tú.$"

Route104_Text_MiaNotEnoughMons: @ 8295449
	.string "Mini: ¿Quieres luchar contra nosotras?\p"
	.string "Pues si no tienes dos Pokémon,\n"
	.string "ni hablar. ¡Somos muy fuertes para ti!$"

Route104_Text_IvanIntro: @ 82954BD
	.string "¿Por qué negarlo?\n"
	.string "¡Soy un experto en Pokémon\l"
	.string "de tipo Agua!\p"
	.string "¿Eh?\n"
	.string "¿Que no sabes quién soy?$"

Route104_Text_IvanDefeat: @ 8295509
	.string "Pensaba que no era muy malo, pero\n"
	.string "me temo que debo mejorar…$"

Route104_Text_IvanPostBattle: @ 829554E
	.string "He estado pescando demasiado.\n"
	.string "Debería haber entrenado a mis Pokémon.$"

Route104_Text_BillyIntro: @ 829558A
	.string "¡Dejar huellas en la arena\n"
	.string "es tan divertido!$"

Route104_Text_BillyDefeat: @ 82955B4
	.string "¡Aaaaah! ¡Tengo arena en los zapatos!\n"
	.string "¡Es la mar de desagradable!$"

Route104_Text_BillyPostBattle: @ 82955E8
	.string "Estoy dejando muchas huellas en la\n"
	.string "arena, pero enseguida desaparecen…$"

Route104_Text_HaleyIntro: @ 829563A
	.string "¿Debería…?\n"
	.string "¿O no debería…?\p"
	.string "¡Venga, sí, vamos a luchar!$"

Route104_Text_HaleyDefeat: @ 829566F
	.string "No hubiera debido…$"

Route104_Text_HaleyPostBattle: @ 8295689
	.string "Si te enfrentas a una decisión y dejas\n"
	.string "que alguien la tome por ti, siempre te\l"
	.string "arrepentirás del resultado…$"

Route104_Text_HaleyRegister1: @ 82956FF
	.string "Eres fuerte, pero ¿mereces que\n"
	.string "te registre en mi Pokénav?\l"
	.string "Igual no…\p"
	.string "Venga, va, ¡te voy a registrar!$"

Route104_Text_HaleyRegister2: @ 829576B
	.string "Eres fuerte, pero ¿mereces que\n"
	.string "te registre en mi Pokénav?\l"
	.string "Igual no…\p"
	.string "Venga, va, ¡te voy a registrar!$"

Route104_Text_HaleyRematchIntro: @ 82957D7
	.string "Vamos, ¡enfréntate a mí!$"

Route104_Text_HaleyRematchDefeat: @ 82957F0
	.string "Ooooh…\n"
	.string "Pensé que podía ganar…$"

Route104_Text_HaleyPostRematch: @ 829580C
	.string "Decidí luchar, así que debo aceptar\n"
	.string "la derrota con espíritu deportivo.\p"
	.string "Aun así hubiera preferido ganar…$"

Route104_Text_WinstonIntro: @ 8295870
	.string "Por supuesto que acepto tu reto.\n"
	.string "¡Me sobra el dinero!$"

Route104_Text_WinstonDefeat: @ 82958AD
	.string "¿Por qué no he ganado?$"

Route104_Text_WinstonPostBattle: @ 82958C1
	.string "Hay cosas que el dinero no puede\n"
	.string "comprar. Por ejemplo, los Pokémon.$"

Route104_Text_WinstonRegister1: @ 82958F8
	.string "¿Eh?\n"
	.string "Anda, si tienes un Pokénav.\p"
	.string "Será un placer registrarte.\n"
	.string "Después de todo, estoy forrado.$"

Route104_Text_WinstonRegister2: @ 829595A
	.string "¿Eh?\n"
	.string "Anda, si tienes un Pokénav.\p"
	.string "Será un placer registrarte.\n"
	.string "Después de todo, estoy forrado.$"

Route104_Text_WinstonRematchIntro: @ 82959BC
	.string "Tras perder contigo, me puse a\n"
	.string "estudiar de todo sobre los Pokémon.$"

Route104_Text_WinstonRematchDefeat: @ 82959FC
	.string "¡¿He perdido otra vez?!\n"
	.string "¿Por qué no he ganado?$"

Route104_Text_WinstonPostRematch: @ 8295A1E
	.string "Soy rico a rabiar, pero no se me\n"
	.string "dan bien los Pokémon…\p"
	.string "Es un mundo tan complejo…$"

Route104_Text_CindyIntro: @ 8295A7E
	.string "El destino ha hecho que nos cruzáramos.\n"
	.string "¿Quieres luchar contra mí?$"

Route104_Text_CindyDefeat: @ 8295ABB
	.string "Ooooh…$"

Route104_Text_CindyPostBattle: @ 8295AC3
	.string "“Hola” siempre precede a “adiós”.\n"
	.string "Espero que volvamos a vernos.$"

Route104_Text_CindyRegister1: @ 8295B01
	.string "Hola, volvemos a encontrarnos.\p"
	.string "Parece ser cosa del destino.\n"
	.string "Registrémonos en nuestros Pokénav.$"

Route104_Text_CindyRegister2: @ 8295B60
	.string "Hay que celebrar que el destino\n"
	.string "no deja de reunirnos.\p"
	.string "Registrémonos en nuestros Pokénav.$"

Route104_Text_CindyRematchIntro: @ 8295BC8
	.string "Hola, volvemos a encontrarnos.\n"
	.string "¿Quieres luchar contra mí?$"

Route104_Text_CindyRematchDefeat: @ 8295BFA
	.string "Ooooh…\n"
	.string "Lo hice lo mejor que pude…$"

Route104_Text_CindyPostRematch: @ 8295C1F
	.string "“Hola” siempre precede a “adiós”.\n"
	.string "Espero que volvamos a vernos.$"

Route104_Text_DarianIntro: @ 8295C5D
	.string "¡He pescado un Pokémon\n"
	.string "con pinta de fiero!\p"
	.string "¡Se ve a leguas que es especial!\n"
	.string "¡Da miedo!$"

Route104_Text_DarianDefeat: @ 8295CC9
	.string "Pero…$"

Route104_Text_DarianPostBattle: @ 8295CD3
	.string "Vaya Magikarp…\n"
	.string "Lo suyo es mucho ruido y pocas nueces.$"

Route105_Text_FosterIntro: @ 8295D0F
	.string "Dicen que hay una roca mística\n"
	.string "por aquí cerca.\l"
	.string "¿Tú sabes algo?$"

Route105_Text_FosterDefeated: @ 8295D62
	.string "Tenía la mente en esa roca y he dejado\n"
	.string "que mis Pokémon se debilitaran…$"

Route105_Text_FosterPostBattle: @ 8295DAB
	.string "Me puedo pasar las horas muertas\n"
	.string "mirando una roca bonita sin cansarme.$"

Route105_Text_LuisIntro: @ 8295DF5
	.string "¡Huy! Cuando te vi pensé que eras\n"
	.string "un crío que se estaba ahogando…\p"
	.string "Parece que estás bien, así que\n"
	.string "¿qué piensas de echar un combate?$"

Route105_Text_LuisDefeated: @ 8295E66
	.string "Glu… Glu… Glu…$"

Route105_Text_LuisPostBattle: @ 8295E72
	.string "Si te estás ahogando, agita el brazo\n"
	.string "hacia la costa para pedir ayuda.$"

Route105_Text_DominikIntro: @ 8295EB7
	.string "Nadar entre las olas del mar…\n"
	.string "¡Mejor que en una piscina!$"

Route105_Text_DominikDefeated: @ 8295EEA
	.string "He perdido…\n"
	.string "Qué depre…$"

Route105_Text_DominikPostBattle: @ 8295F08
	.string "¿Por qué el mar es azul?\p"
	.string "Leí la explicación en el museo de\n"
	.string "ciudad Portual, pero no me acuerdo…$"

Route105_Text_BeverlyIntro: @ 8295F5C
	.string "Mi cuerpo es más ligero en el agua.\n"
	.string "¡Es como si no pesara nada!$"

Route105_Text_BeverlyDefeated: @ 8295FA0
	.string "Me has dejado flotando…$"

Route105_Text_PostBattle: @ 8295FAE
	.string "El peso de tu cuerpo es nueve veces\n"
	.string "más ligero en el agua…\p"
	.string "¡Es normal que puedas saltar y\n"
	.string "moverte como si nada!$"

Route105_Text_ImaniIntro: @ 8296025
	.string "El cielo azul…\n"
	.string "El ancho mar…\l"
	.string "Qué tranquilidad…$"

Route105_Text_ImaniDefeated: @ 8296059
	.string "¡No estaba lista para el combate!$"

Route105_Text_ImaniPostBattle: @ 8296076
	.string "Me gusta que me digan que soy\n"
	.string "buena compañía, ji, ji, ji.$"

Route105_Text_AndresIntro: @ 82960A9
	.string "Tengo la certeza de que el mar\n"
	.string "guarda incontables secretos.$"

Route105_Text_AndresDefeated: @ 82960DB
	.string "Has descubierto mi secreto…\n"
	.string "No sé luchar…$"

Route105_Text_AndresPostBattle: @ 82960FA
	.string "Tengo la certeza de que el mar\n"
	.string "guarda incontables secretos.\p"
	.string "¡Y pienso descubrirlos todos!$"

Route105_Text_AndresRegister: @ 8296159
	.string "¿Cómo? ¿No soy fuerte y sin embargo\n"
	.string "me quieres registrar en tu Pokénav?$"

Route105_Text_AndresRematchIntro: @ 829619E
	.string "Ya te dije que no soy muy fuerte.\n"
	.string "¿Seguro que quieres luchar conmigo?$"

Route105_Text_AndresRematchDefeated: @ 82961DD
	.string "No es ninguna sorpresa…\n"
	.string "Ya sabía que no podía ganar.$"

Route105_Text_AndresRematchPostBattle: @ 82961FE
	.string "Puede que no sepa luchar, pero\n"
	.string "como explorador no tengo igual.\p"
	.string "¡Voy a viajar por todos los mares\n"
	.string "del mundo!$"

Route105_Text_JosueIntro: @ 829626F
	.string "Nadar me agota una barbaridad.\n"
	.string "He perdido costumbre.\p"
	.string "¡Necesito un combate, para variar!$"

Route105_Text_JosueDefeated: @ 82962CB
	.string "He perdido, pero solo porque\n"
	.string "estamos luchando en el mar.$"

Route105_Text_JosuePostBattle: @ 82962EC
	.string "La verdad es que prefiero luchar\n"
	.string "en el aire a luchar en el mar.$"

Route106_Text_ElliotIntro: @ 8296327
	.string "¿Qué prefieres? ¿La pesca en agua\n"
	.string "dulce o en el mar?$"

Route106_Text_ElliotDefeated: @ 829635C
	.string "Los Pokémon se me dan tan mal como\n"
	.string "la pesca en alta mar…$"

Route106_Text_ElliotPostBattle: @ 829638C
	.string "La pesca es un deporte genial,\n"
	.string "ya sea en un río o en el mar…\l"
	.string "¿A que piensas igual?$"

Route106_Text_ElliotRegister: @ 82963E3
	.string "Pescar es genial, pero luchar también.\n"
	.string "Podríamos volver a enfrentarnos, ¿no?$"

Route106_Text_ElliotRematchIntro: @ 829642E
	.string "He atrapado un montón de Pokémon\n"
	.string "pescando. Vas a ver un señor combate.$"

Route106_Text_ElliotRematchDefeated: @ 8296477
	.string "He perdido con todas las de la ley…$"

Route106_Text_ElliotRematchPostBattle: @ 8296493
	.string "Da igual que pierdas o ganes,\n"
	.string "los Pokémon son lo mejor que hay.\l"
	.string "¿A que piensas igual?$"

Route106_Text_NedIntro: @ 82964D4
	.string "¿Qué hace un pescador cuando tiene\n"
	.string "que ir al servicio?\p"
	.string "¿Qué pasa si un pez gordo pica en mi\n"
	.string "CAÑA justo cuando estoy en el servicio?\l"
	.string "Tengo que aguantarme…$"

Route106_Text_NedDefeated: @ 8296553
	.string "He perdido porque tengo ganas de ir\n"
	.string "al servicio y me estoy aguantando…$"

Route106_Text_NedPostBattle: @ 8296588
	.string "¡Yo no me muevo! ¡Tengo la corazonada\n"
	.string "de que va a picar uno gordo de verdad!$"

Route106_Text_DouglasIntro: @ 82965BB
	.string "¡Ja, ja, ja! Corriendo soy una tortuga,\n"
	.string "¡pero en el agua soy un pez!$"

Route106_Text_DouglasDefeated: @ 82965FD
	.string "¡Me rindo!$"

Route106_Text_DouglasPostBattle: @ 8296608
	.string "Seguro que no pierdo en una carrera…$"

Route106_Text_KylaIntro: @ 8296628
	.string "En el mar soy un as. ¡No te lo voy a poner\n"
	.string "nada fácil solo porque seas tan joven!$"

Route106_Text_KylaDefeated: @ 8296674
	.string "Tú no me tomas en serio, ¿verdad?$"

Route106_Text_KylaPostBattle: @ 829669E
	.string "Deslizarse entre las olas…\n"
	.string "Qué placer… ¿Por qué no lo pruebas?$"

Route107_Text_DarrinIntro: @ 82966E5
	.string "Auaaaa…\p"
	.string "Debo de haberme dormido mientras\n"
	.string "me hacía el muerto entre las olas…$"

Route107_Text_DarrinDefeated: @ 829672F
	.string "Bueno, he perdido…\n"
	.string "Pues nada, a dormir otra vez…$"

Route107_Text_DarrinPostBattle: @ 829675B
	.string "Flotar entre las olas arrullado por\n"
	.string "el mar es como dormir en una cama\l"
	.string "muy cómoda y blandita…$"

Route107_Text_TonyIntro: @ 82967AD
	.string "En el mar soy un as.\n"
	.string "¡Vamos a ver si me puedes!$"

Route107_Text_TonyDefeated: @ 82967D8
	.string "He perdido en casa…\n"
	.string "¡No me lo puedo creer!$"

Route107_Text_TonyPostBattle: @ 82967FF
	.string "Nado en el mar con muchas ganas.\p"
	.string "¡Nunca me canso!\n"
	.string "De hecho, voy a nadar un poco más.$"

Route107_Text_TonyRegister: @ 829685A
	.string "Tu estilo me ha dejado de una pieza.\n"
	.string "Espero que no te olvides de mí.$"

Route107_Text_TonyRematchIntro: @ 8296897
	.string "Gracias a haber nadado tanto en el mar,\n"
	.string "mi Pokémon ha mejorado un montón.$"

Route107_Text_TonyRematchDefeated: @ 82968D5
	.string "¡No me lo puedo creer!\p"
	.string "Mi Pokémon es más fuerte, pero yo aún\n"
	.string "tengo que mejorar como Entrenador.$"

Route107_Text_TonyRematchPostBattle: @ 8296923
	.string "Lo que aprendes en los combates\n"
	.string "te hace mejorar como Entrenador.\l"
	.string "Es una lección muy valiosa.$"

Route107_Text_DeniseIntro: @ 8296974
	.string "¿Conoces un pueblecito llamado\n"
	.string "Azuliza?$"

Route107_Text_DeniseDefeated: @ 829699E
	.string "¡Esto no estaba previsto!$"

Route107_Text_DenisePostBattle: @ 82969AB
	.string "Hay un dicho rarísimo que está\n"
	.string "haciendo furor en el club de Azuliza.$"

Route107_Text_BethIntro: @ 82969E4
	.string "¿Buscas pelea?\n"
	.string "¡Pues encantada!$"

Route107_Text_BethDefeated: @ 8296A17
	.string "No he estado a la altura…$"

Route107_Text_BethPostBattle: @ 8296A35
	.string "Apuesto lo que sea a que vas a seguir\n"
	.string "mejorando… ¡Y yo también!$"

Route107_Text_LisaIntro: @ 8296A77
	.string "Lisa: ¡Mi hermano y yo te retamos\n"
	.string "a un combate!$"

Route107_Text_LisaDefeated: @ 8296AA7
	.string "Lisa: Impresionante.\n"
	.string "Eres mucho más que fuerte.$"

Route107_Text_LisaPostBattle: @ 8296ADC
	.string "Lisa: ¿Te apetece venir a la playa\n"
	.string "con nosotros a descansar?$"

Route107_Text_LisaNotEnoughPokemon: @ 8296B1E
	.string "Lisa: Si quieres que luchemos,\n"
	.string "deberás traer más Pokémon.$"

Route107_Text_RayIntro: @ 8296B57
	.string "Roy: Mi hermana y yo siempre luchamos\n"
	.string "con Pokémon.\p"
	.string "Yo solo siempre pierdo, ¡pero esto\n"
	.string "es un Combate Doble!$"

Route107_Text_RayDefeated: @ 8296BB3
	.string "Roy: ¡Halaaa! ¡Nos has ganado\n"
	.string "por goleada!$"

Route107_Text_RayPostBattle: @ 8296BE1
	.string "Roy: Este Pokémon es un regalo de\n"
	.string "mi hermana. Yo mismo lo he entrenado\l"
	.string "y ahora somos uña y carne.$"

Route107_Text_RayNotEnoughPokemon: @ 8296C34
	.string "Roy: Si quieres que luchemos,\n"
	.string "deberás traer más Pokémon.$"

Route107_Text_CamronIntro: @ 8296C6F
	.string "¡Estoy en medio de un triatlón,\n"
	.string "pero aún me quedan fuerzas!$"

Route107_Text_CamronDefeated: @ 8296CAD
	.string "Me has dejado sin fuerzas…$"

Route107_Text_CamronPostBattle: @ 8296CC0
	.string "Todavía tengo que completar\n"
	.string "dos pruebas.\p"
	.string "¿Seré capaz de acabar?$"

Route108_Text_JeromeIntro: @ 8296D10
	.string "Mi sueño es nadar en los siete mares.$"

Route108_Text_JeromeDefeated: @ 8296D3C
	.string "Así no llego ni al río de la esquina…$"

Route108_Text_JeromePostBattle: @ 8296D6E
	.string "Lo mejor de nadar es que puedes\n"
	.string "jugar con los Pokémon marinos.$"

Route108_Text_MatthewIntro: @ 8296DAF
	.string "¡Hola, hola! ¿Tú también vas\n"
	.string "a la Nao Abandonada?$"

Route108_Text_MatthewDefeated: @ 8296DEA
	.string "Me hundo…\n"
	.string "Glu… Glu…$"

Route108_Text_MatthewPostBattle: @ 8296E03
	.string "Creo que hay gente que se atreve\n"
	.string "a entrar en la Nao Abandonada…$"

Route108_Text_TaraIntro: @ 8296E33
	.string "No hay nada más cómodo que\n"
	.string "un bikini para ir a la playa.$"

Route108_Text_TaraDefeated: @ 8296E71
	.string "¡Oh, no!$"

Route108_Text_TaraPostBattle: @ 8296E7A
	.string "Bueno, quizás esté bien para tomar\n"
	.string "el sol, pero no para combatir…$"

Route108_Text_MissyIntro: @ 8296EC7
	.string "¡Me encanta el mar!\n"
	.string "¡Cuando nado, se me olvidan todos\l"
	.string "mis problemas!$"

Route108_Text_MissyDefeated: @ 8296EFC
	.string "Perder combates me estresa\n"
	.string "una barbaridad… ¡Me voy a nadar!$"

Route108_Text_MissyPostBattle: @ 8296F2A
	.string "Combate el estrés nadando.\n"
	.string "¡No hay remedio mejor!$"

Route108_Text_CoryIntro: @ 8296F5D
	.string "Me gustan los Pokémon de tipo Agua.\n"
	.string "¡Pero no les hago ascos a los demás!$"

Route108_Text_CoryDefeated: @ 8296F93
	.string "¡Aaaaaaah! ¡He perdido!\n"
	.string "¡Aaaaaaah! ¡Aaaaaaah!$"

Route108_Text_CoryPostBattle: @ 8296FB0
	.string "Gritar de vez en cuando sienta de\n"
	.string "miedo. ¡Liberas mucha adrenalina!$"

Route108_Text_CoryRegister: @ 8296FD8
	.string "Me gustan los entrenadores fuertes.\n"
	.string "¡Regístrame en tu Pokénav!$"

Route108_Text_CoryRematchIntro: @ 8297011
	.string "¡Gane o pierda, me gusta luchar\n"
	.string "en el mar!$"

Route108_Text_CoryRematchDefeated: @ 8297036
	.string "¡Aaaaaaah! ¡He perdido!\n"
	.string "¡Aaaaaaah! ¡Aaaaaaah!$"

Route108_Text_CoryRematchPostBattle: @ 8297059
	.string "Si algún desafío te estresa demasiado,\n"
	.string "¡prueba a pegar un buen berrido!$"

Route108_Text_CarolinaIntro: @ 8297094
	.string "Estoy muy orgullosa de mis Pokémon.\n"
	.string "¡Vas a ver lo que es luchar con rapidez!$"

Route108_Text_CarolinaDefeated: @ 82970D7
	.string "Te has pasado cantidad.$"

Route108_Text_CarolinaPostBattle: @ 82970F0
	.string "Si te gustan los bañadores, como a\n"
	.string "mí, lo mejor es estar cerca del mar.$"

Route109_Text_DavidIntro: @ 8297140
	.string "¡Ja, ja, ja! ¡Mira mis abdominales!\n"
	.string "¡Y todo es gracias a la natación!$"

Route109_Text_DavidDefeated: @ 829717D
	.string "¡Jarl, jarl, jarl!\n"
	.string "¡La he pifiado!$"

Route109_Text_DavidPostBattle: @ 8297191
	.string "¡Ja, ja, ja!\p"
	.string "¡Mis abdominales son de nadar, no\n"
	.string "de luchar en combates Pokémon!$"

Route109_Text_AliceIntro: @ 82971D1
	.string "¿Te has puesto crema protectora\n"
	.string "antes de exponerte al sol?$"

Route109_Text_AliceDefeated: @ 82971FD
	.string "¡Ay, ay, ay!$"

Route109_Text_AlicePostBattle: @ 829720F
	.string "¡La nariz es la zona que se pela primero!$"

Route109_Text_HueyIntro: @ 8297235
	.string "He anclado en los puertos de todo el\n"
	.string "mundo, pero el mejor es Ciudad Portual.$"

Route109_Text_HueyDefeated: @ 829727B
	.string "¡Tú también eres lo más!$"

Route109_Text_HueyPostBattle: @ 829728C
	.string "Quien mejor sabe entrenar Pokémon\n"
	.string "está en el mejor puerto…$"

Route109_Text_EdmondIntro: @ 82972B3
	.string "Ayyyy…\n"
	.string "¿Combate? ¿Tú y yo?$"

Route109_Text_EdmondDefeated: @ 82972CE
	.string "Ay… Ooooooh…\n"
	.string "Ayyyyyyyyy…$"

Route109_Text_EdmondPostBattle: @ 82972ED
	.string "Normalmente soy más fuerte…\n"
	.string "Pero tengo un mareo… Ayyyy…\p"
	.string "Ya sé que soy Marinero, ya…$"

Route109_Text_RickyIntro: @ 829733B
	.string "Qué sed tengo… Creo que iré a por\n"
	.string "un Refresco a la Casa de la Playa.$"

Route109_Text_RickyDefeated: @ 8297379
	.string "Aaaaargh…$"

Route109_Text_RickyPostBattle: @ 8297380
	.string "Me muero de hambre… Hasta\n"
	.string "el flotador tiene buena pinta…$"

Route109_Text_RickyRegister: @ 82973C1
	.string "Cuando ya no tenga tanta sed,\n"
	.string "¿vendrás a luchar contra mí?$"

Route109_Text_RickyRematchIntro: @ 82973FF
	.string "Qué hambre tengo… ¡Pero todavía\n"
	.string "me quedan energías para un combate!$"

Route109_Text_RickyRematchDefeated: @ 8297437
	.string "He perdido…\n"
	.string "Seguro que es por el hambre que tengo…$"

Route109_Text_RickyRematchPostBattle: @ 8297458
	.string "Cuando haces un picnic en la playa,\n"
	.string "todo parece saber mejor…$"

Route109_Text_LolaIntro: @ 829749C
	.string "¿A que las sombrillas de playa parecen\n"
	.string "flores gigantes?$"

Route109_Text_LolaDefeated: @ 82974CF
	.string "¡Aaaah!$"

Route109_Text_LolaPostBattle: @ 82974D6
	.string "¡Si miras a la playa desde el cielo,\n"
	.string "parece un jardín de flores!$"

Route109_Text_LolaRegister: @ 8297520
	.string "¿Yo?\n"
	.string "¡Aquí estoy cada día!$"

Route109_Text_LolaRematchIntro: @ 8297538
	.string "¡No pienso volver a perder ante ti!\n"
	.string "¡Por eso tengo mi flotador!$"

Route109_Text_LolaRematchDefeated: @ 8297576
	.string "¡Aaaah!$"

Route109_Text_LolaRematchPostBattle: @ 829757D
	.string "Gracias al flotador, tanto yo como\n"
	.string "mis Pokémon estamos mejorando\l"
	.string "una barbaridad.$"

Route109_Text_AustinaIntro: @ 82975C0
	.string "No puedo nadar sin mi flotador,\n"
	.string "¡pero a los Pokémon no me ganan!$"

Route109_Text_AustinaDefeated: @ 8297601
	.string "¿Habré perdido por culpa\n"
	.string "del flotador?$"

Route109_Text_AustinaPostBattle: @ 829762A
	.string "Mi flotador está súper de moda.\n"
	.string "¡Yo es que tengo mucho estilo!$"

Route109_Text_GwenIntro: @ 8297667
	.string "¡Hola!\n"
	.string "¿Te apetece luchar conmigo?$"

Route109_Text_GwenDefeated: @ 8297691
	.string "¡Qué fuerte eres!$"

Route109_Text_GwenPostBattle: @ 82976A4
	.string "¿Cómo has hecho para ser tan fuerte?$"

Route109_Text_CarterIntro: @ 82976C5
	.string "¡Jua, jua, jua! ¡Mi menda lerenda\n"
	.string "te va a dar una buena lección!$"

Route109_Text_CarterDefeated: @ 82976FC
	.string "Ejem… Mi menda se ha dado\n"
	.string "un buen batacazo…$"

Route109_Text_CarterPostBattle: @ 8297715
	.string "Mi menda lerenda opina que llegarás\n"
	.string "lejos, muy lejos… ¡Algún día!$"

Route109_Text_PaulIntro: @ 8297754
	.string "Lino: Estábamos tan tranquilos…\p"
	.string "¡y tienes que venir tú a fastidiar!$"

Route109_Text_PaulDefeated: @ 82977B0
	.string "Lino: Vale, me rindo.$"

Route109_Text_PaulPostBattle: @ 82977C7
	.string "Lino: Oye, no le cuentes a nadie\n"
	.string "que estamos aquí.\l"
	.string "¡No necesitamos metomentodos!$"

Route109_Text_PaulNotEnoughPokemon: @ 829781D
	.string "Lino: Estamos loquitos el uno por\n"
	.string "el otro. Por eso combatimos juntos.$"

Route109_Text_MelIntro: @ 8297872
	.string "Meli: Estamos loquitos el uno por\n"
	.string "el otro. Todo Hoenn nos envidia.$"

Route109_Text_MelDefeated: @ 82978BD
	.string "Meli: Hemos perdido a pesar de todo.\n"
	.string "Qué mal…$"

Route109_Text_MelPostBattle: @ 82978F1
	.string "Meli: Lino, la próxima vez tendremos\n"
	.string "que esforzarnos más…$"

Route109_Text_MelNotEnoughPokemon: @ 829792E
	.string "Meli: Estamos loquitos el uno por\n"
	.string "el otro. Por eso combatimos juntos.$"

Route109_Text_ChandlerIntro: @ 829798A
	.string "¡Tachán! ¿Ves?\n"
	.string "¡Mi flotador es redondo!$"

Route109_Text_ChandlerDefeated: @ 82979AE
	.string "¡Ay, ay!\n"
	.string "¡Qué mala suerte!$"

Route109_Text_ChandlerPostBattle: @ 82979BF
	.string "Y eso que te había enseñado\n"
	.string "mi flotador y todo…$"

Route109_Text_HaileyIntro: @ 82979EC
	.string "No sé nadar, solo finjo que sé.$"

Route109_Text_HaileyDefeated: @ 8297A15
	.string "¡Si ya lo sabía yo!\n"
	.string "Como no sé nadar…$"

Route109_Text_HaileyPostBattle: @ 8297A40
	.string "Cuando aprenda a nadar, no habrá\n"
	.string "rival digno de mis Pokémon.$"

Route109_Text_ElijahIntro: @ 8297A82
	.string "Estos Pokémon están hechos a medida\n"
	.string "de los chicos molones como yo.$"

Route109_Text_ElijahDefeated: @ 8297AC7
	.string "Molo mazo hasta cuando pierdo, ¿eh?$"

Route109_Text_ElijahPostBattle: @ 8297AE5
	.string "¡Los chicos molones como yo\n"
	.string "tienen una novia en cada puerto!\p"
	.string "Creo que iré a ciudad Portual.$"

Route110_Text_JacobIntro: @ 8297B3F
	.string "¡Eh! ¡Cuidado! ¡Se ve que no sueles\n"
	.string "hacer carreras de Bicis!$"

Route110_Text_JacobDefeated: @ 8297B77
	.string "¡Aaaah!\n"
	.string "¡Me han fallado los frenos!$"

Route110_Text_JacobPostBattle: @ 8297B8F
	.string "Cuando las ruedas están desinfladas o\n"
	.string "hay problemas de frenos, puedes tener\l"
	.string "un accidente. ¡Revisa tu Bici!$"

Route110_Text_AnthonyIntro: @ 8297BE7
	.string "¡Eh, tú!\n"
	.string "¿Puedes alcanzarme?$"

Route110_Text_AnthonyDefeated: @ 8297C0F
	.string "¡Me has dejado atrás del todo!$"

Route110_Text_AnthonyPostBattle: @ 8297C1F
	.string "No basta solo la velocidad para ganar\n"
	.string "en los combates Pokémon, está claro…$"

Route110_Text_BenjaminIntro: @ 8297C63
	.string "¡No tengas miedo si tu Bici\n"
	.string "corre mucho!$"

Route110_Text_BenjaminDefeated: @ 8297C8A
	.string "No sé por qué tengo miedo\n"
	.string "en los combates Pokémon…$"

Route110_Text_BenjaminPostBattle: @ 8297CB4
	.string "No hay por qué tener miedo de nada.\n"
	.string "Tómate las cosas con calma…$"

Route110_Text_BenjaminRegister: @ 8297CFE
	.string "No hace falta alterarse. Si quieres\n"
	.string "echar un combate tranquilo, llámame.$"

Route110_Text_BenjaminRematchIntro: @ 8297D4B
	.string "¿No vas muy rápido?\n"
	.string "Para un rato y lucha conmigo.$"

Route110_Text_BenjaminRematchDefeated: @ 8297D8E
	.string "Estaba tranquilo, pero aun así\n"
	.string "he perdido.$"

Route110_Text_BenjaminRematchPostBattle: @ 8297DB0
	.string "No hay por qué tener miedo de nada.\n"
	.string "Tómate las cosas con calma…$"

Route110_Text_AbigailIntro: @ 8297DFA
	.string "El triatlón es una prueba muy dura.\p"
	.string "Tienes que competir en natación,\n"
	.string "ciclismo y carrera.$"

Route110_Text_AbigailDefeated: @ 8297E69
	.string "¡Los combates Pokémon tampoco\n"
	.string "son precisamente fáciles!$"

Route110_Text_AbigailPostBattle: @ 8297E88
	.string "Estoy agotada, necesito descansar.\n"
	.string "Es importante no sobreentrenar.$"

Route110_Text_AbigailRegister: @ 8297ECD
	.string "¡Sabes cuánto te aprecio!\n"
	.string "Te espero en el camino de Bicis.$"

Route110_Text_AbigailRematchIntro: @ 8297F09
	.string "¿A que mola luchar y montar\n"
	.string "en Bici a la vez?$"

Route110_Text_AbigailRematchDefeated: @ 8297F37
	.string "Uf…\n"
	.string "¿Cómo puedes ser tan fuerte?$"

Route110_Text_AbigailRematchPostBattle: @ 8297F58
	.string "¿Quieres lograr un nuevo récord?\p"
	.string "Pues perdona por haberte entretenido.$"

Route110_Text_JasmineIntro: @ 8297F93
	.string "¡He estado montando en Bici tanto,\n"
	.string "tanto, que tengo los gemelos duros\l"
	.string "como una piedra!$"

Route110_Text_JasmineDefeated: @ 8297FD0
	.string "Creo que me ha dado un calambre…$"

Route110_Text_JasminePostBattle: @ 8297FF1
	.string "Así que tienes medallas de gimnasio…\n"
	.string "¡Ahora lo entiendo todo!$"

Route110_Text_EdwardIntro: @ 829802B
	.string "Sé lo que piensas hacer…\n"
	.string "¡No puedo perder!$"

Route110_Text_EdwardDefeated: @ 8298064
	.string "No he sabido predecir mi\n"
	.string "propia derrota…$"

Route110_Text_EdwardPostBattle: @ 829808A
	.string "Puedo ver tu futuro…\p"
	.string "Veo, veo… Mmm…\n"
	.string "Una luz muy brillante…$"

Route110_Text_JaclynIntro: @ 82980B9
	.string "¡Ja, ja, ja, ja!\n"
	.string "Te voy a dejar de piedra…$"

Route110_Text_JaclynDefeated: @ 82980E5
	.string "Ahora yo estoy patidifusa…$"

Route110_Text_JaclynPostBattle: @ 82980F8
	.string "¡Esta vez has ganado de milagro!\n"
	.string "¡Ha sido pura chorra!\l"
	.string "¡No siempre será así, ya verás!$"

Route110_Text_EdwinIntro: @ 829815E
	.string "¿Puedo ver tus Pokémon?\n"
	.string "Sólo una miradita…$"

Route110_Text_EdwinDefeated: @ 829818F
	.string "Yo solo quería completar mi colección…$"

Route110_Text_EdwinPostBattle: @ 82981B3
	.string "Cuando veo un Pokémon que no conozco,\n"
	.string "mi pasión de coleccionista sale a flote.$"

Route110_Text_EdwinRegister: @ 8298201
	.string "A mi también me gusta llenar\n"
	.string "la agenda del móvil.$"

Route110_Text_EdwinRematchIntro: @ 8298232
	.string "Hola, ¿has atrapado nuevos Pokémon?\p"
	.string "¿Puedo verlos?\n"
	.string "Sólo una miradita…$"

Route110_Text_EdwinRematchDefeated: @ 8298288
	.string "Qué Pokémon tan molones tienes…\n"
	.string "Qué envidia…$"

Route110_Text_EdwinRematchPostBattle: @ 82982A2
	.string "Oh, cómo quisiera que todos los Pokémon\n"
	.string "raros que existen fueran míos…$"

Route110_Text_DaleIntro: @ 82982CC
	.string "¡Pero bueno, tú!\n"
	.string "¡Vete a darle la lata a otro!$"

Route110_Text_DaleDefeated: @ 82982F5
	.string "¡Aaaaaargh!\n"
	.string "¡He perdido!$"

Route110_Text_DalePostBattle: @ 8298303
	.string "La pesca requiere concentración.\n"
	.string "Tienes que estar pendiente del corcho\l"
	.string "para ver si ha picado algo.$"

Route110_Text_IsabelIntro: @ 8298349
	.string "¡Ja, ja, ja! ¡Iría al fin del mundo\n"
	.string "solo para fardar de Pokémon!$"

Route110_Text_IsabelDefeated: @ 8298389
	.string "Ésta no era precisamente la idea\n"
	.string "que tenía yo…$"

Route110_Text_IsabelPostBattle: @ 82983A2
	.string "Más que luchar, debería presumir\n"
	.string "de Pokémon en el club de fans.$"

Route110_Text_IsabelRegister: @ 82983EE
	.string "Puedo hacer mucho más para\n"
	.string "presumir de Pokémon.\p"
	.string "¡Quiero que seas mi público\n"
	.string "siempre que puedas!$"

Route110_Text_IsabelRematchIntro: @ 8298466
	.string "¡Ja, ja, ja! ¡Yo es que no me canso de\n"
	.string "fardar de Pokémon lo que haga falta!$"

Route110_Text_IsabelRematchDefeated: @ 82984AF
	.string "Ésta no era precisamente la idea\n"
	.string "que tenía yo…$"

Route110_Text_IsabelRematchPostBattle: @ 82984C8
	.string "No creo que fardar de Pokémon\n"
	.string "me canse jamás.\p"
	.string "¡Pero también me gusta luchar!$"

Route110_Text_TimmyIntro: @ 8298525
	.string "He encontrado algunos Pokémon\n"
	.string "carismáticos entre la hierba.$"

Route110_Text_TimmyDefeated: @ 8298559
	.string "Que tengan carisma no\n"
	.string "basta para ganar…$"

Route110_Text_TimmyPostBattle: @ 8298579
	.string "Lo que pasa es que cuesta controlar a\n"
	.string "los Pokémon que acabas de atrapar…$"

Route110_Text_AlyssaIntro: @ 82985AB
	.string "Me he caído del camino de Bicis…\p"
	.string "¡Aunque no tengas la culpa,\n"
	.string "vas a pagar por ello!$"

Route110_Text_AlyssaDefeated: @ 82985F9
	.string "¡Huy!\n"
	.string "¡He perdido!$"

Route110_Text_AlyssaPostBattle: @ 8298612
	.string "Me he caído… He perdido…\n"
	.string "¡Qué humillación más grande!$"

Route110_Text_JosephIntro: @ 8298642
	.string "¡Es hora de mover las caderas!\n"
	.string "¡Baila al ritmo de mis Pokémon!$"

Route110_Text_JosephDefeated: @ 8298686
	.string "Tu ritmo es imparable…$"

Route110_Text_JosephPostBattle: @ 82986A9
	.string "¡No voy a venirme abajo por haber\n"
	.string "perdido, porque de todo se aprende!$"

Route110_Text_KalebIntro: @ 82986ED
	.string "No hay imagen más encantadora que ver\n"
	.string "a unos Pokémon ayudándose entre sí…$"

Route110_Text_KalebDefeated: @ 8298735
	.string "¿Pero tú no tienes corazón o qué?$"

Route110_Text_KalebPostBattle: @ 8298755
	.string "Ea, ea, tranquilos, chiquitines.\n"
	.string "Habéis dado lo mejor de vosotros.$"

Route111_Text_DrewIntro: @ 829878E
	.string "Las Gafas Aislantes te quedan bien,\n"
	.string "pero creo que me van mejor a mí.\p"
	.string "¡Decidamos con un combate quién\n"
	.string "se las va a quedar!$"

Route111_Text_DrewDefeat: @ 829880A
	.string "No he podido ver lo que me venía de\n"
	.string "lado por culpa de las Gafas Aislantes…$"

Route111_Text_DrewPostBattle: @ 8298853
	.string "Las Gafas Aislantes te permiten\n"
	.string "atravesar las tormentas de arena.\l"
	.string "¡Son superprácticas!$"

Route111_Text_HeidiIntro: @ 82988A3
	.string "Voy a hacer un picnic en el desierto.\p"
	.string "Esto está lleno de entrenadores, así\n"
	.string "que también puedo luchar si me apetece.$"

Route111_Text_HeidiDefeat: @ 8298908
	.string "¡Oooooh! ¿Por qué eres así…?$"

Route111_Text_HeidiPostBattle: @ 829891B
	.string "Cuando luches en medio de una tormenta\n"
	.string "de arena, vigila los PS de tu Pokémon.\p"
	.string "¡Si no, puede que hasta se debilite!$"

Route111_Text_BeauIntro: @ 829898E
	.string "Cuando llevo estas Gafas Aislantes,\n"
	.string "me siento como un superhéroe.\l"
	.string "¡Nadie puede conmigo!$"

Route111_Text_BeauDefeat: @ 82989E6
	.string "Se me va toda la fuerza por la boca…$"

Route111_Text_BeauPostBattle: @ 8298A03
	.string "Algún día seré un héroe de verdad.\n"
	.string "Voy a trabajar duro para que mis\l"
	.string "Pokémon sean los más fuertes.$"

Route111_Text_BeckyIntro: @ 8298A65
	.string "Me han dicho que se pueden encontrar\n"
	.string "fósiles en el desierto, pero ¿dónde?$"

Route111_Text_BeckyDefeat: @ 8298AAF
	.string "Me has pillado desprevenida…$"

Route111_Text_BeckyPostBattle: @ 8298AC0
	.string "Si hay fósiles en el desierto, entonces\n"
	.string "antes debía de haber un mar aquí…$"

Route111_Text_DustyIntro: @ 8298B08
	.string "He buscado restos arqueológicos\n"
	.string "durante más de treinta años. Uf…\l"
	.string "Un combatito me va a despejar un poco…$"

Route111_Text_DustyDefeat: @ 8298B53
	.string "Tanto buscar restos arqueológicos…\n"
	.string "Más bien debería haber buscado\l"
	.string "Pokémon fuertes…$"

Route111_Text_DustyPostBattle: @ 8298B9A
	.string "He buscado restos arqueológicos\n"
	.string "durante más de treinta años…\p"
	.string "¿O han sido cuarenta años?\n"
	.string "He perdido la cuenta…$"

Route111_Text_DustyRegister: @ 8298C00
	.string "No he estado buscando ningún\n"
	.string "Pokémon de gran dureza.\p"
	.string "Pero, por algún motivo,\n"
	.string "los Pokénav me flipan.$"

Route111_Text_DustyRematchIntro: @ 8298C5F
	.string "He buscado restos arqueológicos\n"
	.string "durante más de treinta años…\p"
	.string "¿O han sido cuarenta años?\n"
	.string "Da igual, ¿buscas pelea?$"

Route111_Text_DustyRematchDefeat: @ 8298CD2
	.string "Hasta ahora no he encontrado ni restos\n"
	.string "arqueológicos, ni Pokémon fuertes,\l"
	.string "ni nada de nada…$"

Route111_Text_DustyPostRematch: @ 8298D0C
	.string "He buscado restos arqueológicos\n"
	.string "durante más de treinta años…\p"
	.string "¿O han sido cuarenta años?\p"
	.string "Puede que hayan sido incluso cincuenta\n"
	.string "años… Ay, me estoy agobiando…$"

Route111_Text_TravisIntro: @ 8298DA9
	.string "¡Estoy en racha!\n"
	.string "¡Y mi Pokémon también!$"

Route111_Text_TravisDefeat: @ 8298DD8
	.string "Mi Pokémon ya no va a querer salir\n"
	.string "ni a la vuelta de la esquina…$"

Route111_Text_TravisPostBattle: @ 8298DF1
	.string "Cuando veo a un entrenador que está\n"
	.string "en racha, tengo que desafiarle…$"

Route111_Text_IreneIntro: @ 8298E2F
	.string "No sé quién eres ni adónde vas, pero\n"
	.string "sé que vamos a enfrentarnos…$"

Route111_Text_IreneDefeat: @ 8298E6E
	.string "Tu técnica es tan buena que\n"
	.string "estoy muerta de envidia…$"

Route111_Text_IrenePostBattle: @ 8298E8C
	.string "Pensaba yo que debería ir al Monte\n"
	.string "Cenizo a disfrutar de las vistas,\l"
	.string "pero aquí tampoco se está mal…$"

Route111_Text_DaisukeIntro: @ 8298EE6
	.string "¡Hay que entrenar, así que desafío\n"
	.string "a todo lo que se mueve!$"

Route111_Text_DaisukeDefeat: @ 8298F14
	.string "¡Vale, vale, me rindo!$"

Route111_Text_DaisukePostBattle: @ 8298F26
	.string "Lo único que puedo hacer es seguir\n"
	.string "entrenando hasta que sea capaz de\l"
	.string "derrotar a Entrenadores como tú.$"

Route111_Text_WiltonIntro: @ 8298F79
	.string "Muéstrame cuánto han mejorado\n"
	.string "tus Pokémon, anda.$"

Route111_Text_WiltonDefeat: @ 8298FA9
	.string "Pues sí, lo que es mejorar, han\n"
	.string "mejorado.$"

Route111_Text_WiltonPostBattle: @ 8298FD4
	.string "Los Pokémon y los entrenadores\n"
	.string "aprenden mucho en cada combate.\p"
	.string "Lo que importa no es ganar, sino\n"
	.string "intentarlo y seguir esforzándose.$"

Route111_Text_WiltonRegister: @ 829903D
	.string "Se puede aprender mucho a partir\n"
	.string "de tu estilo de combate.\p"
	.string "Quisiera tomarme la revancha,\n"
	.string "si te atrae la idea.$"

Route111_Text_WiltonRematchIntro: @ 829909B
	.string "Estamos entrenándonos para pasar\n"
	.string "al siguiente nivel.\l"
	.string "¡Ven a entrenarte con nosotros!$"

Route111_Text_WiltonRematchDefeat: @ 82990EE
	.string "¡No se te da nada mal!$"

Route111_Text_WiltonPostRematch: @ 8299102
	.string "Visto tu potencial, deberías ir\n"
	.string "a la Liga Pokémon.$"

Route111_Text_BrookeIntro: @ 8299143
	.string "Eh, tus Pokémon tienen pinta de\n"
	.string "tomarse esto muy en serio.\l"
	.string "Enfrentémonos a ver qué pasa…$"

Route111_Text_BrookeDefeat: @ 8299193
	.string "No es que tengan pinta de tomárselo\n"
	.string "muy en serio, ¡es que lo hacen!$"

Route111_Text_BrookePostBattle: @ 82991C2
	.string "Yo pensaba que me estaba tomando en\n"
	.string "serio entrenar mis Pokémon, pero está\l"
	.string "visto que me queda mucho que aprender.$"

Route111_Text_BrookeRegister: @ 829921D
	.string "¡Me gustaría entablar amistad con más\n"
	.string "Entrenadores fuertes como tú!$"

Route111_Text_BrookeRematchIntro: @ 829925D
	.string "Puedes fortalecer o debilitar tus\n"
	.string "Pokémon según los movimientos\l"
	.string "que les enseñes.\p"
	.string "Veamos qué movimientos han aprendido\n"
	.string "tus Pokémon…$"

Route111_Text_BrookeRematchDefeat: @ 82992D6
	.string "¡Les has enseñado movimientos\n"
	.string "buenos de verdad!$"

Route111_Text_BrookePostRematch: @ 82992F5
	.string "Quizás debería haber impedido que mis\n"
	.string "Pokémon evolucionaran hasta que\l"
	.string "hubieran aprendido mejores ataques…$"

Route111_Text_CeliaIntro: @ 829934B
	.string "¡No debería haber venido a un sitio\n"
	.string "así para hacer un picnic!$"

Route111_Text_CeliaDefeat: @ 8299384
	.string "¡Aaaah!\n"
	.string "¿Por qué habré venido aquí?$"

Route111_Text_CeliaPostBattle: @ 82993A7
	.string "Con una tormenta de arena como\n"
	.string "ésta, no se ve nada ni aunque\l"
	.string "lleves Gafas Aislantes…$"

Route111_Text_BryanIntro: @ 8299401
	.string "¿Eres o no eres fuerte?\n"
	.string "¡Ahora mismo lo vamos a ver!$"

Route111_Text_BryanDefeat: @ 8299431
	.string "¡Eres una fuerza de la naturaleza!\n"
	.string "¡Me has dejado anonadado!$"

Route111_Text_BryanPostBattle: @ 829945F
	.string "Las ardientes arenas de este desierto\n"
	.string "encierran innumerables secretos.$"

Route111_Text_BrandenIntro: @ 8299493
	.string "Si pierdes, te doy mi bocadillo.$"

Route111_Text_BrandenDefeat: @ 82994C5
	.string "¡Uf! Pensaba que un bocadillo como\n"
	.string "el mío sobornaría a cualquiera…$"

Route111_Text_BrandenPostBattle: @ 82994FB
	.string "A mi Sandshrew le encantan\n"
	.string "mis suculentos bocadillos.$"

Route111_Text_TyronIntro: @ 8299524
	.string "Éste es mi tipo preferido\n"
	.string "de Pokémon.$"

Route111_Text_TyronDefeat: @ 8299549
	.string "¡No te vayas todavía!\n"
	.string "¿Qué piensas de mi Pokémon?$"

Route111_Text_TyronPostBattle: @ 8299576
	.string "No pierdo ocasión de presumir de\n"
	.string "Pokémon en todos mis combates.\p"
	.string "¡Pero estoy convencido de que\n"
	.string "todo el mundo hace lo mismo!$"

Route111_Text_CelinaIntro: @ 82995F0
	.string "Qué hastío… Espero que des\n"
	.string "un poco de emoción a mi vida.$"

Route111_Text_CelinaDefeat: @ 8299625
	.string "Pues vaya… Me parece que ha sido\n"
	.string "demasiada emoción de una vez.$"

Route111_Text_CelinaPostBattle: @ 829964B
	.string "Tengo el pulso a cien por hora.\n"
	.string "Tienes un talento excepcional.$"

Route111_Text_HaydenIntro: @ 8299682
	.string "¡Quien lucha con el estómago vacío,\n"
	.string "como yo, pelea de forma temible!$"

Route111_Text_HaydenDefeat: @ 82996BE
	.string "Ah, desfallezco…$"

Route111_Text_HaydenPostBattle: @ 82996C5
	.string "¡Me rugen las tripas!\n"
	.string "Será mejor engullir unas bayas…$"

Route111_Text_BiancaIntro: @ 82996FE
	.string "¿Vienes de Malvalona?\n"
	.string "¡Pues debes de rebosar energía!$"

Route111_Text_BiancaDefeat: @ 829973D
	.string "¡Ay, ay, ay!\n"
	.string "¡Esto es demasiado para mí!$"

Route111_Text_BiancaPostBattle: @ 829975D
	.string "Ruta por aquí, ruta por allá…\n"
	.string "Te ha picado el gusanillo viajero, ¿eh?$"

Route112_Text_BriceIntro: @ 829978E
	.string "¡Ja, ja, ja, ja!\n"
	.string "¿Qué tal si luchamos un poco?\l"
	.string "¡Tú y yo!\l"
	.string "¡Ja, ja, ja, ja!$"

Route112_Text_BriceDefeat: @ 82997CA
	.string "¡He perdido!\n"
	.string "¡Ja, ja, ja, ja!$"

Route112_Text_BricePostBattle: @ 82997DC
	.string "¡Ja, ja, ja, ja!\n"
	.string "¡Algo me está haciendo cosquillas en la\l"
	.string "nariz! Ji, ji, ji, ji… ¡A-a-achís!$"

Route112_Text_TrentIntro: @ 8299815
	.string "Tengo las piernas fuertes como un roble\n"
	.string "de tanto subir y bajar montañas.\p"
	.string "¡No van a flaquear tan fácilmente!$"

Route112_Text_TrentDefeat: @ 829987C
	.string "¡Ay! ¡Me ha dado un calambre!$"

Route112_Text_TrentPostBattle: @ 8299896
	.string "Prueba a caminar, pero en serio,\n"
	.string "por estos senderos de montaña\l"
	.string "con una mochila bien cargada.\p"
	.string "¡Por fuerza te pones en forma!$"

Route112_Text_TrentRegister: @ 829993C
	.string "Ah, tengo calambres en las piernas.\n"
	.string "¿Me puedes pasar unas vendas\l"
	.string "que hay en mi mochila?\p"
	.string "¡No, eso es mi Pokénav!\n"
	.string "Bueno, vale, te voy a registrar.$"

Route112_Text_TrentRematchIntro: @ 82999BD
	.string "Me mantengo en forma gracias al\n"
	.string "senderismo. ¡Estoy hecho un toro!$"

Route112_Text_TrentRematchDefeat: @ 82999F7
	.string "¿Estaré hecho un ternero?$"

Route112_Text_TrentRematchPostBattle: @ 8299A0F
	.string "Me han dicho que hay entrenadores muy\n"
	.string "fuertes en la cima del Monte Cenizo.\p"
	.string "¡Voy a ir allí a desafiarlos a todos!$"

Route112_Text_LarryIntro: @ 8299A89
	.string "Soy fuerte psicológicamente.\n"
	.string "Perder no me supone ningún trauma.$"

Route112_Text_LarryDefeat: @ 8299AAC
	.string "¡Buaaaaaaaaaaaaa!$"

Route112_Text_LarryPostBattle: @ 8299AB4
	.string "¡No estoy llorando! ¡Es que me ha\n"
	.string "entrado algo en el ojo!$"

Route112_Text_CarolIntro: @ 8299AE4
	.string "Cuando sales de picnic, tienes que\n"
	.string "cantar a pleno pulmón.\l"
	.string "¡Venga, canta conmigo!$"

Route112_Text_CarolDefeat: @ 8299B36
	.string "¡Guau, qué fuerte eres!$"

Route112_Text_CarolPostBattle: @ 8299B4C
	.string "No importa lo bueno que seas cantando\n"
	.string "o entrenando Pokémon.\p"
	.string "¡La cosa está en divertirse!$"

Route112_Text_BryantIntro: @ 8299BAE
	.string "¡He atrapado unos Pokémon alucinantes\n"
	.string "en la Senda Ígnea! ¡Mira, mira!$"

Route112_Text_BryantDefeat: @ 8299BDF
	.string "¡Menudo palizón me has dado!$"

Route112_Text_BryantPostBattle: @ 8299BFB
	.string "Me gusta tu forma de pelear.\n"
	.string "Tienes un estilo propio.$"

Route112_Text_ShaylaIntro: @ 8299C34
	.string "¡Oh, qué placer cruzarme contigo!\n"
	.string "¡Estoy deseando luchar con una\l"
	.string "persona tan especial como tú!$"

Route112_Text_ShaylaDefeat: @ 8299C8F
	.string "¡Oh, qué fuerte eres!\n"
	.string "¡No quepo en mí de asombro!$"

Route112_Text_ShaylaPostBattle: @ 8299CC6
	.string "¿Tienes un momento?\n"
	.string "Estaba pensando que quizás podríamos\l"
	.string "volver a luchar ya mismo…\l"
	.string "Pero si tienes cosas que hacer…$"

Route113_Text_JaylenIntro: @ 8299D3C
	.string "¿Sabes por qué es tan chachi\n"
	.string "estar por aquí?$"

Route113_Text_JaylenDefeat: @ 8299D68
	.string "¡Aaaaah!\n"
	.string "¡Esto no es nada chachi!$"

Route113_Text_JaylenPostBattle: @ 8299D7D
	.string "La ceniza volcánica no absorbe los\n"
	.string "rayos del sol, así que no se calienta.\p"
	.string "Por mí, chachi piruli…\n"
	.string "¡No soporto el calor!$"

Route113_Text_DillonIntro: @ 8299DE3
	.string "Cuando un volcán entra en erupción, te\n"
	.string "das cuenta de que la tierra está viva.$"

Route113_Text_DillonDefeat: @ 8299E1C
	.string "¡Tienes la potencia de un volcán!$"

Route113_Text_DillonPostBattle: @ 8299E38
	.string "Me has extinguido…\p"
	.string "¿Lo pillas? Tú eres un volcán activo\n"
	.string "y yo uno extinguido, je, je, je.\p"
	.string "Vale, sí, no tiene gracia…$"

Route113_Text_MadelineIntro: @ 8299EA6
	.string "Uso este parasol para proteger a\n"
	.string "mi querido Numel de esta horrible\l"
	.string "y pegajosa ceniza volcánica.$"

Route113_Text_MadelineDefeat: @ 8299EF9
	.string "Uf, uf…\n"
	.string "Luchar con parasol es agotador.$"

Route113_Text_MadelinePostBattle: @ 8299F15
	.string "Oye, se te da muy bien esto.\n"
	.string "Estoy impresionada.$"

Route113_Text_MadelineRegister: @ 8299F49
	.string "Mi parasol y yo te esperamos.\n"
	.string "Déjame registrarte en mi Pokénav.$"

Route113_Text_MadelineRematchIntro: @ 8299F8A
	.string "Hola, hace tiempo que no te veía.\n"
	.string "¿Te apetece que luchemos?$"

Route113_Text_MadelineRematchDefeat: @ 8299FC9
	.string "¡Qué bien lo has hecho!$"

Route113_Text_MadelinePostRematch: @ 8299FD8
	.string "¡Se te sigue dando estupendamente!\n"
	.string "Estoy impresionada.$"

Route113_Text_LaoIntro: @ 829A015
	.string "¡Surjo de entre las cenizas como una\n"
	.string "sombra! ¡Kiaaaaaaaaa!\l"
	.string "¿Aceptas mi desafío?$"

Route113_Text_LaoDefeat: @ 829A04C
	.string "Acepto mi derrota…$"

Route113_Text_LaoPostBattle: @ 829A067
	.string "Tengo que perfeccionar mi técnica\n"
	.string "de camuflaje.\p"
	.string "¡Me piro, vampiro!$"

Route113_Text_LaoRegister: @ 829A0A2
	.string "¡Yijaaaa! ¡Maravíllate con la antigua\n"
	.string "técnica ninja de registro en Pokénav!$"

Route113_Text_LaoRematchIntro: @ 829A0E8
	.string "¡Surjo de entre las cenizas como una\n"
	.string "sombra! ¡Kiaaaaaaaaa!\l"
	.string "¿Aceptas mi desafío?$"

Route113_Text_LaoRematchDefeat: @ 829A11F
	.string "Acepto mi derrota…$"

Route113_Text_LaoPostRematch: @ 829A13A
	.string "Mi técnica de camuflaje es impecable,\n"
	.string "pero mis técnicas de combate son un\l"
	.string "desastre…\p"
	.string "¡Me piro, vampiro!$"

Route113_Text_LungIntro: @ 829A192
	.string "¡Has sabido encontrarme!\n"
	.string "¡Pero ahora debes derrotarme!$"

Route113_Text_LungDefeat: @ 829A1C6
	.string "Voy a usar el poder del ninjutsu…\n"
	.string "¡“Remolino de Sombras Volcánico”!\p"
	.string "¿Que “yatá”?\n"
	.string "¿Cómo que “yatá”?$"

Route113_Text_LungPostBattle: @ 829A219
	.string "¿Sabes lo más chungo de camuflarse?\n"
	.string "Que, si nadie te encuentra, te aburres.$"

Route113_Text_ToriIntro: @ 829A261
	.string "Tea: Nosotras dos recogemos ceniza\n"
	.string "y además entrenamos Pokémon.$"

Route113_Text_ToriDefeat: @ 829A29D
	.string "Tea: Hemos perdido… Qué rollo…\n"
	.string "Me voy a buscar más ceniza…$"

Route113_Text_ToriPostBattle: @ 829A2DE
	.string "Tea: ¿Cuánta ceniza tenemos ya?\n"
	.string "¿Es suficiente para la Flauta Blanca?$"

Route113_Text_ToriNotEnoughMons: @ 829A31F
	.string "Tea: Queremos un Combate Doble.\n"
	.string "Si no, estamos en desventaja.$"

Route113_Text_TiaIntro: @ 829A35C
	.string "Bea: Nosotras dos recogemos ceniza\n"
	.string "y además entrenamos Pokémon.$"

Route113_Text_TiaDefeat: @ 829A397
	.string "Bea: Hemos perdido… Qué rollo…\n"
	.string "Me voy a buscar más ceniza…$"

Route113_Text_TiaPostBattle: @ 829A3DA
	.string "Bea: ¡Tenemos un montón de ceniza!\n"
	.string "¿Es bastante para la Flauta Blanca?$"

Route113_Text_TiaNotEnoughMons: @ 829A419
	.string "Bea: Queremos un Combate Doble.\n"
	.string "Si no, estamos en desventaja.$"

Route113_Text_CobyIntro: @ 829A453
	.string "¡Je, con estas alas te voy a\n"
	.string "enviar volando por los aires!$"

Route113_Text_CobyDefeat: @ 829A480
	.string "¿Qué? ¿Cómo? ¿Cuándo? ¿Por qué?$"

Route113_Text_CobyPostBattle: @ 829A489
	.string "Que me derroten con tanta facilidad\n"
	.string "me deja sin palabras…$"

Route113_Text_SophieIntro: @ 829A4BF
	.string "Este calor me da sueño. Lucha\n"
	.string "conmigo, a ver si me despierto.$"

Route113_Text_SophieDefeat: @ 829A508
	.string "Seguro que estoy soñando.\n"
	.string "¡No puedo haber perdido!$"

Route113_Text_SophiePostBattle: @ 829A529
	.string "Perder me quema mucho…\n"
	.string "Y lo único que me relaja es echar\l"
	.string "una siestecita, así que zzzzz…$"

Route113_Text_LawrenceIntro: @ 829A566
	.string "¿Es posible que estés recogiendo\n"
	.string "cenizas volcánicas?$"

Route113_Text_LawrenceDefeat: @ 829A5A0
	.string "Je, je, je, qué cenizo soy…\n"
	.string "Has ganado con todas las de la ley.$"

Route113_Text_LawrencePostBattle: @ 829A5BE
	.string "Me voy a esconder entre las cenizas\n"
	.string "y, si te he visto, no me acuerdo.$"

Route113_Text_WyattIntro: @ 829A5E4
	.string "¿Qui-quieres luchar conmigo? ¿Aunque\n"
	.string "acabe de capturar mis Pokémon?$"

Route113_Text_WyattDefeat: @ 829A628
	.string "¿Te alegra ha-haber ganado?\n"
	.string "¿Aunque no sea más que un novato?$"

Route113_Text_WyattPostBattle: @ 829A65D
	.string "Oh, ¿te dignas dirigir la palabra\n"
	.string "al perdedor?\p"
	.string "¿Tú siempre vas de guay?\n"
	.string "¡Bah!$"

Route114_Text_LennyIntro: @ 829A6B1
	.string "¡Ue-i-a-oooo!\p"
	.string "Como aquí no hay eco, me pongo a cantar\n"
	.string "al estilo tirolés para divertirme.$"

Route114_Text_LennyDefeat: @ 829A707
	.string "¡Ue-ia-ooo!$"

Route114_Text_LennyPostBattle: @ 829A715
	.string "¡Cuando era un pitufín, creía que el\n"
	.string "eco era alguien escondido que repetía\l"
	.string "todo lo que yo decía!$"

Route114_Text_LucasIntro: @ 829A777
	.string "Si no te preparas bien antes, ni se\n"
	.string "te ocurra hacer montañismo.$"

Route114_Text_LucasDefeat: @ 829A7B5
	.string "Las montañas son traicioneras…$"

Route114_Text_LucasPostBattle: @ 829A7D4
	.string "En invierno las montañas encierran\n"
	.string "trampas mortales: tormentas de\l"
	.string "nieve, avalanchas…$"

Route114_Text_ShaneIntro: @ 829A818
	.string "¡Acampar es la caña!\n"
	.string "¡Puedes pescar, asar patatas y\l"
	.string "contar historias de terror!\p"
	.string "¡Pero lo mejor son los combates\n"
	.string "Pokémon!$"

Route114_Text_ShaneDefeat: @ 829A88F
	.string "¡Eres mucho más fuerte que yo!$"

Route114_Text_ShanePostBattle: @ 829A89F
	.string "Me encanta ir de acampada con\n"
	.string "mis Pokémon.$"

Route114_Text_NancyIntro: @ 829A8D9
	.string "Me apetece un combate para bajar\n"
	.string "la comida. ¿Qué me dices?$"

Route114_Text_NancyDefeat: @ 829A90E
	.string "¡Oh, no!$"

Route114_Text_NancyPostBattle: @ 829A916
	.string "Creo que he comido demasiado…\n"
	.string "Me está entrando sueño…$"

Route114_Text_SteveIntro: @ 829A943
	.string "¡Jua, jua, jua, jua!\n"
	.string "¿Quieres luchar contra mi Pokémon?$"

Route114_Text_SteveDefeat: @ 829A973
	.string "Mi pobre Pokémon…$"

Route114_Text_StevePostBattle: @ 829A981
	.string "Yo sé muy bien qué Pokémon quiero…\p"
	.string "¡Uno con la piel dura y llena de bultos,\n"
	.string "cuernos enormes y colmillos afilados!$"

Route114_Text_SteveRegister: @ 829A9F7
	.string "¡Acuérdate de mí! ¡Nuestro próximo\n"
	.string "encuentro será inolvidable!$"

Route114_Text_SteveRematchIntro: @ 829AA3E
	.string "¡Jua, jua, jua, jua!\n"
	.string "¡Vamos, lucha contra mi Pokémon!$"

Route114_Text_SteveRematchDefeat: @ 829AA67
	.string "Qué afortunado soy de poder ver\n"
	.string "tus magníficos Pokémon…$"

Route114_Text_StevePostRematch: @ 829AA94
	.string "¡Jua, jua, jua, jua!\p"
	.string "¡Cuando veo un combate Pokémon, me\n"
	.string "emociono tanto que me pongo a temblar!$"

Route114_Text_BernieIntro: @ 829AADB
	.string "Si vas a encender una fogata, ten\n"
	.string "agua cerca por si acaso…$"

Route114_Text_BernieDefeat: @ 829AB1A
	.string "¿Ves? ¡Casi me quemo la mano!$"

Route114_Text_BerniePostBattle: @ 829AB36
	.string "Tienes que tener muchísimo cuidado\n"
	.string "cuando haces fogatas en el bosque…\p"
	.string "¡El fuego es peligroso!$"

Route114_Text_BernieRegister: @ 829ABA6
	.string "¡Ardo de ganas de enfrentarme a ti!\n"
	.string "¡Vamos a registrarnos!$"

Route114_Text_BernieRematchIntro: @ 829ABDC
	.string "¿Te aseguras siempre de tener agua\n"
	.string "a mano para apagar las fogatas?$"

Route114_Text_BernieRematchDefeat: @ 829AC10
	.string "Me siento como si me hubieran echado\n"
	.string "un cubo de agua fría encima…$"

Route114_Text_BerniePostRematch: @ 829AC43
	.string "Tienes que tener muchísimo cuidado\n"
	.string "cuando haces fogatas en el bosque…\p"
	.string "¡El fuego es peligroso!$"

Route114_Text_ClaudeIntro: @ 829ACB3
	.string "En una competición de pesca, no\n"
	.string "tendrías ni una oportunidad…\l"
	.string "A ver, ¡enséñame tus Pokémon!$"

Route114_Text_ClaudeDefeat: @ 829AD0A
	.string "En una competición de pesca, te\n"
	.string "hubiera dado mil vueltas…$"

Route114_Text_ClaudePostBattle: @ 829AD2E
	.string "Creo que voy a probar suerte en la\n"
	.string "Cascada Meteoro, a ver si pican.\p"
	.string "Estoy convencido de que hay peces\n"
	.string "muy gordos por allí…$"

Route114_Text_NolanIntro: @ 829ADA1
	.string "Me gusta pescar, ¡pero también me\n"
	.string "gusta luchar!\p"
	.string "Si alguien me reta, no puedo decir\n"
	.string "que no, aunque esté pescando.$"

Route114_Text_NolanDefeat: @ 829AE05
	.string "Me gusta luchar, pero eso no quiere\n"
	.string "decir que se me dé bien en absoluto…$"

Route114_Text_NolanPostBattle: @ 829AE3D
	.string "¡La próxima vez verás!\p"
	.string "Es lo que siempre digo, para animarme\n"
	.string "a seguir con los combates Pokémon.$"

Route114_Text_TyraIntro: @ 829AE96
	.string "Tula: Sí, sí, encantada.\n"
	.string "Hoy estoy de buen humor.\l"
	.string "Te voy a enseñar algo sobre Pokémon.$"

Route114_Text_TyraDefeat: @ 829AEE7
	.string "Tula: ¡Qué gran estilo de lucha!\n"
	.string "¡No te queda gran cosa que aprender!$"

Route114_Text_TyraPostBattle: @ 829AF0B
	.string "Tula: Pero mi pupila, Ilda, sí tiene\n"
	.string "que aprender bastante todavía…$"

Route114_Text_TyraNotEnoughMons: @ 829AF3D
	.string "Tula: Ji, ji, ji…\n"
	.string "¡Si quieres luchar contra nosotras,\l"
	.string "necesitas más de un Pokémon!$"

Route114_Text_IvyIntro: @ 829AF89
	.string "Ilda: ¿Quién te ha enseñado lo que\n"
	.string "sabes sobre los Pokémon?$"

Route114_Text_IvyDefeat: @ 829AFAC
	.string "Ilda: ¡Vaya estilazo combatiendo!$"

Route114_Text_IvyPostBattle: @ 829AFCF
	.string "Ilda: Empecé a entrenar Pokémon\n"
	.string "porque Tula, mi tutora, quiere que\l"
	.string "sea una figura algún día.$"

Route114_Text_IvyNotEnoughMons: @ 829B01B
	.string "Ilda: ¿Sólo tienes un Pokémon?\n"
	.string "Debe de sentirse solísimo…$"

Route114_Text_KaiIntro: @ 829B05D
	.string "¡He pescado uno enooorme!\n"
	.string "¡Grande como él solo, ya verás!$"

Route114_Text_KaiDefeat: @ 829B089
	.string "¿Qué ha pasado aquí?\n"
	.string "¿Se habrá encogido mi Pokémon?$"

Route114_Text_KaiPostBattle: @ 829B0B5
	.string "¡Me importa un comino!\n"
	.string "¡Voy a pescar uno aún mayor!$"

Route114_Text_CharlotteIntro: @ 829B0DB
	.string "¡Quiero que sepas una cosa!\n"
	.string "¡No soy solo una cara bonita!$"

Route114_Text_CharlotteDefeat: @ 829B0FB
	.string "¡Esta pelea ha sido de todo\n"
	.string "menos bonita!$"

Route114_Text_CharlottePostBattle: @ 829B11A
	.string "Yo no quiero un Pokémon que\n"
	.string "sea únicamente una monada.\p"
	.string "Me gustan los Pokémon bonitos que,\n"
	.string "además, tienen alguna peculiaridad.$"

Route114_Text_AngelinaIntro: @ 829B16F
	.string "¿Has conseguido que tus Pokémon\n"
	.string "evolucionen mucho?$"

Route114_Text_AngelinaDefeat: @ 829B19C
	.string "Ya veo que sí.\n"
	.string "Pues mira qué bien.$"

Route114_Text_AngelinaPostBattle: @ 829B1BC
	.string "¡Algunos Pokémon cambian tanto al\n"
	.string "evolucionar que ni los reconoces!$"

Route115_Text_TimothyIntro: @ 829B1FA
	.string "Mmmm…\n"
	.string "Pareces capaz…\l"
	.string "¡Comprobemos si además lo eres!$"

Route115_Text_TimothyDefeat: @ 829B230
	.string "¡Pues lo eres mucho más de lo\n"
	.string "que lo pareces!$"

Route115_Text_TimothyPostBattle: @ 829B258
	.string "Nadie nace sabiendo.\n"
	.string "¡Hay que esforzarse!\l"
	.string "Ésa es una gran verdad.$"

Route115_Text_TimothyRegister: @ 829B2B3
	.string "Mmm… La derrota que sufrí es\n"
	.string "ahora apenas un recuerdo lejano.\p"
	.string "Si te parece bien, quisiera tener otra\n"
	.string "oportunidad de vencerte en combate.$"

Route115_Text_TimothyRematchIntro: @ 829B32C
	.string "Mmmm… Una vez más, pareces\n"
	.string "de lo más capaz.\l"
	.string "¡Comprobemos si lo sigues siendo!$"

Route115_Text_TimothyRematchDefeat: @ 829B372
	.string "¡Tan capaz como siempre!$"

Route115_Text_TimothyPostRematch: @ 829B385
	.string "¡Hay que esforzarse y sudar!\p"
	.string "Yo he perdido porque no le he\n"
	.string "echado bastantes ganas.$"

Route115_Text_KoichiIntro: @ 829B3CC
	.string "¡Tú!\p"
	.string "¡Mis Machop!\p"
	.string "¡Pelead! ¡Ahora!$"

Route115_Text_KoichiDefeat: @ 829B3ED
	.string "¡Ay, huy, oy!$"

Route115_Text_KoichiPostBattle: @ 829B3FF
	.string "¡Mis Machop!\p"
	.string "¡Mientras sigan motivados, yo seguiré\n"
	.string "mejorando con ellos!$"

Route115_Text_NobIntro: @ 829B449
	.string "¡Mi mayor habilidad es romper\n"
	.string "ladrillos con la frente!$"

Route115_Text_NobDefeat: @ 829B480
	.string "¡Ayyyyy! ¡Qué dolor de cabeza\n"
	.string "más maloooo!$"

Route115_Text_NobPostBattle: @ 829B49D
	.string "Estoy enseñando karate a mi Pokémon.\p"
	.string "Creo que acabará siendo mucho\n"
	.string "mejor que yo. Qué emoción.$"

Route115_Text_NobRegister: @ 829B50B
	.string "¡Me has impresionado hasta la médula!\n"
	.string "¡Volvamos a luchar cuando haya\l"
	.string "terminado mi entrenamiento!$"

Route115_Text_NobRematchIntro: @ 829B547
	.string "Desde que me derrotaste, hemos estado\n"
	.string "entrenando duro para mejorar.\l"
	.string "¡Venga! ¡Es la hora de la revancha!$"

Route115_Text_NobRematchDefeat: @ 829B59D
	.string "¡Ayyyyy!\n"
	.string "¡Hemos vuelto a perder!$"

Route115_Text_NobPostRematch: @ 829B5B5
	.string "¡Mi Pokémon va a ser el mejor!\n"
	.string "¡Voy a entrenarlo como un loco!$"

Route115_Text_CyndyIntro: @ 829B5EF
	.string "Esta playa es mi campo de\n"
	.string "entrenamiento secreto.\l"
	.string "¡Ya te puedes ir a otra parte!$"

Route115_Text_CyndyDefeat: @ 829B62D
	.string "¡No he entrenado bastante!$"

Route115_Text_CyndyPostBattle: @ 829B647
	.string "Me gusta entrenarme aquí porque la\n"
	.string "arena amortigua las caídas y así\l"
	.string "no te haces tanto daño.$"

Route115_Text_CyndyRegister: @ 829B6AB
	.string "Venga, va, puedes venir aquí cuando\n"
	.string "te apetezca, pero a cambio quiero\l"
	.string "volver a luchar contigo.$"

Route115_Text_CyndyRematchIntro: @ 829B6FA
	.string "Muy bien, vamos a entrar en faena.$"

Route115_Text_CyndyRematchDefeat: @ 829B71A
	.string "Yo soy buenísima, pero mis Pokémon…$"

Route115_Text_CyndyPostRematch: @ 829B737
	.string "No me importa perder. Me gustan tanto\n"
	.string "los combates Pokémon que me divierto\l"
	.string "igual, sea cual sea el resultado.$"

Route115_Text_HectorIntro: @ 829B78F
	.string "Tengo un Pokémon rarísimo.\n"
	.string "¿A que quieres verlo?$"

Route115_Text_HectorDefeat: @ 829B7C5
	.string "Tú… ¡Tú quieres quedarte con\n"
	.string "mi Pokémon! ¿A que sí?$"

Route115_Text_HectorPostBattle: @ 829B7EA
	.string "Tengo un Pokémon raro y eso es lo\n"
	.string "único que me importa para ser feliz.$"

Route115_Text_KyraIntro: @ 829B826
	.string "¡Lucharé mientras corro!\n"
	.string "¡A ver si aguantas el ritmo!$"

Route115_Text_KyraDefeat: @ 829B85D
	.string "Ah, que me ahogo…$"

Route115_Text_KyraPostBattle: @ 829B869
	.string "¡Intentar luchar y correr al mismo\n"
	.string "tiempo ha sido un error!\p"
	.string "Será mejor que haga unos\n"
	.string "estiramientos para relajarme…$"

Route115_Text_JaidenIntro: @ 829B8C1
	.string "¡Toma ya!\n"
	.string "¡Ataque ninja Pokémon en acción!$"

Route115_Text_JaidenDefeat: @ 829B8E8
	.string "¡Buaaaaa!\n"
	.string "¡Nuestra estrategia ha fallado!$"

Route115_Text_JaidenPostBattle: @ 829B904
	.string "Pero mis Pokémon eran geniales,\n"
	.string "¡no te atrevas a negarlo!$"

Route115_Text_HeleneIntro: @ 829B92D
	.string "¡Mis Pokémon son cinturón\n"
	.string "negro en fortaleza!$"

Route115_Text_HeleneDefeat: @ 829B958
	.string "¡Qué humillación!$"

Route115_Text_HelenePostBattle: @ 829B971
	.string "No suelo encontrar a nadie\n"
	.string "que me aventaje…\p"
	.string "¡Ya sé!\n"
	.string "Eres líder de gimnasio, ¿verdad?$"

Route115_Text_AlixIntro: @ 829B9CB
	.string "¡No te escondas que te he visto!\n"
	.string "¡Ahora no puedes escapar!$"

Route115_Text_AlixDefeat: @ 829B9F6
	.string "¡Bah!\n"
	.string "¡Te defiendes bien!$"

Route115_Text_AlixPostBattle: @ 829BA04
	.string "En fin, visto lo visto, creo que me\n"
	.string "voy a Teletransportar a casa.$"

Route115_Text_MarleneIntro: @ 829BA2C
	.string "Has interrumpido mi meditación…\n"
	.string "Y vas a pagar por esa afrenta…$"

Route115_Text_MarleneDefeat: @ 829BA67
	.string "¡Me has roto la concentración!$"

Route115_Text_MarlenePostBattle: @ 829BA87
	.string "Quisiera meditar junto a mis Pokémon,\n"
	.string "pero este lugar no se presta a ello…$"

Route116_Text_ClarkIntro: @ 829BACD
	.string "Si no acaban el túnel, no importa: en vez\n"
	.string "de atravesar la montaña, la escalaré.$"

Route116_Text_ClarkDefeat: @ 829BB0F
	.string "Uf… Uf…\n"
	.string "Me he quedado sin aliento…$"

Route116_Text_ClarkPostBattle: @ 829BB31
	.string "¡Qué más da que haya túnel o no!\n"
	.string "Los Montañeros lo tenemos chupado.$"

Route116_Text_JoeyIntro: @ 829BB79
	.string "¡Mis Pokémon son lo más!\n"
	.string "¡Ahora vas a ver!$"

Route116_Text_JoeyDefeat: @ 829BB9A
	.string "¡Ay! ¡Me he hecho un arañazo!\n"
	.string "¿Dónde hay tiritas por aquí?$"

Route116_Text_JoeyPostBattle: @ 829BBC6
	.string "Las tiritas son una señal de todo lo\n"
	.string "que se ha luchado. ¡Mira mi colección!$"

Route116_Text_JoseIntro: @ 829BBFD
	.string "Mis Pokémon de tipo Bicho son\n"
	.string "duros como ellos solos… ¡Ahora verás!$"

Route116_Text_JoseDefeat: @ 829BC25
	.string "¡He perdido! ¡Y eso que pensaba\n"
	.string "que esto era pan comido!$"

Route116_Text_JosePostBattle: @ 829BC42
	.string "Los Pokémon de tipo Bicho evolucionan\n"
	.string "muy rápido. Es decir, mejoran rápido.$"

Route116_Text_JaniceIntro: @ 829BC7F
	.string "¡Déjame mostrarte lo fuerte que\n"
	.string "es mi Pokémon del alma!$"

Route116_Text_JaniceDefeat: @ 829BCB3
	.string "Eres un pelín mejor que yo…$"

Route116_Text_JanicePostBattle: @ 829BCCC
	.string "Los Pokémon que son dulces y fuertes\n"
	.string "son los mejores, en mi opinión.$"

Route116_Text_JerryIntro: @ 829BD0C
	.string "Aprendemos un montón de teoría en\n"
	.string "la escuela de entrenadores.\p"
	.string "¡Ha llegado la hora de practicar!$"

Route116_Text_JerryDefeat: @ 829BD66
	.string "He estado ganduleando en clase,\n"
	.string "por eso he perdido…$"

Route116_Text_JerryPostBattle: @ 829BD92
	.string "Voy a tener que repetir el curso en\n"
	.string "la escuela de entrenadores.\l"
	.string "Si no, Petra va a echar humo…$"

Route116_Text_JerryRegister1: @ 829BDEF
	.string "En la escuela de entrenadores dicen\n"
	.string "que un Pokénav registra entrenadores.\p"
	.string "No acabo de entender cómo funciona,\n"
	.string "¿me lo podrías enseñar?$"

Route116_Text_JerryRegister2: @ 829BE71
	.string "En la escuela de entrenadores dicen\n"
	.string "que un Pokénav registra entrenadores.\p"
	.string "No acabo de entender cómo funciona,\n"
	.string "¿me lo podrías enseñar?$"

Route116_Text_JerryRematchIntro: @ 829BEF3
	.string "He estado empollando un montón en\n"
	.string "la escuela de entrenadores.\l"
	.string "Esta vez no voy a perder…$"

Route116_Text_JerryRematchDefeat: @ 829BF4C
	.string "Pero… Pero…\n"
	.string "¡Pero si he estudiado mogollón!$"

Route116_Text_JerryPostRematch: @ 829BF68
	.string "Voy a tener que repetir el curso en\n"
	.string "la escuela de entrenadores.\l"
	.string "Si no, Petra va a echar humo…$"

Route116_Text_KarenIntro: @ 829BFC5
	.string "Yo estudio en la escuela, en casa, en\n"
	.string "el camino de la escuela a casa…$"

Route116_Text_KarenDefeat: @ 829BFFA
	.string "No me lo puedo creer… ¿He perdido?$"

Route116_Text_KarenPostBattle: @ 829C010
	.string "Aaaaah… ¡Así nunca llegaré a ser una\n"
	.string "gran entrenadora, como Petra!$"

Route116_Text_KarenRegister1: @ 829C052
	.string "¡Ahí va! ¿Eso es un Pokénav?\n"
	.string "¡Yo también tengo uno! ¡Regístrame!$"

Route116_Text_KarenRegister2: @ 829C096
	.string "¡Ahí va! ¿Eso es un Pokénav?\n"
	.string "¡Yo también tengo uno! ¡Regístrame!$"

Route116_Text_KarenRematchIntro: @ 829C0DA
	.string "¡He hincado los codos a fondo desde\n"
	.string "la última vez! ¡Ahora vas a ver!$"

Route116_Text_KarenRematchDefeat: @ 829C11F
	.string "No me lo puedo creer… ¿He perdido?\n"
	.string "¿Otra vez?$"

Route116_Text_KarenPostRematch: @ 829C13B
	.string "¿Has vencido a Petra?\n"
	.string "Pues entonces es normal que no te\l"
	.string "gane… Al menos por ahora.$"

Route116_Text_SarahIntro: @ 829C173
	.string "Para tu información, nunca nadie\n"
	.string "ha logrado superarme en nada.$"

Route116_Text_SarahDefeat: @ 829C1B8
	.string "Ay, qué fatalidad.\n"
	.string "Es una nueva experiencia para mí.$"

Route116_Text_SarahPostBattle: @ 829C1EA
	.string "Llevo un tren de vida muy lujoso.\n"
	.string "Puedo tener todo lo que deseo.\p"
	.string "Pero mi riqueza de poco sirve en\n"
	.string "lo que respecta a los Pokémon.$"

Route116_Text_DawsonIntro: @ 829C266
	.string "¡Cuando veas la maravillosa piel de mis\n"
	.string "Pokémon, caerás ante su belleza\l"
	.string "y la victoria será mía!$"

Route116_Text_DawsonDefeat: @ 829C2C2
	.string "¡No puede ser y además es imposible!$"

Route116_Text_DawsonPostBattle: @ 829C2DD
	.string "¡No, no, no y no!\n"
	.string "¡Has destrozado la piel de mis Pokémon!\l"
	.string "¡Y además me has despeinado!\l"
	.string "¡Te pienso enviar la factura!$"

Route116_Text_DevanIntro: @ 829C350
	.string "¡Prepárate para una buena sacudida!$"

Route116_Text_DevanDefeat: @ 829C365
	.string "¡Aaaah!\n"
	.string "¡Ha sido visto y no visto!$"

Route116_Text_DevanPostBattle: @ 829C380
	.string "Debería probar con diferentes tipos\n"
	.string "de Pokémon. Creo que me iría mejor.$"

Route116_Text_JohnsonIntro: @ 829C3C1
	.string "Por aquí no se llega a ningún sitio.\n"
	.string "Me aburro, así que, ¿luchamos?$"

Route116_Text_JohnsonDefeat: @ 829C3F7
	.string "Qué divertido, y eso que he perdido.$"

Route116_Text_JohnsonPostBattle: @ 829C418
	.string "¿Te quieres quedar aquí\n"
	.string "a hacerme compañía?$"

Route117_Text_IsaacIntro: @ 829C43F
	.string "Dime, ¿quieres luchar contra los\n"
	.string "Pokémon que estoy entrenando?$"

Route117_Text_IsaacDefeat: @ 829C47A
	.string "Los tuyos sí que han recibido\n"
	.string "un buen entrenamiento…$"

Route117_Text_IsaacPostBattle: @ 829C498
	.string "No todo es cuestión de fuerza\n"
	.string "en lo que respecta a los Pokémon.\p"
	.string "También hay que preocuparse de\n"
	.string "potenciar algún aspecto concreto\l"
	.string "de su personalidad.$"

Route117_Text_IsaacRegister: @ 829C508
	.string "Voy a endurecer el entrenamiento.\n"
	.string "¿Querrás ver los resultados?$"

Route117_Text_IsaacRematchIntro: @ 829C549
	.string "Los Pokémon que estoy entrenando\n"
	.string "tienen buen aspecto, como la otra vez.$"

Route117_Text_IsaacRematchDefeat: @ 829C58B
	.string "Sabes cómo cuidar de tus Pokémon.\n"
	.string "Podrías trabajar en la Guardería…$"

Route117_Text_IsaacPostRematch: @ 829C5D0
	.string "Tus Pokémon están muy en forma.\n"
	.string "Deberías participar en algún\l"
	.string "concurso de ciudad Calagua.$"

Route117_Text_LydiaIntro: @ 829C612
	.string "Perdona, pero quisiera ver si sabes\n"
	.string "entrenar a tus Pokémon como se debe.$"

Route117_Text_LydiaDefeat: @ 829C659
	.string "Pues sí, los entrenas muy bien.$"

Route117_Text_LydiaPostBattle: @ 829C679
	.string "Hay que criar a los Pokémon teniendo\n"
	.string "en cuenta su personalidad.$"

Route117_Text_LydiaRegister: @ 829C6BC
	.string "Me alegra haber conocido a alguien\n"
	.string "de tu talla. Espero volver a verte.$"

Route117_Text_LydiaRematchIntro: @ 829C6FD
	.string "Déjame comprobar que sigues\n"
	.string "entrenando Pokémon como se debe.$"

Route117_Text_LydiaRematchDefeat: @ 829C73E
	.string "¡Están creciendo que da gusto!$"

Route117_Text_LydiaPostRematch: @ 829C75A
	.string "Al parecer, según su naturaleza, los\n"
	.string "Pokémon prefieren un Pokécubo u otro.$"

Route117_Text_DylanIntro: @ 829C7A5
	.string "Estoy en medio de una competición de\n"
	.string "triatlón, pero puedo luchar contigo.$"

Route117_Text_DylanDefeat: @ 829C7EB
	.string "¡No me quedan fuerzas!$"

Route117_Text_DylanPostBattle: @ 829C800
	.string "Esta vez la he pifiado…\p"
	.string "Creo que voy a quedar el último en la\n"
	.string "carrera por culpa de este combate…$"

Route117_Text_DylanRegister: @ 829C846
	.string "¿Los Pokémon tienen que ser fuertes?\n"
	.string "¿Por qué no vienes a entrenarnos?$"

Route117_Text_DylanRematchIntro: @ 829C880
	.string "Estoy en medio de una competición de\n"
	.string "triatlón, pero llevo ventaja, así que\l"
	.string "vamos a echarnos un combate.$"

Route117_Text_DylanRematchDefeat: @ 829C8E3
	.string "¡Vuelvo a estar sin fuerzas!$"

Route117_Text_DylanPostRematch: @ 829C8FE
	.string "He conseguido ganar en natación y en\n"
	.string "ciclismo, pero no en Pokémon…$"

Route117_Text_MariaIntro: @ 829C955
	.string "Hago mi entrenamiento en triatlón con\n"
	.string "los Pokémon. ¡Verás qué velocidad!$"

Route117_Text_MariaDefeat: @ 829C9A6
	.string "Creo que tengo que practicar un\n"
	.string "poco más…$"

Route117_Text_MariaPostBattle: @ 829C9D0
	.string "Un entrenamiento solo sirve si lo\n"
	.string "haces de forma constante.\p"
	.string "Muy bien. Voy a entrenarme mucho\n"
	.string "más en serio desde mañana.$"

Route117_Text_MariaRegister: @ 829CA32
	.string "Tu entrenamiento parece ser perfecto.\n"
	.string "¡Lucha conmigo cuando quieras!$"

Route117_Text_MariaRematchIntro: @ 829CA7C
	.string "¿Sigues entrenándote duro?\n"
	.string "¡Yo sí, desde luego!\l"
	.string "¡A ver quién se entrena mejor!$"

Route117_Text_MariaRematchDefeat: @ 829CACC
	.string "Creo que tengo que practicar un\n"
	.string "poco más…$"

Route117_Text_MariaPostRematch: @ 829CAF6
	.string "Voy a ponerme a entrenar más en serio\n"
	.string "desde mañana. ¡Y volveremos a luchar!$"

Route117_Text_DerekIntro: @ 829CB32
	.string "Yo solía ser un Cazabichos.\n"
	.string "Ahora soy un Bichomaníaco.\p"
	.string "¡Pero los Pokémon me siguen\n"
	.string "gustando tanto como siempre!$"

Route117_Text_DerekDefeat: @ 829CB87
	.string "Y sigo siendo un inepto total,\n"
	.string "como siempre…$"

Route117_Text_DerekPostBattle: @ 829CBAD
	.string "Algunos piensan que un Bichomaníaco\n"
	.string "es un chalado de la vida…\p"
	.string "Pero yo soy un experto en Pokémon\n"
	.string "de tipo Bicho, así que es lógico que\l"
	.string "me llamen Bichomaníaco ¿o no?$"

Route117_Text_AnnaIntro: @ 829CC4A
	.string "Ani: Mi pupila está pendiente de mí,\n"
	.string "así que tengo que quedar bien.$"

Route117_Text_AnnaDefeat: @ 829CC8E
	.string "Ani: Mi pupila no me quita ojo.\n"
	.string "¿Por qué no te dejas ganar?$"

Route117_Text_AnnaPostBattle: @ 829CCCB
	.string "Ani: Tus Pokémon tienen buenas\n"
	.string "combinaciones de movimientos.\p"
	.string "¡Casi tanto como las nuestras!$"

Route117_Text_AnnaAndMegRegister: @ 829CD1D
	.string "Ani: ¡Tanta tranquilidad nos aburre!\n"
	.string "Volverás a vernos, ¿verdad?$"

Route117_Text_AnnaNotEnoughMons: @ 829CD61
	.string "Ani: Si quieres luchar contra\n"
	.string "nosotras, trae dos Pokémon.$"

Route117_Text_MegIntro: @ 829CD9D
	.string "Mati: ¡Voy a luchar junto con mi\n"
	.string "supertutora y te vamos a vencer!$"

Route117_Text_MegDefeat: @ 829CDE9
	.string "Mati: Oh, no… No he sabido dar la talla…$"

Route117_Text_MegPostBattle: @ 829CE17
	.string "Mati: No he sabido ayudar a Ani… Si\n"
	.string "no hubiera sido por mí, habría ganado.$"

Route117_Text_MegNotEnoughMons: @ 829CE52
	.string "Mati: ¿Sólo tienes un Pokémon?\n"
	.string "Pues entonces no podemos luchar.\p"
	.string "Nosotras hacemos Combates Dobles.$"

Route117_Text_AnnaRematchIntro: @ 829CEB6
	.string "Ani: Vamos a ver, no puedo seguir\n"
	.string "haciendo el ridículo delante de mi\l"
	.string "pupila, ¿está claro?$"

Route117_Text_AnnaRematchDefeat: @ 829CEF6
	.string "Ani: Nada, que no me concentro…$"

Route117_Text_AnnaPostRematch: @ 829CF1C
	.string "Ani: Tus Pokémon tienen buenas\n"
	.string "combinaciones de movimientos.\p"
	.string "¡Casi tanto como las nuestras!$"

Route117_Text_AnnaRematchNotEnoughMons: @ 829CF6E
	.string "Ani: Si quieres luchar contra\n"
	.string "nosotras, trae dos Pokémon.$"

Route117_Text_MegRematchIntro: @ 829CFAA
	.string "Mati: ¡Voy a luchar junto con mi\n"
	.string "supertutora y esta vez venceremos!$"

Route117_Text_MegRematchDefeat: @ 829CFED
	.string "Mati: Eres demasiado fuerte…$"

Route117_Text_MegPostRematch: @ 829CFFE
	.string "Mati: He combatido junto con mi tutora,\n"
	.string "pero hemos vuelto a perder…\p"
	.string "Creo que voy a cambiar de tutora…\n"
	.string "Esto me deprime…$"

Route117_Text_MegRematchNotEnoughMons: @ 829D053
	.string "Mati: ¿Sólo tienes un Pokémon?\n"
	.string "Pues entonces no podemos luchar.\p"
	.string "Nosotras hacemos Combates Dobles.$"

Route117_Text_MelinaIntro: @ 829D0B7
	.string "¿No es una maravilla poder luchar\n"
	.string "en un paisaje como éste?$"

Route117_Text_MelinaDefeat: @ 829D0F1
	.string "¡Guau, ha sido impresionante!$"

Route117_Text_MelinaPostBattle: @ 829D10E
	.string "Me encanta salir a correr\n"
	.string "en medio de la naturaleza.$"

Route117_Text_BrandiIntro: @ 829D14B
	.string "Quisiera mostrarte el poder oculto\n"
	.string "en un Pokémon Psíquico.$"

Route117_Text_BrandiDefeat: @ 829D189
	.string "¡Eres sorprendente!$"

Route117_Text_BrandiPostBattle: @ 829D196
	.string "Los Pokémon Psíquicos son complejos.\n"
	.string "Atrapa uno y lo comprobarás.$"

Route117_Text_AishaIntro: @ 829D1D1
	.string "Hay que concentrarse para ganar.\n"
	.string "¡Eso es lo que hago yo!$"

Route117_Text_AishaDefeat: @ 829D206
	.string "No pienso perder el tiempo sintiéndome\n"
	.string "mal por haber perdido. Me entrenaré más.$"

Route117_Text_AishaPostBattle: @ 829D24C
	.string "Creo que, si te obsesionas con la\n"
	.string "derrota, nunca lograrás vencer.$"

Route118_Text_RoseIntro: @ 829D290
	.string "El aroma de las flores es casi mágico.\n"
	.string "Te purifica el cuerpo y el espíritu.$"

Route118_Text_RoseDefeat: @ 829D2D8
	.string "Huy, mira tú por dónde…\n"
	.string "Parece que he perdido…$"

Route118_Text_RosePostBattle: @ 829D2FA
	.string "Las flores, los Pokémon…\n"
	.string "Me gusta todo lo que huele bien.\p"
	.string "Paso de cosas apestosas…$"

Route118_Text_RoseRegister: @ 829D343
	.string "Snif… Ese olor… ¡Es un Pokénav!\n"
	.string "¡Tenemos que registrarnos!$"

Route118_Text_RoseRematchIntro: @ 829D382
	.string "¿Te ha atraído mi dulce aroma?$"

Route118_Text_RoseRematchDefeat: @ 829D3AA
	.string "El poder de la aromaterapia no ha\n"
	.string "funcionado esta vez…$"

Route118_Text_RosePostRematch: @ 829D3D9
	.string "Si sabes usar la fragancia adecuada,\n"
	.string "atraerás a los Pokémon.$"

Route118_Text_PerryIntro: @ 829D41D
	.string "Los Pokémon Pájaro vuelan con\n"
	.string "elegancia en el cielo. ¡Qué bonito…!$"

Route118_Text_PerryDefeat: @ 829D45B
	.string "Argh… He caído en picado…$"

Route118_Text_PerryPostBattle: @ 829D46C
	.string "Tus Pokémon son muy buenos.\n"
	.string "Yo tengo que entrenar más a los míos.$"

Route118_Text_ChesterIntro: @ 829D4A6
	.string "¡Pokémon Pájaro!\n"
	.string "¡Alzad el vuelo!$"

Route118_Text_ChesterDefeat: @ 829D4C4
	.string "Se han largado volando…$"

Route118_Text_ChesterPostBattle: @ 829D4DA
	.string "Si mis Pokémon fueran más fuertes,\n"
	.string "podrían volar con más libertad…$"

Route118_Text_BarnyIntro: @ 829D515
	.string "Soy pescador, además de entrenador.\n"
	.string "Atrapo Pokémon y los entreno yo mismo.$"

Route118_Text_BarnyDefeat: @ 829D55C
	.string "Creía que mi método de entrenamiento\n"
	.string "era infalible…$"

Route118_Text_BarnyPostBattle: @ 829D587
	.string "Entrenar Pokémon no es fácil cuando\n"
	.string "estás ocupado pescándolos…\p"
	.string "¿Habré pecado de hacer las cosas\n"
	.string "a medias?$"

Route118_Text_WadeIntro: @ 829D5DF
	.string "Cuando eres pescador, tienes que\n"
	.string "estar bien equipado.\p"
	.string "Pero cuando eres entrenador, tienes\n"
	.string "que tener buen corazón y amor por\l"
	.string "los Pokémon, por supuesto.$"

Route118_Text_WadeDefeat: @ 829D64C
	.string "¿Mi corazón no es bastante noble?$"

Route118_Text_WadePostBattle: @ 829D663
	.string "Ahora que lo pienso, la pesca es un\n"
	.string "combate entre Pescadores y Pokémon.$"

Route118_Text_DaltonIntro: @ 829D6AF
	.string "¡Te voy a hacer mover los pies a mi\n"
	.string "ritmo!$"

Route118_Text_DaltonDefeat: @ 829D6CD
	.string "Ejem… La, la, la…$"

Route118_Text_DaltonPostBattle: @ 829D6D8
	.string "Una guitarra eléctrica no tiene por\n"
	.string "qué hacer siempre ruido.\p"
	.string "Si la tocas con delicadeza, puedes\n"
	.string "arrancarle melodías conmovedoras.$"

Route118_Text_DaltonRegister: @ 829D74A
	.string "Tienes que venir a verme cuando haya\n"
	.string "mejorado mis composiciones, ¿vale?$"

Route118_Text_DaltonRematchIntro: @ 829D789
	.string "Mis Pokémon y yo queremos regalarte\n"
	.string "una canción… ¡guerrera!$"

Route118_Text_DaltonRematchDefeat: @ 829D7CA
	.string "Ejem… La, la, la…$"

Route118_Text_DaltonPostRematch: @ 829D7D5
	.string "Cuando toco mi guitarra, pongo\n"
	.string "el alma en cada nota.$"

Route118_Text_DeandreIntro: @ 829D81B
	.string "¡Adelante, Pokémon!\n"
	.string "¡A la de 1, a la de 2 y a la de 3!$"

Route118_Text_DeandreDefeat: @ 829D83C
	.string "Venid, Pokémon… ¿Estáis bien?\n"
	.string "A la de 1, a la de 2 y a la de 3…$"

Route118_Text_DeandrePostBattle: @ 829D872
	.string "¿No es maravilloso tener un equipo\n"
	.string "de combate Pokémon?\p"
	.string "Cópiame si quieres. ¡No me importa!$"

Route119_Text_BrentIntro: @ 829D8C2
	.string "¡Somos el círculo de imitadores!\n"
	.string "¡Imitamos todo lo que haces!$"

Route119_Text_BrentDefeat: @ 829D8F0
	.string "¡Mira tú por dónde…!\n"
	.string "¡He perdido!$"

Route119_Text_BrentPostBattle: @ 829D902
	.string "¿Que por qué mola imitar a la gente?\p"
	.string "Je, je, je…\n"
	.string "Nunca lo entenderías, mequetrefe…$"

Route119_Text_DonaldIntro: @ 829D941
	.string "¡Por fin nos conocemos!\n"
	.string "¡Mis Pokémon de tipo Bicho\l"
	.string "están encantados!$"

Route119_Text_DonaldDefeat: @ 829D97C
	.string "Ojalá no te hubiera conocido nunca…$"

Route119_Text_DonaldPostBattle: @ 829D993
	.string "Quiero seguir imitando a gente…\p"
	.string "¿Te quieres pirar ya de una vez?$"

Route119_Text_TaylorIntro: @ 829D9CD
	.string "Si tú avanzas, nosotros avanzamos.\p"
	.string "Si retrocedes, nosotros también.$"

Route119_Text_TaylorDefeat: @ 829DA14
	.string "Pero, si tú ganas, nosotros perdemos…$"

Route119_Text_TaylorPostBattle: @ 829DA2C
	.string "No puedo imitarte ganando un\n"
	.string "combate, es imposible.\l"
	.string "Qué frustrante es esto…$"

Route119_Text_DougIntro: @ 829DA7D
	.string "¡Sí, por fin me has encontrado!\n"
	.string "¿O más bien querías evitarme?$"

Route119_Text_DougDefeat: @ 829DABC
	.string "¡Guau, qué buen combate!$"

Route119_Text_DougPostBattle: @ 829DADB
	.string "¡Somos el Círculo de Imitadores!\n"
	.string "Espero que hayas disfrutado de\l"
	.string "nuestra actuación.$"

Route119_Text_GregIntro: @ 829DB17
	.string "No sabes quién soy, ¿verdad?\p"
	.string "Pero yo tampoco sé quién eres tú\n"
	.string "y no me importa. ¡Te desafío!$"

Route119_Text_GregDefeat: @ 829DB66
	.string "¡Eres bastante fuerte!$"

Route119_Text_GregPostBattle: @ 829DB7C
	.string "Mientras estés aquí, seguiremos\n"
	.string "imitando cada uno de tus movimientos.$"

Route119_Text_KentIntro: @ 829DBC2
	.string "El círculo de imitadores lo fundó\n"
	.string "gente a la que le gusta imitar\l"
	.string "a los demás.\p"
	.string "Basta de charlas. ¡A luchar!$"

Route119_Text_KentDefeat: @ 829DC20
	.string "¡Me rindo!$"

Route119_Text_KentPostBattle: @ 829DC2B
	.string "¿No quieres formar parte del\n"
	.string "círculo de imitadores?$"

Route119_Text_JacksonIntro: @ 829DC4C
	.string "¿Quién sabe todo lo que hay que\n"
	.string "saber para sobrevivir?\p"
	.string "¡Pues los Pokéguardas,\n"
	.string "por supuestísimo!$"

Route119_Text_JacksonDefeat: @ 829DC9F
	.string "Todavía tengo mucho que aprender\n"
	.string "sobre los Pokémon, por lo que se ve.$"

Route119_Text_JacksonPostBattle: @ 829DCC6
	.string "Tenemos un sueño: alejarnos\n"
	.string "de la civilización y despertar el\l"
	.string "espíritu salvaje que llevamos dentro.$"

Route119_Text_JacksonRegister: @ 829DD1C
	.string "Espero que me des la revancha y que\n"
	.string "no te burles de mi inexperiencia.$"

Route119_Text_JacksonRematchIntro: @ 829DD62
	.string "Voy a despertar mi espíritu salvaje\n"
	.string "gracias a los Pokémon.$"

Route119_Text_JacksonRematchDefeat: @ 829DDA5
	.string "¡Sigues fuerte como un toro!$"

Route119_Text_JacksonPostRematch: @ 829DDBD
	.string "Ten confianza en tus Pokémon.\n"
	.string "Ten confianza en ti.\p"
	.string "Así conseguirás todo lo que\n"
	.string "te propongas.$"

Route119_Text_CatherineIntro: @ 829DE0F
	.string "Huy, qué curioso…\p"
	.string "Para ser alguien que se va de aventura,\n"
	.string "llevas poco equipaje contigo.$"

Route119_Text_CatherineDefeat: @ 829DE5D
	.string "Las cosas malas pasan cuando no vas\n"
	.string "preparado para cualquier eventualidad.$"

Route119_Text_CatherinePostBattle: @ 829DE88
	.string "Tú no llevas mucho equipaje, pero te\n"
	.string "has preparado bien.\p"
	.string "Y también tienes una buena preparación\n"
	.string "física y psicológica. Te felicito.$"

Route119_Text_CatherineRegister: @ 829DEF7
	.string "¿Tienes un Pokénav? Todo entrenador\n"
	.string "que se precie ha de poseer uno.\p"
	.string "¡Ah, pues sí que lo tienes!\n"
	.string "¡Entonces vamos a registrarnos!$"

Route119_Text_CatherineRematchIntro: @ 829DF6B
	.string "¿Qué tal te va en tu viaje con\n"
	.string "los Pokémon?$"

Route119_Text_CatherineRematchDefeat: @ 829DF92
	.string "Sigo sin estar preparada…\n"
	.string "¿Pero qué me falta? ¿Qué?$"

Route119_Text_CatherinePostRematch: @ 829DFAF
	.string "Del mismo modo que un entrenador\n"
	.string "confía en sus Pokémon, los Pokémon\l"
	.string "confían en su entrenador.$"

Route119_Text_HughIntro: @ 829E007
	.string "¡El cielo infinito encierra todo tipo de\n"
	.string "promesas y sueños!\p"
	.string "¡No hay nada más hermoso que volar!$"

Route119_Text_HughDefeat: @ 829E063
	.string "He caído en picado…$"

Route119_Text_HughPostBattle: @ 829E071
	.string "¡Gracias a mis Pokémon Pájaro, mi\n"
	.string "sueño de surcar los aires es realidad!$"

Route119_Text_PhilIntro: @ 829E0A5
	.string "¡Te voy a enseñar la fuerza del\n"
	.string "ataque de mi Pokémon Pájaro!$"

Route119_Text_PhilDefeat: @ 829E0E1
	.string "Todavía nos falta un hervor…$"

Route119_Text_PhilPostBattle: @ 829E0F6
	.string "Desde que era pequeñito, siempre he\n"
	.string "querido tener Pokémon Pájaro…$"

Route119_Text_YasuIntro: @ 829E134
	.string "Acechar entre las sombras, vivir en\n"
	.string "la oscuridad… Ése es mi destino…\p"
	.string "¡Y ahora salgo a la luz para retarte!$"

Route119_Text_YasuDefeat: @ 829E18D
	.string "¡Acepto mi derrota!$"

Route119_Text_YasuPostBattle: @ 829E19D
	.string "Aquellos que pierden un combate han\n"
	.string "de volver silenciosos a las sombras…\l"
	.string "El destino lo quiere así…$"

Route119_Text_TakashiIntro: @ 829E1F5
	.string "¡Si no estás en guardia, te espera\n"
	.string "una buena tunda!$"

Route119_Text_TakashiDefeat: @ 829E22B
	.string "¡Me has dejado patidifuso!$"

Route119_Text_TakashiPostBattle: @ 829E245
	.string "Mi ataque sorpresa ha sido un fiasco…$"

Route119_Text_HideoIntro: @ 829E26A
	.string "El mejor lugar para esconder un\n"
	.string "árbol es… ¡un bosque!$"

Route119_Text_HideoDefeat: @ 829E288
	.string "Me inclino ante tu superioridad\n"
	.string "en combate…$"

Route119_Text_HideoPostBattle: @ 829E2A3
	.string "El mejor lugar para esconder un\n"
	.string "árbol es… ¡un bosque!\l"
	.string "Y el mejor para esconder un\l"
	.string "Pokémon es… ¡otro Pokémon!\p"
	.string "¿Tú entiendes lo que acabo de decir?\n"
	.string "¡Yo tampoco, ja, ja, ja!$"

Route119_Text_ChrisIntro: @ 829E30D
	.string "Me has dirigido la palabra…,\n"
	.string "¡así que buscas pelea!\p"
	.string "¡Perfecto! ¡Te voy a atacar con los\n"
	.string "Pokémon que atrapé haciendo Surf!$"

Route119_Text_ChrisDefeat: @ 829E372
	.string "No tengo ni idea de qué hay\n"
	.string "que hacer para ganar.$"

Route119_Text_ChrisPostBattle: @ 829E3A2
	.string "Haz Surf sobre un Pokémon…\p"
	.string "y pesca desde su lomo…\p"
	.string "¡Es bestial! ¡Te lo recomiendo!$"

Route119_Text_FabianIntro: @ 829E3FF
	.string "¡Que suene una música triunfal!\n"
	.string "¡La victoria es mía!\l"
	.string "¡Éste es mi momento de gloria!$"

Route119_Text_FabianDefeat: @ 829E44F
	.string "Oh, no, ¡ahora ya sé quién manda!\n"
	.string "No soy yo, ¡pondré una demanda!$"

Route119_Text_FabianPostBattle: @ 829E492
	.string "Que suene una música triste…\n"
	.string "Y piérdete de mi vista…\l"
	.string "¡Te haré pagar por mi derrota!$"

Route119_Text_DaytonIntro: @ 829E4DF
	.string "¡Jo, jo, jo!\n"
	.string "¡Me gusta luchar con las nuevas\l"
	.string "generaciones! ¡Vamos allá!$"

Route119_Text_DaytonDefeat: @ 829E513
	.string "¡Menudos bríos!\n"
	.string "¡Jo, jo, jo!$"

Route119_Text_DaytonPostBattle: @ 829E532
	.string "¡Jo, jo, jo!\n"
	.string "¡Intentaré poner en práctica\l"
	.string "las nuevas técnicas de lucha!$"

Route119_Text_RachelIntro: @ 829E56F
	.string "Mi parasol me acompaña\n"
	.string "allá donde voy.$"

Route119_Text_RachelDefeat: @ 829E5B1
	.string "Oh, no…\n"
	.string "No es justo.$"

Route119_Text_RachelPostBattle: @ 829E5CB
	.string "¿Dices que mi parasol pesa demasiado?\n"
	.string "Ja, tú sí que tienes la Mochila llena\l"
	.string "de tonterías que seguro que no usas.$"

Route120_Text_ColinIntro: @ 829E62D
	.string "¿Tienes algún movimiento que puedas\n"
	.string "usar contra Pokémon que usen Vuelo?$"

Route120_Text_ColinDefeat: @ 829E665
	.string "¡Vuelas más alto que yo!$"

Route120_Text_ColinPostBattle: @ 829E67A
	.string "El movimiento Vuelo es muy práctico,\n"
	.string "¿a que sí?\p"
	.string "Cuando un Pokémon vuela, puede\n"
	.string "escapar de casi cualquier ataque.$"

Route120_Text_RobertIntro: @ 829E6E3
	.string "Mi Pokémon es fuerte.\n"
	.string "¿Y los tuyos?$"

Route120_Text_RobertDefeat: @ 829E70A
	.string "Tus Pokémon son más fuertes…$"

Route120_Text_RobertPostBattle: @ 829E726
	.string "Se puede confiar en los Pokémon\n"
	.string "que crecen de forma continua.$"

Route120_Text_RobertRegister: @ 829E75D
	.string "¡Está cantado que vas a mejorar!\n"
	.string "¡Déjame registrarte en mi Pokénav!$"

Route120_Text_RobertRematchIntro: @ 829E7AA
	.string "Se puede confiar en los Pokémon\n"
	.string "que crecen de forma continua.$"

Route120_Text_RobertRematchDefeat: @ 829E7E1
	.string "Tus Pokémon son más que fuertes.$"

Route120_Text_RobertPostRematch: @ 829E804
	.string "Mis Pokémon se están fortaleciendo\n"
	.string "mucho. Yo también debería hacerlo…$"

Route120_Text_LorenzoIntro: @ 829E843
	.string "Voy a ver si tus Pokémon están\n"
	.string "preparados para vivir al aire libre…$"

Route120_Text_LorenzoDefeat: @ 829E884
	.string "¡Con unos Pokémon tan fuertes,\n"
	.string "no necesitas que nadie te rescate!$"

Route120_Text_LorenzoPostBattle: @ 829E8C5
	.string "Viajar a donde tu corazón te lleve en\n"
	.string "compañía de tus Pokémon…\l"
	.string "¡Es lo mejor de ser entrenador!$"

Route120_Text_JennaIntro: @ 829E91C
	.string "¿Estás en forma?\n"
	.string "Si no es así, podrías pasarlo mal\l"
	.string "cuando un combate se complique.$"

Route120_Text_JennaDefeat: @ 829E980
	.string "Yo estaba en forma, pero…$"

Route120_Text_JennaPostBattle: @ 829E996
	.string "Salgo a correr cada día para estar\n"
	.string "en forma, ¡siempre con mis Pokémon!$"

Route120_Text_JeffreyIntro: @ 829E9D7
	.string "Ejem…\n"
	.string "Ejem…\l"
	.string "¿Quieres luchar?$"

Route120_Text_JeffreyDefeat: @ 829E9FF
	.string "Ejem…\n"
	.string "Ejem…\l"
	.string "He perdido, creo…$"

Route120_Text_JeffreyPostBattle: @ 829EA08
	.string "Ejem…\n"
	.string "Ejem…\l"
	.string "Entrenaré más…$"

Route120_Text_JeffreyRegister: @ 829EA31
	.string "Ejem…\n"
	.string "Ejem…\l"
	.string "¿Tienes un Pokénav…?$"

Route120_Text_JeffreyRematchIntro: @ 829EA61
	.string "Ejem…\n"
	.string "Ejem…\l"
	.string "¿Quieres volver a luchar?$"

Route120_Text_JeffreyRematchDefeat: @ 829EA8F
	.string "Ejem…\n"
	.string "Ejem…\l"
	.string "He vuelto a perder, creo…$"

Route120_Text_JeffreyPostRematch: @ 829EAA9
	.string "Ejem…\n"
	.string "Ejem…\l"
	.string "Entrenaré más…\l"
	.string "Por mis queridos Pokémon de tipo Bicho.$"

Route120_Text_JenniferIntro: @ 829EAEF
	.string "Los Pokémon tienen muchas habilidades\n"
	.string "especiales. Si quieres estar entre los\l"
	.string "grandes Entrenadores, estúdialas bien.$"

Route120_Text_JenniferDefeat: @ 829EB53
	.string "Se ve que has estado hincando\n"
	.string "los codos…$"

Route120_Text_JenniferPostBattle: @ 829EB6E
	.string "Las habilidades especiales de los\n"
	.string "Pokémon pueden cambiar el\l"
	.string "resultado de un combate.$"

Route120_Text_ChipIntro: @ 829EBAF
	.string "¿Con quién tengo el placer de hablar?\p"
	.string "¿Estás buscando antiguas ruinas cuya\n"
	.string "existencia se menciona solo en las\l"
	.string "leyendas?$"

Route120_Text_ChipDefeat: @ 829EC25
	.string "Qué revés tan desafortunado…$"

Route120_Text_ChipPostBattle: @ 829EC41
	.string "Esa roca gigantesca… quizás contenga\n"
	.string "esas ruinas legendarias en su interior.\l"
	.string "Pero… ¿dónde está la entrada?$"

Route120_Text_ClarissaIntro: @ 829ECA6
	.string "¿Por qué llevo este parasol?\p"
	.string "Te lo diré si me vences.$"

Route120_Text_ClarissaDefeat: @ 829ECEF
	.string "Un parasol no puede parar\n"
	.string "los ataques Pokémon…$"

Route120_Text_ClarissaPostBattle: @ 829ED19
	.string "No creo que este sol tan fuerte sea\n"
	.string "bueno para mis Pokémon…\l"
	.string "Por eso los cubro con este parasol.$"

Route120_Text_AngelicaIntro: @ 829ED71
	.string "Mi Pokémon, mi parasol y yo…\p"
	.string "Juntos formamos el cuadro perfecto.$"

Route120_Text_AngelicaDefeat: @ 829EDD3
	.string "¡Has arruinado esta preciosa escena!$"

Route120_Text_AngelicaPostBattle: @ 829EDF7
	.string "A ti no te sientan bien los parasoles.\p"
	.string "Y además seguro que te entorpecerían\n"
	.string "en el combate más que otra cosa.$"

Route120_Text_KeigoIntro: @ 829EE50
	.string "Crearé nuevas técnicas ninja a partir\n"
	.string "de los movimientos de los Pokémon.$"

Route120_Text_KeigoDefeat: @ 829EE97
	.string "Me temo que he estado soñando\n"
	.string "despierto…$"

Route120_Text_KeigoPostBattle: @ 829EED4
	.string "Quizás debería ir a estudiar bajo las\n"
	.string "órdenes de un maestro ninja…$"

Route120_Text_RileyIntro: @ 829EF08
	.string "Los ninjas nos ocultamos usando\n"
	.string "una capa de camuflaje.\l"
	.string "¿A que no sabías dónde estaba?$"

Route120_Text_RileyDefeat: @ 829EF63
	.string "¡He perdido!\n"
	.string "¿Cómo puedo camuflar esta vergüenza?$"

Route120_Text_RileyPostBattle: @ 829EF89
	.string "Mi capa de camuflaje está\n"
	.string "hecha a mano. Bonita, ¿eh?$"

Route120_Text_CallieIntro: @ 829EFB1
	.string "¡Si no tienes cuidado, te harás daño!$"

Route120_Text_CallieDefeat: @ 829EFE1
	.string "¡Auuu!\n"
	.string "¡Yo soy quien se ha hecho daño!$"

Route120_Text_CalliePostBattle: @ 829F002
	.string "Me pregunto si debería hacer que\n"
	.string "mis Pokémon evolucionen.\l"
	.string "Son tan monos así…$"

Route120_Text_LeonelIntro: @ 829F04F
	.string "Dime, ¿tienes diferentes tipos\n"
	.string "de Pokémon en tu equipo?$"

Route120_Text_LeonelDefeat: @ 829F080
	.string "¡Acabo de ver cómo llevas\n"
	.string "la teoría a la práctica!$"

Route120_Text_LeonelPostBattle: @ 829F0A1
	.string "Creo que es genial que luches tan\n"
	.string "bien con tus Pokémon favoritos.$"

Route121_Text_VanessaIntro: @ 829F0EC
	.string "¿Quieres jugar con mi Pokémon,\n"
	.string "que es más bonito que un sol?$"

Route121_Text_VanessaDefeat: @ 829F11F
	.string "¡Yo no me refería a esto!$"

Route121_Text_VanessaPostBattle: @ 829F138
	.string "Voy a un concurso en Calagua.\p"
	.string "Mi Pokémon debería poder superar\n"
	.string "el nivel Experto sin problemas.$"

Route121_Text_WalterIntro: @ 829F199
	.string "Me he recorrido el mundo de cabo a\n"
	.string "rabo en compañía de mi Pokémon.\p"
	.string "Te imaginarás que confío bastante\n"
	.string "en mis posibilidades.$"

Route121_Text_WalterDefeat: @ 829F20D
	.string "Has luchado muy bien…$"

Route121_Text_WalterPostBattle: @ 829F21E
	.string "Creo que voy a volver a dar la vuelta\n"
	.string "al mundo con mi Pokémon.$"

Route121_Text_WalterRegister: @ 829F25B
	.string "Tus Pokémon realizan proezas\n"
	.string "memorables. ¡Permíteme registrarte!$"

Route121_Text_WalterRematchIntro: @ 829F2A6
	.string "Me he recorrido el mundo de cabo a\n"
	.string "rabo en compañía de mi Pokémon.\p"
	.string "Te imaginarás que confío bastante\n"
	.string "en mis posibilidades.$"

Route121_Text_WalterRematchDefeat: @ 829F31A
	.string "Has luchado muy bien…$"

Route121_Text_WalterPostRematch: @ 829F32B
	.string "Tus Pokémon y tú sois tremendos.\p"
	.string "Creo que hablarán de vuestras proezas\n"
	.string "incluso en los pueblos más allá del mar.$"

Route121_Text_TammyIntro: @ 829F381
	.string "En este mundo hay poderes que\n"
	.string "sobrepasan nuestro entendimiento…$"

Route121_Text_TammyDefeat: @ 829F3B9
	.string "Me han derrotado…$"

Route121_Text_TammyPostBattle: @ 829F3C6
	.string "El Monte Pírico…\n"
	.string "Allí se siente la presencia de un\l"
	.string "poder de lo más misterioso.$"

Route121_Text_KateIntro: @ 829F3FB
	.string "Cati: ¡Nosotras no tenemos miedo!\n"
	.string "¡Pero tú sí que deberías temblar!$"

Route121_Text_KateDefeat: @ 829F43F
	.string "Cati: He metido la pata hasta el\n"
	.string "fondo… Y mi pupila ha sido testigo…$"

Route121_Text_KatePostBattle: @ 829F476
	.string "Cati: Cuando alguien confía en mí,\n"
	.string "no puedo decepcionarle…$"

Route121_Text_KateNotEnoughMons: @ 829F4C9
	.string "Cati: Si solo tienes un Pokémon,\n"
	.string "no podemos luchar contigo.\p"
	.string "Sería aprovecharnos de ti…$"

Route121_Text_JoyIntro: @ 829F521
	.string "Feli: ¡Nosotras no tenemos miedo!\n"
	.string "¡Pero tú sí que deberías temblar!$"

Route121_Text_JoyDefeat: @ 829F564
	.string "Feli: ¡Siento no haberte ayudado\n"
	.string "más, Cati!$"

Route121_Text_JoyPostBattle: @ 829F582
	.string "Feli: Qué mal… Tendré que entrenarme\n"
	.string "con Cati, mi tutora, muchísimo más…$"

Route121_Text_JoyNotEnoughMons: @ 829F5CE
	.string "Feli: Necesitas al menos dos Pokémon\n"
	.string "si quieres desafiarnos.$"

Route121_Text_JessicaIntro: @ 829F612
	.string "¡Alto ahí! ¡Echa una miradita\n"
	.string "a mis preciosísimos Pokémon!$"

Route121_Text_JessicaDefeat: @ 829F641
	.string "¡Oh! ¿Cómo osas?\n"
	.string "¡No se puede ir arrollando al personal!$"

Route121_Text_JessicaPostBattle: @ 829F66F
	.string "Creo que voy a ir a atrapar\n"
	.string "más Pokémon al Safari.$"

Route121_Text_JessicaRegister: @ 829F69F
	.string "Esta vez me lo he tomado bien,\n"
	.string "¡pero la próxima vez ya verás!$"

Route121_Text_JessicaRematchIntro: @ 829F6E4
	.string "Mis preciosísimos Pokémon han crecido.\n"
	.string "¡Míralos bien ahora!$"

Route121_Text_JessicaRematchDefeat: @ 829F710
	.string "¡Oh! ¿Cómo osas?\n"
	.string "¡Sigues abusando de la peña!$"

Route121_Text_JessicaPostRematch: @ 829F740
	.string "Creo que voy a ir a atrapar más\n"
	.string "Pokémon al Safari.$"

Route121_Text_CristinIntro: @ 829F770
	.string "Tengo la costumbre de derrotar\n"
	.string "a cinco Entrenadores cada día.\l"
	.string "¡Ven para que complete la cuota!$"

Route121_Text_CristinDefeat: @ 829F7C1
	.string "¡No puede ser!\n"
	.string "¡Eres lo peor!$"

Route121_Text_CristinPostBattle: @ 829F7D4
	.string "No esperaba perder tan fácilmente…\n"
	.string "¡La próxima vez ganaré!$"

Route121_Text_CristinRegister: @ 829F80D
	.string "¡Qué horrible humillación!\n"
	.string "No te olvidaré…\l"
	.string "¡Dame tu Pokénav!$"

Route121_Text_CristinRematchIntro: @ 829F855
	.string "Tengo la nueva costumbre de derrotar\n"
	.string "a diez Entrenadores cada día.\l"
	.string "¡Ven para que complete la cuota!$"

Route121_Text_CristinRematchDefeat: @ 829F8A8
	.string "¡No tan rápido!\n"
	.string "¡Exijo la revancha!$"

Route121_Text_CristinPostRematch: @ 829F8D0
	.string "Alguien a quien no puedo vencer…\n"
	.string "Snif…\l"
	.string "Esto no puede estar pasando…$"

Route121_Text_CaleIntro: @ 829F91A
	.string "¿No ves que voy cargado como una mula?\n"
	.string "¿Y aun así quieres luchar conmigo?$"

Route121_Text_CaleDefeat: @ 829F97B
	.string "¡Es normal que haya perdido!\n"
	.string "¡No tengo ni una mano libre!$"

Route121_Text_CalePostBattle: @ 829F9AE
	.string "He comprado demasiadas cosas en\n"
	.string "el centro comercial de Calagua.\p"
	.string "Está camino arriba. Ojalá tuviera\n"
	.string "una Mochila como la tuya.$"

Route121_Text_MylesIntro: @ 829FA1E
	.string "¡No hay nada que me guste más que\n"
	.string "ver los Pokémon de los demás!$"

Route121_Text_MylesDefeat: @ 829FA64
	.string "¡Flipo en colores!$"

Route121_Text_MylesPostBattle: @ 829FA73
	.string "¡Tus Pokémon son tremendos!\n"
	.string "¿Cómo los has criado?$"

Route121_Text_PatIntro: @ 829FAA7
	.string "¡Quiero que todo el mundo vea\n"
	.string "los Pokémon que he criado!$"

Route121_Text_PatDefeat: @ 829FAD8
	.string "¡Guau!\n"
	.string "¡Espectacular!$"

Route121_Text_PatPostBattle: @ 829FAEA
	.string "Crío a todos mis Pokémon por igual.\n"
	.string "No tengo ningún favorito.$"

Route121_Text_MarcelIntro: @ 829FB35
	.string "¡Mis Pokémon desconocen la derrota!\n"
	.string "La próxima vez que ganen,\l"
	.string "los llevaré a un Concurso.$"

Route121_Text_MarcelDefeat: @ 829FB8C
	.string "Oh, no, ¿qué ha pasado aquí?$"

Route121_Text_MarcelPostBattle: @ 829FBA8
	.string "Se ve que habrá que entrenarse más\n"
	.string "antes de ir a un Concurso.$"

Route123_Text_WendyIntro: @ 829FBEB
	.string "¿Quieres averiguar lo fuerte que eres?\n"
	.string "¡Yo te lo digo ahora mismo!$"

Route123_Text_WendyDefeat: @ 829FC23
	.string "¡Fuerte como un roble!$"

Route123_Text_WendyPostBattle: @ 829FC42
	.string "Tu fuerza es impresionante…\n"
	.string "Me has vencido nada menos que a mí…$"

Route123_Text_BraxtonIntro: @ 829FC6F
	.string "Parece que tienes una gran colección\n"
	.string "de medallas de gimnasio.\p"
	.string "¡Veamos si realmente las mereces!$"

Route123_Text_BraxtonDefeat: @ 829FCD6
	.string "¡Sí, te las has ganado con creces!$"

Route123_Text_BraxtonPostBattle: @ 829FCF4
	.string "¡Has hecho honor a tus medallas\n"
	.string "en este combate!$"

Route123_Text_VioletIntro: @ 829FD1D
	.string "Dicen que muchos buenos recuerdos\n"
	.string "están asociados a aromas.$"

Route123_Text_VioletDefeat: @ 829FD53
	.string "Puaj… Huelo el amargo aroma\n"
	.string "de la derrota…$"

Route123_Text_VioletPostBattle: @ 829FD7B
	.string "El jardín del Bayólogo está\n"
	.string "repleto de aromas vigorizantes.$"

Route123_Text_CameronIntro: @ 829FDBA
	.string "Los poderes psíquicos dependen\n"
	.string "mucho de la fuerza de voluntad.\p"
	.string "Yo no tengo ninguna voluntad\n"
	.string "de perder, ¡por eso soy fuerte!$"

Route123_Text_CameronDefeat: @ 829FE1E
	.string "Qué tristeza más grande…$"

Route123_Text_CameronPostBattle: @ 829FE2A
	.string "Los poderes psíquicos dependen\n"
	.string "mucho de la fuerza de voluntad.\l"
	.string "Nunca creí que perdería…$"

Route123_Text_CameronRegister: @ 829FE70
	.string "¡Lo presiento!\n"
	.string "¡Volveremos a enfrentarnos!\l"
	.string "Pero no sé si ganaré…\p"
	.string "Déjame ver tu Pokénav.$"

Route123_Text_CameronRematchIntro: @ 829FED4
	.string "Me he autoconvencido de que no puedo\n"
	.string "volver a perder, ¡por eso soy fuerte!$"

Route123_Text_CameronRematchDefeat: @ 829FF1B
	.string "Qué tristeza más grande…$"

Route123_Text_CameronPostRematch: @ 829FF27
	.string "Debería entrenarme en el Monte Pírico.\n"
	.string "Si sigo así, no gano en la vida…$"

Route123_Text_JackiIntro: @ 829FF61
	.string "No te pongas a dar botes si tus\n"
	.string "Pokémon desarrollan poderes psíquicos.\p"
	.string "Tienes que perfeccionarlos mucho\n"
	.string "si quieres hacer buen uso de ellos.$"

Route123_Text_JackiDefeat: @ 829FFD8
	.string "¡Prodigioso!$"

Route123_Text_JackiPostBattle: @ 829FFE5
	.string "Todos tenemos poderes psíquicos…\n"
	.string "Simplemente no sabemos cómo usarlos.$"

Route123_Text_JackiRegister: @ 82A0027
	.string "Me gustaría volver a luchar\n"
	.string "contigo. ¿Te apetece?$"

Route123_Text_JackiRematchIntro: @ 82A005E
	.string "¿Has despertado los poderes\n"
	.string "psíquicos que hay en ti?$"

Route123_Text_JackiRematchDefeat: @ 82A008D
	.string "¡Prodigioso!$"

Route123_Text_JackiPostRematch: @ 82A0099
	.string "Esa habilidad tuya con los Pokémon…\n"
	.string "Puede que hasta sea un poder psíquico.$"

Route123_Text_MiuIntro: @ 82A00D6
	.string "Maru: Hola. Espero que tú sepas aceptar\n"
	.string "las derrotas con deportividad, ji, ji…$"

Route123_Text_MiuDefeat: @ 82A0119
	.string "Maru: O-oh, hemos perdido…$"

Route123_Text_MiuPostBattle: @ 82A012E
	.string "Maru: ¿Sabes? Tus Pokémon son\n"
	.string "fuertes porque sois muy amigos.$"

Route123_Text_MiuNotEnoughMons: @ 82A016D
	.string "Maru: No mola nada combatir si no\n"
	.string "tienes dos Pokémon, así que…$"

Route123_Text_YukiIntro: @ 82A01A7
	.string "Yola: ¡No hay escapatoria!\n"
	.string "¡Vamos a machacarte!$"

Route123_Text_YukiDefeat: @ 82A01D8
	.string "Yola: O-oh, hemos perdido…$"

Route123_Text_YukiPostBattle: @ 82A01EE
	.string "Yola: ¿Cómo es que eres tan fuerte?\n"
	.string "No habíamos perdido nunca…$"

Route123_Text_YukiNotEnoughMons: @ 82A0224
	.string "Yola: Nosotras no luchamos si no\n"
	.string "tienes dos Pokémon, se siente…$"

Route123_Text_KindraIntro: @ 82A025F
	.string "El Monte Pírico… Donde duermen los\n"
	.string "espíritus de los Pokémon que han\l"
	.string "partido… ¿Los tuyos también duermen?$"

Route123_Text_KindraDefeat: @ 82A02A6
	.string "Pues no: están la mar de despiertos…$"

Route123_Text_KindraPostBattle: @ 82A02C1
	.string "El Monte Pírico… Donde duermen los\n"
	.string "espíritus de los Pokémon que han\l"
	.string "partido…\p"
	.string "Debe de contener un poder que sosiega\n"
	.string "el alma…$"

Route123_Text_FernandoIntro: @ 82A0323
	.string "¡Mi canto de guerra te\n"
	.string "va a electrificar!$"

Route123_Text_FernandoDefeat: @ 82A035C
	.string "¡Un momento, que todavía\n"
	.string "no había empezado!$"

Route123_Text_FernandoPostBattle: @ 82A0389
	.string "Me gustaría escribir una canción\n"
	.string "sobre tu asombrosa energía.$"

Route123_Text_FernandoRegister: @ 82A03C1
	.string "La próxima vez déjame tocar mi\n"
	.string "canto de guerra entero, ¿vale?$"

Route123_Text_FernandoRematchIntro: @ 82A03FB
	.string "¡Hoy es mi día!\n"
	.string "¡No hará falta ni acabar mi\l"
	.string "canción para desenchufarte!$"

Route123_Text_FernandoRematchDefeat: @ 82A045A
	.string "¡Un momento, que todavía no\n"
	.string "había llegado al estribillo!$"

Route123_Text_FernandoPostRematch: @ 82A0487
	.string "Creía que mi canción te cautivaría\n"
	.string "tanto que no serías capaz de luchar.$"

Route123_Text_DavisIntro: @ 82A04C0
	.string "Éste es mi imponente Pokémon\n"
	.string "Bicho. Me lo ha dado mi hermano.$"

Route123_Text_DavisDefeat: @ 82A04FE
	.string "¡Buaaaaa!\n"
	.string "¡Eso no se hace!$"

Route123_Text_DavisPostBattle: @ 82A0512
	.string "No le digas a mi hermano que he\n"
	.string "perdido. ¡Que quede entre tú y yo!$"

Route123_Text_JazmynIntro: @ 82A054E
	.string "Si venzo a alguien tan fuerte como tú,\n"
	.string "ganaré en confianza.$"

Route123_Text_JazmynDefeat: @ 82A0592
	.string "Adiós a la confianza en mí misma…$"

Route123_Text_JazmynPostBattle: @ 82A05AC
	.string "Todos dicen que no se puede juzgar\n"
	.string "a nadie por su aspecto.\p"
	.string "Pero a veces el aspecto lo dice todo…$"

Route123_Text_FrederickIntro: @ 82A060A
	.string "¡Hola, joven!\n"
	.string "¿Tienes un ratillo?$"

Route123_Text_FrederickDefeat: @ 82A0631
	.string "¡Ah! ¡Juventud, divino tesoro!\n"
	.string "¡Te mereces una recompensa!$"

Route123_Text_FrederickPostBattle: @ 82A0672
	.string "¿Que te dé otra recompensa?\n"
	.string "¿La de antes no te ha bastado?$"

Route123_Text_AlbertoIntro: @ 82A06AF
	.string "Debo reconocerlo: ¡los Pokémon\n"
	.string "Pájaro son mi obsesión!\p"
	.string "¡Los pájaros molan!\n"
	.string "¡Son lo mejor que hay!$"

Route123_Text_AlbertoDefeat: @ 82A0704
	.string "¡Los Pokémon Pájaro molan\n"
	.string "incluso en la derrota!$"

Route123_Text_AlbertoPostBattle: @ 82A072B
	.string "Recojo las plumas que los Pokémon\n"
	.string "Pájaro sueltan durante los combates.\p"
	.string "Me voy a hacer un sombrero con ellas.$"

Route123_Text_EdIntro: @ 82A079B
	.string "Cuando no me encuentro con ningún\n"
	.string "Entrenador, dejo a mis Pokémon\l"
	.string "luchar entre sí. Yo los observo.$"

Route123_Text_EdDefeat: @ 82A07F0
	.string "Me gustan tus Pokémon.$"

Route123_Text_EdPostBattle: @ 82A080D
	.string "¡Je, je, pienso usar tus tácticas!\n"
	.string "Creo que me ayudarán a mejorar.$"

Route123_Text_JonasIntro: @ 82A0854
	.string "¡Te he tendido una emboscada\n"
	.string "y has caído en mis redes!$"

Route123_Text_JonasDefeat: @ 82A088A
	.string "¡Si no te dejas ganar, jugar a\n"
	.string "ser ninja deja de ser divertido!$"

Route123_Text_JonasPostBattle: @ 82A08CA
	.string "Voy a tender una emboscada a un\n"
	.string "Entrenador debilucho la próxima vez.$"

Route123_Text_KayleyIntro: @ 82A0902
	.string "Me acabo de comprar este parasol.\n"
	.string "¡Es lo mejor para proteger la piel!$"

Route123_Text_KayleyDefeat: @ 82A0943
	.string "¡Eres infinitamente mejor que yo!$"

Route123_Text_KayleyPostBattle: @ 82A096E
	.string "Saber usar los accesorios con\n"
	.string "sabiduría es la clave de la victoria.$"

Route124_Text_SpencerIntro: @ 82A09B1
	.string "Oye, ¿te has perdido?\p"
	.string "Si logras vencer a mis Pokémon, te\n"
	.string "ayudaré a encontrar el norte.$"

Route124_Text_SpencerDefeat: @ 82A0A02
	.string "¡Yo sí que he perdido el norte!$"

Route124_Text_SpencerPostBattle: @ 82A0A20
	.string "Mucha gente se pierde en el mar.\p"
	.string "Si es tu caso, deberías consultar\n"
	.string "el Mapa del Pokénav.$"

Route124_Text_RolandIntro: @ 82A0A84
	.string "¡Anda! ¡Montas un Pokémon,\n"
	.string "así no tienes que nadar!\p"
	.string "¡Qué envidia!$"

Route124_Text_RolandDefeat: @ 82A0ACC
	.string "Oh… Así no vale…\n"
	.string "Luchar nadando es más difícil…$"

Route124_Text_RolandPostBattle: @ 82A0AD9
	.string "Me estoy quedando arrugado…\n"
	.string "Llevo demasiado tiempo en el agua…\p"
	.string "Si pudiera montar un Pokémon como tú…$"

Route124_Text_JennyIntro: @ 82A0B37
	.string "Si te quedas flotando en el mar así,\n"
	.string "los Pokémon vienen a jugar contigo.$"

Route124_Text_JennyDefeat: @ 82A0B7C
	.string "Oh…\n"
	.string "Perdida en el mar…$"

Route124_Text_JennyPostBattle: @ 82A0B9A
	.string "Nadando, nadando, me he dado cuenta\n"
	.string "de que hay Pokémon que atacan,\l"
	.string "mientras que otros solo miran…\p"
	.string "Se ve que cada Pokémon tiene una\n"
	.string "personalidad diferente.$"

Route124_Text_JennyRegister: @ 82A0C14
	.string "Tengo un capricho: quiero que\n"
	.string "me registres en tu Pokénav.$"

Route124_Text_JennyRematchIntro: @ 82A0C60
	.string "Si te quedas flotando en el mar así,\n"
	.string "¡los Entrenadores te desafían!$"

Route124_Text_JennyRematchDefeat: @ 82A0CA0
	.string "Esto es rarísimo…\n"
	.string "He vuelto a perder…$"

Route124_Text_JennyPostRematch: @ 82A0CBE
	.string "No es que tenga nada que ver, pero\n"
	.string "creo que voy a ir a la casa Treta.$"

Route124_Text_GraceIntro: @ 82A0D0A
	.string "Estoy harta de nadar.\n"
	.string "¿Y si luchamos un rato?$"

Route124_Text_GraceDefeat: @ 82A0D3D
	.string "¡Si hubiera sabido que eras tan\n"
	.string "fuerte, no habría dicho nada!$"

Route124_Text_GracePostBattle: @ 82A0D66
	.string "Te esfuerzas tanto que ésa debe de\n"
	.string "ser la razón de que seas tan fuerte.$"

Route124_Text_ChadIntro: @ 82A0DA0
	.string "Ja, ja, ja… Buceo hasta el fondo\n"
	.string "para que nadie me vea.\l"
	.string "¡Soy un as del buceo!$"

Route124_Text_ChadDefeat: @ 82A0DFF
	.string "Glu, glu, glu…\n"
	.string "Me hundo…$"

Route124_Text_ChadPostBattle: @ 82A0E1E
	.string "Sé de buena tinta que hay un lugar\n"
	.string "donde hacer Buceo por aquí.\p"
	.string "Me están entrando ganas de ir allí…$"

Route124_Text_LilaIntro: @ 82A0E87
	.string "Rita: Ay…\p"
	.string "Aquí estoy, en medio del mar, ¿y con\n"
	.string "quién? ¡Con el enano de mi hermano!\p"
	.string "¡Estoy tan estresada que tengo\n"
	.string "que combatir con alguien!$"

Route124_Text_LilaDefeat: @ 82A0EFE
	.string "Rita: ¡Saro! ¡Que hayamos perdido\n"
	.string "es culpa tuya! ¡Ya verás luego!$"

Route124_Text_LilaPostBattle: @ 82A0F3A
	.string "Rita: Ay…\p"
	.string "Si en vez de estar con mi hermano,\n"
	.string "estuviera con mis colegas…$"

Route124_Text_LilaNotEnoughMons: @ 82A0F8C
	.string "Rita: ¿Quieres luchar con nosotros?\n"
	.string "¡Pues entonces necesitas más Pokémon!$"

Route124_Text_RoyIntro: @ 82A0FD1
	.string "Saro: Mi hermana mayor es la reina\n"
	.string "de los Pokémon. ¡Ahora verás!$"

Route124_Text_RoyDefeat: @ 82A1012
	.string "Saro: Ay, ay, ay…\n"
	.string "Mi hermana dirá que es culpa mía…$"

Route124_Text_RoyPostBattle: @ 82A103E
	.string "Saro: Mi hermana es un poco abusona\n"
	.string "y da miedo cuando se enfada.\p"
	.string "Ojalá estuviera con mis amigos…$"

Route124_Text_LilaRoyRegister: @ 82A109F
	.string "Saro: ¡Vuelve a luchar con nosotros!\n"
	.string "¡Pero ponnos las cosas más fáciles!$"

Route124_Text_RoyNotEnoughMons: @ 82A10E5
	.string "Saro: ¿Quieres luchar con nosotros?\n"
	.string "¡Pues entonces trae más Pokémon!$"

Route124_Text_LilaRematchIntro: @ 82A111E
	.string "Rita: Ay…\p"
	.string "Aquí estoy, en medio del mar, ¿y con\n"
	.string "quién? ¡Con el enano de mi hermano!\p"
	.string "¡Ah, hola! Mira, estoy tan estresada\n"
	.string "que tengo que luchar con alguien…$"

Route124_Text_LilaRematchDefeat: @ 82A11B2
	.string "Rita: ¡Saro!\n"
	.string "¡Hemos vuelto a perder por tu culpa!\p"
	.string "¡Luego vas a tener una buena sesión\n"
	.string "de entrenamiento, a ver si aprendes!$"

Route124_Text_LilaPostRematch: @ 82A1203
	.string "Rita: Ay…\p"
	.string "Si estuviera con mis colegas, no\n"
	.string "habría rival que se resistiera…$"

Route124_Text_LilaRematchNotEnoughMons: @ 82A1255
	.string "Rita: ¿Quieres luchar con nosotros?\n"
	.string "¡Pues necesitas más Pokémon!$"

Route124_Text_RoyRematchIntro: @ 82A129A
	.string "Saro: Si perdemos, me cae una gorda…\n"
	.string "¡Voy a poner toda la carne en el asador!$"

Route124_Text_RoyRematchDefeat: @ 82A12DD
	.string "Saro: Ay, ay, ay…\n"
	.string "Mi hermana dirá que es culpa mía…$"

Route124_Text_RoyPostRematch: @ 82A130F
	.string "Saro: Mi hermana es un poco abusona\n"
	.string "y da miedo cuando se enfada.\p"
	.string "Seguro que me obliga a entrenar como\n"
	.string "un burro con los Pokémon luego…$"

Route124_Text_RoyRematchNotEnoughMons: @ 82A1384
	.string "Saro: ¿Quieres luchar con nosotros?\n"
	.string "¡Pues entonces trae más Pokémon!$"

Route124_Text_DeclanIntro: @ 82A13BD
	.string "Aquí estoy, nadando más solo que la\n"
	.string "una en este vasto y hermoso mar.\p"
	.string "No hay otro modo de describirlo…\n"
	.string "¡Es para echarse a llorar!$"

Route124_Text_DeclanDefeat: @ 82A142C
	.string "Qué depre tengo…\n"
	.string "Más vasta que el vasto mar…$"

Route124_Text_DeclanPostBattle: @ 82A144F
	.string "Voy a buscar a alguna nadadora\n"
	.string "que quiera flotar un rato conmigo.$"

Route124_Text_IsabellaIntro: @ 82A148E
	.string "Los surfistas me rebotan.\n"
	.string "¡No pienso dejarte ganar!$"

Route124_Text_IsabellaDefeat: @ 82A14BC
	.string "¡Que no! ¡Que no estoy llorando!\n"
	.string "¡Es que me has salpicado!$"

Route124_Text_IsabellaPostBattle: @ 82A14ED
	.string "Por aquí se encuentran trozos\n"
	.string "de cosas de todos los colores.$"

Route125_Text_NolenIntro: @ 82A1527
	.string "Te estaba esperando…\n"
	.string "¡Voy a por ti!$"

Route125_Text_NolenDefeat: @ 82A155A
	.string "¡Esto no estaba previsto!$"

Route125_Text_NolenPostBattle: @ 82A1567
	.string "El sonido viaja más rápido en el agua\n"
	.string "que en el aire. Interesante, ¿eh?$"

Route125_Text_StanIntro: @ 82A159F
	.string "¡Hola, hola!\n"
	.string "¡Mira qué Pokémon tan chulo tengo!$"

Route125_Text_StanDefeat: @ 82A15C7
	.string "No he luchado con ganas…$"

Route125_Text_StanPostBattle: @ 82A15D5
	.string "Me he dejado engatusar por el encanto\n"
	.string "de Horsea, por eso empecé a nadar.$"

Route125_Text_TanyaIntro: @ 82A1615
	.string "Estoy hasta las narices de nadar.\n"
	.string "¿Te apetece luchar contra mí?$"

Route125_Text_TanyaDefeat: @ 82A164D
	.string "¡Eres impresionante!$"

Route125_Text_TanyaPostBattle: @ 82A165E
	.string "Da igual…\n"
	.string "¿Cómo se llega hasta ciudad Algaria?$"

Route125_Text_SharonIntro: @ 82A1686
	.string "¿Estás de humor para enfrentarte\n"
	.string "a mi Pokémon de tipo Agua?$"

Route125_Text_SharonDefeat: @ 82A16C5
	.string "¿He perdido?$"

Route125_Text_SharonPostBattle: @ 82A16CE
	.string "Qué fuerza… No he visto nada igual…\n"
	.string "¡Estoy impresionada!$"

Route125_Text_ErnestIntro: @ 82A16FC
	.string "¡Eh, grumete! Soy un marinero\n"
	.string "muy curtido. ¡Un lobo de mar!$"

Route125_Text_ErnestDefeat: @ 82A173A
	.string "¡Grrrrrrrrrr!\n"
	.string "¡No he logrado derrotarte!$"

Route125_Text_ErnestPostBattle: @ 82A1755
	.string "La marea sube y baja en el interior\n"
	.string "de la Cueva Cardumen.\p"
	.string "¿Sabías que entre la marea alta\n"
	.string "y la baja hay seis horas de diferencia?$"

Route125_Text_ErnestRegister: @ 82A17CF
	.string "Regístrame en tu Pokénav\n"
	.string "y no te arrepentirás.$"

Route125_Text_ErnestRematchIntro: @ 82A180E
	.string "Ya va siendo hora de que me tome\n"
	.string "mi revancha. ¡Ven aquí!$"

Route125_Text_ErnestRematchDefeat: @ 82A1851
	.string "He perdido estrepitosamente…\n"
	.string "Eso es, lisa y llanamente…$"

Route125_Text_ErnestRematchPostBattle: @ 82A187A
	.string "La Cueva Cardumen…\p"
	.string "Hay lugares a los que puedes acceder\n"
	.string "o no según el estado de la marea.\p"
	.string "Ah, recuerda que hay seis horas de\n"
	.string "diferencia entre la marea alta y la baja.$"

Route125_Text_KimIntro: @ 82A192B
	.string "Beth: En la Cueva Cardumen vive un\n"
	.string "anciano la mar de raro. Eso me han dicho.\l"
	.string "¿Vas a ir a verlo tú también?$"

Route125_Text_KimDefeat: @ 82A1989
	.string "Beth: Pensé que ganar era pan comido…$"

Route125_Text_KimPostBattle: @ 82A19A6
	.string "Beth: En la Cueva Cardumen vive un\n"
	.string "anciano la mar de raro, ¿verdad?\p"
	.string "¡Vamos a visitarle, Iris!$"

Route125_Text_KimNotEnoughMons: @ 82A19F8
	.string "Beth: ¡No, no y no! ¡Necesitas tener dos\n"
	.string "Pokémon, si no, no vale!$"

Route125_Text_IrisIntro: @ 82A1A35
	.string "Iris: Beth, ¿me vas a decir de una vez\n"
	.string "adónde quieres ir?$"

Route125_Text_IrisDefeat: @ 82A1A71
	.string "Iris: Uf, pensé que estaría chupado…$"

Route125_Text_IrisPostBattle: @ 82A1A92
	.string "Iris: Beth, ¿de verdad que quieres ir\n"
	.string "a la Cueva Cardumen?\l"
	.string "Mira que nos vamos a mojar…$"

Route125_Text_IrisNotEnoughMons: @ 82A1AD9
	.string "Iris: No, nunca jamás podríamos tener\n"
	.string "un combate de dos contra uno…$"

Route125_Text_PresleyIntro: @ 82A1B1A
	.string "¿Qué hace un ornitólogo como\n"
	.string "yo con el agua hasta el cuello?$"

Route125_Text_PresleyDefeat: @ 82A1B4E
	.string "Vale, te voy a decir qué hago aquí.$"

Route125_Text_PresleyPostBattle: @ 82A1B70
	.string "Voy a meter un mensaje en una\n"
	.string "botella para que se la lleve el mar.\p"
	.string "¡Seguro que la encuentra\n"
	.string "una Nadadora!$"

Route125_Text_AuronIntro: @ 82A1BCE
	.string "¡Oye!\n"
	.string "¿Estabas tirando basura al mar?$"

Route125_Text_AuronDefeat: @ 82A1BFD
	.string "Ah, no, tú eres una persona\n"
	.string "la mar de limpia.$"

Route125_Text_AuronPostBattle: @ 82A1C2A
	.string "Antes he visto una botella\n"
	.string "asquerosa entre las olas.\p"
	.string "¡Me pone de malas pulgas\n"
	.string "la gente que contamina el mar!$"

Route126_Text_BarryIntro: @ 82A1C95
	.string "La natación es el deporte más completo.\n"
	.string "¡Te pones súper en forma!$"

Route126_Text_BarryDefeat: @ 82A1CC8
	.string "¡Vale, vale, sí! ¡Has ganado!$"

Route126_Text_BarryPostBattle: @ 82A1CDD
	.string "Como me hago largos cada día…,\n"
	.string "¡mírame! ¡Estoy hecho un figurín!$"

Route126_Text_DeanIntro: @ 82A1D2A
	.string "Esa alta montaña de roca blanca\n"
	.string "es Arrecípolis.$"

Route126_Text_DeanDefeat: @ 82A1D63
	.string "¡Me dejas hecho polvo!$"

Route126_Text_DeanPostBattle: @ 82A1D72
	.string "No encuentro la entrada a\n"
	.string "Arrecípolis. ¿Dónde estará?$"

Route126_Text_NikkiIntro: @ 82A1DAE
	.string "¡Ji, ji, ji, ji!\n"
	.string "¡Nado como una sirena!$"

Route126_Text_NikkiDefeat: @ 82A1DC8
	.string "Me has dejado más chafada que un\n"
	.string "lenguado… Glu, glu, glu…$"

Route126_Text_NikkiPostBattle: @ 82A1E03
	.string "Vaya paliza me has dado… Quisiera\n"
	.string "que me tragara el mar…$"

Route126_Text_BrendaIntro: @ 82A1E3E
	.string "¡Hola, mequetrefe!\n"
	.string "¿Luchas contra mí?$"

Route126_Text_BrendaDefeat: @ 82A1E63
	.string "¡Oh, nooooo!$"

Route126_Text_BrendaPostBattle: @ 82A1E70
	.string "Me encanta jugar con los Pokémon\n"
	.string "saltando entre las olas…$"

Route126_Text_PabloIntro: @ 82A1EA5
	.string "¡Admira mi escultural cuerpo!\n"
	.string "¡Tengo más músculos que un karateka!$"

Route126_Text_PabloDefeat: @ 82A1EE3
	.string "¡Guau, menudo derroche de fuerza!\n"
	.string "¡No está mal! ¡Pero que nada mal!$"

Route126_Text_PabloPostBattle: @ 82A1F10
	.string "La derrota no me amilana. ¡Pienso\n"
	.string "entrenarme muchísimo más!$"

Route126_Text_PabloRegister: @ 82A1F5A
	.string "¡Oye, no ha estado nada mal!\n"
	.string "¡Me gustaría conocerte mejor!$"

Route126_Text_PabloRematchIntro: @ 82A1F98
	.string "¡Admira mi escultural cuerpo!\n"
	.string "¡Tengo más músculos que un nadador!$"

Route126_Text_PabloRematchDefeat: @ 82A1FD8
	.string "¡Guau, menudo derroche de fuerza!\n"
	.string "¡No está mal! ¡Pero que nada mal!$"

Route126_Text_PabloPostRematch: @ 82A200C
	.string "¡Voy a entrenarme aún más!\n"
	.string "¡Me motivas como nadie!\l"
	.string "¡Tienes que volver por aquí!$"

Route126_Text_LeonardoIntro: @ 82A2063
	.string "No hace mucho que aprendí a nadar,\n"
	.string "pero ya soy todo un Nadador.\p"
	.string "No hay nada que se me resista.$"

Route126_Text_LeonardoDefeat: @ 82A20C6
	.string "Uf, debería haber sido más humilde.$"

Route126_Text_LeonardoPostBattle: @ 82A20F7
	.string "La práctica te ayuda a mejorar.\p"
	.string "Eres joven, así que no dudes\n"
	.string "en probar y experimentar.$"

Route126_Text_IsobelIntro: @ 82A216A
	.string "No hay nada peor que te entre agua\n"
	.string "por la nariz, ¿no estás de acuerdo?$"

Route126_Text_IsobelDefeat: @ 82A21A3
	.string "¡Aj! ¿Por qué…?\n"
	.string "¡Glu, glu, glu!$"

Route126_Text_IsobelPostBattle: @ 82A21B8
	.string "¡Ah, he tragado agua!\n"
	.string "¡Qué salada está!$"

Route126_Text_SiennaIntro: @ 82A21EF
	.string "¡Pienso luchar con todas mis ganas!$"

Route126_Text_SiennaDefeat: @ 82A2216
	.string "¡Tú sí que tenías ganas de ganar!$"

Route126_Text_SiennaPostBattle: @ 82A222A
	.string "Es hora de relajarse…\n"
	.string "Voy a bucear un poco.$"

Route127_Text_CamdenIntro: @ 82A225F
	.string "Se te ve en la cara. Tú quieres\n"
	.string "desafiarme…$"

Route127_Text_CamdenDefeat: @ 82A2294
	.string "Huy, ay, huy, ay, huy…$"

Route127_Text_CamdenPostBattle: @ 82A22A1
	.string "Cuando un combate ha sido bueno,\n"
	.string "me quedo la mar de a gusto…$"

Route127_Text_DonnyIntro: @ 82A22DD
	.string "¿No te pasa a ti que te da mogollón\n"
	.string "de rabia perder?$"

Route127_Text_DonnyDefeat: @ 82A2315
	.string "¡Aaargh! ¡Qué rabia me da!$"

Route127_Text_DonnyPostBattle: @ 82A232C
	.string "¿Esa rabia no te motiva para seguir\n"
	.string "mejorando cada vez más?$"

Route127_Text_JonahIntro: @ 82A2381
	.string "Pescar me da una paz y una serenidad\n"
	.string "increíbles… Mira, vas a ver…$"

Route127_Text_JonahDefeat: @ 82A23E1
	.string "Vale, he perdido, pero sigo tan\n"
	.string "“zen” como siempre…$"

Route127_Text_JonahPostBattle: @ 82A240C
	.string "Me importa un pepino si pesco algo\n"
	.string "o no, yo sigo intentándolo…$"

Route127_Text_HenryIntro: @ 82A2450
	.string "¡Hala! ¡No me digas que ha picado nada\n"
	.string "menos que un Pokémon que hace Surf!$"

Route127_Text_HenryDefeat: @ 82A2483
	.string "¡No puedo con estos Pokémon!$"

Route127_Text_HenryPostBattle: @ 82A2494
	.string "Tus Pokémon parecen bastante fuertes.\n"
	.string "Me vendría de vicio pescar unos así…$"

Route127_Text_RogerIntro: @ 82A24C6
	.string "¡Eh, tú! ¡Éste es un reto entre un fan de\n"
	.string "los Pokémon y un pescador aficionado!$"

Route127_Text_RogerDefeat: @ 82A250B
	.string "¡Oh, no! ¡Se me ha enredado el sedal!\n"
	.string "¡Se acabó la diversión!$"

Route127_Text_RogerPostBattle: @ 82A2538
	.string "¡El sedal se ha puesto a bailar!\n"
	.string "¡El baile del enredo! ¡Ja, ja, ja!$"

Route127_Text_AidanIntro: @ 82A257A
	.string "Los Pokémon Pájaro son capaces de\n"
	.string "ver a sus presas desde gran altura.$"

Route127_Text_AidanDefeat: @ 82A25C1
	.string "Uf… Me rindo…$"

Route127_Text_AidanPostBattle: @ 82A25D2
	.string "Hay un montón de sitios donde bucear\n"
	.string "por aquí cerca.\p"
	.string "Se reconocen rápido por el color del\n"
	.string "agua, que es más oscura que el resto.$"

Route127_Text_KojiIntro: @ 82A264D
	.string "Corre sin zapatillas de deporte.\n"
	.string "¡Las plantas de los pies se te\l"
	.string "pondrán más duras que el granito!$"

Route127_Text_KojiDefeat: @ 82A2685
	.string "¡Au, au, au! ¡Se me ha metido una\n"
	.string "piedrecita en la uña del dedo gordo!$"

Route127_Text_KojiPostBattle: @ 82A26AC
	.string "Me encanta andar descalzo, pero\n"
	.string "tus Deportivas son muy chulas.$"

Route127_Text_KojiRegister: @ 82A26EE
	.string "¡Esto es lo que hago con los que me\n"
	.string "derrotan! Espero volver a verte.$"

Route127_Text_KojiRematchIntro: @ 82A2734
	.string "Sigo corriendo descalzo cada día.\n"
	.string "¡Tengo curtidísimas las plantas\l"
	.string "de los pies!$"

Route127_Text_KojiRematchDefeat: @ 82A276B
	.string "¡Au, au, au! ¡Se me han clavado\n"
	.string "piedrecitas en las plantas de los pies!$"

Route127_Text_KojiPostRematch: @ 82A278E
	.string "¿Quieres descalzarte un rato?\n"
	.string "Así podré probarme tus Deportivas.$"

Route127_Text_AthenaIntro: @ 82A27D0
	.string "Deberíamos enfrentarnos en un\n"
	.string "combate lento y metódico.$"

Route127_Text_AthenaDefeat: @ 82A27FC
	.string "No me has dado la oportunidad\n"
	.string "de usar ninguna estrategia.$"

Route127_Text_AthenaPostBattle: @ 82A2832
	.string "Cuando solo estoy rodeada de mar y\n"
	.string "cielo, siento que el tiempo se detiene.$"

Route128_Text_IsaiahIntro: @ 82A287F
	.string "Ciudad Colosalia todavía\n"
	.string "está muy lejos…$"

Route128_Text_IsaiahDefeat: @ 82A28AB
	.string "Mi primera victoria también parece\n"
	.string "estar muy lejos…$"

Route128_Text_IsaiahPostBattle: @ 82A28D7
	.string "Creo que no he ganado nunca ni de\n"
	.string "casualidad, pero yo sigo dando el callo.$"

Route128_Text_IsaiahRegister: @ 82A2916
	.string "Ahora soy un desastre, pero sé\n"
	.string "que algún día lograré ganar.\p"
	.string "Anda, regístrame en tu Pokénav.$"

Route128_Text_IsaiahRematchIntro: @ 82A2975
	.string "Me siento estupendamente. Voy a seguir\n"
	.string "nadando hasta Ciudad Colosalia.$"

Route128_Text_IsaiahRematchDefeat: @ 82A29B8
	.string "Sigo sin haber saboreado la victoria…$"

Route128_Text_IsaiahPostRematch: @ 82A29DC
	.string "Algún día llegaré a ciudad Colosalia\n"
	.string "y entonces seguro que gano…$"

Route128_Text_KatelynIntro: @ 82A2A1F
	.string "En un triatlón tienes que nadar,\n"
	.string "montar en bici y encima correr…\p"
	.string "Se trata de una feroz carrera que\n"
	.string "combina tres modalidades.$"

Route128_Text_KatelynDefeat: @ 82A2A94
	.string "Un combate Pokémon también\n"
	.string "es feroz…$"

Route128_Text_KatelynPostBattle: @ 82A2AB7
	.string "Ahora me toca montar en Bici, pero…\n"
	.string "estoy por tirar la toalla…$"

Route128_Text_KatelynRegister: @ 82A2AF9
	.string "Será mejor ver el lado positivo de todo\n"
	.string "esto. Volvamos a luchar algún día.$"

Route128_Text_KatelynRematchIntro: @ 82A2B41
	.string "Un triatlón es largo, pero creo que el\n"
	.string "camino para convertirse en Campeón\l"
	.string "Pokémon también es larguísimo…$"

Route128_Text_KatelynRematchDefeat: @ 82A2BAB
	.string "Los combates Pokémon son duros\n"
	.string "y no perdonan…$"

Route128_Text_KatelynPostRematch: @ 82A2BDD
	.string "Deberías plantearte en serio aceptar\n"
	.string "los retos de la Calle Victoria.$"

Route128_Text_AlexaIntro: @ 82A2C1C
	.string "Hemos estado trabajando duro para\n"
	.string "organizar una Liga Pokémon…\p"
	.string "¡No podemos perder ahora!$"

Route128_Text_AlexaDefeat: @ 82A2C79
	.string "¡Pero…!\n"
	.string "¡¿Cómo ha podido pasar?!$"

Route128_Text_AlexaPostBattle: @ 82A2C95
	.string "Después de todo lo que he hecho para\n"
	.string "llegar hasta aquí, no pienso rendirme.$"

Route128_Text_RubenIntro: @ 82A2CD9
	.string "¡No hay entrenador mejor que\n"
	.string "mi menda lerenda!$"

Route128_Text_RubenDefeat: @ 82A2CFE
	.string "¡Esto no ha pasado de verdad!$"

Route128_Text_RubenPostBattle: @ 82A2D0D
	.string "Probablemente no hay entrenador\n"
	.string "que pueda compararse contigo…$"

Route128_Text_WayneIntro: @ 82A2D3D
	.string "Quiero visitar Colosalia, así que\n"
	.string "he atrapado un Pokémon que conoce\l"
	.string "el movimiento Cascada…$"

Route128_Text_WayneDefeat: @ 82A2DA9
	.string "¡Me la he pegado buena!$"

Route128_Text_WaynePostBattle: @ 82A2DBA
	.string "¡Aaaaay! ¿Por qué yoooo?\p"
	.string "¡Mi Pokémon conoce Cascada, pero no\n"
	.string "tengo la medalla del gimnasio de\l"
	.string "Arrecípolis!$"

Route128_Text_HarrisonIntro: @ 82A2E0F
	.string "Pareces asombrosamente fuerte.\n"
	.string "¿Podré hacerme con la victoria?$"

Route128_Text_HarrisonDefeat: @ 82A2E44
	.string "¡Au!\n"
	.string "Supongo que ganar era imposible.$"

Route128_Text_HarrisonPostBattle: @ 82A2E6C
	.string "Hay un montón de entrenadores fuertes\n"
	.string "alrededor de Ciudad Colosalia.\p"
	.string "¿Crees que no merezco estar aquí?$"

Route128_Text_CarleeIntro: @ 82A2EC8
	.string "El sol brilla con mucha fuerza\n"
	.string "por esta zona.$"

Route128_Text_CarleeDefeat: @ 82A2EFA
	.string "No podía ver bien porque el sol\n"
	.string "me había deslumbrado.$"

Route128_Text_CarleePostBattle: @ 82A2F2F
	.string "Me parece que me voy a casa\n"
	.string "a echarme crema protectora.$"

Route129_Text_ChaseIntro: @ 82A2F66
	.string "Éste es mi primer triatlón.\n"
	.string "Huy, qué nervioso estoy…$"

Route129_Text_ChaseDefeat: @ 82A2F9D
	.string "¡Buaaaaaa!\n"
	.string "¡He perdido!$"

Route129_Text_ChasePostBattle: @ 82A2FB9
	.string "Estoy tan, tan nervioso que no voy\n"
	.string "a poder dar lo mejor de mí…$"

Route129_Text_AllisonIntro: @ 82A2FF2
	.string "Estoy en medio de un triatlón, pero\n"
	.string "me puedo parar a luchar un rato…$"

Route129_Text_AllisonDefeat: @ 82A3034
	.string "¡Pensé que sería coser y cantar!$"

Route129_Text_AllisonPostBattle: @ 82A3048
	.string "¿Sabes qué mola más de los triatlones?\p"
	.string "¡Que debes llevar hasta el límite tu\n"
	.string "fuerza y tu resistencia contra\l"
	.string "viento y marea!$"

Route129_Text_ReedIntro: @ 82A30CD
	.string "¡Hola, caracola!\n"
	.string "¡Vamos derechos al asunto!$"

Route129_Text_ReedDefeat: @ 82A30F1
	.string "Vencido. Me han vencido.\n"
	.string "¡Estoy acabado!$"

Route129_Text_ReedPostBattle: @ 82A3114
	.string "Paso de perder más tiempo.\n"
	.string "¡Me voy a casa a olvidarme de todo!$"

Route129_Text_TishaIntro: @ 82A314E
	.string "¿A qué viene tanta prisa?\n"
	.string "Las cosas se hacen despacito y\l"
	.string "con calma…$"

Route129_Text_TishaDefeat: @ 82A317D
	.string "Vaya…\n"
	.string "Yo que estaba aquí tan a gustito…$"

Route129_Text_TishaPostBattle: @ 82A31A6
	.string "¿No te fastidia hacer las cosas\n"
	.string "deprisa y mal?\p"
	.string "Por eso me tomo mi tiempo…$"

Route129_Text_ClarenceIntro: @ 82A3204
	.string "Hacer Surf no es tan fácil\n"
	.string "como parece, ¿verdad?$"

Route129_Text_ClarenceDefeat: @ 82A3239
	.string "Ganar tampoco es fácil.$"

Route129_Text_ClarencePostBattle: @ 82A3252
	.string "¿Que planeas llegar a la Liga Pokémon?\n"
	.string "¡Pues entonces mucha suerte!$"

Route130_Text_RodneyIntro: @ 82A328A
	.string "¡Qué sorpresa! ¡No sabía que los\n"
	.string "Entrenadores salían al mar!\p"
	.string "¡Luchemos para celebrarlo!$"

Route130_Text_RodneyDefeat: @ 82A32E6
	.string "Uf… Eres fuerte, ya lo creo…$"

Route130_Text_RodneyPostBattle: @ 82A3300
	.string "Tus ojos tienen ese brillo propio de los\n"
	.string "que están acostumbrados a aceptar\l"
	.string "retos y salir airosos. ¡Te va muy bien!$"

Route130_Text_KatieIntro: @ 82A3363
	.string "Mi corazón se regocija cuando\n"
	.string "floto entre las suaves olas\l"
	.string "del ancho y profundo mar…$"

Route130_Text_KatieDefeat: @ 82A33AC
	.string "La amplitud de mi derrota se\n"
	.string "pierde en el horizonte…$"

Route130_Text_KatiePostBattle: @ 82A33F5
	.string "Todos los niños del mundo sueñan\n"
	.string "con convertirse en Campeones\l"
	.string "Pokémon algún día. ¡Lógico!$"

Route130_Text_SantiagoIntro: @ 82A343A
	.string "Qué bien se está flotando en el mar…\n"
	.string "Se te olvidan todos los problemas.$"

Route130_Text_SantiagoDefeat: @ 82A346D
	.string "¿Por qué has venido a darme problemas?$"

Route130_Text_SantiagoPostBattle: @ 82A3494
	.string "Nadar, luchar$"

Route131_Text_RichardIntro: @ 82A34C8
	.string "El mar está plagado de Pokémon.\n"
	.string "Así no hay quien nade, uf…$"

Route131_Text_RichardDefeat: @ 82A350D
	.string "Los Pokémon que entrenas tú mismo\n"
	.string "siempre son los más fuertes…$"

Route131_Text_RichardPostBattle: @ 82A353D
	.string "Uf… Uf… No puedo ni con mi alma…\p"
	.string "La ida fue fácil, pero la vuelta…\n"
	.string "¡se me va a salir el higadillo!\p"
	.string "¿Tendré fuerzas para llegar\n"
	.string "hasta la costa?$"

Route131_Text_HermanIntro: @ 82A35C6
	.string "El mar… La mar… El mar…\n"
	.string "El mar es grande hasta aburrir…\l"
	.string "¡Y yo estoy hasta las narices!$"

Route131_Text_HermanDefeat: @ 82A3626
	.string "¡Noooo!$"

Route131_Text_HermanPostBattle: @ 82A362D
	.string "Estoy aburridísimo, pero debo seguir…\p"
	.string "¡Soy un nadador nato!\n"
	.string "¡No sé hacer otra cosa!$"

Route131_Text_SusieIntro: @ 82A367B
	.string "¡Hola, hola, hola…!\n"
	.string "¿Te hace un combatito?$"

Route131_Text_SusieDefeat: @ 82A36AB
	.string "¡No pareces gran cosa, pero\n"
	.string "das mucha guerra!$"

Route131_Text_SusiePostBattle: @ 82A36D6
	.string "¿Has hablado con este chico que no\n"
	.string "para de quejarse todo el rato?\p"
	.string "Es todo de boquilla.\n"
	.string "¡En realidad le gusta el mar más\l"
	.string "que a un niño una piruleta!$"

Route131_Text_KaraIntro: @ 82A3751
	.string "¿Por qué me mirará tanto todo\n"
	.string "el mundo?\p"
	.string "¿Será por mi gran estilo nadando?$"

Route131_Text_KaraDefeat: @ 82A378A
	.string "¡Me he quedado sin aliento!$"

Route131_Text_KaraPostBattle: @ 82A379F
	.string "Pues, si no es por mi fabuloso estilo…,\n"
	.string "¡será por mi brillante personalidad!$"

Route131_Text_ReliIntro: @ 82A37E9
	.string "Ruth: ¡Como mellizos que somos,\n"
	.string "luchamos juntos hasta el final!$"

Route131_Text_ReliDefeat: @ 82A381F
	.string "Ruth: A pesar de trabajar en equipo,\n"
	.string "no hemos conseguido ganar…$"

Route131_Text_ReliPostBattle: @ 82A3855
	.string "Ruth: La gente de Oromar vive\n"
	.string "por y para el mar y los Pokémon…$"

Route131_Text_ReliNotEnoughMons: @ 82A38B7
	.string "Ruth: ¿No tienes dos Pokémon?\n"
	.string "Pues entonces no podemos luchar…$"

Route131_Text_IanIntro: @ 82A38F8
	.string "Igor: Mi hermana y yo lo hacemos\n"
	.string "lo mejor que podemos.$"

Route131_Text_IanDefeat: @ 82A3925
	.string "Igor: Lo hicimos lo mejor que pudimos,\n"
	.string "pero aun así perdimos…$"

Route131_Text_IanPostBattle: @ 82A3960
	.string "Igor: ¿Sabías que Oromar es\n"
	.string "una ciudad flotante?\p"
	.string "¡Por eso todo lo que concierne al\n"
	.string "mar es parte de Oromar!$"

Route131_Text_IanNotEnoughMons: @ 82A39CD
	.string "Igor: Si traes dos Pokémon,\n"
	.string "lucharemos contigo.$"

Route131_Text_TaliaIntro: @ 82A39FE
	.string "¡Si ganas, te daré una información\n"
	.string "que vale su peso en oro!$"

Route131_Text_TaliaDefeat: @ 82A3A38
	.string "¿Eh?\n"
	.string "¿He perdido?$"

Route131_Text_TaliaPostBattle: @ 82A3A48
	.string "Cerca de aquí hay un lugar muy extraño.\n"
	.string "Allí se alza una torre gigantesca.\l"
	.string "¿Por qué no vas a echar un vistazo?$"

Route131_Text_KevinIntro: @ 82A3AA0
	.string "Los habitantes de Oromar son\n"
	.string "de lo más pacífico que hay.\p"
	.string "No se enfadan ni a la de tres.\n"
	.string "De hecho, yo también soy así.$"

Route131_Text_KevinDefeat: @ 82A3AFC
	.string "Me has dejado “plisplado”.$"

Route131_Text_KevinPostBattle: @ 82A3B02
	.string "¡Bah! Eh, un momento…\n"
	.string "No estoy enfadado, ¡en serio!\p"
	.string "¡Pero lo tuyo es fuerza y lo demás\n"
	.string "son tonterías! ¡Ja, ja, ja!$"

Route132_Text_GilbertIntro: @ 82A3B4C
	.string "Cuando era pequeñito, me resfriaba\n"
	.string "cada dos por tres, pero desde que\l"
	.string "nado, no pillo ni uno.$"

Route132_Text_GilbertDefeat: @ 82A3BAC
	.string "Ojalá fuera más fuerte que esto…$"

Route132_Text_GilbertPostBattle: @ 82A3BC0
	.string "Los entrenadores viajan por valles\n"
	.string "y montañas. ¡Deben estar en forma!$"

Route132_Text_DanaIntro: @ 82A3C04
	.string "Nunca nado en los sitios donde\n"
	.string "hay demasiada corriente.$"

Route132_Text_DanaDefeat: @ 82A3C39
	.string "¡Qué requetemal…!$"

Route132_Text_DanaPostBattle: @ 82A3C49
	.string "Si se me llevara la corriente, creo\n"
	.string "que pasaría un mal rato…$"

Route132_Text_RonaldIntro: @ 82A3C7F
	.string "Victoria o derrota… ¡Si no lo intentas,\n"
	.string "no sabrás el resultado!$"

Route132_Text_RonaldDefeat: @ 82A3CAD
	.string "¡Aaaaaah!\n"
	.string "¡Me hundo en la derrota!$"

Route132_Text_RonaldPostBattle: @ 82A3CC5
	.string "Nunca lucho si tengo claro que voy a\n"
	.string "ganar. Lo que me gusta es la emoción\l"
	.string "de la incertidumbre…$"

Route132_Text_KiyoIntro: @ 82A3D26
	.string "Estoy con mi Pokémon las 24 horas\n"
	.string "del día. ¿Cómo pretendes que pierda?$"

Route132_Text_KiyoDefeat: @ 82A3D6C
	.string "¿He perdido…?\n"
	.string "Vaya ridículo que he hecho…$"

Route132_Text_KiyoPostBattle: @ 82A3D8B
	.string "Brrr…\n"
	.string "Tú eres un fan de los Pokémon, ¿eh?\p"
	.string "Tú sí que pasas cada segundo del día\n"
	.string "con tus Pokémon, ¿eh?$"

Route132_Text_MakaylaIntro: @ 82A3DF0
	.string "Siempre lucho junto a mi marido,\n"
	.string "pero podría ganar sin su ayuda.$"

Route132_Text_MakaylaDefeat: @ 82A3E2C
	.string "Oh, parece que la unión hace la fuerza.$"

Route132_Text_MakaylaPostBattle: @ 82A3E4E
	.string "Allí hay un muchacho que es idéntico\n"
	.string "a mi marido de joven.\p"
	.string "¡Ah, cómo pasa el tiempo!$"

Route132_Text_JonathanIntro: @ 82A3EAC
	.string "Hay alguien que no me quita\n"
	.string "ojo de encima. ¿Eres tú?$"

Route132_Text_JonathanDefeat: @ 82A3EDD
	.string "¡Guau!\n"
	.string "¡Menuda exhibición de fuerza!$"

Route132_Text_JonathanPostBattle: @ 82A3F03
	.string "Esta sensación de que hay alguien\n"
	.string "observándote es agobiante.\p"
	.string "¡Así no hay quien se concentre!$"

Route132_Text_PaxtonIntro: @ 82A3F4F
	.string "¿Adónde se habrá ido mi mujercita?\n"
	.string "Siempre luchamos juntos.\l"
	.string "Me pregunto si podré ganar yo solo…$"

Route132_Text_PaxtonDefeat: @ 82A3FA8
	.string "Ya veo que yo solo no\n"
	.string "llego a ninguna parte.$"

Route132_Text_PaxtonPostBattle: @ 82A3FE5
	.string "Seguro que mi mujer me está\n"
	.string "buscando. Me voy con ella.$"

Route132_Text_DarcyIntro: @ 82A4026
	.string "Con lo que me gusta entrenar a solas…\n"
	.string "¿Por qué habrá venido tanta gente?$"

Route132_Text_DarcyDefeat: @ 82A406E
	.string "Vale, no volveré a quejarme.\n"
	.string "Se acabó ser tan asocial.$"

Route132_Text_DarcyPostBattle: @ 82A40A4
	.string "Me voy a asociar a ese señor\n"
	.string "para desafiar al otro equipo.$"

Route133_Text_FranklinIntro: @ 82A40F0
	.string "¿Te ha arrastrado la corriente hasta\n"
	.string "aquí? Es el destino… ¡A luchar!$"

Route133_Text_FranklinDefeat: @ 82A413F
	.string "¡Eres fuerte!\n"
	.string "¡Incluso demasiado!$"

Route133_Text_FranklinPostBattle: @ 82A4154
	.string "Sólo a mí me tenía que tocar alguien\n"
	.string "tan fuerte como tú en un combate…\l"
	.string "Estoy gafado…$"

Route133_Text_DebraIntro: @ 82A41A8
	.string "Llevo una vida de trotamundos…\n"
	.string "Al final he acabado en este lugar…$"

Route133_Text_DebraDefeat: @ 82A4200
	.string "Vaya, me has derrotado…$"

Route133_Text_DebraPostBattle: @ 82A420E
	.string "Vagando, siempre vagando…\n"
	.string "¡Creo que voy a asentarme de una vez!$"

Route133_Text_LindaIntro: @ 82A4236
	.string "¡Hola!\n"
	.string "¡Te estaba esperando!$"

Route133_Text_LindaDefeat: @ 82A4258
	.string "¡Ya vale!\n"
	.string "¡Déjame en paz!$"

Route133_Text_LindaPostBattle: @ 82A4264
	.string "Alguien tan joven y tan fuerte…\n"
	.string "Me entra la depre…$"

Route133_Text_WarrenIntro: @ 82A4290
	.string "Yo nado como todo quisqui, pero soy\n"
	.string "el más original entrenando Pokémon.$"

Route133_Text_WarrenDefeat: @ 82A42E0
	.string "¡Jarl!\n"
	.string "¡Estoy en la cuerda floja!$"

Route133_Text_WarrenPostBattle: @ 82A4304
	.string "Es mucho más original hacer las cosas\n"
	.string "a tu modo en vez de como todo el mundo.\l"
	.string "¡Qué perogrullada acabo de soltar!$"

Route133_Text_BeckIntro: @ 82A436A
	.string "He llegado hasta aquí a lomos de mi\n"
	.string "Pokémon Pájaro.$"

Route133_Text_BeckDefeat: @ 82A439C
	.string "Tu estilo…\n"
	.string "¡es asombrosamente guay!$"

Route133_Text_BeckPostBattle: @ 82A43B9
	.string "Quisiera volver a Arborada, pero\n"
	.string "le he cogido cariño a este lugar.$"

Route133_Text_MollieIntro: @ 82A4401
	.string "He combatido tantísimas veces\n"
	.string "que he perdido la cuenta.$"

Route133_Text_MollieDefeat: @ 82A443A
	.string "Habré combatido miles y miles de veces,\n"
	.string "pero perder me sigue fastidiando igual.$"

Route133_Text_MolliePostBattle: @ 82A4477
	.string "Sigue así, joven. Algún día serás tan\n"
	.string "notable como mi marido y yo.$"

Route133_Text_ConorIntro: @ 82A44BA
	.string "Los jóvenes siempre se dejan llevar. Ni\n"
	.string "planifican ni siguen un rumbo preciso.$"

Route133_Text_ConorDefeat: @ 82A4505
	.string "Tú pareces tener las cosas claras.$"

Route133_Text_ConorPostBattle: @ 82A4527
	.string "No te dejes influir por los demás.\n"
	.string "Sé coherente con tus convicciones.$"

Route134_Text_JackIntro: @ 82A4571
	.string "Incluso los Pokémon que saben nadar\n"
	.string "son arrastrados por las corrientes.$"

Route134_Text_JackDefeat: @ 82A45BB
	.string "¡La marea me arrastra!$"

Route134_Text_JackPostBattle: @ 82A45C5
	.string "Los Pokémon disfrutan en los rápidos,\n"
	.string "pero las corrientes son peligrosas…$"

Route134_Text_LaurelIntro: @ 82A4609
	.string "Mis Luvdisc buscan un rival divertido.\n"
	.string "¿Serás tú?…$"

Route134_Text_LaurelDefeat: @ 82A4643
	.string "¡Oy, oy, oy!$"

Route134_Text_LaurelPostBattle: @ 82A464B
	.string "Hay un coleccionista que busca\n"
	.string "Escamas de Luvdisc, ¿sabías?$"

Route134_Text_AlexIntro: @ 82A4682
	.string "¡Okey, makey! ¡Ya vale de gandulear!\n"
	.string "¡Hay que ponerse a luchar!$"

Route134_Text_AlexDefeat: @ 82A46BE
	.string "Me han dejado para el arrastre…$"

Route134_Text_AlexPostBattle: @ 82A46D2
	.string "Mi Pokémon Pájaro se cansa mucho\n"
	.string "cada vez que vuela una gran distancia…$"

Route134_Text_HitoshiIntro: @ 82A4709
	.string "Tú entrenas Pokémon.\n"
	.string "No digas nada. Sólo pelea.$"

Route134_Text_HitoshiDefeat: @ 82A4745
	.string "Eh… Esto…\n"
	.string "Mejor me callo…$"

Route134_Text_HitoshiPostBattle: @ 82A475D
	.string "Te he desafiado yo y sin embargo\n"
	.string "he perdido. Una vergüenza…$"

Route134_Text_AaronIntro: @ 82A479E
	.string "La fuerte marea de esta zona te\n"
	.string "ayuda a ser cada vez más fuerte.$"

Route134_Text_AaronDefeat: @ 82A47E1
	.string "Sí, ya sé, he perdido.$"

Route134_Text_AaronPostBattle: @ 82A47FD
	.string "Iremos a entrenarnos en serio\n"
	.string "a la Cascada Meteoro.\p"
	.string "Quizás incluso a ti te vendría bien.\n"
	.string "¡Seguro que te haces más fuerte!$"

Route134_Text_KelvinIntro: @ 82A4875
	.string "¡Nu-nuestro barco!\n"
	.string "¡Se lo ha llevado la marea!$"

Route134_Text_KelvinDefeat: @ 82A489B
	.string "¡Auaaaaaaa!\n"
	.string "¡Para, para, por favor!$"

Route134_Text_KelvinPostBattle: @ 82A48BD
	.string "Si no podemos hacer Surf,\n"
	.string "¿cómo vamos a volver a casa?\p"
	.string "Creo que un Pokémon debilitado aún\n"
	.string "puede surfear, pero me parece un abuso.$"

Route134_Text_MarleyIntro: @ 82A4937
	.string "¿Crees que tus Pokémon podrán evitar\n"
	.string "nuestros velocísimos ataques?$"

Route134_Text_MarleyDefeat: @ 82A496B
	.string "¡Has usado una técnica desconocida\n"
	.string "para mí! ¡La derrota ha sido total!$"

Route134_Text_MarleyPostBattle: @ 82A49B1
	.string "Me sigue apasionando la velocidad.\n"
	.string "Me entrenaré con más ardor.$"

Route134_Text_ReynaIntro: @ 82A49E9
	.string "¡No se puede derrotar a mis\n"
	.string "Pokémon fácilmente!$"

Route134_Text_ReynaDefeat: @ 82A4A10
	.string "Esto tiene que ser una broma.\n"
	.string "¡Dime cómo puedo haber perdido!$"

Route134_Text_ReynaPostBattle: @ 82A4A34
	.string "¡Ja, ja, ja!\n"
	.string "¡Has ganado, ya lo creo!\p"
	.string "¡Pero volveré a la cima! ¡Lucharé con\n"
	.string "todos los Entrenadores que vea!$"

Route134_Text_HudsonIntro: @ 82A4A8F
	.string "Dime, ¿has visto a algún otro\n"
	.string "Marinero por aquí?$"

Route134_Text_HudsonDefeat: @ 82A4AC1
	.string "¡Vaya, tú no te andas por las ramas!$"

Route134_Text_HudsonPostBattle: @ 82A4AD8
	.string "La marea se ha llevado nuestro barco.\p"
	.string "Mi compañero es un pelín apocado,\n"
	.string "así que me tiene preocupado.$"
