gTrickHouse_Mechadoll_Oddish:: @ 27ECBC
	.string "Oddish$"

gTrickHouse_Mechadoll_Poochyena:: @ 27ECC3
	.string "Poochyena$"

gTrickHouse_Mechadoll_Taillow:: @ 27ECCD
	.string "Taillow$"

gTrickHouse_Mechadoll_Azurill:: @ 27ECD5
	.string "Azurill$"

gTrickHouse_Mechadoll_Lotad:: @ 27ECDD
	.string "Lotad$"

gTrickHouse_Mechadoll_Wingull:: @ 27ECE3
	.string "Wingull$"

gTrickHouse_Mechadoll_Dustox:: @ 27ECEB
	.string "Dustox$"

gTrickHouse_Mechadoll_Zubat:: @ 27ECF2
	.string "Zubat$"

gTrickHouse_Mechadoll_Nincada:: @ 27ECF8
	.string "Nincada$"

gTrickHouse_Mechadoll_Ralts:: @ 27ED00
	.string "Ralts$"

gTrickHouse_Mechadoll_Zigzagoon:: @ 27ED06
	.string "Zigzagoon$"

gTrickHouse_Mechadoll_Slakoth:: @ 27ED10
	.string "Slakoth$"

gTrickHouse_Mechadoll_Poochyena2:: @ 27ED18
	.string "Poochyena$"

gTrickHouse_Mechadoll_Shroomish:: @ 27ED22
	.string "Shroomish$"

gTrickHouse_Mechadoll_Zigzagoon2:: @ 27ED2C
	.string "Zigzagoon$"

gTrickHouse_Mechadoll_Poochyena3:: @ 27ED36
	.string "Poochyena$"

gTrickHouse_Mechadoll_Zubat2:: @ 27ED40
	.string "Zubat$"

gTrickHouse_Mechadoll_Carvanha:: @ 27ED46
	.string "Carvanha$"

gTrickHouse_Mechadoll_BurnHeal:: @ 27ED4F
	.string "Antiquemar$"

gTrickHouse_Mechadoll_HarborMail:: @ 27ED59
	.string "Cartas Puerto$"

gTrickHouse_Mechadoll_SamePrice:: @ 27ED65
	.string "Cuestan lo mismo.$"

gTrickHouse_Mechadoll_60Yen:: @ 27ED70
	.string "60¥$"

gTrickHouse_Mechadoll_55Yen:: @ 27ED74
	.string "55¥$"

gTrickHouse_Mechadoll_Nothing:: @ 27ED78
	.string "Nada.$"

gTrickHouse_Mechadoll_CostMore:: @ 27ED80
	.string "Cuestan más.$"

gTrickHouse_Mechadoll_CostLess:: @ 27ED95
	.string "Cuestan menos.$"

gTrickHouse_Mechadoll_SamePrice2:: @ 27EDAA
	.string "Cuestan lo mismo.$"

gTrickHouse_Mechadoll_Male:: @ 27EDB5
	.string "Más hombres.$"

gTrickHouse_Mechadoll_Female:: @ 27EDBA
	.string "Más mujeres.$"

gTrickHouse_Mechadoll_Neither:: @ 27EDC1
	.string "Igual.$"

gTrickHouse_Mechadoll_ElderlyMen:: @ 27EDC9
	.string "Ancianos.$"

gTrickHouse_Mechadoll_ElderlyLadies:: @ 27EDD5
	.string "Ancianas.$"

gTrickHouse_Mechadoll_SameNumber:: @ 27EDE4
	.string "El mismo número.$"

gTrickHouse_Mechadoll_None:: @ 27EDF0
	.string "Ninguno.$"

gTrickHouse_Mechadoll_One:: @ 27EDF5
	.string "1$"

gTrickHouse_Mechadoll_Two:: @ 27EDF7
	.string "2$"

gTrickHouse_Mechadoll_Two2:: @ 27EDF9
	.string "2$"

gTrickHouse_Mechadoll_Three:: @ 27EDFB
	.string "3$"

gTrickHouse_Mechadoll_Four:: @ 27EDFD
	.string "4$"

gTrickHouse_Mechadoll_Six:: @ 27EDFF
	.string "6$"

gTrickHouse_Mechadoll_Seven:: @ 27EE01
	.string "7$"

gTrickHouse_Mechadoll_Eight:: @ 27EE03
	.string "8$"

gTrickHouse_Mechadoll_Six2:: @ 27EE05
	.string "6$"

gTrickHouse_Mechadoll_Seven2:: @ 27EE07
	.string "7$"

gTrickHouse_Mechadoll_Eight2:: @ 27EE09
	.string "8$"
