LilycoveCity_ContestLobby_Text_InterviewRequest: @ 827EF15
	.string "¡Hola! Tú has participado en un\n"
	.string "Concurso Pokémon, ¿verdad?\l"
	.string "Se ve por los Pokémon que tienes.\p"
	.string "Soy reportero. Trabajo en una historia\n"
	.string "sobre los ConcursoS Pokémon.\p"
	.string "¿Podría hacerte unas preguntas?$"

LilycoveCity_ContestLobby_Text_DescribeContest: @ 827EFE7
	.string "¿Sí?\n"
	.string "Muchas gracias.\p"
	.string "¿Podrías describirme el Concurso\n"
	.string "en el que has participado?$"

LilycoveCity_ContestLobby_Text_WhatImageWhenYouHearX: @ 827F03E
	.string "Ajá, entiendo.\n"
	.string "Un comentario muy edificante.\p"
	.string "Te haces una buena idea de lo\n"
	.string "que fue el Concurso.\p"
	.string "Tengo otra pregunta…\p"
	.string "Cuando oyes la palabra “{STR_VAR_2}”,\n"
	.string "¿qué te pasa por la mente?$"

LilycoveCity_ContestLobby_Text_ThatsAllForInterview: @ 827F0EC
	.string "Ya veo.\p"
	.string "Así que imaginas el concepto de\n"
	.string "“{STR_VAR_2}” así…\p"
	.string "¡Gracias!\n"
	.string "Resulta inspirador.\p"
	.string "Creo que puedo escribir una buena\n"
	.string "historia sobre los ConcursoS Pokémon.\p"
	.string "Y quizás, solo quizás, esta historia\n"
	.string "llegue a salir en la tele.\l"
	.string "¡Espero que no te la pierdas si sale!$"

LilycoveCity_ContestLobby_Text_PleaseDoShareStoryWithMe: @ 827F1EF
	.string "Oh, qué decepción…\p"
	.string "Bueno, si te encuentras con una buena\n"
	.string "historia, ven a contármela, porfa.$"

LilycoveCity_ContestLobby_Text_LookingForwardToNextContest: @ 827F23F
	.string "Estoy deseando que participes en\n"
	.string "otro Concurso Pokémon.$"

gTVBravoTrainerText00::
	.string "¡Queridos televidentes!\n"
	.string "¡Es la hora del entrenador estrella!\p"
	.string "¡Hoy vamos a presentaros el perfil\n"
	.string "de uno de los Pokémon de {STR_VAR_1}!\p"
	.string "¡Dicho Pokémon logró sobresalir en\n"
	.string "{STR_VAR_2} en el nivel {STR_VAR_3}!$"

gTVBravoTrainerText01::
	.string "¡Más datos sobre {STR_VAR_2},\n"
	.string "el Pokémon {STR_VAR_1}!\p"
	.string "{STR_VAR_2}… ¡Vaya mote!\p"
	.string "¡Sin duda alguna, es un mote que por sí\n"
	.string "solo evoca “{STR_VAR_3}”!$"

gTVBravoTrainerText02::
	.string "Pero lo mejor es que cuando {STR_VAR_1}\n"
	.string "presentó el Pokémon al Concurso,\l"
	.string "nos las arreglamos para conseguir\l"
	.string "unas apasionadas declaraciones.$"

gTVBravoTrainerText03::
	.string "Una vez finalizado el Concurso,\n"
	.string "{STR_VAR_1} nos dijo “¡{STR_VAR_2}!”\l"
	.string "con una enorme sonrisa.\p"
	.string "Nada más natural, pues el Pokémon de\n"
	.string "{STR_VAR_1} quedó en el puesto {STR_VAR_3}\l"
	.string "del Concurso.\p"
	.string "Esa declaración es ideal para {STR_VAR_1}\n"
	.string "en estos momentos, está claro.$"

gTVBravoTrainerText04::
	.string "Una vez finalizado el Concurso,\n"
	.string "{STR_VAR_1} nos dijo “{STR_VAR_2}”\l"
	.string "con cierto tono de amargura.\p"
	.string "Nada más natural, pues el Pokémon de\n"
	.string "{STR_VAR_1} quedó en el puesto {STR_VAR_3}\l"
	.string "del Concurso.\p"
	.string "{STR_VAR_1} ha expresado su decepción\n"
	.string "con mucho acierto, está claro.$"

gTVBravoTrainerText05::
	.string "¿No os gustaría saber también qué\n"
	.string "piensa {STR_VAR_1} que es {STR_VAR_2}?\p"
	.string "¡A nosotros sí!\n"
	.string "¡Por eso se lo preguntamos!\p"
	.string "Y la respuesta es muy clara:\n"
	.string "“¡{STR_VAR_3}!”.\p"
	.string "Eso es lo que el concepto de {STR_VAR_2}\n"
	.string "representa para {STR_VAR_1}.$"

gTVBravoTrainerText06::
	.string "El último movimiento {STR_VAR_2} que\n"
	.string "usó {STR_VAR_1} es la viva expresión\l"
	.string "de “{STR_VAR_3}”.$"

gTVBravoTrainerText07::
	.string "¡Bravo, {STR_VAR_1}!\n"
	.string "¡Bravo, {STR_VAR_2}!\p"
	.string "¡Confío en que podamos ver a\n"
	.string "{STR_VAR_1} subir a lo más alto!\p"
	.string "¡Esto es todo por hoy!\n"
	.string "¡Nos despedimos hasta la próxima!$"

gTVBravoTrainerText08::
	.string "¡Más datos sobre {STR_VAR_1}!$"

BattleFrontier_BattleTowerLobby_Text_InterviewRequest::
	.string "¡Hola! Tú acabas de tener un combate\n"
	.string "Pokémon, ¿me equivoco?\p"
	.string "Estoy entrevistando a todos los\n"
	.string "Entrenadores de la zona.\p"
	.string "¿Podrías compartir tus impresiones de\n"
	.string "la lucha con nosotros?$"

BattleFrontier_BattleTowerLobby_Text_HowDidBattleTowerTurnOut::
	.string "¿Sí? ¿En serio?\n"
	.string "¡Gracias!\l"
	.string "Entonces, a ver…\p"
	.string "¿Qué tal te ha ido hoy en la\n"
	.string "Torre Batalla?\p"
	.string "¿Estás alegre por el resultado del\n"
	.string "combate? ¿O más bien triste?$"

BattleFrontier_BattleTowerLobby_Text_SorryWeDisturbedYou::
	.string "Oh, lástima…\n"
	.string "Siento haberte molestado.\p"
	.string "Pero me gustaría que te dejaras\n"
	.string "entrevistar la próxima vez que\l"
	.string "vengas a la Torre Batalla.$"

BattleFrontier_BattleTowerLobby_Text_ObviousYouHadGreatBattle::
	.string "¡Pues claro que sí!\p"
	.string "Tienes una mirada de completa\n"
	.string "satisfacción en el rostro…\p"
	.string "Obviamente, has disfrutado de\n"
	.string "un gran combate…$"

BattleFrontier_BattleTowerLobby_Text_DifficultToMakeBattleTurnOutAsPlanned::
	.string "Ajá, ya veo…\p"
	.string "Bueno, no es fácil que un combate\n"
	.string "te salga como esperabas…$"

BattleFrontier_BattleTowerLobby_Text_DescribeYourBattle::
	.string "Ah, ah, ¿puedo preguntarte otra cosa?\p"
	.string "Si tuvieras que describir tus\n"
	.string "impresiones del combate con una\l"
	.string "expresión, ¿qué dirías?$"

BattleFrontier_BattleTowerLobby_Text_ThatsGreatLine::
	.string "Vaya, ¡es asombrosamente guay!\p"
	.string "¡Qué respuesta tan memorable!\n"
	.string "Espero que te siga yendo igual de bien.\p"
	.string "¡Y espero volver a verte!$"

BattleFrontier_BattleTowerLobby_Text_SilentType::
	.string "Ajá, ya veo…\p"
	.string "En fin, no decir ni mu te da un aire\n"
	.string "misterioso muy guay también.\p"
	.string "¡Pero espero que algún día me dejes\n"
	.string "compartir tus pensamientos!$"

BattleFrontier_BattleTowerLobby_Text_LookingForwardToNextBattle::
	.string "¡Estoy deseando asistir a tu\n"
	.string "próximo combate!$"

BravoTrainerBattleTower_Text_Intro::
	.string "¡Queridos televidentes!\n"
	.string "¡Es la hora del entrenador estrella!\p"
	.string "¡Hoy contamos con el perfil de {STR_VAR_1},\n"
	.string "que ha aceptado el terrible desafío\l"
	.string "de la Torre Batalla!\p"
	.string "{STR_VAR_1} luchó con su feroz {STR_VAR_2}.$"

BravoTrainerBattleTower_Text_NewRecord::
	.string "La pareja estableció un nuevo récord\n"
	.string "de {STR_VAR_2} victorias seguidas en el\l"
	.string "{STR_VAR_1} de la competición.\l"
	.string "¡Impresionante!$"

BravoTrainerBattleTower_Text_Lost::
	.string "Ambos acabaron por caer ante\n"
	.string "{STR_VAR_1} en el combate número {STR_VAR_2}.\l"
	.string "Fue una pelea muy reñida.\p"
	.string "Es simplemente mala suerte enfrentarse\n"
	.string "a {STR_VAR_1} tan pronto en la serie\l"
	.string "de combates clasificatorios…\p"
	.string "Pedimos que nos hiciera partícipes de\n"
	.string "sus impresiones con respecto a\l"
	.string "la lucha contra {STR_VAR_1}.$"

BravoTrainerBattleTower_Text_Won::
	.string "El dúo obtuvo una aplastante victoria\n"
	.string "contra el {STR_VAR_2} de {STR_VAR_1}.\l"
	.string "¡Bravo!\p"
	.string "Derrotar a {STR_VAR_1}…\n"
	.string "Desafía toda lógica. Es algo increíble.\p"
	.string "Pedimos que nos hiciera partícipes de\n"
	.string "sus impresiones en este momento\l"
	.string "glorioso de su carrera.$"

BravoTrainerBattleTower_Text_LostFinal::
	.string "Tras una serie de victorias, la pareja\n"
	.string "sucumbió ante el {STR_VAR_2} de\l"
	.string "{STR_VAR_1}, un obstáculo insalvable.\p"
	.string "¡Fue una pelea muy reñida!\p"
	.string "Sin embargo, tiene su mérito, pues no\n"
	.string "se suelen encontrar combinaciones\l"
	.string "como la de {STR_VAR_1} y {STR_VAR_2}.\p"
	.string "Pedimos que nos hiciera partícipes de\n"
	.string "sus impresiones sobre el combate\l"
	.string "contra este célebre dúo.$"

BravoTrainerBattleTower_Text_Satisfied::
	.string "Esto es lo que nos dijo:\n"
	.string "“¡Ha estado bien!”.\p"
	.string "¡Es lo que llamo una respuesta\n"
	.string "positiva! ¡Bravo!\p"
	.string "¿No es simplemente extraordinario\n"
	.string "poder combatir a tu gusto?\p"
	.string "En cualquier caso, supe lo bien que se\n"
	.string "sentía cuando oí lo siguiente:$"

BravoTrainerBattleTower_Text_Unsatisfied::
	.string "Esto es lo que nos dijo:\n"
	.string "“Ha estado mal…”.\p"
	.string "Era presa del decaimiento mientras\n"
	.string "hacía estas declaraciones. Es natural…\p"
	.string "Aun así, ningún combate puede estar\n"
	.string "nunca bien del todo, ¿no es cierto?\p"
	.string "En cualquier caso, supe lo mal que se\n"
	.string "sentía cuando oí lo siguiente:$"

BravoTrainerBattleTower_Text_None1::
	.string "Nada$"

BravoTrainerBattleTower_Text_None2::
	.string "Nada$"

BravoTrainerBattleTower_Text_None3::
	.string "Nada$"

BravoTrainerBattleTower_Text_None4::
	.string "Nada$"

BravoTrainerBattleTower_Text_Response::
	.string "“{STR_VAR_1}”.$"

BravoTrainerBattleTower_Text_ResponseSatisfied::
	.string "“{STR_VAR_1}”.\n"
	.string "¿No es genial?\p"
	.string "En mi opinión expresa toda la alegría\n"
	.string "que siente {STR_VAR_2}.\p"
	.string "Ese combate contra {STR_VAR_3}\n"
	.string "al final… Es lo que se llama un\l"
	.string "“{STR_VAR_1}”, sin duda.$"

BravoTrainerBattleTower_Text_ResponseUnsatisfied::
	.string "“{STR_VAR_1}”.\n"
	.string "¿No es muy apropiado?\p"
	.string "Ese combate contra {STR_VAR_3}\n"
	.string "al final… Sólo puede describirse como\l"
	.string "“{STR_VAR_1}”, claro.\p"
	.string "La decepción de {STR_VAR_2} queda\n"
	.string "reflejada alta y clara, así es.$"

BravoTrainerBattleTower_Text_Outro::
	.string "¡Bravo, {STR_VAR_1}!\n"
	.string "¡Bravo, {STR_VAR_2}!\p"
	.string "¡Confío en que podamos ver a\n"
	.string "{STR_VAR_1} subir a lo más alto!\p"
	.string "¡Esto es todo por hoy!\n"
	.string "¡Nos despedimos hasta la próxima!$"

SlateportCity_PokemonFanClub_Text_InterviewRequestHasName: @ 08280270
	.string "¡Guau!\p"
	.string "Se ve a la legua que quieres a tu\n"
	.string "{STR_VAR_1} con locura.\p"
	.string "Vale, sí, se llama {STR_VAR_2}.\p"
	.string "¿Puedes hacerme un favor?\p"
	.string "Soy reportera de TV y estoy haciendo\n"
	.string "una encuesta sobre los Pokémon.\p"
	.string "¿Querrías contestar a algunas\n"
	.string "preguntas facilísimas?$"

SlateportCity_PokemonFanClub_Text_HereGoesQuickAnswers: @ 0828034F
	.string "¡Mola! ¡Gracias!\p"
	.string "Venga, allá vamos.\n"
	.string "Necesito respuestas rápidas, ¿vale?$"

SlateportCity_PokemonFanClub_Text_DescribeFeelingsFirstMetMon: @ 08280393
	.string "Cuando viste por primera vez a\n"
	.string "{STR_VAR_1}, ¿qué fue lo que sentiste?\p"
	.string "¿Cómo describirías tus sentimientos\n"
	.string "de entonces?$"

SlateportCity_PokemonFanClub_Text_LikenMonToSomethingYouLike: @ 082803EF
	.string "Cuidas a tu {STR_VAR_1} con mucho\n"
	.string "amor y cariño.\p"
	.string "Si quisieras compararlo con algo\n"
	.string "que te gusta, ¿qué sería?$"

SlateportCity_PokemonFanClub_Text_WhatAttractedYouAboutMon: @ 08280454
	.string "Esta pregunta está relacionada con\n"
	.string "tu querido {STR_VAR_1}.\p"
	.string "¿Qué tenía {STR_VAR_1} que te atrajo\n"
	.string "tanto desde el principio?$"

SlateportCity_PokemonFanClub_Text_WhatDoPokemonMeanToYou: @ 082804AC
	.string "Sí, tiene sentido.\p"
	.string "La siguiente pregunta podría\n"
	.string "parecerte un pelín fuerte…\p"
	.string "Allá voy…\p"
	.string "¿Qué significan los Pokémon\n"
	.string "para ti?$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview: @ 08280523
	.string "¡Ajá!\p"
	.string "Mmmm…\p"
	.string "¡Vale!\n"
	.string "Gracias por participar.\p"
	.string "Charlar contigo ha sido divertido\n"
	.string "y revelador.\p"
	.string "Con toda probabilidad, la entrevista\n"
	.string "se retransmitirá por la tele.\l"
	.string "¡Enciéndela de vez en cuando!\p"
	.string "Pues esto era todo.\n"
	.string "¡Hala! ¡Hasta otra!$"

SlateportCity_PokemonFanClub_Text_HereIfYouGetUrgeToTellMe: @ 082805E2
	.string "Oh, de acuerdo…\p"
	.string "Pero si de repente te entran unas ganas\n"
	.string "irresistibles de decírmelo, ven a verme.$"

SlateportCity_PokemonFanClub_Text_EnjoyDoingInterviews: @ 0828062E
	.string "Me encanta este trabajo: aprendes\n"
	.string "tantísimo sobre los Pokémon con\l"
	.string "cada entrevista…$"

SlateportCity_PokemonFanClub_Text_InterviewRequest: @ 08280674
	.string "Hola, parece que hay un vínculo muy\n"
	.string "fuerte entre tu {STR_VAR_1} y tú.\p"
	.string "¿Sabes qué?\n"
	.string "Soy reportera de TV.\p"
	.string "Viajo por aquí, por allá y por acullá\n"
	.string "haciendo entrevistas sobre Pokémon.\p"
	.string "Me pregunto si querrías contarme\n"
	.string "alguna cosilla sobre tu {STR_VAR_1}…$"

SlateportCity_PokemonFanClub_Text_TellMeAnythingAboutYourMon: @ 0828073B
	.string "¡Hala, qué bien!\p"
	.string "Pues mira, cuéntame lo que te\n"
	.string "apetezca sobre tu {STR_VAR_1}.$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview2: @ 08280789
	.string "Huy…\n"
	.string "Qué interesante…\p"
	.string "Tu {STR_VAR_1} y tú sois uña y\n"
	.string "carne, ¿eh?\p"
	.string "Yo creo que tu declaración puede dar\n"
	.string "para una gran historia en la tele.\p"
	.string "Voy a hacer lo imposible para que salga\n"
	.string "en el próximo programa de variedades.\l"
	.string "¡No te lo pierdas!\p"
	.string "Pues esto era todo.\n"
	.string "¡Hala! ¡Hasta otra!$"

gTVFanClubOpinionsText00::
	.string "¡Somos el Club de fans de Pokémon!\p"
	.string "¡Estamos en el aire!\p"
	.string "En este programa, recogemos vuestras\n"
	.string "opiniones y las emitimos a todo Hoenn.\l"
	.string "¿No es un concepto fantástico?\p"
	.string "Hoy os presentamos el informe\n"
	.string "elaborado desde el Club de fans\l"
	.string "de Pokémon.\p"
	.string "Bien, ¿quién será el superfán\n"
	.string "Pokémon del día?…\p"
	.string "A ver…\p"
	.string "¡{STR_VAR_1}!\p"
	.string "Escuchemos lo que {STR_VAR_1} tiene que\n"
	.string "decir sobre su {STR_VAR_2}, {STR_VAR_3}.\p"
	.string "¡Yo voy a retransmitir bien alto por\n"
	.string "la tele esas palabras de amor!\p"
	.string "¡Yupi!\p"
	.string "¡Gritemos todos juntos!$"

gTVFanClubOpinionsText01::
	.string "Hemos preguntado a {STR_VAR_1}: “Cuando\n"
	.string "viste por primera vez a {STR_VAR_2},\l"
	.string "¿qué fue lo que sentiste?”.\p"
	.string "“¡{STR_VAR_3}!”\p"
	.string "¡Guau! ¡Es una declaración impactante!\p"
	.string "¿No os trae recuerdos de esos felices\n"
	.string "días que dejasteis atrás?$"

gTVFanClubOpinionsText02::
	.string "Hemos preguntado a {STR_VAR_1}: “Si\n"
	.string "quisieras compararlo con algo que\l"
	.string "te gusta, ¿qué sería?”.\p"
	.string "Pues sería…\p"
	.string "“¡{STR_VAR_3}!”\p"
	.string "¡Guau! ¡Qué idea tan original!\p"
	.string "Sin duda transmite la intensidad de\n"
	.string "los sentimientos que siente por\l"
	.string "su {STR_VAR_2}.$"

gTVFanClubOpinionsText03::
	.string "Hemos preguntado a {STR_VAR_1}: “¿Qué\n"
	.string "tenía {STR_VAR_2} que te atrajo tanto\l"
	.string "desde el principio?”.\p"
	.string "Y respondió…\p"
	.string "“¡{STR_VAR_3}!”\p"
	.string "¡Guau! ¡Una declaración espectacular!\p"
	.string "Es una clara muestra de la fuerza\n"
	.string "del amor que siente por su {STR_VAR_2}.$"

gTVFanClubOpinionsText04::
	.string "Eh… Queda una todavía…\n"
	.string "¡Pasemos a ella!\p"
	.string "Cómo era… ¡Ah, sí!\p"
	.string "Hemos preguntado a {STR_VAR_1}: “¿Qué\n"
	.string "significan los Pokémon para ti?”.\p"
	.string "Y respondió…\p"
	.string "“¡{STR_VAR_3}!”\p"
	.string "¡Grandioso!\p"
	.string "¡Es lo mejor que he oído nunca!\p"
	.string "“¡{STR_VAR_3}!”\p"
	.string "Te dan ganas de gritarlo una y otra vez.\p"
	.string "Ahora que ya tenemos un gran “grito”,\n"
	.string "es hora de despedirnos de vosotros.\p"
	.string "Venga, gritemos todos juntos una\n"
	.string "última vez…\p"
	.string "“¡{STR_VAR_3}!”$"

gTVFanClubText00::
	.string "¡Somos el Club de fans de Pokémon!\p"
	.string "¡Estamos en el aire!\p"
	.string "Hoy vamos a pasarlo como enanos\n"
	.string "con la hora de las Pokécartas.\p"
	.string "De todas las emocionantes historias\n"
	.string "de Pokémon y entrenadores, ¿cuál \l"
	.string "captará nuestra atención hoy?\p"
	.string "A ver…\p"
	.string "¡Ésta!\p"
	.string "¡Empezaremos con esta carta!\p"
	.string "Una carta de {STR_VAR_1} sobre su\n"
	.string "querido {STR_VAR_2}.\p"
	.string "Veamos con qué pasión expresa su\n"
	.string "amor por {STR_VAR_2}…\l"
	.string "Ajá…$"

gTVFanClubText01::
	.string "¡Vaya!\n"
	.string "¡Esta carta es una obra de arte!$"

gTVFanClubText02::
	.string "Me ha encantado, así que la\n"
	.string "voy a leer otra vez.$"

gTVFanClubText03::
	.string "¡Cuando algo está bien escrito, se\n"
	.string "puede leer hasta el aburrimiento!$"

gTVFanClubText04::
	.string "La parte que dice “{STR_VAR_3}” es\n"
	.string "la que añade más contenido emocional.\p"
	.string "Es una carta magnífica que expresa\n"
	.string "sentimientos realmente profundos.$"

gTVFanClubText05::
	.string "Sobre todo eso: “{STR_VAR_3}”…\p"
	.string "Es una parte genial. Me encanta cómo\n"
	.string "suena: “{STR_VAR_3}”…$"

gTVFanClubText06::
	.string "Por cierto, no es que vaya a cambiarme\n"
	.string "la vida, pero “{STR_VAR_3}” es\l"
	.string "una expresión genial.\p"
	.string "He usado “{STR_VAR_3}” cada\n"
	.string "dos por tres últimamente.$"

gTVFanClubText07::
	.string "Si tuviera que puntuar esta carta,\n"
	.string "le daría {STR_VAR_3} puntos.\p"
	.string "¡La próxima vez espero que la\n"
	.string "carta sea aún mejor, {STR_VAR_1}!\p"
	.string "Oh… ¿Sabes qué hora es?\n"
	.string "¡Hora de decir hasta luego, Lucas!$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequest: @ 082811A0
	.string "¿Eh?\n"
	.string "¿Te gustan los Pokémon?\p"
	.string "La emisora de TV me ha enviado a\n"
	.string "hacer un reportaje.\p"
	.string "Estoy recogiendo historias recientes\n"
	.string "sobre Pokémon y entrenadores.\p"
	.string "Si no te importa, ¿podrías contarme\n"
	.string "algo sobre ti?$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequestShort: @ 0828126D
	.string "Estoy recogiendo historias recientes\n"
	.string "sobre Pokémon y entrenadores.\p"
	.string "Si no te importa, ¿podrías contarme\n"
	.string "algo sobre ti?$"

SlateportCity_OceanicMuseum_1F_Text_TellMeExperienceInvolvingPokemon: @ 082812F2
	.string "¿Sí?\n"
	.string "¡Muchas gracias!\p"
	.string "Pues dime cualquier cosa interesante\n"
	.string "que te haya pasado hace poco con\l"
	.string "Pokémon de por medio…$"

SlateportCity_OceanicMuseum_1F_Text_LetMeKnowIfYouHaveStory: @ 08281367
	.string "Ah, ya…\p"
	.string "Pero cuando tengas algo bueno que\n"
	.string "contar, ven a verme, porfa.$"

SlateportCity_OceanicMuseum_1F_Text_ThatsAllForInterview: @ 082813B9
	.string "¡Qué historia tan edificante!\p"
	.string "Me aseguraré de que mi emisora\n"
	.string "la retransmita.\p"
	.string "Puede salir en cualquier momento,\n"
	.string "así que mira la tele de vez en cuando.$"

SlateportCity_OceanicMuseum_1F_Text_BetterWriteUpStory: @ 0828144D
	.string "Mmmm…\n"
	.string "Tengo una buena historia para un\l"
	.string "programa de la tele.\p"
	.string "¡Mejor la escribo antes de que se\n"
	.string "me olvide!$"

gTVRecentHappeningsText00::
	.string "Hola, presentamos la Última Hora.\p"
	.string "Para los entrenadores Pokémon,\n"
	.string "cada día encierra una nueva aventura.\p"
	.string "Queremos presentaros algunas de\n"
	.string "estas aventuras Pokémon.\p"
	.string "Hoy os traemos la historia de {STR_VAR_1}.\p"
	.string "¿Qué le ha pasado a {STR_VAR_1} en los\n"
	.string "últimos tiempos? Ahora lo sabremos.\p"
	.string "Veamos…$"

gTVRecentHappeningsText01::
	.string "¿No es asombroso?\p"
	.string "Esta historia te da una clara idea de\n"
	.string "lo que le ha pasado a {STR_VAR_1}, casi\l"
	.string "como si lo hubiésemos vivido nosotros.$"

gTVRecentHappeningsText02::
	.string "“{STR_VAR_3}” añade\n"
	.string "matices y profundidad a la historia.$"

gTVRecentHappeningsText03::
	.string "“{STR_VAR_3}” sitúa\n"
	.string "la historia en contexto.\l"
	.string "Nos permite imaginar la escena.$"

gTVRecentHappeningsText04::
	.string "La parte de la historia que dice\n"
	.string "“{STR_VAR_3}” es\l"
	.string "altamente expresiva.$"

gTVRecentHappeningsText05::
	.string "{STR_VAR_1} nos ha deleitado con una\n"
	.string "maravillosa historia sobre Pokémon.\p"
	.string "Y ahora la historia de {STR_VAR_1} está\n"
	.string "grabada a fuego en nuestra mente.\p"
	.string "Esto es todo por hoy.\n"
	.string "¡Hasta el próximo programa!$"

gTVMassOutbreakText00::
	.string "¡Saludos!\n"
	.string "Es la hora de las Noticias Pokémon.\p"
	.string "Acabamos de ser informados de\n"
	.string "un extraño suceso.\p"
	.string "Al parecer, un montón de {STR_VAR_2}\n"
	.string "asola la zona de {STR_VAR_1}.\p"
	.string "Los {STR_VAR_2}, como seguramente\n"
	.string "sabéis ya, son unos Pokémon raros\l"
	.string "muy difíciles de encontrar.\p"
	.string "Parece que es la oportunidad de ver\n"
	.string "a los {STR_VAR_2} en estado salvaje.\p"
	.string "Y esto es todo en las Noticias\n"
	.string "Pokémon.$"

gTV3CheersForPokeblocksText00::
	.string "PresentadorA: ¿Cómo estáis? ¡Llegó la\n"
	.string "hora de la Cata de Pokécubos!\p"
	.string "Hoy vamos a examinar el Pokécubo\n"
	.string "mezclado por {STR_VAR_1} y compañía.\p"
	.string "Sin más preámbulos, nuestro Pokémon\n"
	.string "catador, Gulpin, lo va a degustar.\p"
	.string "¿Cuál será el veredicto?…$"

gTV3CheersForPokeblocksText01::
	.string "Gulpin: ¡Gubi, gubiii!\p"
	.string "PresentadorA: ¡Muy {STR_VAR_1}! \n"
	.string "¡Gulpin dice que está “{STR_VAR_2}”!\p"
	.string "¡Muchas gracias, {STR_VAR_3}!$"

gTV3CheersForPokeblocksText02::
	.string "Las habilidades de {STR_VAR_1}\n"
	.string "no acaban de convencernos.\p"
	.string "Si mezclara bayas mejor, el sabor\n"
	.string "de este Pokécubo sería excelente.$"

gTV3CheersForPokeblocksText03::
	.string "Gulpin: ¡Gubi, gubiii!\p"
	.string "PresentadorA: Demasiado {STR_VAR_1}…\n"
	.string "¡Gulpin dice que está “{STR_VAR_2}”!\p"
	.string "Parece que los errores de {STR_VAR_3}\n"
	.string "afectaron a la calidad de la mezcla…$"

gTV3CheersForPokeblocksText04::
	.string "Es una lástima que los esfuerzos de\n"
	.string "{STR_VAR_1} hayan sido inútiles.\p"
	.string "¡Esperemos que {STR_VAR_2} lo haga\n"
	.string "mejor la próxima vez!$"

gTV3CheersForPokeblocksText05::
	.string "¡No os perdáis la próxima emisión!\n"
	.string "¡Os esperamos en la cata de Pokécubos!$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer::
	.string "¡Hola, colega!\p"
	.string "Soy un gran fan de {STR_VAR_1}.\n"
	.string "¿Qué te sugiere {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_ThatsWhatYouThink::
	.string "Ya veo. Así que eso es lo\n"
	.string "que te sugiere…$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer::
	.string "¿Te has olvidado totalmente\n"
	.string "de {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer2::
	.string "Soy un gran fan de {STR_VAR_1}.\n"
	.string "¿Qué te sugiere {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_HowStrongRateTrainer::
	.string "Si tuvieras que puntuar la fuerza de\n"
	.string "{STR_VAR_1} en una escala del 0 al 100,\l"
	.string "¿qué valor dirías?$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer2::
	.string "¿Te has olvidado totalmente\n"
	.string "de {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_YouShouldMeetTrainer::
	.string "Ya veo…\n"
	.string "Deberías acordarte de {STR_VAR_1}.\l"
	.string "¡Seguro que serías su fan!$"

LilycoveCity_PokemonTrainerFanClub_Text_ThankYouIllShareThisInfo::
	.string "Ya veo…\p"
	.string "¡Gracias por participar!\n"
	.string "Tu respuesta es interesante.\p"
	.string "Pienso compartirla con todos\n"
	.string "los fans de {STR_VAR_1}.$"

LilycoveCity_PokemonTrainerFanClub_HopeYouCatchTVSpecial::
	.string "Van a hacer un programa especial\n"
	.string "sobre {STR_VAR_1} muy pronto.\p"
	.string "¡No te lo pierdas!$"

gTVTrainerFanClubSpecialText00::
	.string "Club de fans de entrenadores\n"
	.string "¡Especial sobre {STR_VAR_1}!\p"
	.string "¡Este programa está dedicado a todos\n"
	.string "los fans de {STR_VAR_1} en Hoenn!\p"
	.string "Nos hemos hecho esta pregunta:\n"
	.string "¿qué sugiere {STR_VAR_1} a la gente?\p"
	.string "Primero respondió {STR_VAR_2} en\n"
	.string "representación de otros Entrenadores.\p"
	.string "Le pedimos que nos dijera la palabra\n"
	.string "con la que asocia a {STR_VAR_1}.\p"
	.string "Su respuesta fue: “{STR_VAR_3}”.\p"
	.string "¡Debemos felicitar a {STR_VAR_2} por\n"
	.string "su perspicacia y originalidad!\p"
	.string "“{STR_VAR_1} {STR_VAR_3}.”\n"
	.string "¡Qué sonido tan celestial!\p"
	.string "{STR_VAR_2} también puntuó la fuerza de\n"
	.string "{STR_VAR_1} en una escala del 0 al 100.$"

gTVTrainerFanClubSpecialText01::
	.string "¡Ha conseguido nada menos que\n"
	.string "{STR_VAR_3} puntos! ¡Menuda puntuación!\p"
	.string "Es obvio que {STR_VAR_2} tiene a\n"
	.string "{STR_VAR_1} en muy alta estima.$"

gTVTrainerFanClubSpecialText02::
	.string "¡Ha conseguido {STR_VAR_3} puntos!\n"
	.string "¡No está nada mal!\p"
	.string "{STR_VAR_2} debe considerar a\n"
	.string "{STR_VAR_1} como un rival.$"

gTVTrainerFanClubSpecialText03::
	.string "¡Ha conseguido {STR_VAR_3} puntos!\n"
	.string "No es para echar cohetes.\p"
	.string "{STR_VAR_2} no debe admirar\n"
	.string "demasiado a {STR_VAR_1}.$"

gTVTrainerFanClubSpecialText04::
	.string "Sólo ha conseguido esta puntuación:\n"
	.string "¡{STR_VAR_3}! No podría ser peor.\p"
	.string "Está claro que {STR_VAR_2} tiene a\n"
	.string "{STR_VAR_1} en poca consideración.$"

gTVTrainerFanClubSpecialText05::
	.string "¡Y así llegamos al fin de la emisión!\p"
	.string "Creo que todos hemos aprendido\n"
	.string "algo nuevo de {STR_VAR_1}.\p"
	.string "Para terminar, me despido con las\n"
	.string "palabras de {STR_VAR_2}.\p"
	.string "¡{STR_VAR_1} {STR_VAR_3}!$"

gTVNameRaterText00::
	.string "Ya ha llegado…\n"
	.string "La hora del inspector de los motes.\p"
	.string "Por el mote de un Pokémon sé ver\n"
	.string "la relación con su Entrenador.\p"
	.string "Mis palabras son sabias, ya lo verás.\p"
	.string "Hoy voy a predecir la suerte de\n"
	.string "{STR_VAR_3}, el Pokémon {STR_VAR_2}\l"
	.string "de {STR_VAR_1}.\p"
	.string "Ommmm…\p"
	.string "Ommmm…\n"
	.string "Este mote…$"

gTVNameRaterText01::
	.string "Este mote denota un gran talento\n"
	.string "en muchos sentidos.\p"
	.string "Animo a quien lo puso a ser valiente\n"
	.string "y aceptar muchos desafíos…$"

gTVNameRaterText02::
	.string "Este mote complementa perfectamente\n"
	.string "a quien lo puso, {STR_VAR_1}.\p"
	.string "Sugiere que se forjará una amistad\n"
	.string "perfecta al cabo del tiempo…$"

gTVNameRaterText03::
	.string "Este mote se adapta a la personalidad\n"
	.string "propia de su Pokémon.\p"
	.string "Si se le entrena correctamente, este\n"
	.string "Pokémon llegará a lo más alto…$"

gTVNameRaterText04::
	.string "Este mote potenciará el lado cariñoso\n"
	.string "y compasivo de su Pokémon.\p"
	.string "Si se le entrena correctamente, este\n"
	.string "Pokémon será realmente adorable…$"

gTVNameRaterText05::
	.string "Este mote indica un futuro brillante.\p"
	.string "Me pregunto qué reserva el destino\n"
	.string "a este Pokémon…$"

gTVNameRaterText06::
	.string "Este mote favorecerá la fuerza\n"
	.string "y belleza de su Pokémon.\p"
	.string "Este Pokémon será robusto y estará\n"
	.string "en forma durante mucho tiempo…$"

gTVNameRaterText07::
	.string "Este gran mote hará que su Pokémon\n"
	.string "sea muy activo.\p"
	.string "Yo diría que este Pokémon será muy\n"
	.string "bueno en los combates…$"

gTVNameRaterText08::
	.string "Este atractivo mote concederá\n"
	.string "un gran encanto a su Pokémon.\p"
	.string "Sin duda este Pokémon será el rey\n"
	.string "de los ConcursoS Pokémon…$"

gTVNameRaterText09::
	.string "El mote {STR_VAR_1} proviene de\n"
	.string "la letra “{STR_VAR_3}”.\p"
	.string "Esta letra está apoyada por la primera\n"
	.string "letra, “{STR_VAR_2}”, que le otorga una\l"
	.string "gran solidez como mote…$"

gTVNameRaterText10::
	.string "El mote {STR_VAR_1} es de lo más\n"
	.string "armonioso y agradable.\p"
	.string "La presencia de las letras “{STR_VAR_2}” y\n"
	.string "“{STR_VAR_3}” le da mucha clase…$"

gTVNameRaterText11::
	.string "El mote {STR_VAR_1} transmite una\n"
	.string "sensación de sublime fluidez.\p"
	.string "Desde la letra inicial “{STR_VAR_2}” hasta\n"
	.string "“{STR_VAR_3}” es una auténtica maravilla…$"

gTVNameRaterText12::
	.string "Vamos a examinar otros ejemplos\n"
	.string "de buenos motes, ¿de acuerdo?$"

gTVNameRaterText13::
	.string "Por ejemplo: toma parte del nombre del\n"
	.string "Entrenador, en este caso {STR_VAR_1},\l"
	.string "y añade el bonito mote {STR_VAR_2}{STR_VAR_3}.$"

gTVNameRaterText14::
	.string "El mote {STR_VAR_2}{STR_VAR_3} también\n"
	.string "puede funcionar muy bien.$"

gTVNameRaterText15::
	.string "Se puede usar el nombre de la especie\n"
	.string "del Pokémon, {STR_VAR_2}, como base\l"
	.string "para crear el mote {STR_VAR_1}{STR_VAR_3}.$"

gTVNameRaterText16::
	.string "{STR_VAR_1}{STR_VAR_3} también sería\n"
	.string "un mote efectivo.$"

gTVNameRaterText17::
	.string "Lo que hay que evitar siempre es usar\n"
	.string "el nombre de otra especie de Pokémon.\p"
	.string "Por ejemplo, evita tomar el nombre de\n"
	.string "{STR_VAR_2} para crear el mote {STR_VAR_1}{STR_VAR_3}.\l"
	.string "Eso no está nada bien.$"

gTVNameRaterText18::
	.string "Pero debo decir que {STR_VAR_1}\n"
	.string "es un buen mote.\p"
	.string "Espero que quien lo entrene\n"
	.string "continúe tratándolo con amor.\p"
	.string "Esto es todo por hoy.\n"
	.string "Hasta el próximo programa.$"

gTVPokemonAnglerText00::
	.string "Pescador de {STR_VAR_2}\p"
	.string "PresentadorA: ¡Hola! Hoy vamos\n"
	.string "a aprender cómo pescar {STR_VAR_2}.\p"
	.string "Gurú pescador, ¿qué consejo puedes\n"
	.string "darnos para atrapar {STR_VAR_2}?\p"
	.string "Gurú pescador: ¿Pescar {STR_VAR_2}?\n"
	.string "Pues hay que ser muy paciente.\l"
	.string "Eso es lo básico.\p"
	.string "¿Has visto a {STR_VAR_1} en acción?\n"
	.string "Es un ejemplo perfecto.\p"
	.string "Ya se le han escapado…\n"
	.string "{STR_VAR_3} Pokémon.\p"
	.string "Pero {STR_VAR_1} espera. No se rinde.\n"
	.string "Así ha de ser para pescar {STR_VAR_2}.\p"
	.string "PresentadorA: Entiendo…\p"
	.string "¡Oh! ¡{STR_VAR_1} se ha hecho con un\n"
	.string "escurridizo {STR_VAR_2}!\p"
	.string "¡Se diría que se le van a saltar\n"
	.string "las lágrimas de pura alegría!\p"
	.string "Viéndole, me entran unas ganas\n"
	.string "tremendas de ponerme a pescar.\p"
	.string "Queridos telespectadores, ¿por qué no\n"
	.string "intentamos todos pescar {STR_VAR_2}?\p"
	.string "Os deseo una buena pesca a todos.\n"
	.string "Hasta nuestro próximo programa.$"

gTVPokemonAnglerText01::
	.string "Pescador de {STR_VAR_2}\p"
	.string "PresentadorA: ¡Hola! Hoy vamos\n"
	.string "a aprender cómo pescar {STR_VAR_2}.\p"
	.string "Gurú pescador, ¿qué consejo puedes\n"
	.string "darnos para atrapar {STR_VAR_2}?\p"
	.string "Gurú pescador: ¿Pescar {STR_VAR_2}?\n"
	.string "Pues hay que tirar de la\l"
	.string "Caña con fuerza.\p"
	.string "¿Has visto a {STR_VAR_1} en acción?\n"
	.string "¿Ves cómo sostiene la caña?\p"
	.string "Ya ha conseguido pescar {STR_VAR_3}\n"
	.string "Pokémon seguidos.\p"
	.string "PresentadorA: Impresionante…\n"
	.string "¡Es un as de la caña!\p"
	.string "Al ver su magnífica técnica, me entran\n"
	.string "muchas ganas de ponerme a pescar.\p"
	.string "Queridos telespectadores, ¿por qué no\n"
	.string "intentamos todos pescar {STR_VAR_2}?\p"
	.string "Os deseo una buena pesca a todos.\n"
	.string "Hasta nuestro próximo programa.$"

gTVPokemonTodayFailedText00::
	.string "¡Hola!\p"
	.string "¡Bienvenidos a actualidad Pokémon!\p"
	.string "Pibita: ¡Hola a todos!\n"
	.string "¿Cómo estamos hoy?\p"
	.string "Vamos a conocer al Pokémon {STR_VAR_2}\n"
	.string "de {STR_VAR_1}.\p"
	.string "Pibe: ¡Así es! ¡Pasemos a ello!$"

gTVPokemonTodayFailedText01::
	.string "Y, ya que mencionas su nombre,\n"
	.string "¿a que no sabes una cosa?\p"
	.string "Pibita, ¡he visto a {STR_VAR_1} en\n"
	.string "acción con mis propios ojos!\p"
	.string "Pibita: ¿Y qué has visto?\p"
	.string "Pibe: Bien, yo tenía que viajar\n"
	.string "a {STR_VAR_2}, ¿no?\p"
	.string "Fue entonces cuando me crucé\n"
	.string "con {STR_VAR_1}, que intentaba atrapar\l"
	.string "al Pokémon {STR_VAR_3}, pero…$"

gTVPokemonTodayFailedText02::
	.string "¡el Pokémon logró escapar!\p"
	.string "Usó este número de Poké Balls\n"
	.string "para nada: {STR_VAR_2}.\p"
	.string "¡Deberías haber visto la expresión\n"
	.string "de frustración en la cara de {STR_VAR_1}\l"
	.string "cuando el Pokémon huyó!$"

gTVPokemonTodayFailedText03::
	.string "¡{STR_VAR_1} la pifió y debilitó\n"
	.string "al Pokémon!\p"
	.string "Usó este número de Poké Balls\n"
	.string "para nada: {STR_VAR_2}.\p"
	.string "¡Deberías haber visto la expresión\n"
	.string "de consternación en la cara de {STR_VAR_1}\l"
	.string "cuando el Pokémon se debilitó!$"

gTVPokemonTodayFailedText04::
	.string "Pibita: ¡Pero bueno!\n"
	.string "¡Eso no está bien!\p"
	.string "¡No deberías burlarte\n"
	.string "de las desgracias ajenas!\p"
	.string "Pobre {STR_VAR_1}…\n"
	.string "¡Qué lástima!\p"
	.string "Pibe: Tienes razón…\n"
	.string "Ha estado mal por mi parte.$"

gTVPokemonTodayFailedText05::
	.string "Pibita: (Ji, ji, ji…)\p"
	.string "Pibe: Qué vergüenza…\n"
	.string "¡Te estás riendo de {STR_VAR_1}!\p"
	.string "Pibita: ¿Qué dices?\p"
	.string "¡Yo no me estaba riendo!\n"
	.string "¡De verdad de la buena!\p"
	.string "Pobre {STR_VAR_1}…\n"
	.string "¡Qué lástima!\p"
	.string "Pibe: Ya, ya…$"

gTVPokemonTodayFailedText06::
	.string "Pibita: ¡Bueno, ya está bien!\n"
	.string "Veamos el Pokémon de hoy…\p"
	.string "¿Qué?\n"
	.string "¿Se nos ha acabado el tiempo?\p"
	.string "¡Horror!\n"
	.string "¡No hemos podido emitir el perfil\l"
	.string "del Pokémon de la jornada!\p"
	.string "Pibe: ¡Hasta el próximo\n"
	.string "programa!\p"
	.string "Pibita: ¡Eh, no acabes el programa\n"
	.string "sin mí!$"

gTVPokemonTodaySuccessfulText00::
	.string "¡Hola!\p"
	.string "¡Bienvenidos a actualidad Pokémon!\p"
	.string "Pibita: ¡Hola a todos!\n"
	.string "¿Cómo estamos hoy?\p"
	.string "Vamos a conocer al Pokémon {STR_VAR_2}\n"
	.string "de {STR_VAR_1}.\p"
	.string "Pibe: ¡Así es! ¡Pasemos a ello!$"

gTVPokemonTodaySuccessfulText01::
	.string "Pibita: {STR_VAR_1} dio a su {STR_VAR_2}\n"
	.string "el mote {STR_VAR_3}.\p"
	.string "Parece que {STR_VAR_3} recibe unos\n"
	.string "cuidados excelentes.$"

gTVPokemonTodaySuccessfulText02::
	.string "Pibe: ¡Lo atrapó con una {STR_VAR_2}!\n"
	.string "¿Y sabes cuántas balls lanzó? ¡{STR_VAR_3}!$"

gTVPokemonTodaySuccessfulText03::
	.string "Pibita: Si fue tan fácil de atrapar,\n"
	.string "ha debido de ser el destino el que\l"
	.string "ha unido a {STR_VAR_1} y a {STR_VAR_2}.$"

gTVPokemonTodaySuccessfulText04::
	.string "Pibita: ¡Guau! ¡Realmente fantástico!\p"
	.string "Pero sabes lo que dicen, cuanto más\n"
	.string "trabajo cuesta atrapar un Pokémon,\l"
	.string "más cariño se le coge…$"

gTVPokemonTodaySuccessfulText05::
	.string "Pibita: ¡El {STR_VAR_2} de {STR_VAR_1}\n"
	.string "es un Pokémon muy especial, pues hubo\l"
	.string "que atraparlo con una Master Ball!\p"
	.string "Pibe: ¡Asombroso! ¡Grandioso!\p"
	.string "Pibita: ¡{STR_VAR_1} debía de desear ese\n"
	.string "{STR_VAR_2} con fuerza, está claro!$"

gTVPokemonTodaySuccessfulText06::
	.string "Pibe: Y el hecho de llamar al\n"
	.string "{STR_VAR_2} con el mote {STR_VAR_3}…\p"
	.string "Te da una buena idea del tipo\n"
	.string "de Entrenador que es {STR_VAR_1}.\p"
	.string "Pibita: ¡No podría estar\n"
	.string "más de acuerdo!$"

gTVPokemonTodaySuccessfulText07::
	.string "¡En su lugar, yo pondría ese mote\n"
	.string "a algún {STR_VAR_3}, por ejemplo!\p"
	.string "Pibe: ¡Eso podría ser el inicio\n"
	.string "de una nueva moda!$"

gTVPokemonTodaySuccessfulText08::
	.string "{STR_VAR_2}, el {STR_VAR_1}.\n"
	.string "¿No va junto estupendamente?\p"
	.string "Las letras y todo lo demás le pegan\n"
	.string "perfectamente al Pokémon {STR_VAR_1}.\p"
	.string "Pibe: ¡Y tanto!$"

gTVPokemonTodaySuccessfulText09::
	.string "Por lo que sé, ningún entrenador\n"
	.string "ha llamado jamás {STR_VAR_2}\l"
	.string "a un {STR_VAR_1}.\p"
	.string "Pibe: ¡Esto muestra una vez más su\n"
	.string "extraordinario gusto eligiendo motes!$"

gTVPokemonTodaySuccessfulText10::
	.string "La próxima vez que atrape un Pokémon,\n"
	.string "lo llamaré {STR_VAR_2}.\p"
	.string "Pibe: ¿Sí? ¡Yo también!\n"
	.string "¡Ese mote, {STR_VAR_2}, me chifla!$"

gTVPokemonTodaySuccessfulText11::
	.string "Pibita: ¡Oh, no!\n"
	.string "¡Mira la hora!\p"
	.string "Me temo que esto es todo por hoy.\n"
	.string "¡Hasta el próximo programa!\p"
	.string "Pibe: ¡Recuerda que el próximo\n"
	.string "Pokémon estrella podría ser el tuyo!$"

SmartShopper_Text_Intro::
	.string "¡Hola!\p"
	.string "Es la hora del Pokécomprador del día.\p"
	.string "Entrevistador: ¿Cómo estáis todos?\p"
	.string "Hoy vamos a visitar una tienda\n"
	.string "en {STR_VAR_2}.\p"
	.string "Comprobemos qué se ha estado\n"
	.string "vendiendo últimamente.$"

SmartShopper_Text_ClerkNormal::
	.string "Entrevistemos al encargado para\n"
	.string "sacar algo de información.\p"
	.string "Hola, ¿qué tal va el negocio?\p"
	.string "Encargado: Oh, de rechupete.\p"
	.string "Últimamente vendemos {STR_VAR_2}\n"
	.string "estupendamente.\p"
	.string "De hecho, el otro día {STR_VAR_1}, sin ir\n"
	.string "más lejos, compró {STR_VAR_3}.$"

SmartShopper_Text_RandomComment1::
	.string "Entrevistador: ¿Compró {STR_VAR_2}?\n"
	.string "¿Nada menos que {STR_VAR_3}? ¡Qué exageración!\p"
	.string "Yo diría que {STR_VAR_1} está almacenando\n"
	.string "una gran cantidad para realizar\l"
	.string "largos viajes muy, muy lejos.\p"
	.string "¡En ningún viaje debe faltar algo tan\n"
	.string "importante como {STR_VAR_2}!$"

SmartShopper_Text_RandomComment2::
	.string "Entrevistador: Hablando de algo como\n"
	.string "{STR_VAR_2}, hace nada compré {STR_VAR_3}.\p"
	.string "¡Después de todo, es un gran objeto!$"

SmartShopper_Text_RandomComment3::
	.string "Entrevistador: ¡¿{STR_VAR_2}?!\n"
	.string "¡¿Y encima {STR_VAR_3}?!\p"
	.string "Nunca pensé que nadie podría\n"
	.string "comprar tanto de eso.\p"
	.string "Yo solo me puedo comprar una\n"
	.string "o dos unidades cada vez…$"

SmartShopper_Text_RandomComment4::
	.string "Entrevistador: ¡Una vez compré\n"
	.string "{STR_VAR_2} y un montón, además!\p"
	.string "Pero resultó ser demasiado.\n"
	.string "Al final me arrepentí…\p"
	.string "Desde entonces solo compro lo\n"
	.string "estrictamente necesario…\p"
	.string "¡Huy!\p"
	.string "¡Si yo no tengo que hablar de mí!$"

SmartShopper_Text_SecondItem::
	.string "Encargado: ¡{STR_VAR_1} también compró\n"
	.string "{STR_VAR_2} y nada menos que {STR_VAR_3}!\p"
	.string "Entrevistador: Muy inteligente.\n"
	.string "{STR_VAR_2} es una gran elección.$"

SmartShopper_Text_ThirdItem::
	.string "Encargado: Igualmente, compró estas\n"
	.string "unidades de {STR_VAR_2}: {STR_VAR_3}.$"

SmartShopper_Text_DuringSale::
	.string "Encargado: Además, fue durante\n"
	.string "las rebajas. Una gran compra.$"

SmartShopper_Text_OutroNormal::
	.string "Entrevistador: Mmmm… {STR_VAR_1}\n"
	.string "parece encontrar las mejores ofertas.\p"
	.string "En total, las compras de {STR_VAR_1}\n"
	.string "ascienden a…\p"
	.string "¡¿{STR_VAR_2}??!\n"
	.string "¡Qué montón de dinero!\p"
	.string "¡Huy! ¡Se nos acabó el tiempo!\n"
	.string "¡Hasta el próximo programa!$"

SmartShopper_Text_IsVIP::
	.string "Encargado: No hay mejor cliente que\n"
	.string "{STR_VAR_1}. No cabe ninguna duda.$"

SmartShopper_Text_ClerkMax::
	.string "Entrevistemos al encargado para\n"
	.string "obtener algo de información.\p"
	.string "Hola, ¿qué tal va el negocio?\p"
	.string "Encargado: Pues mejor que\n"
	.string "bien. Es que no doy abasto.\p"
	.string "Hace poco, {STR_VAR_1} compró\n"
	.string "{STR_VAR_2} y en gran cantidad.\p"
	.string "Casi acabó con todas nuestras\n"
	.string "reservas, así que imagínate.\p"
	.string "Nunca pensé que alguien pudiera\n"
	.string "necesitar tantas unidades de\l"
	.string "{STR_VAR_2}, la verdad…\p"
	.string "Entrevistador: ¿Así que has\n"
	.string "vendido como 100 ó 200?\p"
	.string "EncArgAdo: ¡Oh, no, mucho más!\p"
	.string "Entrevistador: ¡Extraordinario!\n"
	.string "¡No debe de haber muchos compradores\l"
	.string "como {STR_VAR_1}!\p"
	.string "Encargado: No hay mejor cliente que\n"
	.string "{STR_VAR_1}. No cabe ninguna duda.$"

SmartShopper_Text_OutroMax::
	.string "Entrevistador: Mmmm…\n"
	.string "Es absolutamente increíble…\p"
	.string "¿Pero por qué querría ningún\n"
	.string "Entrenador tal cantidad?\p"
	.string "¿Por qué?\p"
	.string "Es un misterio insondable, pero no\n"
	.string "tenemos tiempo de investigarlo.\l"
	.string "¡Hasta el próximo programa!\p"
	.string "Aunque {STR_VAR_1} me desconcierta…$"

gTVWorldOfMastersText00::
	.string "El Mundo de los Pokémaestros\p"
	.string "Hola, queridos telespectadores.\p"
	.string "Quizás conozcáis ya a {STR_VAR_1}.\p"
	.string "{STR_VAR_1} debe su fama a su maestría\n"
	.string "atrapando Pokémon.\p"
	.string "{STR_VAR_1} se caracteriza por buscar\n"
	.string "Pokémon a pie.\p"
	.string "¡Un día memorable, llegó incluso\n"
	.string "a dar {STR_VAR_2} pasos!\p"
	.string "¡El número de Pokémon que atrapó\n"
	.string "ese día fue nada más y nada menos\l"
	.string "que {STR_VAR_3}!$"

gTVWorldOfMastersText01::
	.string "Tamaña proeza ha debido de ser\n"
	.string "posible gracias a la confianza\l"
	.string "que le tiene su {STR_VAR_1}.$"

gTVWorldOfMastersText02::
	.string "Atrapó el último {STR_VAR_3} del día\n"
	.string "cerca de {STR_VAR_2}.\p"
	.string "Ese Pokémon parece ser especialmente\n"
	.string "bueno obteniendo récords.\p"
	.string "Todo entrenador cualificado\n"
	.string "debería enfrentarse a este Pokémon.\p"
	.string "Eso es todo por hoy.\n"
	.string "¡Hasta el próximo programa!$"

gTVTodaysRivalTrainerText00::
	.string "¡Mi rival hoy, tu rival mañana!\p"
	.string "¡Hola, Entrenadores Pokémon!\n"
	.string "¿Cómo estáis todos?\p"
	.string "¡Hoy, como solemos hacer a menudo,\n"
	.string "analizaremos a uno de nuestros rivales!$"

gTVTodaysRivalTrainerText07::
	.string "El rival de hoy es {STR_VAR_1},\n"
	.string "que ahora anda por {STR_VAR_3}.\p"
	.string "{STR_VAR_1} lleva registrados por ahora\n"
	.string "{STR_VAR_2} Pokémon en la Pokédex.$"

gTVTodaysRivalTrainerText08::
	.string "El rival de hoy es {STR_VAR_1},\n"
	.string "que está en una Base Secreta.\p"
	.string "{STR_VAR_1} lleva registrados por ahora\n"
	.string "{STR_VAR_2} Pokémon en la ºPokédex.$"

gTVTodaysRivalTrainerText09::
	.string "El rival de hoy es {STR_VAR_1}.\p"
	.string "{STR_VAR_1} lleva registrados por ahora\n"
	.string "{STR_VAR_2} Pokémon en la Pokédex.$"

gTVTodaysRivalTrainerText10::
	.string "El rival de hoy es {STR_VAR_1},\n"
	.string "que está ahora en el ferry.\p"
	.string "{STR_VAR_1} lleva registrados por ahora\n"
	.string "{STR_VAR_2} Pokémon en la Pokédex.$"

	.string "$"

gTVTodaysRivalTrainerText01::
	.string "¿Y con cuántas medallas cuenta\n"
	.string "ya nuestro rival? ¡Pues con {STR_VAR_1}!$"

gTVTodaysRivalTrainerText02::
	.string "Pero nuestro rival aún no\n"
	.string "ha obtenido ninguna Medalla.$"

gTVTodaysRivalTrainerText03::
	.string "Eso sí, no ha obtenido ningún símbolo\n"
	.string "del Frente de Batalla por el momento.$"

gTVTodaysRivalTrainerText04::
	.string "Veamos cuántos símbolos del\n"
	.string "Frente de Batalla posee.\p"
	.string "Símbolos de oro: ¡{STR_VAR_1}!\n"
	.string "Símbolos de plata: ¡{STR_VAR_2}!$"

gTVTodaysRivalTrainerText05::
	.string "El Frente de Batalla ha recompensado\n"
	.string "a nuestro rival con Puntos de Batalla.\l"
	.string "Concretamente, ha obtenido {STR_VAR_1} PB.$"

gTVTodaysRivalTrainerText06::
	.string "Bueno, ¿qué tal lo estáis haciendo\n"
	.string "vosotros comparado con {STR_VAR_1}?\p"
	.string "¡La aventura aún no ha acabado!\p"
	.string "¡Queridos e intrépidos entrenadores!\p"
	.string "¡No os durmáis y seguid ampliando\n"
	.string "esa ventaja sobre vuestros rivales!$"

TrendWatcher_Text_Intro::
	.string "¡Lo Más Azuliza, Lo Más in!\p"
	.string "Presentador: ¿Cómo lo lleváis, gente?\n"
	.string "Aquí os ponemos al día de lo que se dice\l"
	.string "entre los más guays de Azuliza.\p"
	.string "Hoy, nuestro invitado es este genio\n"
	.string "de la tercera edad que presume de\l"
	.string "saber todo, todito sobre Azuliza.\p"
	.string "Anciano: Ése soy yo.\p"
	.string "Presentador: Vamos al grano, escribano.\p"
	.string "¿Qué es lo que más les mola decir\n"
	.string "a los guays de Azuliza?\p"
	.string "Anciano: {STR_VAR_1} {STR_VAR_2}.\p"
	.string "Presentador: ¿Has dicho…\n"
	.string "{STR_VAR_1} {STR_VAR_2}?\p"
	.string "Anciano: Bueno, eso decían.\p"
	.string "Aunque {STR_VAR_1} {STR_VAR_2}\n"
	.string "nunca acabó de cuajar.\p"
	.string "¿Y quieres saber por qué?\p"
	.string "Presentador: Ah, no. Lo que queremos\n"
	.string "saber es lo que más se lleva ahora…$"

TrendWatcher_Text_MaleTaughtMePhrase::
	.string "Anciano: {STR_VAR_1} {STR_VAR_2}\n"
	.string "es lo que {STR_VAR_3} de Villa Raíz\l"
	.string "me dijo que estaba de moda…$"

TrendWatcher_Text_FemaleTaughtMePhrase::
	.string "Anciano: {STR_VAR_1} {STR_VAR_2}\n"
	.string "es lo que {STR_VAR_3} de Villa Raíz\l"
	.string "me dijo que estaba de moda…$"

TrendWatcher_Text_PhraseWasHopeless::
	.string "Pero la cosa no acabó de pegar fuerte.\p"
	.string "¡Festival {STR_VAR_1} {STR_VAR_2}!\p"
	.string "¡Concurso {STR_VAR_1} {STR_VAR_2}!\p"
	.string "Traté de enseñárselo a toda la peña\n"
	.string "lo mejor que pude, pero…\p"
	.string "Quizás eso de {STR_VAR_1} rallaba\n"
	.string "un poco…\p"
	.string "Presentador: Oye, abuelo, te he dicho\n"
	.string "que yo quiero saber lo que mola ahora…$"

TrendWatcher_Text_MaleTellMeBigger::
	.string "Anciano: ¡{STR_VAR_3}!\n"
	.string "¡Anda, dime algo que tenga más fuerza\l"
	.string "que {STR_VAR_1} {STR_VAR_2}!$"

TrendWatcher_Text_FemaleTellMeBigger::
	.string "Anciano: ¡{STR_VAR_3}!\n"
	.string "¡Anda, dime algo que tenga más fuerza\l"
	.string "que {STR_VAR_1} {STR_VAR_2}!$"

TrendWatcher_Text_Outro::
	.string "Presentador: Eh… ¡Bueno, ahí lo tenéis,\n"
	.string "todos vosotros, amigos de lo más!\p"
	.string "{STR_VAR_1} {STR_VAR_2}… Esto…\n"
	.string "¡No acabó de cuajar en Azuliza!\p"
	.string "No hay tiempo para más. ¡Nos vemos!\p"
	.string "Anciano: ¡{STR_VAR_1} {STR_VAR_2}!$"

gTVHoennTreasureInvestigatorsText00::
	.string "¡Los tesoros de Hoenn!\p"
	.string "¡Hola, amigos y amigas televidentes!\n"
	.string "¿Seguís buscando ese objeto perdido?\p"
	.string "¡Como siempre, vamos a examinar\n"
	.string "las cartas que nos llegan de testigos\l"
	.string "que al menos han visto alguno!\p"
	.string "Hoy vamos a leer esta carta.\n"
	.string "Dice así: “¡{STR_VAR_1}, qué envidia!”$"

gTVHoennTreasureInvestigatorsText01::
	.string "¡Guau! ¡Qué interesante!…\n"
	.string "Pero sigamos leyendo…\p"
	.string "“Queridos investigadores:\n"
	.string "Enhorabuena por el programa.\p"
	.string "Resulta que el otro día, cerca\n"
	.string "de {STR_VAR_3}, vi a {STR_VAR_2}.\p"
	.string "¡Y vi cómo encontró una unidad\n"
	.string "de {STR_VAR_1}! ¡Qué envidia me dio!”\p"
	.string "¡Enhorabuena, {STR_VAR_2}!\p"
	.string "¡Y ojalá esto sirva para animaros a los\n"
	.string "que estáis en vuestra casa a encender\l"
	.string "el Buscaobjetos y salir a buscar!\p"
	.string "¡Espero ansioso vuestras noticias!$"

gTVHoennTreasureInvestigatorsText02::
	.string "¡Guau! ¡Qué interesante!…\n"
	.string "Pero sigamos leyendo…\p"
	.string "“Queridos investigadores:\n"
	.string "Enhorabuena por el programa.\p"
	.string "El otro día vi a {STR_VAR_2} en un ferry.\p"
	.string "¡Y vi cómo encontró una unidad\n"
	.string "de {STR_VAR_1}! ¡Qué envidia me dio!”\p"
	.string "¡Enhorabuena, {STR_VAR_2}!\p"
	.string "¡Y ojalá esto sirva para animaros a los\n"
	.string "que estáis en vuestra casa a encender\l"
	.string "el Buscaobjetos y salir a buscar!\p"
	.string "¡Espero ansioso vuestras noticias!$"

gTVFindThatGamerText00::
	.string "¡Casi sí, casi no!\p"
	.string "¡Hola, incansables jugadores!\n"
	.string "¿Cómo va la suerte en esa {STR_VAR_2}?\p"
	.string "Como solemos hacer, hoy nos hemos\n"
	.string "fijado en alguien muy especial que\l"
	.string "ha visitado nuestro Casino.\p"
	.string "Hoy, nuestro jugador número 1 es…\n"
	.string "¡{STR_VAR_1}!$"

gTVFindThatGamerText01::
	.string "¡{STR_VAR_1} ganó en la {STR_VAR_2}\n"
	.string "nada menos que {STR_VAR_3} Fichas!\p"
	.string "“Cuando viene, hay que asegurarse\n"
	.string "de tener suficientes Fichas.”\p"
	.string "¡Eso es lo que dicen los crupier del\n"
	.string "Casino cuando hablan de {STR_VAR_1}!\p"
	.string "Queridos amigos, controlad las Fichas\n"
	.string "como hace {STR_VAR_1} cuando vengáis\l"
	.string "al Casino a jugar a la {STR_VAR_2}.\p"
	.string "¡Y eso es todo desde aquí, desde\n"
	.string "el Casino donde “casi” no pierde nadie!\p"
	.string "¡Hasta la próxima!$"

gTVFindThatGamerText02::
	.string "¡{STR_VAR_1} jugó a la {STR_VAR_2}\n"
	.string "y perdió {STR_VAR_3} Fichas!\p"
	.string "“Cuando viene por aquí,\n"
	.string "hacemos el agosto en Fichas.”\p"
	.string "¡Eso es lo que dicen los crupier del\n"
	.string "Casino cuando hablan de {STR_VAR_1}!$"

gTVFindThatGamerText03::
	.string "Queridos amigos, controlad las Fichas\n"
	.string "como hace {STR_VAR_1} cuando vengáis\l"
	.string "al Casino a jugar a la {STR_VAR_2}.\p"
	.string "¡Y eso es todo desde aquí, desde\n"
	.string "el Casino donde “casi” no pierde nadie!\p"
	.string "¡Hasta la próxima!$"

gTVBreakingNewsText00::
	.string "¡Especial informativo!$"

gTVBreakingNewsText01::
	.string "¡{STR_VAR_1} ha logrado\n"
	.string "capturar un {STR_VAR_2} raro!\p"
	.string "¡Estamos en directo,\n"
	.string "cerca de {STR_VAR_3}!\p"
	.string "¡Hace poco, {STR_VAR_1} ha capturado\n"
	.string "aquí un raro ejemplar de {STR_VAR_2}!$"

gTVBreakingNewsText02::
	.string "Cuando {STR_VAR_1} se encontró\n"
	.string "con el raro ejemplar de {STR_VAR_2},\l"
	.string "sacó a su Pokémon {STR_VAR_3}.$"

gTVBreakingNewsText03::
	.string "Capturarlo le costó\n"
	.string "{STR_VAR_1} de sus Poké Balls.\p"
	.string "Al final, logró encerrar al Pokémon\n"
	.string "en una {STR_VAR_2}.$"

gTVBreakingNewsText04::
	.string "Al instante, los gritos de alegría\n"
	.string "de {STR_VAR_1} se podían oír hasta en\l"
	.string "el último rincón de {STR_VAR_2}.\p"
	.string "Reconozco que hasta yo tuve envidia.\n"
	.string "¿A quién no le gustaría gritar así?\p"
	.string "¡Y con la alegre noticia de este día\n"
	.string "nos despedimos hasta otra ocasión!$"

gTVBreakingNewsText05::
	.string "¡{STR_VAR_1} ha fracasado al intentar\n"
	.string "capturar un {STR_VAR_2} raro!\p"
	.string "¡Estamos en directo,\n"
	.string "cerca de {STR_VAR_3}!\p"
	.string "¡Ha sido aquí donde, hace muy poco,\n"
	.string "un raro ejemplar de {STR_VAR_2}\l"
	.string "se le ha escapado a {STR_VAR_1}!$"

gTVBreakingNewsText06::
	.string "Cuando {STR_VAR_1} se encontró\n"
	.string "con el raro ejemplar de {STR_VAR_2},\l"
	.string "sacó a su Pokémon {STR_VAR_3}.$"

gTVBreakingNewsText07::
	.string "Cuando tenía todo a su favor, ordenó\n"
	.string "a {STR_VAR_2} usar {STR_VAR_1}.\p"
	.string "Sin quererlo, ese movimiento debilitó\n"
	.string "al Pokémon que pretendía capturar…$"

gTVBreakingNewsText12::
	.string "Sin embargo, {STR_VAR_1} debió de\n"
	.string "pasarlo mal al ver al {STR_VAR_2} raro.\p"
	.string "Quizás por eso ordenó a {STR_VAR_3}\n"
	.string "atacar.\p"
	.string "Sin quererlo, al atacar debilitó\n"
	.string "al Pokémon que pretendía capturar…$"

gTVBreakingNewsText08::
	.string "Al instante, los lamentos de {STR_VAR_1}\n"
	.string "se podían oír hasta en el último rincón\l"
	.string "de {STR_VAR_2}…$"

gTVBreakingNewsText09::
	.string "Sin embargo, parece que {STR_VAR_1}\n"
	.string "se quedó sin Poké Balls.\p"
	.string "{STR_VAR_1} no tuvo más remedio\n"
	.string "entonces que abandonar\l"
	.string "el combate contra el {STR_VAR_2} raro.\p"
	.string "Al instante, los lamentos de {STR_VAR_1}\n"
	.string "se podían oír hasta en el último rincón\l"
	.string "de {STR_VAR_3}…$"

gTVBreakingNewsText10::
	.string "Sin embargo, {STR_VAR_2} huyó\n"
	.string "de manera inesperada.\p"
	.string "Al instante, los lamentos de {STR_VAR_1}\n"
	.string "se podían oír hasta en el último rincón\l"
	.string "de {STR_VAR_3}…$"

gTVBreakingNewsText11::
	.string "Debo reconocer que yo también comparto\n"
	.string "la desesperación de {STR_VAR_1}…\p"
	.string "Y, con este lamento, nos despedimos\n"
	.string "de todos hasta una nueva ocasión.$"

gTVSecretBaseVisitText00::
	.string "¡Hola, queridos amigos!\n"
	.string "Es hora de hacer otra de nuestras\l"
	.string "Visitas a la Base Secreta.\p"
	.string "Hoy visitaremos la Base Secreta\n"
	.string "de {STR_VAR_1}.\p"
	.string "¿Qué toque especial le habrá dado\n"
	.string "{STR_VAR_1} a su Base Secreta?\p"
	.string "¡Vamos a verlo!\n"
	.string "Mmm…$"

gTVSecretBaseVisitText01::
	.string "¡Oh!\n"
	.string "¡Qué maravilla!\p"
	.string "Aquí ha puesto su {STR_VAR_2}…\n"
	.string "¡Vaya, no esperaba encontrar aquí\l"
	.string "una cosa así!$"

gTVSecretBaseVisitText02::
	.string "¡Oh!\n"
	.string "¡Fantástico!\p"
	.string "¡No hay ni un solo mueble!\n"
	.string "¡Ni siquiera un adorno!\p"
	.string "¡Esto sí que es una declaración\n"
	.string "de principios decorativos!\p"
	.string "¡Minimalismo extremo, sí,\n"
	.string "un minimalismo impresionante!\p"
	.string "Me descubro ante ti, {STR_VAR_1}.\n"
	.string "¡Quién si no!$"

gTVSecretBaseVisitText03::
	.string "¡Ah, ya veo!\n"
	.string "¡Lo veo perfectamente!\p"
	.string "Has puesto aquí tu {STR_VAR_2}…\n"
	.string "¡La idea está clara!$"

gTVSecretBaseVisitText04::
	.string "¡Ah, ya veo!\n"
	.string "¡Y con toda claridad, lo veo!\p"
	.string "El interior no tiene nada de decoración.\p"
	.string "¡La idea está clara!$"

gTVSecretBaseVisitText05::
	.string "¡Aaaaah!\p"
	.string "¡Excelente poner su {STR_VAR_2}\n"
	.string "al lado de su {STR_VAR_3}!\p"
	.string "¡El resultado es sin duda\n"
	.string "una combinación magnífica!$"

gTVSecretBaseVisitText06::
	.string "¡Aaaaah!\p"
	.string "Al colocar aquí su {STR_VAR_2},\n"
	.string "justo aquí…\p"
	.string "¡Su presencia llena por completo\n"
	.string "la Base Secreta!$"

gTVSecretBaseVisitText07::
	.string "¡Aaaaah!\p"
	.string "Aquí no hay colocado nada.\p"
	.string "Este espacio vacío tiene un impacto\n"
	.string "en toda la Base Secreta.$"

gTVSecretBaseVisitText08::
	.string "¡Oh!\n"
	.string "¡Aquí llega {STR_VAR_1}!\l"
	.string "¡Que dé comienzo el desafío!\p"
	.string "Mmm…$"

gTVSecretBaseVisitText09::
	.string "¡Extraordinario!…\n"
	.string "¡La victoria es para {STR_VAR_1}!\p"
	.string "Sus Pokémon han estado realmente\n"
	.string "a la altura del título de Campeón.\p"
	.string "Han demostrado que {STR_VAR_1} les\n"
	.string "ha entrenado con enorme dureza.\p"
	.string "Hasta hemos visto que {STR_VAR_2}\n"
	.string "conocía el movimiento {STR_VAR_3}…\p"
	.string "Todo ello muestra la categoría\n"
	.string "de {STR_VAR_1} para entrenar.\p"
	.string "¡Ha sido toda una lección!$"

gTVSecretBaseVisitText10::
	.string "¡Bravo!…\n"
	.string "¡La victoria es para {STR_VAR_1}!\p"
	.string "Sus Pokémon han estado\n"
	.string "realmente magníficos.\p"
	.string "Han demostrado que {STR_VAR_1} les\n"
	.string "ha entrenado con enorme tenacidad.\p"
	.string "Hasta hemos visto que {STR_VAR_2}\n"
	.string "conocía el movimiento {STR_VAR_3}…\p"
	.string "Todo ello muestra la categoría\n"
	.string "de {STR_VAR_1} para entrenar.\p"
	.string "¡Ha sido toda una lección!$"

gTVSecretBaseVisitText11::
	.string "¡Sí!…\n"
	.string "¡La victoria es para {STR_VAR_1}!\p"
	.string "Sus Pokémon sin duda han sido\n"
	.string "entrenados de manera equilibrada.\p"
	.string "Han demostrado que {STR_VAR_1} les\n"
	.string "ha entrenado con enorme seriedad.\p"
	.string "Hasta hemos visto que {STR_VAR_2}\n"
	.string "conocía el movimiento {STR_VAR_3}…\p"
	.string "Todo ello muestra la categoría\n"
	.string "de {STR_VAR_1} para entrenar.\p"
	.string "¡Ha sido toda una lección!$"

gTVSecretBaseVisitText12::
	.string "¡Bien, muy bien!…\n"
	.string "¡La victoria es para {STR_VAR_1}!\p"
	.string "Sus Pokémon han demostrado tener\n"
	.string "un gran potencial de crecimiento.\p"
	.string "Sin duda {STR_VAR_1} tiene depositadas\n"
	.string "en ellos todas sus esperanzas.\p"
	.string "Hasta hemos visto que {STR_VAR_2}\n"
	.string "conocía el movimiento {STR_VAR_3}…\p"
	.string "Todo ello muestra la categoría\n"
	.string "de {STR_VAR_1} para entrenar.\p"
	.string "¡Ha sido toda una lección!$"

gTVSecretBaseVisitText13::
	.string "¡Debo reconocer que ha sido un honor\n"
	.string "conocer en persona esta Base Secreta!\p"
	.string "Amigos y amigas, si tenéis ocasión,\n"
	.string "visitad la Base Secreta de {STR_VAR_1}.\p"
	.string "¡Y desde este magnífico escenario,\n"
	.string "os decimos adiós a todos!$"

gTVPokemonLotteryWinnerFlashReportText00::
	.string "¡Qué emoción!\n"
	.string "¡Qué nervios!\p"
	.string "Es el… \n"
	.string "¡Especial Lotería Pokémon!\p"
	.string "¡Hola! Estamos aquí, en directo, desde\n"
	.string "el Despacho de Lotería Pokémon\l"
	.string "situado en la planta baja del centro\l"
	.string "comercial de Calagua.\p"
	.string "¡Como siempre sucede, hoy ha aparecido\n"
	.string "otro afortunado Entrenador!\p"
	.string "En esta ocasión, la suerte ha ido para…\n"
	.string "¡{STR_VAR_1}!\p"
	.string "¡{STR_VAR_1} ha ganado nada menos que\n"
	.string "el {STR_VAR_2} y se lleva a casa\l"
	.string "su correspondiente {STR_VAR_3}!\p"
	.string "¡{STR_VAR_1}!\n"
	.string "¡Enhorabuena!\p"
	.string "Queridos amigos, no lo olvidéis \n"
	.string "¡vosotros podéis ser los siguientes!\p"
	.string "¡Todos los que trabajamos aquí\n"
	.string "esperamos vuestra visita!\p"
	.string "¡Ha sido una retransmisión en directo\n"
	.string "desde el centro comercial de Calagua,\l"
	.string "donde encontraréis la más amplia\l"
	.string "selección de objetos de todo Hoenn!$"

gTVThePokemonBattleSeminarText00::
	.string "¡LA Moviola Pokémon!\p"
	.string "¡Bienvenidos todos al programa donde\n"
	.string "aprendemos de los errores de los demás!\p"
	.string "Hoy vamos a analizar un combate\n"
	.string "disputado por {STR_VAR_1}.\p"
	.string "El {STR_VAR_2} de {STR_VAR_1} se estaba\n"
	.string "enfrentando a un {STR_VAR_3}…$"

gTVThePokemonBattleSeminarText01::
	.string "Y usó el movimiento {STR_VAR_3}\n"
	.string "contra {STR_VAR_2}…\p"
	.string "Mmm… ¡Pero {STR_VAR_1}!\n"
	.string "¡Eso es justo lo que no debiste hacer!$"

gTVThePokemonBattleSeminarText02::
	.string "Aparte de ese movimiento mal empleado,\n"
	.string "ese {STR_VAR_1} también conocía$"

gTVThePokemonBattleSeminarText03::
	.string "los movimientos {STR_VAR_1},\n"
	.string "{STR_VAR_2} y {STR_VAR_3}.$"

gTVThePokemonBattleSeminarText04::
	.string "los movimientos {STR_VAR_1}\n"
	.string "y {STR_VAR_2}.$"

gTVThePokemonBattleSeminarText05::
	.string "el movimiento {STR_VAR_2}.$"

gTVThePokemonBattleSeminarText06::
	.string "Así que, en esa situación, ¿qué debería\n"
	.string "haber usado un buen Entrenador?…\p"
	.string "¡Claro!\n"
	.string "¡El movimiento {STR_VAR_1}!\p"
	.string "El movimiento {STR_VAR_1} habría\n"
	.string "sido mucho mejor que {STR_VAR_2}.\p"
	.string "¡Queridos telespectadores, aprended de\n"
	.string "este error y combatid con inteligencia!\p"
	.string "¡Hasta el próximo programa!$"

gTVTrainerFanClubText00::
	.string "¡Venga, todos a la vez!\n"
	.string "¡Entrenadores supremos!\p"
	.string "Presentador: ¡Bienvenidos todos!\n"
	.string "¡Hoy hemos traído al estudio a los fans\l"
	.string "de alguien que Entrena como nadie!\p"
	.string "Fans: ¡Uaaaaaaaa!\p"
	.string "Presentador: ¡Alguien que está pegando\n"
	.string "muy fuerte y que se llama…!\p"
	.string "Fans: ¡¡¡{STR_VAR_1}!!! ¡¡¡Uaaaaaa!!!\p"
	.string "Presentador: ¡Venga, todos!\n"
	.string "¡¿Os gusta {STR_VAR_1}?!\p"
	.string "Fans: ¡¡¡Nos encantaaaaa {STR_VAR_1}!!!\p"
	.string "Presentador: ¡¿Qué es lo que más os\n"
	.string "gusta de {STR_VAR_1}?!$"

gTVTrainerFanClubText01::
	.string "Fans: ¡Su estilo al lanzar Poké Balls!$"

gTVTrainerFanClubText02::
	.string "Fans: ¡Su estilo al correr!$"

gTVTrainerFanClubText03::
	.string "Fans: ¡Su manera de crecerse\n"
	.string "cuando la cosa se pone fea!$"

gTVTrainerFanClubText04::
	.string "Fans: ¡Que es quien más sabe\n"
	.string "sobre Pokémon!$"

gTVTrainerFanClubText05::
	.string "Fans: ¡Lo bien que trata\n"
	.string "a todos los Pokémon!$"

gTVTrainerFanClubText06::
	.string "Fans: ¡Lo guay que maneja la bici!$"

gTVTrainerFanClubText07::
	.string "Fans: ¡El ingenio que tiene\n"
	.string "para comprar objetos!$"

gTVTrainerFanClubText08::
	.string "Fans: ¡Los motes tan graciosos\n"
	.string "que les pone a sus Pokémon!$"

gTVTrainerFanClubText09::
	.string "Fans: ¡El estilo que le ha dado\n"
	.string "a su Base Secreta!$"

gTVTrainerFanClubText10::
	.string "Fans: ¡Lo original que es usando las MT!$"

gTVTrainerFanClubText11::
	.string "Presentador: Ya lo veis, tenía razón:\n"
	.string "¡{STR_VAR_1} está pegando muy fuerte!\p"
	.string "Entre los fans de {STR_VAR_1},\n"
	.string "hay un grito muy especial.\p"
	.string "Presentador: Si yo digo {STR_VAR_1},\n"
	.string "vosotros decís…\p"
	.string "Fans: ¡{STR_VAR_2}!\p"
	.string "Fans: ¡{STR_VAR_3}!\p"
	.string "Fans: ¡{STR_VAR_2}!\p"
	.string "Fans: ¡{STR_VAR_3}!\p"
	.string "Presentador: Eso es, si alguien dice,\n"
	.string "“{STR_VAR_1}”…\p"
	.string "Responded: “¡{STR_VAR_2}!\n"
	.string "¡{STR_VAR_3}!”\p"
	.string "¡Suena de una manera especial!\n"
	.string "¡Ahora veo por qué la gente\l"
	.string "se hace Fan de {STR_VAR_1}!\p"
	.string "¡Y ahora todos, desde vuestras casas!\n"
	.string "¡Gritemos juntos a la vez!\p"
	.string "Presentador: Si yo digo {STR_VAR_1},\n"
	.string "vosotros decís…\p"
	.string "Fans: ¡{STR_VAR_2}!\p"
	.string "Fans: ¡{STR_VAR_3}!\p"
	.string "Fans: ¡{STR_VAR_2}!\p"
	.string "Fans: ¡{STR_VAR_3}!\p"
	.string "Presentador: Y ahora me despido\n"
	.string "dándole las gracias a todos los\l"
	.string "Fans de {STR_VAR_1} por venir.\l"
	.string "¡Hasta otra!\p"
	.string "Presentador: Si yo digo {STR_VAR_1},\n"
	.string "vosotros decís…\p"
	.string "Fans: ¡{STR_VAR_2}!\p"
	.string "Fans: ¡{STR_VAR_3}!$"

TVSpotTheCuties_Text_Intro::
	.string "¡Mi adorable monstruito\n"
	.string "con cintas!\p"
	.string "¡Hola, amigas y amigos!\p"
	.string "¿Hay algo que le quede mejor a un\n"
	.string "Pokémon que una bonita cinta?\p"
	.string "Hoy quería hablaros de un Pokémon\n"
	.string "realmente encantador que he visto\l"
	.string "mientras daba uno de mis paseos.\p"
	.string "El Pokémon adorable de hoy es\n"
	.string "el {STR_VAR_2} de {STR_VAR_1}.$"

TVSpotTheCuties_Text_RibbonsLow::
	.string "¿Que cuántas cintas llevaba puestas?\n"
	.string "¡Esa monada de {STR_VAR_2} llevaba {STR_VAR_3}!\p"
	.string "Creo que eso dice mucho sobre cuánto\n"
	.string "adora {STR_VAR_1} a su Pokémon.$"

TVSpotTheCuties_Text_RibbonsMid::
	.string "¡{STR_VAR_2} llevaba puestas nada más\n"
	.string "y nada menos que {STR_VAR_3} cintas!\p"
	.string "Creo que eso lo dice todo sobre cuánto\n"
	.string "adora {STR_VAR_1} a su Pokémon.$"

TVSpotTheCuties_Text_RibbonsHigh::
	.string "¡{STR_VAR_2} lleva puestas {STR_VAR_3} cintas!\n"
	.string "¿Podéis creerlo?\p"
	.string "¡Lo de {STR_VAR_1} es\n"
	.string "un amor de coleccionista!$"

TVSpotTheCuties_Text_RibbonIntro::
	.string "Pero echemos un vistazo de cerca\n"
	.string "a las Cintas que lleva {STR_VAR_2}.$"

TVSpotTheCuties_Text_RibbonChampion::
	.string "Llama especialmente la atención\n"
	.string "la cinta campeón.\p"
	.string "{STR_VAR_2} la recibió al entrar\n"
	.string "en el Hall de la Fama.\p"
	.string "Realmente consigue realzar\n"
	.string "el valor de {STR_VAR_2}.\p"
	.string "¡{STR_VAR_2} y la cinta campeón!\n"
	.string "¡La combinación es muy eficaz!$"

TVSpotTheCuties_Text_RibbonCool::
	.string "Llama especialmente la atención\n"
	.string "la cinta Carisma.\p"
	.string "{STR_VAR_2} la recibió al ganar\n"
	.string "el concurso de carisma.\p"
	.string "Realmente consigue realzar\n"
	.string "el carisma de {STR_VAR_2}.\p"
	.string "¡{STR_VAR_2} y la cinta carisma!\n"
	.string "¡La combinación es muy eficaz!$"

TVSpotTheCuties_Text_RibbonBeauty::
	.string "Llama especialmente la atención\n"
	.string "la cinta belleza.\p"
	.string "{STR_VAR_2} la recibió al ganar\n"
	.string "el concurso de belleza.\p"
	.string "Realmente consigue realzar\n"
	.string "la belleza de {STR_VAR_2}.\p"
	.string "¡{STR_VAR_2} y la cinta belleza!\n"
	.string "¡La combinación es muy eficaz!$"

TVSpotTheCuties_Text_RibbonCute::
	.string "Llama especialmente la atención\n"
	.string "la cinta dulzura.\p"
	.string "{STR_VAR_2} la recibió al ganar\n"
	.string "el concurso de dulzura.\p"
	.string "Realmente consigue realzar\n"
	.string "la dulzura de {STR_VAR_2}.\p"
	.string "¡{STR_VAR_2} y la cinta dulzura!\n"
	.string "¡La combinación es muy eficaz!$"

TVSpotTheCuties_Text_RibbonSmart::
	.string "Llama especialmente la atención\n"
	.string "la dinta ingenio.\p"
	.string "{STR_VAR_2} la recibió al ganar\n"
	.string "el concurso de ingenio.\p"
	.string "Realmente consigue realzar\n"
	.string "el ingenio de {STR_VAR_2}.\p"
	.string "¡{STR_VAR_2} y la cinta ingenio!\n"
	.string "¡La combinación es muy eficaz!$"

TVSpotTheCuties_Text_RibbonTough::
	.string "Llama especialmente la atención\n"
	.string "la cinta dureza.\p"
	.string "{STR_VAR_2} la recibió al ganar\n"
	.string "el concurso de dureza.\p"
	.string "Realmente consigue realzar\n"
	.string "la dureza de {STR_VAR_2}.\p"
	.string "¡{STR_VAR_2} y la cinta dureza!\n"
	.string "¡La combinación es muy eficaz!$"

TVSpotTheCuties_Text_RibbonWinning::
	.string "Llama especialmente la atención\n"
	.string "la cinta triunfo.\p"
	.string "{STR_VAR_2} la recibió por sus hazañas\n"
	.string "en la Torre Batalla.\p"
	.string "Realmente consigue realzar\n"
	.string "la grandeza de {STR_VAR_2}.\p"
	.string "¡{STR_VAR_2} y la cinta triunfo!\n"
	.string "¡La combinación es muy eficaz!$"

TVSpotTheCuties_Text_RibbonVictory::
	.string "Llama especialmente la atención\n"
	.string "la cinta victoria.\p"
	.string "{STR_VAR_2} la recibió por sus hazañas\n"
	.string "en la Torre Batalla.\p"
	.string "Realmente consigue realzar\n"
	.string "la enorme grandeza de {STR_VAR_2}.\p"
	.string "¡{STR_VAR_2} y la cinta victoria!\n"
	.string "¡La combinación es muy eficaz!$"

TVSpotTheCuties_Text_RibbonArtist::
	.string "Llama especialmente la atención\n"
	.string "la cinta del artista.\p"
	.string "{STR_VAR_2} la recibió por hacer\n"
	.string "de modelo para un artista.\p"
	.string "Realmente consigue realzar\n"
	.string "el encanto de {STR_VAR_2}.\p"
	.string "¡{STR_VAR_2} y la cinta del artista!\n"
	.string "¡La combinación es muy eficaz!$"

TVSpotTheCuties_Text_RibbonEffort::
	.string "Llama especialmente la atención\n"
	.string "la cinta del esfuerzo.\p"
	.string "{STR_VAR_2} la recibió por su gran\n"
	.string "dedicación y su trabajo.\p"
	.string "Realmente consigue realzar\n"
	.string "la determinación de {STR_VAR_2}.\p"
	.string "¡{STR_VAR_2} y la cinta del esfuerzo!\n"
	.string "¡La combinación es muy eficaz!$"

TVSpotTheCuties_Text_Outro::
	.string "¡Ay!…\p"
	.string "Cintas y Pokémon…\n"
	.string "¡Se complementan tan bien!\p"
	.string "Antes de desmayarme,\n"
	.string "¡adiós y que la belleza os posea!$"

gTVPokemonNewsBattleFrontierText00::
	.string "¡Saludos a nuestros telespectadores!\n"
	.string "Es la hora de las Noticias Pokémon.\p"
	.string "Nos ha llegado la última hora\n"
	.string "desde el Frente de Batalla.$"

gTVPokemonNewsBattleFrontierText01::
	.string "{STR_VAR_1} ha batido un nuevo récord\n"
	.string "al ganar {STR_VAR_2} veces consecutivas\l"
	.string "el desafío del combate individual\l"
	.string "de la Torre Batalla.\p"
	.string "¡Enhorabuena, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText02::
	.string "{STR_VAR_1} ha batido un nuevo récord\n"
	.string "al ganar {STR_VAR_2} veces consecutivas\l"
	.string "el desafío del Combate Doble\l"
	.string "de la Torre Batalla.\p"
	.string "¡Enhorabuena, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText03::
	.string "{STR_VAR_1} ha batido un nuevo récord\n"
	.string "al ganar {STR_VAR_2} veces consecutivas\l"
	.string "el desafío del combate múltiple\l"
	.string "de la Torre Batalla.\p"
	.string "¡Enhorabuena, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText04::
	.string "{STR_VAR_1} ha batido un nuevo récord\n"
	.string "al ganar {STR_VAR_2} veces consecutivas\l"
	.string "el desafío del combate multijugador\l"
	.string "con conexión de la Torre Batalla.\p"
	.string "¡Enhorabuena, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText05::
	.string "{STR_VAR_1} ha batido un nuevo récord\n"
	.string "al ganar {STR_VAR_2} veces consecutivas\l"
	.string "el torneo de combates individuales\l"
	.string "de la Cúpula Batalla.\p"
	.string "¡Enhorabuena, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText06::
	.string "{STR_VAR_1} ha batido un nuevo récord\n"
	.string "al ganar {STR_VAR_2} veces consecutivas\l"
	.string "el Torneo de Combates Dobles\l"
	.string "de la Cúpula Batalla.\p"
	.string "¡Enhorabuena, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText07::
	.string "{STR_VAR_1} ha batido un nuevo récord\n"
	.string "al ganar {STR_VAR_2} veces consecutivas\l"
	.string "el Torneo de Combates\l"
	.string "con trueque individuales\l"
	.string "de la Fábrica Batalla.\p"
	.string "¡Enhorabuena, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText08::
	.string "{STR_VAR_1} ha batido un nuevo récord\n"
	.string "al ganar {STR_VAR_2} veces consecutivas\l"
	.string "el Torneo de Combates\l"
	.string "con Trueque Dobles\l"
	.string "de la Fábrica Batalla.\p"
	.string "¡Enhorabuena, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText09::
	.string "{STR_VAR_1} ha batido un nuevo récord\n"
	.string "al ganar {STR_VAR_2} veces consecutivas\l"
	.string "el desafío de la Elección de Combates\l"
	.string "de la Sierpe Batalla.\p"
	.string "¡Enhorabuena, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText10::
	.string "{STR_VAR_1} ha batido un nuevo récord\n"
	.string "al ganar {STR_VAR_2} veces consecutivas\l"
	.string "el desafío del torneo con juez\l"
	.string "del Dojo Batalla.\p"
	.string "¡Enhorabuena, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText11::
	.string "{STR_VAR_1} ha batido un nuevo récord\n"
	.string "al ganar {STR_VAR_2} veces consecutivas\l"
	.string "el desafío del combate sin tutela\l"
	.string "individual del Palacio Batalla.\p"
	.string "¡Enhorabuena, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText12::
	.string "{STR_VAR_1} ha batido un nuevo récord\n"
	.string "al ganar {STR_VAR_2} veces consecutivas\l"
	.string "el desafío del combate sin tutela\l"
	.string "doble del Palacio Batalla.\p"
	.string "¡Enhorabuena, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText13::
	.string "{STR_VAR_1} ha batido un nuevo récord\n"
	.string "al ganar {STR_VAR_2} veces consecutivas\l"
	.string "el desafío de la expedición de\l"
	.string "combates de la Pirámide Batalla.\p"
	.string "¡Enhorabuena, {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText14::
	.string "¡Y a los tres Pokémon: {STR_VAR_1},\n"
	.string "{STR_VAR_2} y {STR_VAR_3}!\p"
	.string "¡Enhorabuena también por\n"
	.string "vuestra magnífica actuación!$"

gTVPokemonNewsBattleFrontierText15::
	.string "¡Y a los dos Pokémon: {STR_VAR_1}\n"
	.string "y {STR_VAR_2}!\p"
	.string "¡Enhorabuena también por\n"
	.string "vuestra magnífica actuación!$"

gTVPokemonNewsBattleFrontierText16::
	.string "¡Y a los cuatro Pokémon: {STR_VAR_1}!\p"
	.string "¡{STR_VAR_2}!\p"
	.string "¡{STR_VAR_3}!$"

gTVPokemonNewsBattleFrontierText17::
	.string "¡Y {STR_VAR_1}!\p"
	.string "¡Enhorabuena también por\n"
	.string "vuestra magnífica actuación!$"

gTVPokemonNewsBattleFrontierText18::
	.string "¡Esperemos que {STR_VAR_1} y sus leales\n"
	.string "Pokémon sigan cosechando éxitos!\p"
	.string "¡Esto es todo desde Noticias Pokémon!$"

gTVWhatsNo1InHoennTodayText00::
	.string "¿Quién es el n.º 1 de Hoenn?\n"
	.string "¡Sí, aquí estamos otra vez!\p"
	.string "¡Hola, amigos telespectadores!\n"
	.string "¿Estáis esforzándoos todos al máximo\l"
	.string "en lo que estáis haciendo?\p"
	.string "¡Veamos a quién nombramos hoy el\n"
	.string "Entrenador más constante del día!\p"
	.string "El Entrenador n.º 1\n"
	.string "de hoy es… ¡{STR_VAR_1}!$"

gTVWhatsNo1InHoennTodayText01::
	.string "¿Cuántas veces jugó {STR_VAR_1}\n"
	.string "a las tragaperras del Casino\l"
	.string "en un solo día? ¡{STR_VAR_2}!\p"
	.string "Mientras jugaba, se dice que alguien le\n"
	.string "oyó murmurar: “Para mí, que los rodillos\l"
	.string "no se mueven…”\l"
	.string "Interesante, ¿verdad?$"

gTVWhatsNo1InHoennTodayText02::
	.string "¿Cuántas veces jugó {STR_VAR_1}\n"
	.string "a la ruleta del Casino\l"
	.string "en un solo día? ¡{STR_VAR_2}!\p"
	.string "Mientras jugaba, {STR_VAR_1} gritó:\n"
	.string "“¡Que decida la bola!”\p"
	.string "Su mirada estaba fija y en el rostro\n"
	.string "se podía apreciar la concentración.$"

gTVWhatsNo1InHoennTodayText03::
	.string "¡En un solo día, {STR_VAR_1} se enfrentó\n"
	.string "a {STR_VAR_2} Pokémon salvajes!\p"
	.string "Al parecer, los Pokémon de {STR_VAR_1}\n"
	.string "se han hecho increíblemente fuertes.\p"
	.string "¡Están ansiosos por combatir como sea\n"
	.string "en cualquier lugar y a cualquier hora!$"

gTVWhatsNo1InHoennTodayText04::
	.string "¡En un solo día, {STR_VAR_1} giró {STR_VAR_2}\n"
	.string "veces la Licuabayas!\p"
	.string "Dicen que, al final, hasta {STR_VAR_1}\n"
	.string "parecía que se había mareado.\p"
	.string "¡Que iba dando tumbos como un Spinda!$"

gTVWhatsNo1InHoennTodayText05::
	.string "¡En un solo día, {STR_VAR_1} plantó\n"
	.string "{STR_VAR_2} bayas!\p"
	.string "Lógicamente, se manchó toda la ropa.\p"
	.string "Pero ahora, donde plantó las bayas,\n"
	.string "han crecido cientos de flores.\p"
	.string "Dicen que mirar esas flores\n"
	.string "tranquiliza a la gente.$"

gTVWhatsNo1InHoennTodayText06::
	.string "¡En un solo día, {STR_VAR_1} recogió\n"
	.string "{STR_VAR_2} Bayas!\p"
	.string "Dicen que metió tantas bayas en la\n"
	.string "Mochila, que apenas podía caminar.$"

gTVWhatsNo1InHoennTodayText07::
	.string "¡En un solo día, {STR_VAR_1} consiguió\n"
	.string "{STR_VAR_2} Puntos de Batalla!\p"
	.string "{STR_VAR_1} estuvo luego sopesando\n"
	.string "cambiar sus Puntos de Batalla\l"
	.string "por algún objeto o algún adorno\l"
	.string "que le gustase.\p"
	.string "Dicen que sonreía mientras pensaba\n"
	.string "en lo que podía elegir.$"

gTVWhatsNo1InHoennTodayText08::
	.string "¡Bueno! ¿Qué os parece?\p"
	.string "¡{STR_VAR_1}!\n"
	.string "¡N.º 1 de los Entrenadores!\p"
	.string "¡Aprended de {STR_VAR_1}, amigos!\n"
	.string "¡Vosotros también podéis ser el n.º 1!$"

TVSecretBaseSecrets_Text_Intro::
	.string "¡Los secretos de las Bases Secretas!\p"
	.string "¿Queréis saber a qué se dedican los\n"
	.string "entrenadores en sus Bases Secretas?\p"
	.string "Hoy tenemos un reportaje sobre\n"
	.string "la Base Secreta de {STR_VAR_1}.\p"
	.string "¡Oh, parece que {STR_VAR_2} acaba\n"
	.string "de llegar para hacer una visita!\p"
	.string "¡Vamos a echar un vistazo!\p"
	.string "¿Qué hará ahora {STR_VAR_2}?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext1::
	.string "¿Y qué hará {STR_VAR_2} después?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext2::
	.string "¿Y ahora? ¿Qué hará {STR_VAR_2}?$"

TVSecretBaseSecrets_Text_TookXStepsBeforeLeaving::
	.string "Al final, {STR_VAR_2} ha dado {STR_VAR_3} pasos\n"
	.string "en la Base Secreta de {STR_VAR_1}\l"
	.string "antes de salir.$"

TVSecretBaseSecrets_Text_BaseFailedToInterestPlayer::
	.string "Mmm…\p"
	.string "La Base Secreta de {STR_VAR_1} no\n"
	.string "ha interesado demasiado a {STR_VAR_2}…$"

TVSecretBaseSecrets_Text_PlayerEnjoyedBase::
	.string "Parece que {STR_VAR_2} ha disfrutado\n"
	.string "de la Base Secreta de {STR_VAR_1}.$"

TVSecretBaseSecrets_Text_PlayerHugeFanOfBase::
	.string "Vaya, parece que a {STR_VAR_2} le\n"
	.string "encanta la Base Secreta de {STR_VAR_1}.$"

TVSecretBaseSecrets_Text_Outro::
	.string "¡Y no olvidéis que también podéis\n"
	.string "visitar la Base Secreta de {STR_VAR_1}!\p"
	.string "¡Esperamos teneros con nosotros\n"
	.string "en el próximo programa! ¡Adiós!$"

TVSecretBaseSecrets_Text_StoppedMoving1::
	.string "¡Se ha parado!\p"
	.string "¡No mueve ni un dedo!\p"
	.string "¿Tanto le habrá impresionado\n"
	.string "la Base Secreta de {STR_VAR_1}?$"

TVSecretBaseSecrets_Text_StoppedMoving2::
	.string "¡Se ha parado!\p"
	.string "¡No mueve ni un dedo!\p"
	.string "¿Será el cansancio?\n"
	.string "¿Se estará aburriendo?$"

TVSecretBaseSecrets_Text_UsedChair::
	.string "¡Se ha sentado en una silla!\p"
	.string "¡Parece que está muy a gusto!\p"
	.string "¡Tiene toda la pinta de ser\n"
	.string "una silla muy cómoda!$"

TVSecretBaseSecrets_Text_UsedBalloon::
	.string "¡Se ha puesto a jugar con un globo!\p"
	.string "¡Ha estallado!\n"
	.string "¡El globo ha estallado!\p"
	.string "¡Parece que se ha llevado\n"
	.string "un buen susto!$"

TVSecretBaseSecrets_Text_UsedTent::
	.string "¡Ha entrado en una tienda!\p"
	.string "¡Está correteando un poco!\p"
	.string "¡Vaya, parece que está jugueteando!\p"
	.string "¡Parece que le sorprende el tamaño\n"
	.string "de la Tienda!$"

TVSecretBaseSecrets_Text_UsedPlant::
	.string "¡Está examinando una planta!\p"
	.string "¡Ojalá todos los visitantes mostrasen\n"
	.string "un gusto tan refinado!$"

TVSecretBaseSecrets_Text_UsedGoldShield::
	.string "¡Se ha parado justo delante\n"
	.string "de un Escudo de Oro!\p"
	.string "¡Creo que le brillan los ojos\n"
	.string "de la emoción!$"

TVSecretBaseSecrets_Text_UsedSilverShield::
	.string "¡Se ha parado justo delante\n"
	.string "de un Escudo de Plata!\p"
	.string "¡Creo que se le han puesto los ojos\n"
	.string "como platos!$"

TVSecretBaseSecrets_Text_UsedGlassOrnament::
	.string "¡Ahora se fija en un Adorno de Cristal!\p"
	.string "¡Oh, no!\p"
	.string "¡Lo está tocando!\p"
	.string "Lo va a poner perdido de huellas…$"

TVSecretBaseSecrets_Text_UsedTV::
	.string "¡Se pone a ver la televisión!\p"
	.string "¡Parece que tenemos otro teleadicto!$"

TVSecretBaseSecrets_Text_UsedMudBall::
	.string "¡Se encuentra con una Bola de Lodo!\p"
	.string "¡Se muestra radiante!$"

TVSecretBaseSecrets_Text_UsedBag::
	.string "¡Oh!\p"
	.string "¡Parece que está buscando algo\n"
	.string "dentro de su Mochila!\p"
	.string "¡Ha sacado algo!\n"
	.string "Es una especie de… ¡{STR_VAR_2}!\p"
	.string "¡Mirad cómo sonríe mientras sostiene\n"
	.string "su {STR_VAR_2} en la mano!\p"
	.string "¡Igual que en un anuncio de la tele!$"

TVSecretBaseSecrets_Text_UsedCushion::
	.string "Ha echado mano de un cojín…$"

TVSecretBaseSecrets_Text_HitCushion::
	.string "¡Y ha empezado a darle golpes!\p"
	.string "¿Será cosa del estrés?$"

TVSecretBaseSecrets_Text_HuggedCushion::
	.string "¡Y lo ha abrazado con mucha fuerza!\p"
	.string "¿Será que se siente feliz por algo?$"

TVSecretBaseSecrets_Text_BattledWon::
	.string "¡Se ha puesto a hablar con {STR_VAR_1}!\p"
	.string "¡Creo que se van a poner a luchar!\p"
	.string "Y…\p"
	.string "¡Ha ganado!\n"
	.string "¡Ha ganado el equipo visitante!\p"
	.string "¡Y ahora lo celebra poniéndose a bailar!$"

TVSecretBaseSecrets_Text_BattledLost::
	.string "¡Se ha puesto a hablar con {STR_VAR_1}!\p"
	.string "¡Creo que se van a poner a luchar!\p"
	.string "Y…\p"
	.string "¡Ha perdido!\n"
	.string "¡Ha perdido el equipo visitante!\p"
	.string "¡No le ha sentado nada bien la derrota!$"

TVSecretBaseSecrets_Text_DeclinedBattle::
	.string "¡Se ha puesto a hablar con {STR_VAR_1}!\p"
	.string "¡Creo que se van a poner a luchar!\p"
	.string "Y…\p"
	.string "No, se ha echado atrás.\p"
	.string "¡Parece que al final no habrá combate!\p"
	.string "¿Será que no le gustó nada {STR_VAR_1}?$"

TVSecretBaseSecrets_Text_UsedPoster::
	.string "¡Se ha fijado en un póster!\p"
	.string "¿Le estará gustando?\p"
	.string "Pero… Hay algo raro\n"
	.string "en su manera de mirar el póster.$"

TVSecretBaseSecrets_Text_UsedNoteMat::
	.string "¡Se ha puesto encima de un Tapete Nota!\p"
	.string "Mmm…\n"
	.string "¡No está mal esa melodía!$"

TVSecretBaseSecrets_Text_BattledDraw::
	.string "¡Se ha puesto a hablar con {STR_VAR_1}!\p"
	.string "¡Creo que se van a poner a luchar!\p"
	.string "Y…\p"
	.string "¡Ha habido un empate!\n"
	.string "¡No ha habido ganador!\p"
	.string "¡El empate no le ha gustado a nadie!$"

TVSecretBaseSecrets_Text_UsedSpinMat::
	.string "¡Se ha puesto encima de un Tapete Giro!\p"
	.string "¡Parece que se ha mareado!\p"
	.string "¡Se tambalea! ¡Cuidado!$"

TVSecretBaseSecrets_Text_UsedSandOrnament::
	.string "¡Ha echado mano a un Adorno Arena!\p"
	.string "¡Oh!\p"
	.string "¡Se está desmoronando!\n"
	.string "¡Se va a quedar en nada!\p"
	.string "¡Parece que le invade un sentimiento\n"
	.string "de vergüenza y de culpa!$"

TVSecretBaseSecrets_Text_UsedDesk::
	.string "¡Está pasando el dedo por la mesa!\p"
	.string "Al parecer, no le gusta mucho el polvo.\p"
	.string "¡Espero no tener muchos visitantes\n"
	.string "así en mi casa!$"

TVSecretBaseSecrets_Text_UsedBrick::
	.string "¡Se ha parado delante de un Ladrillo!\p"
	.string "Quizás esté pensando en el objeto\n"
	.string "que hay encima del Ladrillo.$"

TVSecretBaseSecrets_Text_UsedSolidBoard::
	.string "Se ha puesto a andar sobre una Tabla.\p"
	.string "No deja de mirar para abajo.\p"
	.string "¡Parece que mide cada paso que da!$"

TVSecretBaseSecrets_Text_UsedFence::
	.string "¡Está mirando con curiosidad una Valla!\p"
	.string "¿Estará pensando en hacer algún\n"
	.string "tipo de trampa?$"

TVSecretBaseSecrets_Text_UsedGlitterMat::
	.string "¡Se ha parado sobre un Tapete Brillo!\p"
	.string "¡Está haciendo poses!\p"
	.string "¡Quizás sueñe con la fama!$"

TVSecretBaseSecrets_Text_UsedTire::
	.string "¡Está mirando con curiosidad\n"
	.string "un Neumático!\p"
	.string "¿Estará pensando en el coche\n"
	.string "que podría llevarlo?$"

TVSecretBaseSecrets_Text_UsedStand::
	.string "¡Se ha subido a un Podio!\p"
	.string "¡Y ahora está viendo desde arriba\n"
	.string "la Base Secreta de {STR_VAR_1}!\p"
	.string "Y…\p"
	.string "¡Ha emitido una especie de rugido!\n"
	.string "¡Está rugiendo!$"

TVSecretBaseSecrets_Text_BrokeDoor::
	.string "¡Se ha lanzado de cabeza contra\n"
	.string "una Puerta Rara!\p"
	.string "¡Y se ha puesto a reír de forma\n"
	.string "escandalosa!$"

TVSecretBaseSecrets_Text_UsedDoll::
	.string "¡No puedo creerlo!\n"
	.string "¡Está hablando con un Muñeco!\p"
	.string "Sin comentarios…$"

TVSecretBaseSecrets_Text_UsedSlide::
	.string "¡Está subiendo por la escalera\n"
	.string "de un Tobogán!\p"
	.string "Y…\p"
	.string "¡Se ha tirado!\p"
	.string "¡Parece que está recordando\n"
	.string "los viejos y buenos tiempos!$"

TVSecretBaseSecrets_Text_UsedSlideButDidntGoDown::
	.string "¡Está subiendo por la escalera\n"
	.string "de un Tobogán!\p"
	.string "Y…\p"
	.string "¡Se ha dado la vuelta!\p"
	.string "¿Le habrá dado miedo de repente?$"

TVSecretBaseSecrets_Text_UsedJumpMat::
	.string "¡Se ha puesto sobre un Tapete Muelle!\p"
	.string "¡Y salta una vez!\p"
	.string "¡Y dos!\p"
	.string "¡Y cae bien al suelo!\p"
	.string "¡Está aplaudiendo!\n"
	.string "¡Qué actuación!$"

gTVSafariFanClubText00::
	.string "¡Club Safari!\p"
	.string "Reportero: ¡Hola, queridos primates!\n"
	.string "¿Aún os queda una Safari Ball vacía?\p"
	.string "¡Como podéis imaginar, estoy en la Zona\n"
	.string "Safari, plagada de Pokémon increíbles!\p"
	.string "¡Hoy tenemos con nosotros a alguien\n"
	.string "que trabaja como guía del safari!\p"
	.string "Dime, colega, ¿qué tal lo están haciendo\n"
	.string "los Entrenadores que andan por aquí?$"

gTVSafariFanClubText01::
	.string "Guía: Pues parece que todos\n"
	.string "se lo están tomando muy en serio.\p"
	.string "{STR_VAR_1} lo está haciendo\n"
	.string "especialmente bien.\p"
	.string "¡Con decirte que antes\n"
	.string "atrapó {STR_VAR_2} Pokémon!$"

gTVSafariFanClubText02::
	.string "Se le dan bien los Pokécubos.\n"
	.string "Esa vez usó {STR_VAR_2}, creo.$"

gTVSafariFanClubText03::
	.string "Eso sí, ¡no ha usado ni un solo Pokécubo!\n"
	.string "¡Ni uno solo!\p"
	.string "Eso sí que es saber hacer las cosas.$"

gTVSafariFanClubText04::
	.string "Reportero: ¿En serio? ¡Vaya!\p"
	.string "¡Parece que {STR_VAR_1} tiene instinto\n"
	.string "cazador para esto del Safari!\p"
	.string "Guía: ¡Ojalá vuelva otro día\n"
	.string "y nos enseñe su técnica!$"

gTVSafariFanClubText05::
	.string "Guía: Pues la verdad es\n"
	.string "que no destaca ninguno.\p"
	.string "A {STR_VAR_1} se le ha dado\n"
	.string "especialmente mal.\p"
	.string "Sólo consiguió atrapar\n"
	.string "{STR_VAR_2} Pokémon.$"

gTVSafariFanClubText06::
	.string "Guía: Pues la verdad es\n"
	.string "que no destaca ninguno.\p"
	.string "A {STR_VAR_1} se le ha dado\n"
	.string "especialmente mal.\p"
	.string "No ha conseguido atrapar\n"
	.string "ni un triste Pokémon.$"

gTVSafariFanClubText07::
	.string "Y eso que usó Pokécubos.\n"
	.string "Concretamente {STR_VAR_2}, si mal no recuerdo.\p"
	.string "Pero, oye, más le valdría practicar\n"
	.string "un poco más con ellos.$"

gTVSafariFanClubText08::
	.string "Creo que habría tenido más suerte\n"
	.string "si hubiese usado Pokécubos, \l"
	.string "pero no los usó para nada.$"

gTVSafariFanClubText09::
	.string "Reportero: ¿En serio? ¡Vaya!\p"
	.string "¡Creo que {STR_VAR_1} necesita mejorar\n"
	.string "su instinto cazador en el Safari!\p"
	.string "GUÍA: ¡Ojalá vuelva más veces,\n"
	.string "a ver si le pilla el tranquillo!$"

gTVSafariFanClubText10::
	.string "Reportero: ¡Así es!\n"
	.string "¡Uno debe saber afrontar los retos!\p"
	.string "¡Queridos teleprimates, visitad\n"
	.string "el Safari y despertad vuestro\l"
	.string "instinto cazador recolector!\p"
	.string "¡Hasta la próxima!$"

ContestLiveUpdates_Text_Intro::
	.string "¡Última Hora de ConcursoS Pokémon!\p"
	.string "Presentador: ¡Saludos a todos!\p"
	.string "Estamos emitiendo en directo desde\n"
	.string "el lugar donde se ha celebrado\l"
	.string "el último Concurso de {STR_VAR_1}.\p"
	.string "Nos rodea un público enfervorizado\n"
	.string "que se resiste a marcharse.\p"
	.string "Espectador: ¡Arriba {STR_VAR_2}!\p"
	.string "Espectador: ¡Viva {STR_VAR_3}!\p"
	.string "Presentador: Como podéis\n"
	.string "oír, el Pokémon {STR_VAR_2} de\l"
	.string "{STR_VAR_3} ha ganado el Concurso.\p"
	.string "Espectador: ¡{STR_VAR_2},\n"
	.string "eres increíble!\p"
	.string "Espectador: ¡{STR_VAR_3},\n"
	.string "sigue así!\p"
	.string "Presentador: Ahora vamos a recoger\n"
	.string "las impresiones de algunos fans.$"

ContestLiveUpdates_Text_WonBothRounds::
	.string "Espectador: ¡{STR_VAR_2} ha arrasado\n"
	.string "tanto en la primera como\l"
	.string "en la segunda votación!\p"
	.string "¡{STR_VAR_2} ha nacido para ganar!$"

ContestLiveUpdates_Text_BetterRound2::
	.string "Espectador: ¡{STR_VAR_2} no tuvo un\n"
	.string "gran resultado en la primera votación,\l"
	.string "pero recuperó puestos en la segunda!\p"
	.string "{STR_VAR_2} logró sorprender\n"
	.string "a todos. ¡Hurra!$"

ContestLiveUpdates_Text_EqualRounds::
	.string "Espectador: {STR_VAR_2} tuvo una\n"
	.string "actuación consistente tanto en la\l"
	.string "primera como en la segunda votación.\p"
	.string "{STR_VAR_3} y {STR_VAR_2} forman\n"
	.string "un equipo extraordinario.$"

ContestLiveUpdates_Text_BetterRound1::
	.string "Espectador: En lo que respecta a\n"
	.string "{STR_VAR_1}, {STR_VAR_2} es alucinante.\p"
	.string "Pero espero que haga mejores\n"
	.string "exhibiciones la próxima vez.$"

ContestLiveUpdates_Text_GotNervous::
	.string "Espectador: Cuando {STR_VAR_2} se puso\n"
	.string "nervioso, lo animé todo lo que pude.\p"
	.string "Quisiera poder decir a {STR_VAR_2}\n"
	.string "que ha estado espectacular.$"

ContestLiveUpdates_Text_StartledFoes::
	.string "Espectador: La exhibición de\n"
	.string "{STR_VAR_2} me ha dejado sin habla.\p"
	.string "¡{STR_VAR_2}, eres grande!$"

ContestLiveUpdates_Text_UsedCombo::
	.string "Espectador: El combo que ha realizado\n"
	.string "{STR_VAR_2} ha sido excepcional.\p"
	.string "¡Me ha llegado a lo más hondo!$"

ContestLiveUpdates_Text_ExcitingAppeal::
	.string "Espectador: ¡La exhibición ganadora\n"
	.string "de {STR_VAR_2} me ha impresionado!$"

ContestLiveUpdates_Text_WasCool::
	.string "¡{STR_VAR_2}, has demostrado\n"
	.string "tener mucho carisma!$"

ContestLiveUpdates_Text_WasBeautiful::
	.string "¡{STR_VAR_2}, has demostrado\n"
	.string "poseer una gran belleza!$"

ContestLiveUpdates_Text_WasCute::
	.string "¡{STR_VAR_2}, has demostrado\n"
	.string "poseer una gran dulzura!$"

ContestLiveUpdates_Text_WasSmart::
	.string "¡{STR_VAR_2}, has demostrado\n"
	.string "tener mucho ingenio!$"

ContestLiveUpdates_Text_WasTough::
	.string "¡{STR_VAR_2}, has demostrado\n"
	.string "gran dureza!$"

ContestLiveUpdates_Text_VeryExcitingAppeal::
	.string "Espectador: ¡La exhibición ganadora\n"
	.string "de {STR_VAR_2} me sigue impresionando!$"

ContestLiveUpdates_Text_VeryCool::
	.string "¡{STR_VAR_2}, tu carisma\n"
	.string "es inconmensurable!$"

ContestLiveUpdates_Text_VeryBeautiful::
	.string "¡{STR_VAR_2}, tu belleza\n"
	.string "no tiene igual!$"

ContestLiveUpdates_Text_VeryCute::
	.string "¡{STR_VAR_2}, no hay quien\n"
	.string "te supere en dulzura!$"

ContestLiveUpdates_Text_VerySmart::
	.string "¡{STR_VAR_2}, tu ingenio\n"
	.string "es sobresaliente!$"

ContestLiveUpdates_Text_VeryTough::
	.string "¡{STR_VAR_2}, no hay quien\n"
	.string "te gane en dureza!$"

ContestLiveUpdates_Text_TookBreak::
	.string "Espectador: Incluso cuando {STR_VAR_2}\n"
	.string "detuvo sus exhibiciones,\l"
	.string "no podía apartar los ojos de él.\p"
	.string "Ese {STR_VAR_2} me tiene a cuadros.$"

ContestLiveUpdates_Text_GotStartled::
	.string "Espectador: Cuando {STR_VAR_2} se\n"
	.string "asustó con la exhibición de otro\l"
	.string "Pokémon, casi me echo a llorar.\p"
	.string "¡{STR_VAR_2}, tú puedes! ¡Adelante!$"

ContestLiveUpdates_Text_MoveWonderful::
	.string "Espectador: Oh…\n"
	.string "¡{STR_VAR_2} ha usado {STR_VAR_3}!\l"
	.string "¡{STR_VAR_2} ha usado {STR_VAR_3}!\l"
	.string "¡{STR_VAR_2} ha usado {STR_VAR_3}!\l"
	.string "¿Cómo logra hacerlo tan bien?$"

ContestLiveUpdates_Text_TalkAboutAnotherMon::
	.string "Presentador: ¡Como veis, este lugar\n"
	.string "está lleno de fans de {STR_VAR_1}!\p"
	.string "También debemos mencionar que hay\n"
	.string "otro Pokémon que nos ha llamado la \l"
	.string "atención: el {STR_VAR_3} de {STR_VAR_2}.\p"
	.string "{STR_VAR_3}, de {STR_VAR_2}…$"

ContestLiveUpdates_Text_FailedToAppeal::
	.string "Su nerviosismo le impidió exhibirse\n"
	.string "en la segunda votación.\p"
	.string "Esperamos que {STR_VAR_1} haga al \n"
	.string "menos una exhibición la próxima vez.$"

ContestLiveUpdates_Text_LastInBothRounds::
	.string "Acabó en último lugar tanto en la\n"
	.string "primera como en la segunda votación.\p"
	.string "Esperamos que {STR_VAR_1} entrene mejor\n"
	.string "a {STR_VAR_2} y nos haga olvidar este\l"
	.string "vergonzoso último puesto.$"

ContestLiveUpdates_Text_NotExcitingEnough::
	.string "No consiguió sacar partido del\n"
	.string "entusiasmo del público y hacer\l"
	.string "una exhibición adecuada.\p"
	.string "Esperamos que {STR_VAR_1} aprenda\n"
	.string "a conectar mejor con el público\l"
	.string "y a avivar su interés la próxima vez.$"

ContestLiveUpdates_Text_LostAfterWinningRound1::
	.string "Aunque logró el primer puesto en la\n"
	.string "primera votación, su exhibición en\l"
	.string "la segunda no acabó de cuajar.\p"
	.string "De hecho, sufrió una derrota\n"
	.string "inesperada y humillante.\p"
	.string "Seguro que {STR_VAR_1} está planteándose\n"
	.string "cómo exhibirse de forma más eficaz.$"

ContestLiveUpdates_Text_NeverExciting::
	.string "El público no llegó a emocionarse\n"
	.string "con las exhibiciones que realizó\l"
	.string "en la segunda votación.\p"
	.string "Esperamos que deje de preocuparse\n"
	.string "por los demás Pokémon y aprenda\l"
	.string "a conectar mejor con el público.$"

ContestLiveUpdates_Text_LostBySmallMargin::
	.string "Perdió ante el {STR_VAR_2} de\n"
	.string "{STR_VAR_1} por muy poco.\p"
	.string "Haber rozado la victoria tan\n"
	.string "de cerca debe de ser horrible.\p"
	.string "No sería sorprendente que este\n"
	.string "resultado haya afligido a {STR_VAR_3}.$"

ContestLiveUpdates_Text_RepeatedAppeals::
	.string "Decepcionó al juez al repetir\n"
	.string "las mismas exhibiciones.\p"
	.string "Se trata de un error imperdonable en\n"
	.string "cualquier Concurso y lo ha pagado caro.\p"
	.string "{STR_VAR_1} debería avergonzarse\n"
	.string "de una actuación tan pobre.$"

ContestLiveUpdates_Text_ValiantEffortButLost::
	.string "{STR_VAR_1} dio lo mejor de sí, pero a\n"
	.string "pesar de todo acabó en último lugar.\p"
	.string "{STR_VAR_1} debería aprender de esta\n"
	.string "derrota para la próxima vez.$"

ContestLiveUpdates_Text_Outro::
	.string "Vamos a concluir este programa\n"
	.string "con nuestra tradicional despedida\l"
	.string "conjunta a los ganadores.\p"
	.string "¡Hablamos de {STR_VAR_1} y {STR_VAR_2}!\p"
	.string "Presentador: ¿Estáis listos?\n"
	.string "¡Venga, todos a la vez!\p"
	.string "Público: ¡{STR_VAR_1}! ¡{STR_VAR_2}!\n"
	.string "¡Enhorabuena!\l"
	.string "¡Habéis ganado el Concurso!$"

gTVPokemonBattleUpdateText00::
	.string "¡Última Hora de Combates Pokémon!\p"
	.string "¡Os traemos los resultados de los\n"
	.string "combates Pokémon más recientes!$"

gTVPokemonBattleUpdateText01::
	.string "{STR_VAR_1} y {STR_VAR_2} se han\n"
	.string "enfrentado en un emocionante\l"
	.string "Combate {STR_VAR_3}.\p"
	.string "¡Dicho enfrentamiento concluyó\n"
	.string "con la victoria de {STR_VAR_1}!$"

gTVPokemonBattleUpdateText02::
	.string "¡El {STR_VAR_2} de {STR_VAR_1} se\n"
	.string "impuso con claridad meridiana\l"
	.string "e hizo uso de {STR_VAR_3}!$"

gTVPokemonBattleUpdateText03::
	.string "El {STR_VAR_2} de {STR_VAR_1} tuvo\n"
	.string "una actuación mediocre que\l"
	.string "dejó mucho que desear.$"

gTVPokemonBattleUpdateText04::
	.string "¡Felicidades por la victoria,\n"
	.string "{STR_VAR_1}!\p"
	.string "A {STR_VAR_2}, le deseamos más\n"
	.string "suerte la próxima vez.\p"
	.string "¡Y así ponemos fin a este episodio de\n"
	.string "la Última Hora de Combates Pokémon!$"

gTVPokemonBattleUpdateText05::
	.string "Los equipos de {STR_VAR_1} y\n"
	.string "{STR_VAR_2} midieron sus fuerzas\l"
	.string "en un combate múltiple.\p"
	.string "¡Dicho enfrentamiento concluyó con\n"
	.string "la victoria del equipo de {STR_VAR_1}!$"

gTVPokemonBattleUpdateText06::
	.string "¡El {STR_VAR_2} del equipo de\n"
	.string "{STR_VAR_1} se impuso con claridad\l"
	.string "meridiana e hizo uso de {STR_VAR_3}!$"

gTVPokemonBattleUpdateText07::
	.string "El {STR_VAR_3} del equipo de {STR_VAR_2}\n"
	.string "tuvo una actuación mediocre que\l"
	.string "dejó mucho que desear.\p"
	.string "¡Felicidades por la victoria\n"
	.string "de tu equipo, {STR_VAR_1}!\p"
	.string "Al equipo de {STR_VAR_2}, le deseamos\n"
	.string "más suerte la próxima vez.\p"
	.string "¡Y así ponemos fin a este episodio de\n"
	.string "la Última Hora de Combates Pokémon!$"

GabbyAndTy_Text_GabbyPreFirstBattle: @ 0828AF05
	.string "Gabi: ¡Precisamente aquí hemos ido\n"
	.string "a encontrar una estrella como tú!\p"
	.string "¡Mira a la cámara! ¡Vamos a hacerte\n"
	.string "una entrevista de alto voltaje!$"

GabbyAndTy_Text_GabbyIntro: @ 0828AF7D
	.string "Gabi: ¡Anda, si eres {PLAYER}!\n"
	.string "¡Hola! ¿Te acuerdas de nosotros?\p"
	.string "¿Me enseñas lo fuerte que te has\n"
	.string "vuelto? ¡Empezamos a grabar!$"

GabbyAndTy_Text_GabbyDefeatFirstTime: @ 0828B000
	.string "Gabi: ¡Es que tengo una vista…!\n"
	.string "¡Eres una estrella entrenando Pokémon!$"

GabbyAndTy_Text_WhoAreYouInterview: @ 0828B042
	.string "Gabi: ¡Asombroso! ¡Qué flipe!\n"
	.string "¡¿Pero quién eres tú?!\p"
	.string "¡Sabía que había encontrado algo\n"
	.string "bueno cuando te vi!\p"
	.string "A ver, te voy a explicar. Viajamos\n"
	.string "por todas partes entrevistando\l"
	.string "a todo tipo de Entrenadores.\p"
	.string "¿Nos dedicarías un poco\n"
	.string "de tu tiempo para una entrevista?$"

GabbyAndTy_Text_QuoteFromLastInterview: @ 0828B137
	.string "Gabi: “{STR_VAR_1}”.\p"
	.string "¿Te acuerdas? Eso fue lo que decidió\n"
	.string "el último combate, según nos dijiste.\p"
	.string "¡Yo nunca olvido citas tan geniales!$"

GabbyAndTy_Text_YouStompedUsInterviewAgain: @ 0828B1B3
	.string "En el último combate, nos aplastaste\n"
	.string "antes de que pudiéramos prepararnos.\p"
	.string "Bueno, ¿qué me dices?\n"
	.string "¿Te entrevistamos otra vez?$"

GabbyAndTy_Text_YouThrewABallAtUsInterviewAgain: @ 0828B23D
	.string "En el último combate, nos lanzaste\n"
	.string "una Poké Ball, ¿verdad?\p"
	.string "¡Nos quedamos de piedra! ¡Por eso\n"
	.string "se lo contamos a todo quisqui!\p"
	.string "Bueno, ¿qué me dices?\n"
	.string "¿Te entrevistamos otra vez?$"

GabbyAndTy_Text_CleverItemSkillsInterviewAgain: @ 0828B2FA
	.string "En el último combate, tu genial técnica\n"
	.string "de lucha nos liquidó del todo.\p"
	.string "Bueno, ¿qué me dices?\n"
	.string "¿Te entrevistamos otra vez?$"

GabbyAndTy_Text_WeLookedRespectableInterviewAgain: @ 0828B379
	.string "En el último combate, luchamos\n"
	.string "bastante decentemente.\p"
	.string "Bueno, ¿qué me dices?\n"
	.string "¿Te entrevistamos otra vez?$"

GabbyAndTy_Text_InterviewAgain: @ 0828B3F3
	.string "Bueno, ¿qué me dices?\n"
	.string "¿Te entrevistamos otra vez?$"

GabbyAndTy_Text_DescribeYourFeelings: @ 0828B433
	.string "¿Te apetece?\n"
	.string "¡Gracias!\p"
	.string "Vale, quiero que me resumas\n"
	.string "tus sentimientos con respecto\l"
	.string "a nuestro combate. ¡Adelante!$"

GabbyAndTy_Text_PerfectWellBeSeeingYou: @ 0828B4AB
	.string "Gabi: Mmmm… ¡Sí!\n"
	.string "¡Has sabido sintetizarlo bien!\p"
	.string "Me da a mí que esto es material\n"
	.string "de primera para un programa de TV.\p"
	.string "Casi seguro que lo retransmitirán.\n"
	.string "¡No olvides mirar la tele alguna vez!\p"
	.string "¡Pues esto es todo!\n"
	.string "¡Hasta la próxima!$"

GabbyAndTy_Text_DontGiveUpKeepingEyeOut: @ 0828B577
	.string "Gabi: Oh…\p"
	.string "Vale, pero tú continúa así.\n"
	.string "¡Te seguiremos de cerca!$"

GabbyAndTy_Text_KeepingAnEyeOutForYou: @ 0828B5C0
	.string "Gabi: ¡Te seguiremos de cerca!$"

GabbyAndTy_Text_GabbyNotEnoughMons: @ 0828B5EC
	.string "Gabi: ¿Habrá algún entrenador fuerte\n"
	.string "por ahí que tenga muchos Pokémon?$"

GabbyAndTy_Text_GiveUsAnInterviewThisTime: @ 0828B62D
	.string "Gabi: Guau, tú sí que eres especial.\p"
	.string "Has mejorado mucho, muchísimo,\n"
	.string "desde nuestro último combate.\p"
	.string "Teníamos razón cuando dijimos que\n"
	.string "eras una estrella entrenando Pokémon.\p"
	.string "Bueno, ¿qué me dices?\n"
	.string "¿Nos dejas entrevistarte?$"

GabbyAndTy_Text_GabbyDefeat: @ 0828B719
	.string "Gabi: ¡Ha sido un combate tremendo!\n"
	.string "¿Lo has grabado todo?$"

GabbyAndTy_Text_TyPreFirstBattle: @ 0828B75C
	.string "Teo: ¡Eh, mira aquí! ¡Qué suerte,\n"
	.string "encontrar una estrella justo aquí!\l"
	.string "¡Estoy listo para grabar!$"

GabbyAndTy_Text_TyIntro: @ 0828B7B1
	.string "Teo: ¡Eh, mira aquí!\n"
	.string "Un momento, yo sé quién eres…\p"
	.string "¡Voy a grabar nuestro combate\n"
	.string "para la posteridad!$"

GabbyAndTy_Text_TyPostBattle: @ 0828B805
	.string "Teo: ¡Tienes talento natural!\n"
	.string "¡He grabado material de primera!$"

GabbyAndTy_Text_TyNotEnoughMons: @ 0828B841
	.string "Teo: ¿Sólo tienes un Pokémon?\p"
	.string "Si tuvieras alguno más, podría grabar\n"
	.string "algo bueno para la tele, pero…$"

GabbyAndTy_Text_TyDefeatFirstTime: @ 0828B8B1
	.string "Teo: Sí, sin duda hemos encontrado\n"
	.string "a una estrella. ¡Vaya notición!$"

GabbyAndTy_Text_TyDefeat: @ 0828B8F6
	.string "Teo: Sí, lo he grabado todo.\n"
	.string "Está todo en la cámara.$"

gTVInSearchOfTrainersText00::
	.string "Operación entrenador…\p"
	.string "Gabi: ¡Hola! Hoy hemos visitado\n"
	.string "la zona cercana a {STR_VAR_1}.\p"
	.string "Nuestra esperanza era encontrar\n"
	.string "algún nuevo talento desconocido.\p"
	.string "Hoy hemos descubierto\n"
	.string "a una nueva promesa: {PLAYER}.\p"
	.string "Tenía algo que captó nuestro interés\n"
	.string "desde el primer momento…$"

gTVInSearchOfTrainersText01::
	.string "Ya habíamos luchado contra {PLAYER},\n"
	.string "pero ahora podemos atestiguar que\l"
	.string "ha mejorado mucho desde entonces.\p"
	.string "¡Desde el primer momento, supimos\n"
	.string "que era alguien especial!$"

gTVInSearchOfTrainersText02::
	.string "La mejor manera de determinar\n"
	.string "la fuerza de un Entrenador es…\p"
	.string "Bueno, la más rápida es luchando.\n"
	.string "¡Así abrimos nuestra investigación!\p"
	.string "Y…\p"
	.string "Así fue como entablamos combate\n"
	.string "con {PLAYER}.\p"
	.string "En una actuación espectacular, nos\n"
	.string "arrolló, aplastó y dejó hechos polvo.\p"
	.string "{PLAYER} es impresionantemente fuerte.\p"
	.string "Quisiera compartir con vosotros\n"
	.string "mis apreciaciones sobre el combate.$"

gTVInSearchOfTrainersText03::
	.string "La combinación de {STR_VAR_1}\n"
	.string "y {STR_VAR_3} es simplemente divina.\p"
	.string "Ambos, {STR_VAR_1} y {STR_VAR_3},\n"
	.string "se apoyan mutuamente sin flaquear.\p"
	.string "¡Verlos en acción es maravilloso!\p"
	.string "El último movimiento usado\n"
	.string "en el combate fue {STR_VAR_2}.\p"
	.string "El movimiento {STR_VAR_2} simboliza\n"
	.string "perfectamente la amistad que\l"
	.string "hay entre {STR_VAR_1} y {STR_VAR_3}.$"

gTVInSearchOfTrainersText04::
	.string "Perdí algo de confianza en mí como\n"
	.string "consecuencia de ese combate.\p"
	.string "Nos derrotaron antes incluso de que\n"
	.string "pudiéramos preparar un ataque…\l"
	.string "Una victoria aplastante…\p"
	.string "A pesar de todo, los combates\n"
	.string "de {PLAYER} son dignos de verse.\p"
	.string "Recomiendo a todo entrenador seguro\n"
	.string "de sí que se enfrente a {PLAYER}.$"

gTVInSearchOfTrainersText05::
	.string "Sólo se puede decir una cosa…\n"
	.string "¡Ni se te ocurra lanzar otra Poké Ball\l"
	.string "mientras luches contra un Entrenador!\p"
	.string "{PLAYER} es muy fuerte, cierto, pero no\n"
	.string "tiene ni idea de las reglas más básicas.\p"
	.string "Quisiera pedir algo a nuestro público…\p"
	.string "Si veis a {PLAYER}, ¡recordadle\n"
	.string "lo que hay que hacer!$"

gTVInSearchOfTrainersText06::
	.string "{PLAYER} parece poder leer las mentes\n"
	.string "de sus rivales.\p"
	.string "¡Siempre acierta con el momento\n"
	.string "de usar uno u otro objeto!$"

gTVInSearchOfTrainersText07::
	.string "A decir verdad, yo antes pensaba\n"
	.string "que se me daba bien todo esto…\p"
	.string "Aunque acabamos perdiendo, el combate\n"
	.string "fue muy reñido hasta el final.\p"
	.string "¡Así que no te pienses que lo vas a\n"
	.string "tener chupado la próxima vez, {PLAYER}!$"

gTVInSearchOfTrainersText08::
	.string "Tras el combate, pedimos a {PLAYER}\n"
	.string "que nos resumiera sus impresiones.\p"
	.string "Respondió esto: “{STR_VAR_1}”.\p"
	.string "Los Pokémon {STR_VAR_2} y {STR_VAR_3}\n"
	.string "de {PLAYER}…\l"
	.string "“{STR_VAR_1}”…\p"
	.string "Mmmm… Qué profundo… Qué cita tan\n"
	.string "inteligente… Es casi filosófica…\p"
	.string "No debe sorprendernos: un buen\n"
	.string "Entrenador sabe siempre qué decir.\p"
	.string "¡Eso es todo por hoy!\n"
	.string "¡Hasta el próximo programa!$"

ContestLadyShow_Text_Intro::
	.string "¡Última Hora de Concursos Pokémon!\p"
	.string "Presentador: Sentimos\n"
	.string "interrumpir la programación habitual\l"
	.string "y os damos la bienvenida.\p"
	.string "¡Emitimos en directo desde el\n"
	.string "lugar de celebración del último\l"
	.string "Concurso de {STR_VAR_1}!\p"
	.string "Espectadores: (?)\p"
	.string "Presentador: ¡Oh, parece que\n"
	.string "los participantes vienen hacia aquí!\p"
	.string "¡Intentemos conseguir una\n"
	.string "entrevista para los telespectadores!\p"
	.string "Espectadores: (?)\n"
	.string "(!)$"

ContestLadyShow_Text_Won::
	.string "Presentador: ¡Disculpa y gracias\n"
	.string "por estar con nosotros en directo!\p"
	.string "¡Permítenos felicitarte\n"
	.string "por tu victoria!\p"
	.string "Dinos, ¿cuál ha sido el factor\n"
	.string "determinante de este gran triunfo?\p"
	.string "Bella: ¡Mi {STR_VAR_2} y yo\n"
	.string "nos esforzamos al máximo!\p"
	.string "Pero sé que no lo habríamos logrado\n"
	.string "si tanta gente no nos hubiera ayudado\l"
	.string "a prepararnos para el Concurso.\p"
	.string "Presentador: ¿Hay alguien\n"
	.string "especial con quien quieres compartir\l"
	.string "estos momentos? ¡Cuéntanos!\p"
	.string "Bella: ¡Claro que sí!\p"
	.string "¡{STR_VAR_3}! ¿Estás viendo la tele?\n"
	.string "¡Lo hemos logrado!\l"
	.string "¡Muchísimas gracias!$"

ContestLadyShow_Text_Lost::
	.string "Presentador: ¡Disculpa y gracias\n"
	.string "por estar con nosotros en directo!\p"
	.string "El resultado debe de haberte\n"
	.string "desilusionado. ¿Algún comentario?\p"
	.string "Bella: Es desolador…\n"
	.string "{STR_VAR_2} y yo nos esforzamos mucho.\p"
	.string "Pero siento que hemos decepcionado\n"
	.string "a todos aquellos que nos han\l"
	.string "apoyado para llegar hasta aquí.\p"
	.string "Presentador: Sin ánimo de\n"
	.string "ofender, el colorido de este Pokémon\l"
	.string "es algo pobretón.\p"
	.string "Bella: {STR_VAR_3}, cuánto lo siento…\n"
	.string "La próxima vez lo haré mejor, de verdad.\l"
	.string "Snif, snif… ¡Buaaaa!\p"
	.string "Espectadores: ¿Lo habéis visto?\n"
	.string "¡Pobre chica!\p"
	.string "Presentador: Vaya… Ejem…\p"
	.string "¡Bueno, esto ha sido todo por hoy!\n"
	.string "¡Gracias por conectar con nosotros!$"

ContestLadyShow_Text_LostBadly::
	.string "Presentador: ¡Disculpa y gracias\n"
	.string "por estar con nosotros en directo!\p"
	.string "¿Qué tal ha ido tu participación\n"
	.string "en este Concurso?\p"
	.string "Bella: Fatal del verbo fatal…\n"
	.string "Mi {STR_VAR_2} no logró meterse al\l"
	.string "público en el bolsillo, no sé por qué.\p"
	.string "Presentador: Sin ánimo de\n"
	.string "ofender, el colorido de este Pokémon\l"
	.string "parece algo desvaído.\p"
	.string "Bella: Snif, snif… ¡Buaaaa!\p"
	.string "Espectadores: ¿Lo habéis visto?\n"
	.string "¡Pobre chica!\p"
	.string "Presentador: Vaya… Ejem…\p"
	.string "¡Bueno, esto ha sido todo por hoy!\n"
	.string "¡Gracias por conectar con nosotros!$"
