@ Note: local IDs shared with scripts.inc for LilycoveCity_ContestLobby
.set LOCALID_MAN, 3
.set LOCALID_BOY, 9
.set LOCALID_TWIN, 10
.set LOCALID_POKEFAN_F, 15
.set LOCALID_EXPERT_M, 16
.set LOCALID_GIRL, 17

.set NUM_OPPONENTS, VAR_0x8009

BerryBlender_Text_WantToMakePokeblocks: @ 8292DEE
	.string "Dime, ¿quieres hacer algunos Pokécubos\n"
	.string "con este viejales?$"

BerryBlender_Text_Excellent: @ 8292E28
	.string "¡Maravilloso!$"

BerryBlender_Text_MadeOldTimerSad: @ 8292E33
	.string "Oh…\n"
	.string "Me has puesto tristón…$"

BerryBlender_Text_KnowHowToMakePokeblocks: @ 8292E57
	.string "¿Sabes cómo hacer Pokécubos?$"

BerryBlender_Text_LetsBerryBlender: @ 8292E78
	.string "¡Pues manos a la obra!\p"
	.string "¡A por la Licuabayas!$"

BerryBlender_Text_ExplainBerryBlending: @ 8292EA6
	.string "Vale, pues entonces te explico.\p"
	.string "No te asustes, es facilísimo.\p"
	.string "Cuando la flecha de la Licuabayas\n"
	.string "llegue a tu marcador, pulsa el Botón A.\p"
	.string "Es lo único que hay que hacer.\n"
	.string "Ya verás qué fácil es. Vamos allá…$"

BerryBlender_Text_DontHaveAnyBerries: @ 8292F77
	.string "¿Pero…?\n"
	.string "¿No tienes ninguna baya?\p"
	.string "Pues si no tienes bayas,\n"
	.string "no puedes hacer Pokécubos.$"

BerryBlender_Text_CanHaveOneOfMyBerries: @ 8292FD1
	.string "Pues así no llegamos a ninguna\n"
	.string "parte, ¿no te parece?\p"
	.string "Si no te importa que esté manoseada,\n"
	.string "puedo darte una de mis bayas.\p"
	.string "Así podremos hacer algunos Pokécubos\n"
	.string "juntos usando la Licuabayas.$"

BerryBlender_Text_DontHaveAnyBerriesToSpare: @ 829307D
	.string "Si me sobrara alguna baya,\n"
	.string "te la daría con sumo gusto…\p"
	.string "Pero hoy solo tengo una. Lo tendremos\n"
	.string "que dejar para otro día, lo siento.$"

BerryBlender_Text_PokeblockCaseIsFull: @ 8293101
	.string "Pero tu Tubo de Pokécubos está lleno.\p"
	.string "Deberías usar algunos Pokécubos\n"
	.string "antes de volver por aquí.$"

BerryBlender_Text_DontHavePokeblockCase: @ 8293157
	.string "Pero si no tienes ningún tubo\n"
	.string "de Pokécubos…\p"
	.string "Deberías conseguir un tubo de Pokécubos\n"
	.string "antes de volver por aquí.$"

BerryBlender_Text_LetsGetBlendingAlready: @ 82931AA
	.string "¡Vamos a bayalicuar!$"

BerryBlender_Text_WhatKindOfPokeblockWillIGet: @ 82931C6
	.string "Me pregunto qué tipo de Pokécubo\n"
	.string "conseguiré… ¡Qué emoción!$"

BerryBlender_Text_WantToBlendPokeblocksWithUs: @ 8293201
	.string "¡Eh, hola! ¿Licúas Bayas con nosotros,\n"
	.string "a ver qué Pokécubos sacamos?$"

BerryBlender_Text_Okay: @ 8293237
	.string "¡Genial!$"

BerryBlender_Text_ThatsTooBad: @ 829323D
	.string "Tú te lo pierdes…\p"
	.string "¡Si de repente sientes un impulso\n"
	.string "irrefrenable de licuar, ya sabes!$"

BerryBlender_Text_KnowHowToMakePokeblocks2: @ 829328C
	.string "Supongo que sabes cómo crear Pokécubos,\n"
	.string "¿no?$"

BerryBlender_Text_LetsBerryBlender2: @ 82932C3
	.string "¡Pues manos a la obra!\p"
	.string "¡A por la Licuabayas!$"

BerryBlender_Text_ExplainBerryBlending2: @ 82932F1
	.string "¡Bien!\n"
	.string "¡Entonces déjame que te explique!\p"
	.string "Cuando la flecha giratoria de la\n"
	.string "Licuabayas llegue a tu marca,\l"
	.string "pulsa el Botón A.\p"
	.string "Eso es todo.\n"
	.string "Chupado, ¿verdad?$"

BerryBlender_Text_DontHaveAnyBerries2: @ 8293394
	.string "Eh, pero espera un segundo…\n"
	.string "¡Si no tienes ni una baya!\p"
	.string "No puedes hacer Pokécubos sin bayas…\p"
	.string "Pero tranqui, aquí estaremos\n"
	.string "para cuando consigas algunas.$"

BerryBlender_Text_PokeblockCaseIsFull2: @ 829343E
	.string "Pero tu tubo de Pokécubos está lleno.\p"
	.string "Deberías usar algunos Pokécubos\n"
	.string "antes de volver por aquí.$"

BerryBlender_Text_DontHavePokeblockCase2: @ 82934A2
	.string "Pero si no tienes ningún tubo\n"
	.string "de Pokécubos…\p"
	.string "Deberías conseguir un tubo de Pokécubos\n"
	.string "antes de volver por aquí.$"

@ Unused
BerryBlender_Text_MakePokeblocksWithOurGroup: @ 829350B
	.string "¡Oh, hola! ¿Quieres hacer algunos\n"
	.string "Pokécubos with our little group?$"

BerryBlender_Text_OhDear: @ 829354E
	.string "¡Ay, ay!$"

BerryBlender_Text_LeftUsInShock: @ 8293558
	.string "¡Ay de mí!…\p"
	.string "¡Me dejas de piedra!$"

BerryBlender_Text_KnowHowToMakePokeblocks3: @ 829357E
	.string "¿Sabes cómo hacer Pokécubos$"

BerryBlender_Text_LetsBerryBlender3: @ 82935B1
	.string "¡Pues manos a la obra!\p"
	.string "¡A por la Licuabayas!$"

BerryBlender_Text_ExplainBerryBlending3: @ 82935E5
	.string "¡Ay, ay!\p"
	.string "Entonces te lo explicaré.\p"
	.string "Cuando la flecha giratoria de la\n"
	.string "Licuabayas llegue a tu marca,\l"
	.string "pulsa el Botón A.\p"
	.string "Eso es todo.\n"
	.string "Sencillo, ¿verdad?$"

BerryBlender_Text_DontHaveAnyBerries3: @ 829367D
	.string "Pero tú no tienes ninguna baya,\n"
	.string "¿verdad?\p"
	.string "Pues sin bayas no puedes\n"
	.string "hacer Pokécubos…\p"
	.string "Nosotros seguiremos haciendo Pokécubos\n"
	.string "aquí, así que vuelve si al final\l"
	.string "encuentras algunas bayas.$"

BerryBlender_Text_PokeblockCaseIsFull3: @ 8293738
	.string "Pero tu Tubo de Pokécubos está lleno.\p"
	.string "Deberías usar algunos Pokécubos\n"
	.string "antes de volver por aquí.$"

BerryBlender_Text_DontHavePokeblockCase3: @ 8293792
	.string "Pero si no tienes ningún tubo\n"
	.string "de Pokécubos…\p"
	.string "Deberías conseguir un tubo de Pokécubos\n"
	.string "antes de volver por aquí.$"

BerryBlender_Text_SetNewBlenderRecord: @ 82937F9
	.string "¡Prepárate porque voy a pulverizar el\n"
	.string "récord de velocidad de la Licuabayas!$"

BerryBlender_Text_LookGoodAtBlendingJoinUs: @ 8293842
	.string "¡Huy, huy, huy!\n"
	.string "¡Tienes pinta de saber licuar!\l"
	.string "¿Te gustaría hacerlo con nosotros?$"

BerryBlender_Text_MakeDeliciousPokeblocks: @ 829388F
	.string "Voy a hacer unos Pokécubos deliciosos\n"
	.string "que harán a mis Pokémon más dulces.$"

BerryBlender_Text_SaveGameBeforeBerryBlenderLink: @ 82938CD
	.string "Usa las Bayas para hacer Pokécubos\n"
	.string "con tus amigos en la Licuabayas.\p"
	.string "Debes guardar la partida antes\n"
	.string "de conectarte con tus amigos.\l"
	.string "¿Estás de acuerdo?$"

BerryBlender_Text_SearchingForFriends: @ 8293955
	.string "Buscando a tus amigos…\n"
	.string "(…) Botón B: cancelar$"

BerryBlender_Text_Player1Arrived: @ 8293986
	.string "{STR_VAR_1} se ha conectado.$"

BerryBlender_Text_Player1And2Arrived: @ 8293992
	.string "{STR_VAR_1} y {STR_VAR_2} se han\nconectado.$"

BerryBlender_Text_AllPlayersArrived: @ 82939A5
	.string "{STR_VAR_1}, {STR_VAR_2}, y\n"
	.string "{STR_VAR_3} se han conectado.$"

BerryBlender_Text_NoBerriesLink: @ 82939BD
	.string "No tienes ninguna baya.\n"
	.string "No puedes usar la Licuabayas.$"

BerryBlender_Text_PokeblockCaseIsFullLink: @ 82939F3
	.string "Tu Tubo de Pokécubos está lleno.\n"
	.string "No puedes usar la Licuabayas.$"

BerryBlender_Text_DontHavePokeblockCaseLink: @ 8293A2D
	.string "No tienes ningún tubo de Pokécubos.\n"
	.string "No puedes usar la Licuabayas.$"

BerryBlender_Text_LoveMakingPokeblocks: @ 8293A6B
	.string "Me encanta preparar Pokécubos.\p"
	.string "Por eso siempre llevo bayas encima.$"

BerryBlender_Text_MakePokeblocksUsingBerryBlender: @ 8293AA5
	.string "Si quieres, podríamos preparar algunos\n"
	.string "Pokécubos juntos con la Licuabayas.$"

BerryBlender_Text_DontHaveAnyBerriesHaveOne: @ 8293AF0
	.string "¿Cómo?\n"
	.string "¿Que no tienes bayas?\p"
	.string "Pues así poco vamos a hacer, ¿no?\p"
	.string "Si no te importa que esté manoseada,\n"
	.string "puedo darte una de mis bayas.$"

BerryBlender_Text_UseItToMakePokeblocksTogether: @ 8293B76
	.string "La usaremos para preparar Pokécubos\n"
	.string "juntos con la Licuabayas.$"

BerryBlender_Text_DontHaveAnyBerriesNoneToSpare: @ 8293BB4
	.string "¿Cómo?\n"
	.string "¿Que no tienes bayas?\p"
	.string "Si me sobraran, te daría una…\p"
	.string "Pero solo tengo una. Lo siento.$"

BerryBlender_EventScript_BerryBlender1::
	lockall
	goto_if_unset FLAG_HIDE_LILYCOVE_CONTEST_HALL_BLEND_MASTER, BerryBlender_EventScript_BlendMasterPresent
	setvar NUM_OPPONENTS, 1
	applymovement LOCALID_EXPERT_M, BerryBlender_Movement_BlendLeaderWalkInPlace
	waitmovement 0
	msgbox BerryBlender_Text_WantToMakePokeblocks, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_TryUseBerryBlender1
	goto BerryBlender_EventScript_DeclineBlender1
	end

BerryBlender_EventScript_DeclineBlender1:
	msgbox BerryBlender_Text_MadeOldTimerSad, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender1NoBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerries, MSGBOX_DEFAULT
	dotimebasedevents
	goto_if_set FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY, BerryBlender_EventScript_Blender1NoSpareBerries
	goto BerryBlender_EventScript_Blender1GiveSpareBerry
	end

BerryBlender_EventScript_Blender1NoSpareBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerriesToSpare, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender1GiveSpareBerry:
	msgbox BerryBlender_Text_CanHaveOneOfMyBerries, MSGBOX_DEFAULT
	giveitem ITEM_PECHA_BERRY
	setflag FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY
	goto BerryBlender_EventScript_UseBerryBlender1
	end

BerryBlender_EventScript_UseBerryBlender1:
	msgbox BerryBlender_Text_KnowHowToMakePokeblocks, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_StartBlender1
	goto BerryBlender_EventScript_ExplainBlending1
	end

BerryBlender_EventScript_StartBlender1:
	msgbox BerryBlender_Text_LetsBerryBlender, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoBerryBlending
	end

BerryBlender_EventScript_ExplainBlending1:
	msgbox BerryBlender_Text_ExplainBerryBlending, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_StartBlender1
	end

BerryBlender_EventScript_TryUseBerryBlender1:
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender1NoCase
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_Blender1CaseFull
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender1NoBerries
	msgbox BerryBlender_Text_Excellent, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_UseBerryBlender1
	end

BerryBlender_EventScript_DoBerryBlending:
	copyvar VAR_0x8004, NUM_OPPONENTS
	fadescreen FADE_TO_BLACK
	special DoBerryBlending
	waitstate
	releaseall
	end

BerryBlender_EventScript_Blender1CaseFull:
	msgbox BerryBlender_Text_PokeblockCaseIsFull, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender1NoCase:
	msgbox BerryBlender_Text_DontHavePokeblockCase, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BerryBlender2::
	lockall
	setvar NUM_OPPONENTS, 2
	applymovement LOCALID_TWIN, Common_Movement_FaceOriginalDirection
	applymovement LOCALID_MAN, BerryBlender_Movement_BlendLeaderWalkInPlace
	waitmovement 0
	msgbox BerryBlender_Text_WantToBlendPokeblocksWithUs, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_TryUseBerryBlender2
	goto BerryBlender_EventScript_DeclineBlender2
	end

BerryBlender_EventScript_DeclineBlender2:
	msgbox BerryBlender_Text_ThatsTooBad, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender2NoBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerries2, MSGBOX_DEFAULT
	release
	end

BerryBlender_EventScript_UseBerryBlender2:
	msgbox BerryBlender_Text_KnowHowToMakePokeblocks2, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_StartBlender2
	goto BerryBlender_EventScript_ExplainBlending2
	end

BerryBlender_EventScript_StartBlender2:
	msgbox BerryBlender_Text_LetsBerryBlender2, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoBerryBlending
	end

BerryBlender_EventScript_ExplainBlending2:
	msgbox BerryBlender_Text_ExplainBerryBlending2, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_StartBlender2
	end

BerryBlender_EventScript_TryUseBerryBlender2:
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender2NoBerries
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender2NoCase
	msgbox BerryBlender_Text_Okay, MSGBOX_DEFAULT
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_ne VAR_RESULT, 65535, BerryBlender_EventScript_UseBerryBlender2
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_Blender2CaseFull
	end

BerryBlender_EventScript_Blender2CaseFull:
	msgbox BerryBlender_Text_PokeblockCaseIsFull2, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender2NoCase:
	msgbox BerryBlender_Text_DontHavePokeblockCase2, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BerryBlender3::
	lockall
	setvar VAR_0x8008, LOCALID_POKEFAN_F
	setvar NUM_OPPONENTS, 3
	applymovement LOCALID_BOY, Common_Movement_FaceOriginalDirection
	applymovement LOCALID_GIRL, Common_Movement_FaceOriginalDirection
	applymovement VAR_0x8008, BerryBlender_Movement_BlendLeaderWalkInPlace
	waitmovement 0
	msgbox BerryBlender_Text_LookGoodAtBlendingJoinUs, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_TryUseBlender3
	goto BerryBlender_EventScript_DeclineBlender3
	end

BerryBlender_EventScript_DeclineBlender3:
	msgbox BerryBlender_Text_LeftUsInShock, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender3NoBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerries3, MSGBOX_DEFAULT
	release
	end

BerryBlender_EventScript_UseBerryBlender3:
	msgbox BerryBlender_Text_KnowHowToMakePokeblocks3, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_StartBlender3
	goto BerryBlender_EventScript_ExplainBlending3
	end

BerryBlender_EventScript_StartBlender3:
	msgbox BerryBlender_Text_LetsBerryBlender3, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoBerryBlending
	end

BerryBlender_EventScript_ExplainBlending3:
	msgbox BerryBlender_Text_ExplainBerryBlending3, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_StartBlender3
	end

BerryBlender_EventScript_TryUseBlender3:
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender3NoBerries
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender3NoCase
	msgbox BerryBlender_Text_OhDear, MSGBOX_DEFAULT
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_ne VAR_RESULT, 65535, BerryBlender_EventScript_UseBerryBlender3
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_Blender3CaseFull
	end

BerryBlender_EventScript_Blender3CaseFull:
	msgbox BerryBlender_Text_PokeblockCaseIsFull3, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender3NoCase:
	msgbox BerryBlender_Text_DontHavePokeblockCase3, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BlendMasterPresent:
	lockall
	setvar NUM_OPPONENTS, 1
	msgbox BerryBlender_Text_SeeMyMasteryInAction, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_TryBlendWithBlendMaster
	msgbox BerryBlender_Text_TooBusyNowIsee, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BlendMasterNoBerries:
	msgbox BerryBlender_Text_BlendMasterNoBerries, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_TryBlendWithBlendMaster:
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_BlendMasterNoCase
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_BlendMasterNoBerries
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_ne VAR_RESULT, 65535, BerryBlender_EventScript_BlendWithBlendMaster
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_BlendMasterCaseFull
	end

BerryBlender_EventScript_BlendWithBlendMaster:
	msgbox BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks, MSGBOX_YESNO
	call_if_eq VAR_RESULT, NO, BerryBlender_EventScript_BlendMasterExplainBlending
	msgbox BerryBlender_Text_BlendMasterLetsBerryBlender, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoBerryBlending
	end

BerryBlender_EventScript_BlendMasterExplainBlending:
	msgbox BerryBlender_Text_BlendMasterExplainBerryBlending, MSGBOX_DEFAULT
	return

BerryBlender_EventScript_BlendMasterNoCase:
	msgbox BerryBlender_Text_BlendMasterNoPokeblockCase, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BlendMasterCaseFull:
	msgbox BerryBlender_Text_BlendMasterPokeblockCaseFull, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender2Man::
	msgbox BerryBlender_Text_SetNewBlenderRecord, MSGBOX_NPC
	end

BerryBlender_EventScript_Blender3PokefanF::
	msgbox BerryBlender_Text_LookGoodAtBlendingJoinUs, MSGBOX_NPC
	end

BerryBlender_EventScript_Blender2Twin::
	msgbox BerryBlender_Text_MakeDeliciousPokeblocks, MSGBOX_NPC
	end

BerryBlender_EventScript_Blender1ExpertM::
	setvar VAR_0x8008, 15
	goto BerryBlender_EventScript_ExpertMCheckGiveBerry
	end

BerryBlender_EventScript_ExpertMCheckGiveBerry:
	lock
	faceplayer
	msgbox BerryBlender_Text_LoveMakingPokeblocks, MSGBOX_DEFAULT
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, TRUE, BerryBlender_EventScript_ExpertMPlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_ExpertMNoBerries
	end

BerryBlender_EventScript_ExpertMPlayerHasBerries:
	msgbox BerryBlender_Text_MakePokeblocksUsingBerryBlender, MSGBOX_DEFAULT
	release
	end

BerryBlender_EventScript_ExpertMNoBerries:
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_ExpertMNoSpareBerries
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_ExpertMNoSpareBerries
	dotimebasedevents
	goto_if_set FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY, BerryBlender_EventScript_ExpertMNoSpareBerries
	goto BerryBlender_EventScript_ExpertMGiveBerry
	end

BerryBlender_EventScript_ExpertMNoSpareBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerriesNoneToSpare, MSGBOX_DEFAULT
	release
	end

BerryBlender_EventScript_ExpertMGiveBerry:
	msgbox BerryBlender_Text_DontHaveAnyBerriesHaveOne, MSGBOX_DEFAULT
	giveitem ITEM_PECHA_BERRY
	setflag FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY
	msgbox BerryBlender_Text_UseItToMakePokeblocksTogether, MSGBOX_DEFAULT
	release
	end

BerryBlender_Movement_BlendLeaderWalkInPlace:
	walk_in_place_faster_right
	step_end

BerryBlender_EventScript_BerryBlenderLink::
	lockall
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_LinkBlenderNoBerries
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_LinkBlenderNoCase
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_ne VAR_RESULT, 65535, BerryBlender_EventScript_LinkBlenderSaveGame
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_LinkBlenderCaseFull
	end

BerryBlender_EventScript_LinkBlenderSaveGame:
	msgbox BerryBlender_Text_SaveGameBeforeBerryBlenderLink, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_TryDoLinkBlender
	goto_if_eq VAR_RESULT, NO, BerryBlender_EventScript_CancelLinkBlender
	end

BerryBlender_EventScript_LinkBlenderNoBerries:
	msgbox BerryBlender_Text_NoBerriesLink, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_TryDoLinkBlender:
	call Common_EventScript_SaveGame
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_CancelLinkBlender
	specialvar VAR_RESULT, IsWirelessAdapterConnected
	goto_if_eq VAR_RESULT, TRUE, BerryBlender_EventScript_StartDecideLinkLeader
	message BerryBlender_Text_SearchingForFriends
	waitmessage
	special TryBerryBlenderLinkup
	waitstate
	goto_if_eq VAR_RESULT, LINKUP_SUCCESS, BerryBlender_EventScript_SpawnLinkPartners
	goto_if_eq VAR_RESULT, LINKUP_SOMEONE_NOT_READY, BerryBlender_EventScript_CloseLinkNotReady
	goto_if_eq VAR_RESULT, LINKUP_DIFF_SELECTIONS, BerryBlender_EventScript_CloseLinkDifferentSelections
	goto_if_eq VAR_RESULT, LINKUP_FAILED, BerryBlender_EventScript_CloseLink
	goto_if_eq VAR_RESULT, LINKUP_CONNECTION_ERROR, BerryBlender_EventScript_LinkError
	end

BerryBlender_EventScript_TwoPlayerLink:
	msgbox BerryBlender_Text_Player1Arrived, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoLinkBerryBlending
	end

BerryBlender_EventScript_ThreePlayerLink:
	msgbox BerryBlender_Text_Player1And2Arrived, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoLinkBerryBlending
	end

BerryBlender_EventScript_FourPlayerLink:
	msgbox BerryBlender_Text_AllPlayersArrived, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoLinkBerryBlending
	end

BerryBlender_EventScript_DoLinkBerryBlending:
	setvar VAR_0x8004, 0  @ number of opponents, 0 indicates Link
	fadescreen FADE_TO_BLACK
	removeobject 240 @ Unclear where these local IDs come from,
	removeobject 239 @ but presumably they'd be the 4 link players
	removeobject 238
	removeobject 237
	special DoBerryBlending
	waitstate
	releaseall
	end

BerryBlender_EventScript_CancelLinkBlender:
	releaseall
	end

BerryBlender_EventScript_LinkBlenderCaseFull:
	msgbox BerryBlender_Text_PokeblockCaseIsFullLink, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_LinkBlenderNoCase:
	msgbox BerryBlender_Text_DontHavePokeblockCaseLink, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_CloseLinkNotReady:
	special CloseLink
	msgbox Text_SomeoneIsNotReadyToLink, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_CloseLinkDifferentSelections:
	special CloseLink
	msgbox Text_PlayersMadeDifferentSelections, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_CloseLink:
	special CloseLink
	msgbox gText_PokeblockLinkCanceled, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_LinkError:
	special CloseLink
	msgbox Text_LinkErrorPleaseReset, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_SpawnLinkPartners:
	fadescreen FADE_TO_BLACK
	specialvar VAR_RESULT, GetLinkPartnerNames
	copyvar VAR_0x8008, VAR_RESULT
	copyvar VAR_0x8004, VAR_0x8008
	special SpawnLinkPartnerObjectEvent
	goto BerryBlender_EventScript_LinkPlayersArrived
	end

BerryBlender_EventScript_LinkPlayersArrived:
	fadescreen FADE_FROM_BLACK
	switch VAR_0x8008
	case 2, BerryBlender_EventScript_TwoPlayerLink
	case 3, BerryBlender_EventScript_ThreePlayerLink
	case 4, BerryBlender_EventScript_FourPlayerLink
	end

BerryBlender_EventScript_StartDecideLinkLeader:
	setvar VAR_0x8004, LINK_GROUP_BERRY_BLENDER
	goto BerryBlender_EventScript_DecideLinkLeader
	end

BerryBlender_EventScript_DecideLinkLeader:
	message LilycoveCity_ContestLobby_Text_PleaseDecideLinkLeader
	waitmessage
	multichoice 16, 6, MULTI_LINK_LEADER, FALSE
	switch VAR_RESULT
	case 0, BerryBlender_EventScript_TryJoinGroup
	case 1, BerryBlender_EventScript_TryLeadGroup
	case 2, BerryBlender_EventScript_CloseLink
	case MULTI_B_PRESSED, BerryBlender_EventScript_CloseLink
	end

BerryBlender_EventScript_TryLeadGroup:
	call BerryBlender_EventScript_TryBecomeLinkLeader
	goto_if_eq VAR_RESULT, LINKUP_SUCCESS, BerryBlender_EventScript_LinkLeaderDecided
	goto_if_eq VAR_RESULT, LINKUP_FAILED, BerryBlender_EventScript_DecideLinkLeader
	goto_if_eq VAR_RESULT, LINKUP_RETRY_ROLE_ASSIGN, BerryBlender_EventScript_TryLeadGroup
	release
	end

BerryBlender_EventScript_TryJoinGroup:
	call BerryBlender_EventScript_TryJoinLinkGroup
	goto_if_eq VAR_RESULT, LINKUP_SUCCESS, BerryBlender_EventScript_LinkLeaderDecided
	goto_if_eq VAR_RESULT, LINKUP_FAILED, BerryBlender_EventScript_DecideLinkLeader
	goto_if_eq VAR_RESULT, LINKUP_RETRY_ROLE_ASSIGN, BerryBlender_EventScript_TryJoinGroup
	release
	end

BerryBlender_EventScript_TryBecomeLinkLeader:
	special TryBecomeLinkLeader
	waitstate
	return

BerryBlender_EventScript_TryJoinLinkGroup:
	special TryJoinLinkGroup
	waitstate
	return

BerryBlender_EventScript_LinkLeaderDecided:
	goto BerryBlender_EventScript_SpawnLinkPartners
	end
